### ISSUE TITLE
proxy: provide logout link on 403 page

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#100]
I use Google OAuth to login to Pomerium. I usually have more than 2 Google accounts login at the same time, but not all of them are whitelisted to access pages protected by Pomerium.

Sometimes, I would choose the wrong email address and get a 403 page. But there's no logout link on the 403 page and I have to either remember the secret URL to logout (`/.pomerium/somethingsomething`) or delete the cookie.

It would be great if you can add some description on the 403 page. E.g.: You are logged in as XXX@gmail.com. Do not intend to use this email? Click Here to login again.

Alternative without this feature: delete the cookie, or use the `/.pomerium/` link to logout (which I can barely remember 😞.

**Comment by yegle** [comment]
OK it's `/.pomerium/sign_out`. I would use it as a workaround for now.

**Comment by desimone** [comment]
I've been meaning to improve the 5XX and 4XX / logout screens for a while. This would be a good place to do that.
