### ISSUE TITLE
proxy: x-forwarded-for not set

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#1013]
## What happened?

`x-forwarded-for` headers are not being set by default.

## What did you expect to happen?

`x-forwarded-for` headers are being set by default.

## How'd it happen?

```
policy:
  - from: https://httpbin.imac.bdd.io
    to: http://httpbin.org
```

Go to https://httpbin.imac.bdd.io/headers

```json

{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en-US,en;q=0.9", 
    "Cache-Control": "max-age=0", 
    "Content-Length": "0", 
    "Cookie": "", 
    "Dnt": "1", 
    "Host": "httpbin.imac.bdd.io", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "cross-site", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "30000"
  }
}
```

I expect x-forarded-for headers above.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `v0.9.0+ecdf7ee`
- Server Operating System/Architecture/Cloud: OSX

## Additional context

- https://github.com/pomerium/pomerium/issues/1012

**Comment by cuonglm** [comment]
After digging in, the `X-Forwarded-For` header has been set by envoy, but [httpbin strips some headers by default](https://github.com/postmanlabs/httpbin/blob/7b3b70dbca05cdea049e1a74073339d52089c05b/httpbin/helpers.py#L132). Adding `?show_env=true` does show `X-Forwarded-For`.
