### ISSUE TITLE
Unable to logout of services behind forward-auth

### ISSUE THREAD

**Issue by branchmispredictor** [pomerium/pomerium#1014]
When using Pomerium in forward auth mode, none of the proxy routes are served. Trying to access `/.pomerium` would result in an forward auth call to Pomerium, but the request itself would ultimately be routed to the underlying service.

The only option I see for signing out are using the auth service's signout url at `authenticate.localhost/.pomerium/sign_out`. However, doing that and then accessing the service in forward auth mode results in an http 403 with "access denied". Leaving no way to log back in or further log out.

Pomerium v0.9.0+5358839

**Comment by cuonglm** [comment]
I think this is duplicated of https://github.com/pomerium/pomerium/issues/858
