### ISSUE TITLE
Deployment: arm versions on dockerhub

### ISSUE THREAD

**Issue by alceasan** [pomerium/pomerium#1031]
The last image aviable for ARM arch on dockerhub is version 0.8.3, ¿are new versions not planned to be released on dockerhub for ARM anymore?

**Comment by desimone** [comment]
\cc @travisgroth

**Comment by travisgroth** [comment]
HI @alceasan - we've switched to envoy for our proxy implementation and they, unfortunately, don't have any official arm images published at this time.  

https://github.com/tetratelabs/getenvoy/issues/82
https://github.com/tetratelabs/getenvoy/issues/84
https://github.com/envoyproxy/envoy/issues/1861

Creating our own build is something we've begun working on, but the envoy build ecosystem is a bit complicated and the task isn't completed yet.  It is definitely something we want to bring back; just a matter of priorities.  

FWIW, it looks like some progress is being made in 1861 that may be helpful.

**Comment by calebdoxsey** [comment]
Unfortunately emulating arm64 locally on amd64 hardware is incredibly slow and it will take too long to compile envoy. We will need to run the compilation on cloud hardware. AFAIK GCE does not currently offer arm instances, but AWS does so that's likely our best option.

Even with fast hardware compiling envoy takes several hours.

**Comment by travisgroth** [comment]
Hi @alceasan - we have now resumed publishing Linux/Arm64 images, starting with v0.10.0-RC3.

**Comment by alceasan** [comment]
No arm32 images? Last builds are version 0.8.4

**Comment by travisgroth** [comment]
Hi there @alceasan - not at this time.  We're leaning on upstream work and the only build that is officially supported is arm64.  Unsure if arm32 works at this time.

OOC, what platform are you on that is arm32?

**Comment by alceasan** [comment]
I have Pomerium deployed on a Raspberry Pi 4, but Raspbian ([Raspberry Pi Os](https://www.raspberrypi.org/downloads/raspberry-pi-os) now) only supports as official armv7 arch (32 bit) by now.

**Comment by travisgroth** [comment]
Thanks.  Appreciate the context.  

I opened https://github.com/pomerium/pomerium/issues/1352 to track 32bit support.

**Comment by Knappek** [comment]
Raspbian 64-bit version is in beta officially: https://www.raspberrypi.org/forums/viewtopic.php?t=275370
