### ISSUE TITLE
Query: Regarding additional headers and URL modifications

### ISSUE THREAD

**Issue by kumarjp** [pomerium/pomerium#1036]
I've been testing on v0.8.0 for the last 2 weeks, and I had tested addition of custom X-headers, and downstream request URL modifications, in the reverseProxyHandler in proxy.go.  Post upgrade to 0.9.0, I dont find these.  Could you advice how to do these on v0.9.0

**Comment by cuonglm** [comment]
Global wide, you can use https://www.pomerium.io/configuration/#headers, for per policy-basis, you can use https://www.pomerium.io/configuration/#set-request-headers for adding additional headers.

v0.10.x will add more functionalities to headers manipulation:

 - https://master.docs.pomerium.io/configuration/#remove-request-headers
 - https://master.docs.pomerium.io/configuration/#pass-identity-headers

**Comment by kumarjp** [comment]
Thanks.. But No, not the preconfigured ones.. The value of the header is to be generated dynamically from the request or authentication info.. For ex, X-Test-Name (not the JWT), if that's to be generated based on the authentication response..

**Comment by kumarjp** [comment]
In v 0.8.0, i was able to do this.. in proxy.go -> func: reverseProxyHandler func..  proxy.Director
func (p *Proxy) reverseProxyHandler(r *mux.Router, policy config.Policy) *mux.Router {
  ...
  // 3. Rewrite host headers and add X-Forwarded-Host header
  director := proxy.Director
  proxy.Director = func(req *http.Request) {
    req.Header.Add(httputil.HeaderForwardedHost, req.Host)
    director(req)
    if !policy.PreserveHostHeader {
      req.Host = policy.Destination.Host
    }

    //Additional custom headers, URL -> prefix stripping/modifying, etc... 
    **DoCustomModifications(policy, req)**
  }

**Comment by cuonglm** [comment]
@kumarjp to clarify, you're talking about modify pomerium source code to do what you want?

**Comment by kumarjp** [comment]
Yes,

**Comment by cuonglm** [comment]
> Yes,

Then you may want to look at https://github.com/pomerium/pomerium/tree/master/internal/controlplane.

Since v0.9.x, pomerium use an embedded envoy proxy instead of hand written proxy.

**Comment by kumarjp** [comment]
ok, sure.. thanks. will check that.
