### ISSUE TITLE
Get List of Active Sessions

### ISSUE THREAD

**Issue by wrecker** [pomerium/pomerium#1051]
**Is your feature request related to a problem? Please describe.**

I am looking to deploy pomerium in a small production environment to expose an internal app to remote users. We were using Cloudflare Access for a while but I want to switch to Pomerium. I have pomerium running successfully, but what I am missing is the ability to see which users currently have an "active" session.

**Describe the solution you'd like**

A simple internal API that I can query to get a list of active sessions.

**Explain any additional use-cases**

Similar to impersonate, the ability to clear out the session for an active user would be useful.

**Comment by calebdoxsey** [comment]
@wrecker in the latest version of Pomerium sessions are now stored in-memory in the Cache service (now renamed the Databroker service). You can get all of them using the gRPC `GetAll` method:

https://github.com/pomerium/pomerium/blob/master/pkg/grpc/databroker/databroker.proto#L63

The expected data type is `type.googleapis.com/session.Session`.

You can delete a session by using the `Set` method and setting `deleted_at` to `Now`: 

https://github.com/pomerium/pomerium/blob/master/pkg/grpc/session/session.proto#L29

You can also just restart the data broker service to erase all sessions.

**Comment by wrecker** [comment]
@calebdoxsey :+1: 
I was able to query for what I wanted with this
`./grpcurl -plaintext -d '{"type": "type.googleapis.com/session.Session"}' localhost:5443 databroker.DataBrokerService/GetAll`

Deleting a session though didn't quite work the way I expected. After deleting the session, the user whose session was deleted, couldn't access the app behind the proxy anymore. The only way was to restart the service to clear the in-memory cache. Still this is great and gets most of what I need. 
This issue can be closed.
