### ISSUE TITLE
`certificates.cert` / `certificates.key` should accept base64 in addition to file refs.

### ISSUE THREAD

**Issue by dmitrif** [pomerium/pomerium#1054]
**Is your feature request related to a problem? Please describe.**

Currently using Pomerium with "known quantities" — services that are hosted with static hostnames / ports. Working on adding possibility of spinning up n-number of services that are tagged as `internal` in Consul and having them load-balanced by Pomerium.

As we are using nomad, there is consul-template which allows templating out certs from our secret store (Vault), however they do not handle indeterminate number of templates, you can either output all certs to one file or into the config file as Base64. 

**Describe the solution you'd like**

As the framework is already there to read in Base64 values for single certs, it'd be nice for the certificates subtree to also attempt to read in Base64.

**Describe alternatives you've considered**

- Attempted using Levant in combination with Nomad to template this out but Levant does not implement consul-template and instead focuses on a subset of interactions with Consul. No integration with Vault.
- Considered created a docker image that extends Pomerium and splits out a single bundle into many certificates, which will be my fallback... but I think this feature would generally be useful.

**Explain any additional use-cases**

- Integrations with service directories like Consul with a possibility of spinning up new internal sites post-pomerium deploy.

**Additional context**

N/A

**Comment by nicgrayson** [comment]
@dmitrif Sorry to ping you. Do you have an example of running pomerium in nomad? I'm trying to do the same.

**Comment by dmitrif** [comment]
@nicgrayson Just saw this notification. Yes I do, I have HAProxy on a different server forwarding requests to the pomerium instance.
