### ISSUE TITLE
docs: add versioning to documentation

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#109]
**Is your feature request related to a problem? Please describe.**

Documentation is currently un-versioned which can create confusion when upgrading or moving between versions. 

**Describe the solution you'd like**

- Documentation to support versioning. 
- Depreciated and changed functionality should called out. 

**Describe alternatives you've considered**

Unfortunately, vuepress does not support versioning (https://github.com/vuejs/vuepress/issues/1018).

**Additional context**

- https://docusaurus.io/en/
- https://github.com/facebook/Docusaurus/issues/789
- https://middlemanapp.com/
- https://gohugo.io/documentation/

If we do switch documentation systems, URLs should stay the same.

**Comment by desimone** [comment]
Update in my thinking.

1. **Vuepress** Ideally, I'd like to stay with vuepress... it's lightweight and does the job well. Unfortunately, versioning doesn't immediately seem to be on their roadmap. There was a one-off effort but that seems to have stalled.
2. ** docusaurus** is an interesting project but seems to be getting a major v2 overhaul. I'd rather not switch systems because it would entail a bunch of time making sure URLs don't change.
3. ** Separate deployments per tagged release**  The easiest alternative might just be to deploy a separate firebase site for each tagged version of pomerium and use a separate subdomain. 

I'm leaning towards 3.

**Comment by desimone** [comment]
is pretty straight forward

1. Just have to create new site in firebase under the project
2. checkout the tag`git checkout v0.0.4`
3. add  `"target": "pomerium-0-0-4",` to `firebaes.json`
4. Apply the target `firebase target:apply hosting pomerium-0-0-4 pomerium-0-0-4`
5. `yarn docs:build && yarn docs:deploy` as always
6. ???
7.  Viola https://v0-0-4.docs.pomerium.io/

**Comment by nareddyt** [comment]
Just curious how the user will discover the documentation for their version of pomerium when they visit https://pomerium.io. I imagine either:

- Have https://pomerium.io redirect to the docs for the latest stable release of pomerium (such as https://v0-0-4.docs.pomerium.io)
- Provide the user with a list of versions to their corresponding documentation subdomain

**Comment by desimone** [comment]
Well right now we have a link on the navbar which is... minimal and puts a lot of the onus on the end user to find out the correct docs.
![Screen Shot 2019-05-29 at 4 56 42 PM](https://user-images.githubusercontent.com/1544881/58598838-c107cb80-8232-11e9-83ef-5960990dd7e3.png)

One option is maybe add a get parameter to the "powered by pomerium" logo on the troubleshooting page and then write a small program to redirect the user to the appropriate docs based on that?

<img width="942" alt="Screen Shot 2019-05-19 at 10 30 31 PM" src="https://user-images.githubusercontent.com/1544881/58598809-a9c8de00-8232-11e9-92a0-7083a739aed4.png">
^ for reference

**Comment by nareddyt** [comment]
I do like the nav-bar implementation, but it would be more apparent if we force the user to choose a version to view documentation for. One possible way to do so:

- Don't display the "Config Reference" on pomerium.io. Only include the "Documentation" and "Quick Start" sections on the main webpage
- Place all the latest documentation on a subdomain like https://latest.docs.pomerium.io/
- Add `latest` to the list of versions

Then it would be obvious to the user which version of documentation they are viewing. Thoughts? Would this be too difficult to implement with the current way we handle docs?

I'm not sure how much value changing the hyperlink would provide. Most of the time when I needed documentation, I would come directly to this github repo or pomerium.io (even when I landed on an error page). But I can work on that if you think it would be used!

**Comment by nareddyt** [comment]
To be honest, even the "Quick Start" section and some parts of the "Documentation" section need to be versioned. Not sure how much we'd move away from the main page to handle versioning.

**Comment by desimone** [comment]
As you mentioned, we could change the landing page of `docs.pomerium.io` (which isn't doing much of anything today) to be a list of all the documentation versions, like you said...
- https://latest.docs.pomerium.io/ (which is an alias to docs.pomerium.io)
- https://v0-0-4.docs.pomerium.io/
- https://v0-0-5.docs.pomerium.io/ 
- and so on

> I'm not sure how much value changing the hyperlink would provide. Most of the time when I needed documentation, I would come directly to this github repo or pomerium.io (even when I landed on an error page). But I can work on that if you think it would be used!

It's low priority and we could backfill this functionality but basically my thinking is since we know what version someone is using, we might as well direct them to the correct docs given their version. As you said though, it will probably be more useful to endusers than administrators.

**Comment by desimone** [comment]
@nareddyt Changes are up @ https://www.pomerium.io/ let me know what you think.

**Comment by nareddyt** [comment]
> @nareddyt Changes are up @ https://www.pomerium.io/ let me know what you think.

Looks pretty good. My only comment is perhaps we can make it more obvious that the current webpage is documentation for a given version. Something like this?

![image](https://user-images.githubusercontent.com/11142171/59439366-0509dd00-8daa-11e9-998b-093490caefb4.png)
