### ISSUE TITLE
Impersonate form visible for non-administrators

### ISSUE THREAD

**Issue by shreyaskarnik** [pomerium/pomerium#1090]
## What happened?
Non-administrator user was logged in and upon going to the `.pomerium` page saw this 
![image](https://user-images.githubusercontent.com/311217/87736142-3d89a080-c78c-11ea-80df-e5c300189fd6.png)
 

## What did you expect to happen?
The sign-in as/impersonate form should only be visible to administrators

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
```
pomerium/0.9.4 (+https://wwww.pomerium.io; 167c079; go1.14.5)
```

**Comment by desimone** [comment]
Related to https://github.com/pomerium/pomerium/pull/979
\cc @cuonglm

**Comment by cuonglm** [comment]
The issues was fixed for v0.10.x, not for v0.9.x

Should we backport @desimone ?

**Comment by desimone** [comment]
Yes, I think so.

**Comment by cuonglm** [comment]
Fixed in https://github.com/pomerium/pomerium/commit/ef2e5869b6a3e295c65c898f37871df1640aa0ce
