### ISSUE TITLE
Impersonation email not used when impersonating user

### ISSUE THREAD

**Issue by shreyaskarnik** [pomerium/pomerium#1091]
## What happened?
* Admin user impersonated an user in the same domain
* Restricted page was visible upon impersonation
* Triaging this issue with @desimone it seems like this is a regression and the admin identity is being used for policy evaluation. 

## What did you expect to happen?
* Upon impersonation the non-admin user should get 401 for a restricted page. 

## What's your environment like?

```
pomerium/0.9.4 (+https://wwww.pomerium.io; 167c079; go1.14.5)
```

**Comment by cuonglm** [comment]
> Triaging this issue with @desimone it seems like this is a regression and the admin identity is being used for policy evaluation.

This is not a regression though, I can reproduce with v0.8.4, v0.9.4 and master as well
