### ISSUE TITLE
WebAuthn / U2F support

### ISSUE THREAD

**Issue by sim1** [pomerium/pomerium#113]
It would be great to be able for users to support 2FA by allowing users to add their U2F keys. https://github.com/clems4ever/authelia/ is a similar project providing this functionality.

**Comment by desimone** [comment]
Hi @chauffer thank you for creating an issue. 

Pomerium does support 2FA/MFA authentication but is turned on and enforced by the underlying identity provider. For example, in the [synology docs](https://www.pomerium.io/guide/synology.html) I'm use my U2F key as an additional factor. Would that work?

**Comment by chauffer** [comment]
Not really, as I do use U2F on my Google account, but there's no way for Pomerium to know whether I do or not.
This is useful when sharing backends outside of an organisation; where there is no way to enforce it at the organisation level.

This can also prevent attacks where the attacker can login the account but doesn't have the U2F device.
Google by default allows OTP+U2F, and only after scary warnings do they let you disable OTP.

**Comment by yegle** [comment]
@chauffer since you are using Google account, have you tried https://landing.google.com/advancedprotection/? I was told this effectively forces you to use U2F for each login.

**Comment by chauffer** [comment]
@yegie Yes. 

>**Google by default allows OTP+U2F, and only after scary warnings do they let you disable OTP.**

This is what I reference here. This does however not solve the issue.

**Comment by yegle** [comment]
Ah, I reviewed the Advanced Protection program and it seems like it's just an additional protection when you login to a new device or when you logged out. It doesn't require 2fa for every login.

**Comment by desimone** [comment]
@chauffer can you explain the use-case a bit more? 

I'm a huge fan of MFA/2FA but I'm concerned adding ad-hoc MFA bleeds into what I see as being the identity provider's responsibility. 

> This is useful when sharing backends outside of an organisation; where there is no way to enforce it at the organisation level.

When you say sharing backend outside of an organization, do you mean allowing access to a pomerium protected endpoint to a group of users whose identity provider you do not control? 


Current MFA support for 2FA :
- [Okta](https://help.okta.com/en/prod/Content/Topics/Security/MFA.htm)
- [Gsuite](https://support.google.com/a/answer/175197?hl=en)
- [Azure ADFS](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/configure-additional-authentication-methods-for-ad-fs)
- [Ping](https://www.pingidentity.com/en/platform/multi-factor-authentication.html)
-[Onelogin](https://www.onelogin.com/product/multi-factor-authentication)

**Comment by chauffer** [comment]
>When you say sharing backend outside of an organization, do you mean allowing access to a pomerium protected endpoint to a group of users whose identity provider you do not control?

Yes, exactly.

The usecases are two:
1. Share it with G Suite accounts which are not in an organisation I have admin access to
2. Ensure identity with a physical U2F key when accessing the service. Providers do not necessarily do this (definitely not the case for Google). This can mean the difference between a compromised account being able to access the service and not. In case the user is compromised, they can still be forced at Pomerium level to use U2F.

**Comment by desimone** [comment]
Haven't had time to dive into this but I saw the following which may ease support.

- [Users of U2F APIs should migrate to Webauth](https://groups.google.com/a/chromium.org/forum/#!msg/security-dev/BGWA1d7a6rI/W2avestmBAAJ)
-[Web_Authentication_API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)

**Comment by chauffer** [comment]
Changed the title to reflect the fact WebAuthn is slowly taking over over supportly U2F directly.

**Comment by darks73** [comment]
There is a way for the IDP to tell downstream services which authentication factors were used.

https://tools.ietf.org/html/rfc8176
Authentication Method Reference Values - or in short amr.
An addition claim that states which auth methods were used.

For example:
"amr": ["pwd", "kba"]

**Comment by desimone** [comment]
Thanks @darks73  -- Do you know which IdP's currently support this claim?

**Comment by darks73** [comment]
> Thanks @darks73 -- Do you know which IdP's currently support this claim?

Well, worst case you can usually manually add them. In the end it is just another claim. I do know that Microsoft will rely on amr claims for 3rd party integration in the future so there is a good chance that it will be common soon.

**Comment by desimone** [comment]
FYI -- https://github.com/pomerium/webauthn

**Comment by desimone** [comment]
This should be dropping in the next release. Stay tuned :) 

Related:

- https://github.com/pomerium/pomerium/pull/2700
- https://github.com/pomerium/pomerium/pull/2699
- https://github.com/pomerium/pomerium/pull/2696
