### ISSUE TITLE
Accessing via pomerium using programatic client returns login page

### ISSUE THREAD

**Issue by lyndon160** [pomerium/pomerium#1130]
## What happened?

Following the example from https://github.com/pomerium/pomerium/tree/master/examples/traefik I have successfully setup the example with my IDP (Keycloak) to work with the browser login.

However, when I try to access the page programmatically using either curl or postman with a bear token obtained using password grant, 

## What did you expect to happen?

I expected to see the response from the httpbin application in postman/curl

## How'd it happen?

1. Ran docker-compose up with the example above
2. Configured postman to get a token from IDP using my user and the same client that pomerium is configured with
3. Hit send, and got redirected to the login page, instead of seeing the response from httpbin

## What's your environment like?

- pomerium/0.10.0-rc2 (+https://wwww.pomerium.io; bfc726e; go1.14.6)
- macos (10.15.5), docker-compose (docker engine 19.03.12, compose 1.26.2)

## What's your config.yaml?

```config.yaml
pomerium_debug: true
address: :80
shared_secret: <removed>

insecure_server: true
forward_auth_url: http://pomerium
authenticate_service_url: https://authenticate.localhost.pomerium.io

idp_provider: oidc
idp_client_id: <removed>
idp_client_secret: <removed>
idp_scopes: ["openid", "email", "profile"]

jwt_claim_headers: ["email", "user-id", "tenant", "profile"]

cookie_secret: <removed>

idp_provider_url: <removed>

policy:
  - from: http://httpbin.localhost.pomerium.io
    to: http://httpbin
    allowed_domains:
      - <removed>


```

## What did you see in the logs?
Key logs:
```pomerium_1  | 9:22AM ERR proxy: could not locate session from context error="internal/sessions: session is not found"```
```pomerium_1  | 9:22AM INF authenticate: session load error error="Bad Request: internal/sessions: session is not found"```

Full logs for request in debug mode:
https://pastebin.com/Q5y82XDr

**Comment by cuonglm** [comment]
It works for me with [commit]()

```
$ pipenv run python scripts/programmatic_access.py --dst "https://httpbin.localhost.pomerium.io/headers"
==> request
https://httpbin.localhost.pomerium.io/headers
==> response.status_code
200
==>response.text
{
  "headers": {
    "Accept": "application/json",
    "Accept-Encoding": "gzip, deflate",
    "Authorization": "Pomerium eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aGVudGljYXRlLmxvY2FsaG9zdC5wb21lcml1bS5pbyIsImxvY2FsaG9zdDo4MDAwIiwiYXV0aGVudGljYXRlLmxvY2FsaG9zdC5wb21lcml1bS5pbyJdLCJleHAiOjE1OTU1MjMxNjQsImlhdCI6MTU5NTUyNDIyMCwiaXNzIjoiYXV0aGVudGljYXRlLmxvY2FsaG9zdC5wb21lcml1bS5pbyIsImp0aSI6ImE3MzQxYTIzLTc4Y2EtNGMyMi05Njk3LWIzNmNkMmI4NzNkOCIsIm5iZiI6MTU5NTUyNDIyMCwicHJvZ3JhbWF0aWMiOnRydWUsInN1YiI6IjI3OTY3MCIsInZlciI6ImFhMmY0NjY3LTMzZTktNGQ4ZS1iZmNhLWZlZWFjNjUzMjdmMiJ9.9f_c96DHS4Qc7YJyWK8EPDSUhIoL-SBj8Ad_3_V8ggw",
    "Content-Type": "application/json",
    "Host": "httpbin.localhost.pomerium.io",
    "User-Agent": "python-requests/2.24.0",
    "X-Forwarded-Host": "httpbin.localhost.pomerium.io",
    "X-Forwarded-Server": "672975597b5f",
}

**Comment by calebdoxsey** [comment]
AFAIK this use case is not supported.

Users must go through the authenticate service to have access via the authorize service. Pomerium sessions are stored in a databroker service populated by authenticate and queried by authorize.

Generating a token via a separate mechanism, even with the same client credentials, will not log a user into Momerium.

**Comment by lyndon160** [comment]
@calebdoxsey thanks for pointing that out, I started to get that feel from the Docs.

It's a shame as Pomerium ticks so many other boxes. Is there a reason this flow is not supported? It's a fairly common flow for m2m communications. Most if not all of the other popular IAPs support this flow.

I will close this issue as the cause is by design.

**Comment by lyndon160** [comment]
@cuonglm unfortunately that does not help me for my use case as I don't have control over how the clients interface with the backend API. They simply have a bearer token in the header.

**Comment by hammadzz** [comment]
I have a use case that this is fitting for and am wondering what the alternative is going to be.

I want to secure ArgoCD with Pomerium. It will be publicly accessible through this proxy. Unfortunately this restricts programmatic access by CI tools like GitHub actions that need to invoke the ArgoCD API via the cli tool.

I imagine this is a common use case for others as well.
