### ISSUE TITLE
Path stripped from `to` URI starting in v0.9.0

### ISSUE THREAD

**Issue by jfcantu** [pomerium/pomerium#1136]
## What happened?

Starting with v0.9.0, Pomerium appears to strip the path from URI specified in the `to:` directive if one is specified. 

## What did you expect to happen?

Prior to v0.9.0, Pomerium would include the path in the proxied requests.

## How'd it happen?

I have the following proxy policy set up:

```yaml
policy: 
- from: https://kibana.[redacted] 
  to: http://proxy-mapper-nginx:8081/kibana 
```
Trying to access `https://kibana.[redacted]` instead returns the nginx default install page, and the nginx logs show a request for the URI root:

127.0.0.1 - - [24/Jul/2020:22:33:26 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" 

Trying to access `https://kibana.redacted/test` returns a 404 and shows requests for `/test` in the nginx logs.

Doing the same thing while running a Pomerium version prior to v0.9.0 shows requests being proxied to subpaths of `/kibana`.

## What's your environment like?

- Tested on Pomerium v0.9.0 and v0.9.5.

**Comment by desimone** [comment]
Additional context here: https://pomerium-io.slack.com/archives/CK92MUAES/p1595616693306100

@jfcantu : Where you able to compare the differences in the request headers that hit nginx?

**Comment by jaguarcy** [comment]
I've experienced the same issue with the switch to envoy, but assumed it was WAI.

**Comment by calebdoxsey** [comment]
This appears to be fixed on master. I believe from this PR: https://github.com/pomerium/pomerium/pull/1034.
