### ISSUE TITLE
How to add / use other auth providers

### ISSUE THREAD

**Issue by joe-getcouragenow** [pomerium/pomerium#1137]
**Is your feature request related to a problem? Please describe.**

The internal namespace has about 6 auth providers, but we want to add our own....

**Describe the solution you'd like**

The ability to add ours on the side.

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

Its because we do not want to rely on other for providing Auth, Users and roles. It is for privacy reasons, and also for self control reasons.
Its also because we want to be able to extend things to support WebAuthN and Fido 2

**Comment by cuonglm** [comment]
@joe-getcouragenow If your auth provider supports OIDC, you can easily make pomerium uses it, by providing all necessary configurations.

See https://www.pomerium.io/configuration/#identity-provider-client-id for all details configurations.

**Comment by desimone** [comment]
I believe generic, locally hosted, OIDC provider support is reasonably covered in the documentation now.

https://www.pomerium.com/guides/local-oidc.html
https://www.pomerium.io/reference/#authenticate-service

_Nota bene: To pull back custom directory information to write policies against groups, custom provider support will have to be added._

For examples see: 

- https://github.com/pomerium/pomerium/tree/master/internal/directory
- https://github.com/pomerium/pomerium/tree/master/internal/identity
