### ISSUE TITLE
Use Pomerium to Authenticate an API

### ISSUE THREAD

**Issue by Djiit** [pomerium/pomerium#1141]
**Is your feature request related to a problem? Please describe.**

I want to authenticate my APIs with a JWT validation layer. Can this layer be Pomerium ?

Pomerium is really great to authenticate users from their browser, can I use it with API access where users give a Auth header containing a JWT ?

**Describe the solution you'd like**

As in solutions like [NGINX Plus JWT](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-jwt-authentication/) or  [Kong JWT plugin](https://docs.konghq.com/hub/kong-inc/jwt/), I'd like Pomerium, with the right configuration, to be able to validate a "machine to machine" access to my APIs. It should be responsible for verifying that a valid JWT is contained in the user request.

**Describe alternatives you've considered**

- NGINX Plus JWT
- Kong JWT plugin
- Add Auth in every APIs
- Create an API to valite every request (seems like a job for Pomerium?)

**Additional context**

Is this already a feature ? Did I miss something in the docs ?

Thanks

**Comment by cuonglm** [comment]
I think [this](https://www.pomerium.io/docs/reference/programmatic-access.html#components) is what you want, though you still need a browser to get the token.

**Comment by Djiit** [comment]
Hey, thanks for your quick answer !

No, I really need to do a JWT validation like the other listed alternatives do.

**Comment by cuonglm** [comment]
> Hey, thanks for your quick answer !
> 
> 
> 
> No, I really need to do a JWT validation like the other listed alternatives do, without any browser actions.

Sorry, this is not supported, see https://github.com/pomerium/pomerium/issues/1130#issuecomment-663154929
