### ISSUE TITLE
pkg/storage/redis: spurious i/o timeout error messages

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#1154]
## What happened?

When using the redis backend, I'm seeing regular errors from timeouts when log level is debug:

```
{"level":"debug","error":"read tcp 127.0.0.1:50134->127.0.0.1:6379: i/o timeout","time":"2020-07-28T22:14:37-04:00","message":"redis subscribe error"}
{"level":"debug","error":"read tcp 127.0.0.1:50135->127.0.0.1:6379: i/o timeout","time":"2020-07-28T22:14:41-04:00","message":"redis subscribe error"}
{"level":"debug","error":"read tcp 127.0.0.1:50136->127.0.0.1:6379: i/o timeout","time":"2020-07-28T22:14:51-04:00","message":"redis subscribe error"}
{"level":"debug","error":"read tcp 127.0.0.1:50137->127.0.0.1:6379: i/o timeout","time":"2020-07-28T22:15:08-04:00","message":"redis subscribe error"}
```

## What did you expect to happen?
No errors when working normally

## How'd it happen?

1. Enabled redis databroker backend
2. Started with either existing or empty redis store
3. Errors occur regularly

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): 72b6347886bd4faeb12ec0025b133643de8f01ba
- Server Operating System/Architecture/Cloud: OSX

## What's your config.yaml?

```config.yaml
...
databroker_storage_type: redis
databroker_storage_connection_string: 127.0.0.1:6379
```

## Additional context

I think this is the `doNotify()` code timing out every second.  

- If I'm understanding the intent of the code correctly, I believe we should be blocking for much longer there to minimize the chance of missed messages
- If this is indeed just a lack of update before the timeout, we should try to differentiate a timeout from an actual error

**Comment by cuonglm** [comment]
I think we can safely remove the debug log. The open question is, whether we should make the timeout configurable?
