### ISSUE TITLE
Setting to threat email as case-insensitive

### ISSUE THREAD

**Issue by mig4ng** [pomerium/pomerium#1194]
**Is your feature request related to a problem? Please describe.**

The auth provider I am using threats emails as case-insensitive. Some users have uppercase letters (e.g. the first letter of the name) in their email addresses but in all the tools (e.g. internal tools/apps, gmail, etc) these uppercase letters are ignored. In other words emails are handled as case insensitive.

Pomerium threats email as case sensitive (and there is nothing wrong about this) yet I believe it could have a setting to enable Pomerium to threat email as case insensitive as it is the case with many services.

**Describe the solution you'd like**

A setting that when enabled would make Pomerium thread emails as case-insensitive for all the policies (e.g. when configuring the `allowed_users` of a policy).

**Describe alternatives you've considered**

None, yet I am open to suggestions 😄 

*Explain any additional use-cases**

That I remember none, yet it helps the users of Pomerium to debug some strange behavior. 

**Additional context**

**I would love to develop this feature myself if possible.** I have close to none experience in Go, yet with some guidance (and of course harsh code reviews 😅) I am sure I am able to complete it.

Opening this issue to check first if this would be a feature that makes sense and asking for advice on how to initially tackle its development.

**Comment by cuonglm** [comment]
cc @desimone

**Comment by desimone** [comment]
Hi @mig4ng  -- Totally understand why this would be helpful to you and appreciate you offering to contribute the implementation. However, to keep our code paths as concise / simple to manage (especially around authorization controls) I would prefer to keep everything case sensitive for the moment. 

I know it's a bit of a pain given your existing workflow but, would it be possible to get a case sensitive list of the user addresses you are writing for?

**Comment by mig4ng** [comment]
It is okay, it was just a nice to have, I understand that this might be a bloat feature. Even more if it complects the paths of the currently simple and concise code.

This is one great example that would go nicely into a patch (e.g. DWM Patches https://dwm.suckless.org/patches/) which changes the code directly instead of adding complexity but requires compilation. 

Can you give me a small guide of what files would require change in order to make this change hard-coded (in a patch or fork)? I still would like to try and do this even if it does get merged to the upstream 😄

**Comment by cuonglm** [comment]
@mig4ng you may want to look at `func (e *Evaluator) newInput(req *Request, isValidClientCertificate bool) *input`, which prepares data for passing to rego.
