### ISSUE TITLE
Make dashboard Sign Out destination configurable

### ISSUE THREAD

**Issue by bradjones1** [pomerium/pomerium#1213]
**Is your feature request related to a problem? Please describe.**

It would be helpful if the destination for redirection after sign out via the dashboard (`https://proxy-service/.pomerium`) were configurable.

**Describe the solution you'd like**

Configuration option for the proxy service's dashboard to make the redirection after sign out configurable.

**Describe alternatives you've considered**

Not sure what alternatives might exist here?

**Explain any additional use-cases**

None yet.

**Additional context**

N/a

**Comment by desimone** [comment]
At one point we definitely supported this. 

https://github.com/pomerium/pomerium/pull/183

**Comment by cuonglm** [comment]
@desimone I don't think this is a bug, but a feature request. Pomerium still supports `redirect_url` in query params when performing SignOut. What the OP wants, seems to make a configuration for that redirect uri, so if it's not present in query params, pomerium will use that value.

**Comment by desimone** [comment]
@cuonglm , sounds good. Either way, I think this is reaosnable to support.

**Comment by bradjones1** [comment]
Wow, talk about a quick turnaround - thanks everyone!
