### ISSUE TITLE
"Edit this page on GitHub" links broken

### ISSUE THREAD

**Issue by bradjones1** [pomerium/pomerium#1216]
## What happened?

Clicked the "Edit this page on GitHub" link on https://www.pomerium.io/configuration/ and received a 404 at the destination, https://github.com/pomerium/pomerium/edit/master/docs/configuration/readme.md

## What did you expect to happen?

It should have sent me to https://github.com/pomerium/pomerium/blob/master/docs/reference/readme.md

## How'd it happen?

1. Visit a documentation page as above
1. Be sent to the wrong path.

## Additional context

n/a

**Comment by desimone** [comment]
Hi @bradjones1 thanks for making this issue. We recently renamed `configuration` to `reference` paths on `master` so I think that's where the disconnect is coming from. 

E.G. if you go to https://master.docs.pomerium.io/reference/#google-cloud-serverless-authentication-service-account and click edit, it should work. 

Unfortunately, the default button to edit a page is actually being built from `:latest` which is slightly out of date. 

I'm not sure of a great way of fixing this without making docs be built from master ; or having docs being aware of what branch the are on.

**Comment by bradjones1** [comment]
@desimone No worries, obviously I found the right page (thanks for the quick merge!) but figured I'd open this in case it was "really" an issue. Static sites can be tough in this regard. I'll defer to you of course whether this should stay open/is actionable or not.

**Comment by desimone** [comment]
I'm going to close for now; this should be a temporary issue.
