### ISSUE TITLE
Certificate renewal process blocks envoy from starting on startup

### ISSUE THREAD

**Issue by jaguarcy** [pomerium/pomerium#1232]
## What happened?
* Valid certificates eligible for renewal, port 80 firewalled to the pomerium instance. Pomerium serving traffic just fine.
* Pomerium container restarts
* No routes resolve, no traffic flows through the proxy.

## What did you expect to happen?

* Pomerium to continue serving with the old certs.

If anything, even if the certs were expired, I'd have expected pomerium to continue serving with expired certs, rather than block access alltogether. As long as the certs aren't revoked, they should still be usable.

## How'd it happen?

1. Restarted pomerium container
2. Everything failed silently.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): 0.9.6 (tried from 0.9.0 to 0.10.0, same behavior)
- Server Operating System/Architecture/Cloud: Docker on DSM (Synology)

## What's your config.yaml?

The only settings that matter are

auto_cert: true

Anything else was irrelevant.

## What did you see in the logs?

Only INFO logs from the certificate maintenance routine. Letsencrypt was timing out trying to access the /.well-known/.. endpoint. 100% of the logs were related to my firewall issues, which are not related to this bug.

## Additional context

The biggest problem I think is that pomerium is failing completely silently. No logs other than "Letsencrypt is timing out". Which is technically what's broken, but it doesn't explain why envoy isn't running, there are valid certificates present.

Also, huge red herring, because the trick is Letsencrypt is actually timing out on the "http" endpoint. Having missed that little tidbit, I was thinking that the letsencrypt timeout was a side-effect (Since the https endpoints, which should be valid, were not resolving - envoy wasn't running at all).

**Comment by cuonglm** [comment]
@jaguarcy Thanks for reporting.

Would you mind trying `gnouc/pomerium:1232` image, which contains [this fix](https://github.com/pomerium/pomerium/pull/1237)

**Comment by jaguarcy** [comment]
Unfortunately all of my certs are now renewed, don't have any that are close to expiry. And since this fix only allows re-using valid certs in case renewal fails (i.e. won't bring up envoy if the initial issuing fails, which fair enough - it makes sense from a security pov), I don't think I have a way to test.

**Comment by desimone** [comment]
I'm not sure this is fixed per: https://github.com/pomerium/pomerium/pull/1237#pullrequestreview-464002551

**Comment by jaguarcy** [comment]
It might have fixed it in a roundabout way, considering this would allow cert renewal to move forward.

The main question I guess is how much it matters that pomerium is unresponsive during startup while renewal is happening, and whether pomerium being completely dead on restart in case someone ignores the errors and lets the certs expire.
