### ISSUE TITLE
Forward auth redirect uri is loosing the path

### ISSUE THREAD

**Issue by mike-code** [pomerium/pomerium#1248]
## What happened?

I hit the authz endpoint with a redirection uri like so
`http://10.133.38.108:6000/?uri=https://redacted.acme.com/my_path?foo=bar` 
I can see in the logs that the request path was `path=/my_path?foo=bar` although the `pomerium_redirect_uri` will be missing the `my_path` string from the location uri (check additional context below for full HTTP response).

## What did you expect to happen?

The Location header in the response should not omit the `my_path` in `pomerium_redirect_uri`.

## How'd it happen?

(explained in what happened)

## What's your environment like?

docker image (latest)
`pomerium/0.10.0 (+https://wwww.pomerium.io; bfc3fb6; go1.14.7)`

## What's your config.yaml?

```config.yaml
services: "all"
address: ":6000"

insecure_server: true
pomerium_debug: true
cookie_secret: "<redacted>"
shared_secret: "<redacted>"

idp_provider: "gitlab"
idp_client_id: "<redacted>"
idp_client_secret: "<redacted>"
idp_service_account: "<redacted>"

idp_scopes: openid,profile,email,read_user,read_api

authenticate_service_url: "https://authenticate.acme.com"
forward_auth_url: "http://10.133.38.108:6000"

proxy_log_level: "info"
log_level: "info"

policy:
  - from: 'https://redacted.acme.com'
    to: 'https://1.1.1.1'
    timeout: 10s
    allowed_groups: ["<redacted>"]
```

## What did you see in the logs?

```logs
pomerium_1  | 4:46PM ERR proxy: could not locate session from context error="internal/sessions: session is not found"
pomerium_1  | 4:46PM INF authorize check allow=false check-request-id=e3f48511-435e-4df7-a1a4-01111bc13b78 host=redacted.acme.com method=GET path=/my_path?foo=bar query= request-id=ec16fd71-d696-45b4-b724-65ebfcd74ff4 service=authorize status=401
pomerium_1  | 4:46PM INF http-request authority=10.133.38.108:6000 duration=3.384647 forwarded-for=10.133.101.75 method=HEAD path=/?uri=https%3A%2F%2Fenv%2Estaging%2Ewocozon%2Edev%2Fmy%5Fpath%3Ffoo%3Dbar referer= request-id=e3f48511-435e-4df7-a1a4-01111bc13b78 response-code=302 response-code-details=via_upstream service=envoy size=0 upstream-cluster=pomerium-control-plane-http user-agent=haproxy-lua-http/1.0
```

## Additional context

HTTP Response from pomerium
```
HTTP/1.1 302 Found
content-type: text/html; charset=utf-8
location: https://authenticate.acme.com/.pomerium/sign_in?pomerium_callback_uri=https%3A%2F%2Fredacted.acme.com%3Ffoo%3Dbar&pomerium_expiry=1597078621&pomerium_forward_auth=10.133.38.108&pomerium_issued=1597078321&pomerium_redirect_uri=https%3A%2F%2Fredacted.acme.com%3Ffoo%3Dbar&pomerium_signature=<redacted>
set-cookie: _pomerium=; Path=/; Expires=Mon, 10 Aug 2020 15:52:01 GMT; Max-Age=0; HttpOnly; Secure
x-pomerium-intercepted-response: true
date: Mon, 10 Aug 2020 16:52:01 GMT
content-length: 381
x-envoy-upstream-service-time: 3
server: envoy
```

**Comment by cuonglm** [comment]
What's the proxy you use, nginx or traefik?

**Comment by mike-code** [comment]
It's neither, but the example was done via cURL

**Comment by cuonglm** [comment]
> It's neither, but the example was done via cURL

So it won't work as you expected.

Pomerium currently only supports Nginx and Traefik in forward auth mode. The request you used `http://10.133.38.108:6000/?uri=https://redacted.acme.com/my_path?foo=bar` is the one that match traefik handler. But traefik send the uri via `X-Forwarded-Uri` header, instead of via raw path like that, so pomerium will ignore the rest of your raw url path.
