### ISSUE TITLE
Add docker image for arm64v8 architecture

### ISSUE THREAD

**Issue by deltabweb** [pomerium/pomerium#125]
Hi,
Great project

It would be great if a docker image for arm64 could be added as more and more SBC are using this architecture.
I was able to build the docker image by using the existing `Dockerfile.arm32v7` file and changing
```
ENV GOARCH=arm
ENV GOARM=7
```
to
```
ENV GOARCH=arm64
```

**Comment by desimone** [comment]
@deltabweb Thanks! Happy to accept a PR.

**Comment by deltabweb** [comment]
Sure, I can create the `Dockerfile.arm64` file but I am unsure of what else needs to be done?

**Comment by desimone** [comment]
I’ll set it up on Docker hub side. Thanks!

**Comment by deltabweb** [comment]
I have just created the pull request
