### ISSUE TITLE
Logging out of pomerium doesn't cancel websocket connection

### ISSUE THREAD

**Issue by karelbilek** [pomerium/pomerium#1279]
## What happened?

Start WebSocket connection in pomerium-protected app.

After logging out of pomerium, websockets are still going on, despite user being logged out.

## What did you expect to happen?

The WebSocket will be cancelled, as if the server was turned off.

## How'd it happen?

1. run docker compose, similar to this one

https://github.com/pomerium/pomerium/blob/master/examples/tiddlywiki/docker-compose.yaml#L13

with this simple WS echo service

```
helloworld:
  image: jmalloc/echo-server:latest
  ports:
    8080:80
```

and with
`allow_websockets: true` 
in policy

2.
go to `[service]/.ws`, send WS messages back and forth (everything working as it should)

3. go to `[service]/.pomerium/` in a new tab, click on sign out

4. in the previous tab, the user can still send WS messages back and forth. The logout didn't do anything. 

Reloading the tab correctly gets me to login; I think (not sure) new WS connections are not allowed; but existing keep working until I close them

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
Tried with both self-built master and docker latest

- Server Operating System/Architecture/Cloud:
Tried with both docker-compose and k8s cluster

## Additional context

This bug makes logging out "useless" for some apps that are heavily based on websockets.

**Comment by cuonglm** [comment]
I think this works as expected.

Websocket connection is a long lived connection, one connected, the client and server will do communication via that long lived connection, instead of creating new connection for every packet. The authz check is only performed for the initial request, that's why when you logging out in other tab, the connected connection in existing tab does not take effect.

Suggestions for solving this are welcome.

**Comment by karel-3d** [comment]
I tried to look into the proxy part and the envoy protobufs are way too complex :) and not sure if that's even the correct place

**Comment by karel-3d** [comment]
I think that if pomerium is sold as "alternative to VPN", as it is on the frontpage, it should terminate all connections when logged out. 

I'm not sure how Envoy works so I'm not sure if it's even possible.

**Comment by karel-3d** [comment]
Is it possible to tell envoy to "just" terminate all existing connections that matched the policy, when the user is logging out?

**Comment by travisgroth** [comment]
Closing this out as we've put in a way to limit the length of lingering connections.
