### ISSUE TITLE
Forward `X-Pomerium-Jwt-Assertion` in a Cookie

### ISSUE THREAD

**Issue by andreyvital** [pomerium/pomerium#1282]
Is there a way to have `X-Pomerium-Jwt-Assertion` header as a value in a cookie that is also forwarded to the destination? 

The issue is that, I have a frontend app that will be gated by Pomerium, and there's no way for me to access headers in the JS client-side and I wouldn't want to create a middle service just to forward the Cookie.

I've tried to locate documentation regarding this but didn't find any.

**Comment by andreyvital** [comment]
So Travis, imagine that I'm serving a frontend app in my upstream, I want to be able to access the authenticated user in the JS side, hence I'd need access to the token.

Since I can't read request headers in the browser (JS client side) I wouldn't be able to access that token, hence my idea to also allow to pass the identity header as a Cookie. This can be a custom config on each `policy`

**Comment by andreyvital** [comment]
@travisgroth the solution I have right now is to create a middle service that proxies the request through by reading the header and manually sending it as a Cookie down the stream...I want to use only pomerium and remove that middle service

Today:
```
https://my.service.com => Pomerium => http://read-header-and-set-cookie-proxy => https://my.protected.frontend.com
```

Ideally:
```
https://my.service.com => Pomerium (instead of sending X-Pomerium-Jwt-Assertion header, send it in a Cookie) => https://my.protected.frontend.com
```

**Comment by calebdoxsey** [comment]
@andreyvital Are you making an ajax fetch call to get data in a single page app? If so you should be able to read the headers that way: https://developer.mozilla.org/en-US/docs/Web/API/Response/headers

**Comment by andreyvital** [comment]
@calebdoxsey I don't think you understood...so basically pomerium is in front of my frontend app (which's pure JS), I need to read the cookie on the JS side to send to my API.

I don't have a way to read headers on JS client side, there's no `document.headers` like you have `document.cookie`.

**Comment by desimone** [comment]
👋 @andreyvital,

I hadn't considered this use case before. I think it's possible that we have a setting that adds a SetCookie for every requests on a given request, but I would like  to better understand the use-case before going that route.  I think we want to be careful about modifying the user's response context. I'd like to be as invisible to the end users / upstream hosts as possible. Do you mind telling me a bit more about your deployment? What is the interplay between your front and backend?  

It sounds like:

1. You have a frontend (behind pomerium) and a backend API server (is that server behind Pomerium as well?) that trusts the CA signing the attestation headers.
1.  You want to be able to forward the attestation value to the backend, and have the backend verify frontend was provided through Pomerium, and the associated users/groups attached to that. 
1. Can you put both the frontend and backend behind pomerium and use that backend to check the assertion?

**Comment by andreyvital** [comment]
Hmmm...yes I think I can put my API behind pomerium but that's something I wouldn't like.

Regarding this:

```
I think we want to be careful about modifying the user's response context.
```

You kinda have that functionality built in already with `set_request_headers` right? It'd set a header to a request downstream. What I'd need to do is like, have the same kind of thing, but with the current JWT assertion.

**Comment by andreyvital** [comment]
Any updates on this @desimone? Not sure it's something y'all have interest to go with, so feel free to close the issue if that's the case—no problem.

I just find it'd be way more simpler and cleaner for us to allow pomerium to set a Cookie with the current JWT assertion value rather than wrapping all of our APIs. There's performance concerns too I forgot to mention, because if I do what you're proposing then all the API traffic would need to go through my pomerium server—so I'd be doubling my network costs.

Here's an image to illustrate:

![undefined (2)](https://user-images.githubusercontent.com/967317/91637739-f6c0d480-e9e0-11ea-828b-557871fcac69.png)

Ideally I wouldn't have to access my API through pomerium. Since I'll have the JWT assertion on a cookie that I can read in the frontend, I can connect to my API directly (less costs, less efforts)

**Comment by desimone** [comment]
Hi @andreyvital , 

Sorry, I think I am confused because my brain is planted in the idea most of Pomerium's value is in being able to authorize / authenticate every single incoming request, and having an attestation to that effect, and I am having a hard time conceptualizing what that looks like if only the frontend code is going through pomerium, and how that would be used and extended in an authorization system not directly behind pomerium itself. 

Can you walk me through the workflow of your application a bit? Is the idea that a user will hit a frontend server behind pomerium, and if allowed,  that frontend code will be downloaded (SPA?) along with a SetCookie header that will be cached (for how long? What are the implications of that?) and then subsequent API requests will always contain that attestation cookie which can then be validated by the backend? How would the attestation-jwt get updated? How does that effect your threat model? Other than the initial download, I assume you are going to have your backend application handle all the authorization code?


> You kinda have that functionality built in already with set_request_headers right? 

Sort of. 

> It'd set a header to a request downstream. What I'd need to do is similar....but with the current JWT assertion.

The difference is that the attestation cookie would not be attesting to the authorization of the _current_ request, but rather the previous request. It would almost be like an authorization off-by-one error in this case. I suppose this is fine if all you are using Pomerium for is passing _authentication_ information (although.... it's by definition stale) to the upstream server, but this gets to be problematic if you are using Pomerium for any sort of authorization (what does this model look look like with path based authorization)?

>  There's performance concerns too I forgot to mention, because if I do what you're proposing then all the API traffic would need to go through my pomerium server—so I'd be doubling my network costs.

Can you elaborate on the performance concerns? 

Can you share a configuration / deployment configuration for context?

**Comment by andreyvital** [comment]
> Can you walk me through the workflow of your application a bit?

Well, I have a SPA that's hosted on S3. Pomerium is in front of it. If the user is authenticated, then he's allowed to see that UI.

**The issue:** from the frontend I cannot access the JWT assertion because I don't have access to headers on the client-side, hence, I cannot authenticate with my API which isn't behind Pomerium.

> Can you elaborate on the performance concerns?

Extra roundtrip to get to the destination. Instead of the frontend reaching out directly to the API, now it has to go through Pomerium and then Pomerium will talk to the API. But Pomerium is running on a limited server and can't handle all the ingress that the API has.

> Can you share a configuration / deployment configuration for context?

Unfortunately not, I tried to elaborate more or less what the setup looks like.

--

> Is the idea that a user will hit a frontend server behind pomerium, and if allowed, that frontend code will be downloaded (SPA?) along with a SetCookie header that will be cached (for how long? What are the implications of that?) and then subsequent API requests will always contain that attestation cookie which can then be validated by the backend? How would the attestation-jwt get updated? How does that effect your threat model? Other than the initial download, I assume you are going to have your backend application handle all the authorization code?

**for how long?**: for the time I've configured the expiration to be - current parameters do apply.

**What are the implications of that?**: currently — none AFAIK. If I can only get to the frontend if I authenticate through Pomerium, then the cookie should be on my hands anyway. And I guess that's more of who's using to decide if I want to take 
the risks of that cookie to be accessible by my frontend SPA app? 🤔 

**(...) will always contain that attestation cookie which can then be validated by the backend**: yessir—the frontend will the pass that JWT back to the API through each request. My backend will have code to authenticate requests based off that specific token that my frontend will set.

**How would the attestation-jwt get updated?**: whenever I refresh the page, Pomerium produces the cookie again, right? other than that, it's just me relying on a expiration higher than my expectation of how often users will refresh the page to get a new cookie haha

**How does that effect your threat model?**: can't see the threat right now TBH

**(...) your backend application handle all the authorization code?**: spot on

**Comment by namelivia** [comment]
I may be wrong, but I would say this scenario is very similar to the one discussed on #1402

**Comment by andreyvital** [comment]
Yeah @namelivia—sort of!

**Comment by desimone** [comment]
Hey @andreyvital / @namelivia -- 

As a work around, would it be possible to use the recently introduced jwt endpoint instead?

- #1369 (comment)
- #1446
