### ISSUE TITLE
Multi-Subdomain support not possible

### ISSUE THREAD

**Issue by seng-siong** [pomerium/pomerium#1302]
## What happened?

We deployed Pomerium in **full production mode** (i.e. multiple containers with dedicated service modes). We have 2 proxy nodes each serving a different subdomain (i.e. app1.example.org, app2.example.org) connected to a single authenticate service (i.e. login.example.org). The cookie domain is set to *.example.org.

The policy is configured as follows:

- from: https://app1.example.org
  to: http://app1.internal.local
  allowed_groups:
    - (some group id)
- from: https://app2.example.org
  to: http://app2.internal.local
  allowed_groups:
    - (some group id)

A user visits https://app1.example.org and authenticates himself successfully.
However, when he/she visits https://app2.example.org, access is denied with the error: "Audience is invalid"

## What did you expect to happen?
Pomerium should allow me through or at least allow me to re-authenticate.

## What's your environment like?

- Pomerium version: **v0.8.4**
- Server Operating System/Architecture/Cloud: **AWS ECS + AWS App Mesh**

**Comment by desimone** [comment]
Hey @seng-siong -- 

Multi-domain should be working. 

Could you provide a bit more context here including your redacted configurations, and the redacted contents of the session tokens that are both working and not working? In particular, what is the audience being presented that is generating the audience is invalid message? 

Thanks!

**Comment by seng-siong** [comment]
Ok. We figured out the issue. 

We remove cookie_domain from config and everything worked fine now.

Thanks @desimone for following up. I'm going to close this issue.
