### ISSUE TITLE
Configurable 403 page

### ISSUE THREAD

**Issue by bradjones1** [pomerium/pomerium#1333]
**Is your feature request related to a problem? Please describe.**

When access is denied, it would be nice to show a custom `403 Access Denied` page content, e.g., explaining to the user how to be added to the appropriate group in GitLab, and/or logout instructions to re-authenticate to Pomerium.

**Describe the solution you'd like**

Configuration option to provide or reference (perhaps through a proxied page request?) custom 403 HTML.

**Describe alternatives you've considered**

Not sure, since this would have to come server-side.

**Explain any additional use-cases**

n/a

**Additional context**

I've looked in the docs and old issues and do not see 1) an existing configuration option for this nor 2) any prior feature requests for same.

**Comment by enenum** [comment]
Sure thing.  This would be nice. The current functionality offers a debug link that leads to the session info page which leads to pomerium documentation. Pretty good stuff when you are developing, but perhaps not for customer exposure - so the session debug info should be only displayed if in debug mode or some other configurable setting...

**Comment by desimone** [comment]
The ability to white-label and support custom branding is coming in v0.19.0 on Enterprise.
