### ISSUE TITLE
Provide a way to customize the AuthN process

### ISSUE THREAD

**Issue by haohaolee** [pomerium/pomerium#1342]
**Is your feature request related to a problem? Please describe.**

Now we have policies like `allowed_users` and `allowed_groups`, but sometimes we want a more find-grained way to control the Authentication, e.g. allow users to access the services only during working days, but not the weekend (I made up this, but you got my idea)

**Describe the solution you'd like**
Maybe a well-defined webhook or API to somewhere outside can be implemented before the authentication succeeds?

**Describe alternatives you've considered**

**Explain any additional use-cases**

The idea behind this is sometimes we cannot easily define a group of people who has the access to our service, and IdP could not help us for this either. So we want an additional layer defined by the service owners to solve this for the authentication process.

**Additional context**

**Comment by desimone** [comment]
Hi @haohaolee,

This is absolutely on the roadmap. Any chance you could reach out to me offline to chat more about your specific use case? bdd[at]pomerium.com

Thanks!
Bobby

**Comment by desimone** [comment]
I believe this can be resolved per https://github.com/pomerium/pomerium/issues/1472#issue-711998960

Let me know if that is not the case @haohaolee
