### ISSUE TITLE
internal/identity: re-enable gitlab

### ISSUE THREAD

**Issue by jakesmolka** [pomerium/pomerium#136]
**Is your feature request related to a problem? Please describe.**

The docs are saying Gitlab was removed as provider because there is no access to private emails. This seems to be fixed now: https://gitlab.com/gitlab-org/gitlab-ce/issues/44435#note_156557985

**Describe the solution you'd like**

I'm new here but I'd guess most old code from the former integration should work.

**Comment by desimone** [comment]
I'd love to have gitlab back in the mix but probably won't have time to get to it in the near future. Would very much welcome the contribution though. Like you said, it should be very similar to the original implementation.

**Comment by thoth291** [comment]
It seems like the only possible auth method is Gitlab for me and my clients, but that's not working, so can't use (or even try) your wonderful project... But maybe there is someone who can pick it up?
