### ISSUE TITLE
User Info Endpoint

### ISSUE THREAD

**Issue by devstein** [pomerium/pomerium#1369]
**Is your feature request related to a problem? Please describe.**
A common pattern we've been using to get the user identity on the Frontend is to have the backend parse the Pomerium JWT header and send it back to the frontend. I noticed all of the user information is already available at the `/.pomerium` endpoint, but its an HTML page, rather than the user info in JSON form. 

**Describe the solution you'd like**
It would be very convenient to have a special endpoint, like `/.pomerium`, specifically for getting the information on the current user. 

**Describe alternatives you've considered**
We have a microservice that implements this behavior.

**Additional context**

[See Slack thread for details](https://pomerium-io.slack.com/archives/CK6SVMPU0/p1599150196054200)

**Comment by travisgroth** [comment]
Hi @devstein - after some discussion, we could add an endpoint under the `/.pomerium` path that returns the attestation JWT in the response body.  Would that work for your use case?

**Comment by devstein** [comment]
@travisgroth Yes that is exactly what I am looking for

**Comment by travisgroth** [comment]
👍  thanks for the quick feedback.

**Comment by calebdoxsey** [comment]
@devstein I just merged a change to master that will added a `/.pomerium/jwt` endpoint that returns the attestation JWT. Will that work for you needs?

**Comment by devstein** [comment]
@calebdoxsey Yes thank you!
