### ISSUE TITLE
request details link on pomerium styled error page is pointing to a wrong url

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium#1392]
## What happened?
On Pomerium styled error page with text and link  `If you should have access, contact your administrator and provide them with your request details`, `request details` link is pointing to beyondcorp.example.com/.pomerium url, instead of authentication.pomerium.example.com/.pomerium url.
 

## What did you expect to happen?
`request details` should redirect You to `authentication.pomerium.example.com/.pomerium` session dashboard.

## What's your environment like?

pomerium:v0.10.2

## Related
https://github.com/pomerium/pomerium/issues/867#issuecomment-646486331

Thanks

**Comment by desimone** [comment]
Going to tackle this as part of standardizing the interfaces for forward-auth providers.
