### ISSUE TITLE
what is free and what is not?

### ISSUE THREAD

**Issue by matti** [pomerium/pomerium#1393]
I don't think its clear what parts of this are free and what are commercial.

**Comment by desimone** [comment]
Hey @matti ,

Thanks for the inquiry. Everything publicly available today (as covered by the docs, recipes, etc) is free and open-source under the apache 2 license. 

We are working on a yet to be released enterprise version of Pomerium that is focused on using and managing Pomerium at scale. This would be an adjunct to the core product. We aren't quite ready to talk about the exact features and functionality yet publicly. The closest guide I can give you right now is we are thinking about open / enterprise will feel most similar to Hashicorp.

Hope that helps. Happy to answer any questions you may have.

Bobby

**Comment by matti** [comment]
Thank you, good answer
