### ISSUE TITLE
Question: Nested groups for Azure Authentication

### ISSUE THREAD

**Issue by Mberga14** [pomerium/pomerium#1397]
Hello, 

I have a question regardign the implementation of Pomerium with Azure AD, we have created a pomerium deployment with a `policy` that uses `allowed_groups` feature. 

The Issue is, the group specified in the Pomerium config consists of other groups ( groups are nested), but when the token for the user is returned, the membership of the user is not correct, if the user is not **directly** assigned to that group. I have searched around and have not found any configuration that would allow for checking transitive attributes of groups for user.

 I have tried giving the Service principal permissions to read directory [(See microsoft docs)](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http), but that has not solved the issue. Is there a way for pomerium to see transitive group membership of Azure AD?

Thank you for your help

**Comment by calebdoxsey** [comment]
@Mberga14 we updated the azure code to handle nested groups. This was just merged to master if you want to try it.

**Comment by Mberga14** [comment]
Hey @calebdoxsey , I finally found the time to upgrade pomerium and test it out, but my problem is still persising.  I have tested this with dynamic and assigned groups but I cannot get it working. Current setup is like this: 

* Group1, which is in the `allowed_groups` part of the pomerium config, users in here can access my page
* Group2, which is part of group1, and pomerium reports that users are part of it, but not that they are a part of group1... but pomerium returns 403 forbidden.

**Comment by calebdoxsey** [comment]
@Mberga14 sorry for the delayed response. I've not been able to reproduce this issue. Perhaps there's something different about the configuration I'm using?

I have a user that pomerium sees in these groups: 

```json
[
  "bbb1f46d-01e5-4fd1-a683-53e4d1240246",
  "c65cb541-2184-45b2-9b98-f4b91c180f38",
  "f8f3e689-668d-4536-a37b-7a7d24e4795b"
]
```

Group `f8f3e689-668d-4536-a37b-7a7d24e4795b` is named `child` and has a single user member.

![Screenshot from 2020-11-18 12-00-53](https://user-images.githubusercontent.com/395272/99575423-daa45200-2995-11eb-8c49-f079064e6761.png)

Group `bbb1f46d-01e5-4fd1-a683-53e4d1240246` is named `parent` and has a single group member:

![Screenshot from 2020-11-18 12-01-19](https://user-images.githubusercontent.com/395272/99575502-f27bd600-2995-11eb-8513-1a6a079d3899.png)

So its picking up the transitive membership. Is there something different about the way you have this setup?

**Comment by Mberga14** [comment]
Hey @calebdoxsey , the configuration you are using to test is exactly the same as I have in my environment, I am not sure why it isn't working on mine. I will test further and try to report back.

**Comment by calebdoxsey** [comment]
@Mberga14 are you running the master tag (or the 0.11 rc)? I believe these changes weren't backported to 0.10.

**Comment by Mberga14** [comment]
@calebdoxsey  I have just noticed that helm version has not been updated yet, and I deploy pomerium to my cluster with helm. I will wait for the chart to be updated. My mistake, sorry!

**Comment by Mberga14** [comment]
@calebdoxsey  Had time today to manually update the versions. Everything looks good! Thank you for your help!
