### ISSUE TITLE
POLICY_FILE is deprecated but still referenced in various places.

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#140]
E.g. https://www.pomerium.io/guide/#configure

**Comment by desimone** [comment]
I think @travisgroth has this handled, we've just split the configuration [feature into several parts.](https://github.com/pomerium/pomerium/issues/115#issuecomment-495993513)

**Comment by travisgroth** [comment]
#139 should have updates for most of the non-ref docs. Not final form but enough to work with.  

https://www.pomerium.io/reference/#global-settings looks up to date though. That went out with the deprecation PR.

**Comment by desimone** [comment]
I think it's mostly the examples that are left. 

```bash
helm/templates/authorize-deployment.yaml
61:        - name: POLICY_FILE

internal/config/options.go
230:		return errors.New("Setting POLICY_FILE is deprecated, use policy env var or config file instead")

helm/templates/all-in-one-deployment.yaml
89:        - name: POLICY_FILE

helm/templates/proxy-deployment.yaml
74:        - name: POLICY_FILE

docs/docs/examples/docker/basic.docker-compose.yml
26:      - POLICY_FILE=./policy.yaml

docs/docs/examples/docker/nginx.docker-compose.yml
45:      - POLICY_FILE=policy.yaml
73:      - POLICY_FILE=policy.yaml
```
