### ISSUE TITLE
Regression: HSTS header missing

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1413]
## What happened?
HSTS header is missing in HTTP request:

$ curl -I your-dns.run
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Type: text/html; charset=utf-8
Location: https://your-dns.run
Date: Thu, 17 Sep 2020 04:26:08 GMT

## What did you expect to happen?
HSTS header is present

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): pomerium/0.10.3 (+https://wwww.pomerium.io; 7d77dc2; go1.14.9)
- Server Operating System/Architecture/Cloud: n/a

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by yegle** [comment]
Note this happened before: https://github.com/pomerium/pomerium/issues/901

Should we have a regression test to prevent this from happening again?

**Comment by calebdoxsey** [comment]
I see the header on normal authenticated requests. Since this is a 301 it may be due to the redirect to HTTPS. I will try and reproduce.

**Comment by calebdoxsey** [comment]
@yegle I was able to reproduce with the redirect handler. I merged a fix into master if you want to try it.

**Comment by yegle** [comment]
Confirm issue fixed with container image from master branch.

**Comment by yegle** [comment]
Any chance the fix can be cherrypicked into a current release, or cut a new version now?

**Comment by desimone** [comment]
@yegle / @calebdoxsey I think we cherrypick this and add this a patch release which we can cut in the next few days. 

https://github.com/pomerium/pomerium/pull/1427
