### ISSUE TITLE
Gsuite/domain

### ISSUE THREAD

**Issue by poltakgerem** [pomerium/pomerium#1424]
I need someon can help me , because i configuration domain in my account gsuite and send mail to hotmail junk all message

**Comment by desimone** [comment]
Hi @poltakgerem ,

Do you mind reposting your issue according to the provided templates?

Thanks!

**Comment by poltakgerem** [comment]
I need fix the issue bro

Pada tanggal Sen, 21 Sep 2020 23.14, bobby <notifications@github.com>
menulis:
