### ISSUE TITLE
Ability to filter groups with Kubernetes integration

### ISSUE THREAD

**Issue by simongottschlag** [pomerium/pomerium#1425]
Hi!

We are having a problem with Azure AD integration and Kubernetes (AKS and on-prem vanilla), where users that are members of more than 200 groups doesn't get these groups in their access token but instead using distributed claims.

Azure AD distributed claims doesn't work with vanilla Kubernetes, but seems to be working fine with AKS.

Now when we want to have the same authentication with both on-prem and AKS, it doesn't work and we are trying to find a good solution. We've tried what is called "app roles" in Azure AD (appends role claim with specific strings) - but it doesn't work with nested groups which we use profusely.

The solution I'm thinking of right now is using Pomerium as a proxy for both on-prem and AKS, but I think we still may have an issue with Pomerium if there are too many groups appended. It does seem like Pomerium supports distributed claims (or at least isn't using the groups from the token but Graph API).

My question is quite simple, would it be possible to add a feature to the Kubernetes Integration where we can filter the groups that are passed to the cluster? All our AKS-groups are prefixed with "aks-" which would make this quite neat.

I wasn't able to find if this is possible today? Do you see this feature as something that could add value to the project?

Thank you!

**Comment by travisgroth** [comment]
Hi @simongottschlag - 

One thing to keep in mind.  There's an issue with users that have more than one group due to https://github.com/kubernetes/kubernetes/issues/94683.  It seems hard to solve there due to legacy compatibility, so https://github.com/envoyproxy/envoy/issues/13053 is tracking the ability to change the header format.

As to the specific feature here -  do you think you would want to only filter the groups attached to the upstream request, or would you rather filter the groups pomerium syncs?

**Comment by simongottschlag** [comment]
Hi @travisgroth!

In our use case, we don't need to forward more than perhaps 5-10 groups as separate headers and no there are proxies between the Pomerium and kube-apiserver. This should mean that the issue shouldn't (I hope) apply to our use case.

As a side note, the Azure ADs we work in contain quite a large number of groups and users - and it may be problematic to actually sync all of them on a regular basis. Looked through how the sync works and seems like it's scraping everything. Could also be other aspects of this that may be an issue, like having PII in the cluster for all groups instead of the "few" users that need to access it. 

Just to make it clear, we are not looking into the other features of Pomerium right now (but I do like them and will most likely use them in the future as well!) - we are only looking at this from the perspective of using Pomerium as a way of handling two specific issues:
* Doing blue/green deployment of managed clusters but keeping the same API address
* Handling this issue with Azure AD groups for non-AKS clusters

With all that said, it would be really great if Pomerium was able to:
* Do real-time lookup to Graph API when user logs on and extract all groups (recursive lookup/transitive) using: https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0&tabs=http
* This lookup would be done with the Azure AD access_token, which means a separate Service Principal wouldn't be required for Pomerium
* Make it possible to filter the groups extracted and cache them for the session
* Pass all the (already filtered) groups to kube-apiserver


Since the above may not be what you actually envisioned for the project, the second option would be to filter what is synced (and preferably not lookup all groups in Azure AD but only those matching the filter - with an OData filter). This would also solve possible performance issues with very large Azure ADs since we would be able to take them down to something like 10 groups (most likely not more than 50).

Not sure if users are synced, but if they are - only members of the synced groups should be synced from Azure AD as well.

Thank you for taking the time to think about it and I'll try to answer whatever you need!

Best regards,
Simon

**Comment by simongottschlag** [comment]
And as a reference, the issue we are seeing with Azure AD on-prem is talked about here: https://github.com/kubernetes/kubernetes/issues/62920
