### ISSUE TITLE
Git server support

### ISSUE THREAD

**Issue by nihaals** [pomerium/pomerium#1442]
**Is your feature request related to a problem? Please describe.**

Running a Git server behind pomerium is an interesting goal as it includes a variety of features for it to work well:
- SSH support
- Support for CLIs without patches (e.g. Git over HTTP using standard Git client)
- ~~Web client~~

(I guess this is more of a tracking issue for the goal of being able to do this)

At the moment, you could:
- Use the web client
- Keep your SSH access exposed then use Git over SSH like normal (everyone would be forced to use SSH)
- Possibly setting the endpoints to public? (Would be exposed anyway so not ideal)
- Not use pomerium (e.g. VPN just for Git)

Both GitHub Enterprise and GitLab would require similar features to work, GitLab probably being much easier to document, test and is just more popular in self-hosted instances

**Describe the solution you'd like**

- SSH support
  - One solution to do this is to have a user dashboard where they can add their SSH keys (then the SSH bastion/proxy would just use a whitelist check) but this would probably be out of scope since it’s quite different to the rest of pomerium
    - There’s also probably something out there that already does just this
    - GitHub and possibly GitLab support SSH key CAs so you could use Vault

**Explain any additional use-cases**

SSH support could allow for SSHing into servers and any CLI that connects to a self hosted instance could benefit from “CLI support”.

**Additional context**

Documenting an example GitLab integration could help users learn a wide variety of features or other software that is relevant to a BeyondCorp setup and compliments pomerium

[Cloudflare Access docs for GitLab (includes SSH)](https://developers.cloudflare.com/access/common-access-configurations/gitlab/)

**Comment by mescanne** [comment]
Looking into the same thing for me, wouldn't it make sense to simply use pomerium ssh tunneling:
https://www.pomerium.io/docs/tcp/ssh.html

Mark

**Comment by nihaals** [comment]
At the time I don't think SSH support was implemented, now that it has, this should be possible. It might still be worth adding documentation (for e.g. GitLab self-hosted) though, which will both serve as a tutorial and a chance to see if it works as expected with Git
