### ISSUE TITLE
Session lost after restarting Pomerium

### ISSUE THREAD

**Issue by whs** [pomerium/pomerium#1448]
Cont. of https://pomerium-io.slack.com/archives/CK92MUAES/p1600835890000900

## What happened?
Sessions are lost and all users get 403 errors

## What did you expect to happen?
User who are logged in can continuously use the service after Pomerium restart

## How'd it happen?

1. Login with forward auth
2. Restart all Pomerium services
3. Refresh and observe 403
4. Workaround: clear Pomerium cookie and reauth would work

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): https://github.com/wongnai/pomerium master (2364da14c81c9945b6098906bbbedcbef32919ba plus my 2 PR)
- Pomerium in HA mode (one of each service run in standalone, in Kubernetes), although 1 of each. Databroker backend is Elasticache Redis
- Using forward proxy auth

## What's your config.yaml?

```jsonnet
		AUTOCERT: 'false',
		TIMEOUT_READ: '60s',
		AUTHENTICATE_SERVICE_URL: 'https://' + gatewayHost,
		FORWARD_AUTH_URL: 'https://' + forwardAuthHost,
		JWT_CLAIMS_HEADERS: 'email,groups,user',
		AUTHORIZE_SERVICE_URL: 'http://pomerium-authorize:3000',
		CACHE_SERVICE_URL: 'http://pomerium-cache:3000',
		INSECURE_SERVER: 'true',
		GRPC_INSECURE: 'true',
		METRICS_ADDRESS: ':9000',
		TRACING_PROVIDER: 'jaeger',
		TRACING_SAMPLE_RATE: '0.1',
		TRACING_JAEGER_AGENT_ENDPOINT: services.jaeger(namespace),
```

Also

- SHARED_SECRET
- IDP_SERVICE_ACCOUNT
- IDP_REFRESH_DIRECTORY_TIMEOUT=5m
- IDP_REFRESH_DIRECTORY_INTERVAL=10m
- IDP_PROVIDER_URL=https://accounts.google.com
- IDP_PROVIDER=google
- IDP_CLIENT_ID 
- IDP_CLIENT_SECRET 
- DATABROKER_STORAGE_TYPE=redis
- DATABROKER_STORAGE_CONNECTION_STRING
- DATABROKER_STORAGE_CA_FILE
- COOKIE_SECRET
- policies (in config.yaml)
- idp_request_params

All of those env keys are provided to all pods

## What did you see in the logs?

Authorize

```json
{"level":"warn","error":"rpc error: code = NotFound desc = record not found","time":"2020-09-23T04:14:36Z","message":"failed to get session from databroker"}
{"level":"warn","error":"session not found","time":"2020-09-23T04:14:36Z","message":"clearing session due to force sync failed"}
{"level":"info","service":"authorize","request-id":"67affc94-2ff9-48e5-923c-4289e2764e8f","check-request-id":"56901530-8b4b-4c49-a293-b19e7613d6ad","method":"GET","path":"/applications/pomerium","host":"xxxx","query":"","allow":false,"status":401,"message":"login required","user":"","groups":[],"time":"2020-09-23T04:14:36Z","message":"authorize check"}
```

Cache

```json
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","id":"2e611f4d-825d-42a5-876d-4b276a1def5e","time":"2020-09-23T04:14:36Z","message":"get"}
{"level":"info","service":"databroker","type":"type.googleapis.com/directory.Group","server_version":"6a085039-e1ec-4f94-aa37-01fef026d9f8","record_version":"000000000352","time":"2020-09-23T04:14:36Z","message":"sync"}
{"level":"error","error":"ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`, ","time":"2020-09-23T04:14:36Z","message":"failed to setup redis notification"}
{"level":"info","service":"databroker","type":"type.googleapis.com/pomerium.config.Config","server_version":"6a085039-e1ec-4f94-aa37-01fef026d9f8","record_version":"","time":"2020-09-23T04:14:36Z","message":"sync"}
{"level":"error","error":"ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`, ","time":"2020-09-23T04:14:36Z","message":"failed to setup redis notification"}
{"level":"info","service":"databroker","type":"type.googleapis.com/pomerium.config.Config","server_version":"6a085039-e1ec-4f94-aa37-01fef026d9f8","record_version":"","time":"2020-09-23T04:14:37Z","message":"sync"}
{"level":"error","error":"ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`, ","time":"2020-09-23T04:14:37Z","message":"failed to setup redis notification"}
{"level":"info","service":"databroker","type":"type.googleapis.com/pomerium.config.Config","server_version":"6a085039-e1ec-4f94-aa37-01fef026d9f8","record_version":"","time":"2020-09-23T04:14:37Z","message":"sync"}
{"level":"info","service":"databroker","type":"type.googleapis.com/session.Session","server_version":"6a085039-e1ec-4f94-aa37-01fef026d9f8","record_version":"000000000519","time":"2020-09-23T04:14:37Z","message":"sync"}
{"level":"error","error":"ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`, ","time":"2020-09-23T04:14:37Z","message":"failed to setup redis notification"}
{"level":"error","error":"ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`, ","time":"2020-09-23T04:14:37Z","message":"failed to setup redis notification"}
```

**Comment by whs** [comment]
Turning on notify-keyspace-events and it seems to work. I think:

1. This should be documented. In Elasticache this can be changed in the console but cannot be changed at runtime
2. IMO application shouldn't change Redis global configuration (it shouldn't assume the Redis is single tenent) - can add a log message to warn this
3. Even though I have changed notify-keyspace-events I'm still getting the `ERR unknown command `CONFIG`, with args beginning with: `SET`, `notify-keyspace-events`, `Kz`` errors flooding the logs. This probably can be fixed in the short term or it should be done automatically with 2)

**Comment by travisgroth** [comment]
Hi @whs, are you using elasticache in clustered mode?

**Comment by calebdoxsey** [comment]
@whs I merged a change which will use a pub/sub key instead of keyspace events. We will also no longer use the CONFIG command.

**Comment by whs** [comment]
No this is not clustered Redis. I'll test from master.

Yesterday in addition to session lost, I often found that authZ decision seems to get cached when group info is not fetched. The users who get cached then cannot enter any group-locked endpoints. Sometimes even user info is not even present (only ID) and they cannot enter any endpoint at all. I'm not sure if Pomerium has a cache-clearing endpoint (/.pomerium/refresh was removed), and my attempt trying to remove some Redis keys seems to crash Pomerium.

This might be a separate issue that I probably should split to another ticket later.

**Comment by whs** [comment]
Installed from master, restarted pomerium twice, everything seems to be working properly.

I have another non-Kubernetes setup that I will try

**Comment by whs** [comment]
I'm observing random session timeouts. After a while, I get 403 error but when I clear cookie it works again

**Comment by travisgroth** [comment]
> No this is not clustered Redis. 

Okay, thanks.  Hopefully this was all related to the way keyspace notifications were used, then.

> I'll test from master.

master is quite ahead of the patch @calebdoxsey merged into `0-10-0`.  It would be best to test a build from `0-10-0`, rather than master, just to properly isolate the behavior we're working on.  

> Yesterday in addition to session lost...

Yes, if you wouldn't mind opening issues around this session behavior.  While we use pubsub to quickly signal changes from storage, problems with subscriptions shouldn't ultimately lead to what sounds like data loss.  I think we'll need to dig into what you're seeing more thoroughly, and it would be best not to conflate the conversations.

**Comment by whs** [comment]
Just restarted the non-Kubernetes setup and it seems to be working fine.

If I can reliably get session timeout issue then I'll open a new issue. Thanks!

**Comment by travisgroth** [comment]
Great.  Thanks @whs!
