### ISSUE TITLE
Support preserving path+parameters on HTTP->HTTPS redirect

### ISSUE THREAD

**Issue by ekovac** [pomerium/pomerium#1449]
**Is your feature request related to a problem? Please describe.**

I have a branded link shortener sitting behind pomerium. I'd like to be able to write the link without specifying the protocol and still have it work as expected. Eg: http://vix.link/radar (which is what users will hit first if they type 'vix.link/radar' into their address bar if they haven't visited the site before to add it to their HSTS list) will redirect to https://vix.link/, dropping the path; in the case of my specific configuration, the root on that domain is an authenticated path because it contains the admin dashboard for the branded link, and so provides no value.

**Describe the solution you'd like**

An option for the HTTP redirect server to preserve the path and parameters on the HTTPS redirect.

**Describe alternatives you've considered**

Putting nginx in front of pomerium to handle the http -> https redirect behavior. Ideally I'd like to just use pomerium's http redirector.

**Comment by calebdoxsey** [comment]
@ekovac A change has been merged to master which will preserve the path and query string when doing an `HTTP -> HTTPS` redirect.

**Comment by ekovac** [comment]
Excellent, thanks!
