### ISSUE TITLE
Auth0 Provider

### ISSUE THREAD

**Issue by lxfontes** [pomerium/pomerium#1453]
We would like to integrate Auth0 into Pomerium, allowing user/group information to be used in policy decisions.

Essentially combining logic from https://github.com/go-auth0/auth0/blob/master/management/role.go with https://github.com/pomerium/pomerium/blob/master/internal/directory/provider.go

Would Pomerium be open to a PR adding Auth0 as Directory Provider?

**Comment by desimone** [comment]
Hi @lxfontes , 

> Would Pomerium be open to a PR adding Auth0 as Directory Provider?

Definitely. 

In addition to pulling directory data back, would it make sense to integrate into auth0 as an oidc provider?

**Comment by grounded042** [comment]
Hey @desimone 👋 I work with @lxfontes at Auth0. What are the steps needed to integrate Auth0 as an OIDC provider? We have already confirmed that Auth0 works out of the box with the generic OIDC setup, but that setup didn't have groups.

**Comment by calebdoxsey** [comment]
Hi @grounded042, we separate oauth login from group data. We call the former `identity` and the latter `directory` in the code.

To implement a new directory provider create a directory under `internal/directory/` and create a type which implements the provider interface:

```go
type Provider interface {
  UserGroups(ctx context.Context) ([]*Group, []*User, error)
}

type Group struct {
  Version string
  Id      string
  Name    string
  Email   string
}

type User struct {
  Version  string
  Id       string
  GroupIds []string
}
```

The provider should return all of the users and groups for the account. `Group` and `User` are protobuf types and you can leave the `Version` field unset.

For all of the providers we have also followed a convention where a `ParseServiceAccount` package-level function is defined which returns a type that can be used by the provider for API credentials. For example it may be a bearer token, a JWT, api key + secret, etc. Typically this field is a base64-encoded string, but it's different for each provider. Although the contents of the field vary, the name is the same in the config. All of them use `idp_service_account` in the config file.

Once the implementation has been written you can add it to the global registry in `internal/directory/provider.go`. There's a switch statement with each possible provider, so just add a case for `auth0`. For example:

```go
switch options.Provider {
case auth0.Name:
  serviceAccount, err := auth0.ParseServiceAccount(options)
  if err == nil {
    return auth0.New(auth0.WithServiceAccount(serviceAccount))
  }
  log.Warn().
    Str("service", "directory").
    Str("provider", options.Provider).
    Err(err).
    Msg("invalid service account for auth0 directory provider")
```

Hope that helps.

**Comment by grounded042** [comment]
Thanks @calebdoxsey! That does make sense for the `directory` component. I don't understand what would need to be done to support Auth0 for the `identity` piece though.

**Comment by calebdoxsey** [comment]
@grounded042 I went ahead and implemented the identity piece since its just OIDC. If there are no issues with my PR I will merge it to master.

Basically it lets us use the type `auth0` in the config file. Otherwise the other config settings are the same.

**Comment by grounded042** [comment]
Thanks @calebdoxsey! Now that I see the code I understand what you mean by the two different components.

As I mentioned in that PR I'm planning on carving out some time this week to work on docs and the `directory` component.

**Comment by grounded042** [comment]
👋 I've opened the above PR for this issue. I noted in the PR that I did not add docs and could either do that as part of this PR, or as a new PR - let me know what is preferred.
