### ISSUE TITLE
forward-auth nginx behavior changes

### ISSUE THREAD

**Issue by whs** [pomerium/pomerium#1497]
## What happened?
With #1482 the forward auth behavior changed and is not compatible to previous nginx ingress setup

```
{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"pomerium-proxy-internal.ops-prod.svc.cluster.local","path":"/verify?uri=https://xxxx/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0","referer":"","forwarded-for":"xxxx","request-id":"745a4796-be9e-4fb6-a366-706e3ce528f0","duration":12.237621,"size":63124,"response-code":302,"response-code-details":"ext_authz_denied","time":"2020-10-08T01:54:25Z","message":"http-request"}
```

It seems that authz denied is now 302, previously it was 401. As ingress-nginx [only handle 401](https://github.com/kubernetes/ingress-nginx/blob/master/rootfs/etc/nginx/template/nginx.tmpl#L1144) this would break.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.10.0+d729ae5
- Server Operating System/Architecture/Cloud:

**Comment by whs** [comment]
Looking further to this:

- I have two pomerium-proxy, namely internal (has FORWARD_AUTH_URL set to Kubernetes service URL) and external (has ingress). nginx-ingress use the internal one, but all other Pomerium instances are configured with external's URL.
- The internal one does return 302:

```
 $ curl -v 'http://localhost:8080/verify?uri=https://xxx'  -H 'Host: pomerium-proxy-internal.ops-prod.svc.cluster.local'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /verify?uri=https://xxx HTTP/1.1
> Host: pomerium-proxy-internal.ops-prod.svc.cluster.local
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< content-length: 5
< content-type: text/plain
< location: https://gateway/.pomerium/sign_in?pomerium_expiry=1602123251&pomerium_issued=1602122951&pomerium_redirect_uri=xxxx&pomerium_signature=xxxx%3D
< date: Thu, 08 Oct 2020 02:09:11 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
Login* Closing connection 0
```

- Connecting to the internal one with other host header, but same path returns 404
- The external one does behave correctly, returning 401
- I've verified that both group has the same pomerium binary version

**Comment by travisgroth** [comment]
Hi @whs,

Could you post redacted configurations, ingress and service definitions?

Thanks.

**Comment by whs** [comment]
Here's the env
```
local gatewayHost = 'kgateway.domain.com';
local forwardAuthHost = 'kgateway-fw.domain.com';
local config = {
	AUTOCERT: 'false',
	TIMEOUT_READ: '60s',
	AUTHENTICATE_SERVICE_URL: 'https://' + gatewayHost,
	FORWARD_AUTH_URL: 'https://' + forwardAuthHost,
	JWT_CLAIMS_HEADERS: 'email,groups,user',
	AUTHORIZE_SERVICE_URL: 'http://pomerium-authorize:3000',
	CACHE_SERVICE_URL: 'http://pomerium-cache:3000',
	INSECURE_SERVER: 'true',
	GRPC_INSECURE: 'true',
	ADDRESS: ':8080',
	GRPC_ADDRESS: ':3000',
	METRICS_ADDRESS: ':9000',
	TRACING_PROVIDER: 'jaeger',
	TRACING_SAMPLE_RATE: '0.1',
	TRACING_JAEGER_AGENT_ENDPOINT: services.jaeger(namespace),
};

local configFile = std.manifestJsonEx({
	policies: policy,
	idp_request_params: {
		hd: 'domain.com',
		prompt: 'select_account consent',
	},
}, "  ");
```

The value in configFile is JSONinfied and mounted as configuration file. The value in config is set as env, with addtional SERVICES key set to the appropriate value.

The internal proxy instance has `FORWARD_AUTH_URL: 'http://pomerium-proxy-internal.' + namespace + '.svc.cluster.local',` overridden.

**Comment by desimone** [comment]
@whs would you be able to test if #1505 provides the expected behavior in your deployment?

Thanks!

**Comment by whs** [comment]
Sorry for not updating, I'm quite busy atm. I'll let you know asap when I'm available to test both pprof and this

**Comment by desimone** [comment]
@whs Totally understand. The fix should now be on master. I've been able to manually confirm the fix but wanted to ping you as well. Thanks again for reporting the issue.

**Comment by whs** [comment]
I'm still seeing this behavior:

```
$ export
declare -x SERVICES="proxy"
$ pomerium --version
v0.10.0+a375f70

{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"pomerium-proxy-internal.ops-prod.svc.cluster.local","path":"/verify?uri=https://xxxx/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0","referer":"","forwarded-for":"xxxx","request-id":"4fe6b168-a0ce-41de-b85f-9a395c19c799","duration":16.206192,"size":63124,"response-code":302,"response-code-details":"ext_authz_denied","time":"2020-10-20T02:53:58Z","message":"http-request"}
```

**Comment by whs** [comment]
I think what happened is that the internal envoy probably pass the request to some other pomerium services for authZ. That service check its own env for expected forward host which is different, so it return 302.

I tried reading the source, but I'm not familiar with how XDS work so I'm not sure if this is the case. If it is, then I'll open a new ticket requesting for support of this internal forward auth behavior

**Comment by whs** [comment]
Seems like settings authN to the internal URL does fix this
