### ISSUE TITLE
update kubernetes dashboard guide 

### ISSUE THREAD

**Issue by Hokwang** [pomerium/pomerium#1498]
Hi,

I am reading kubernetes dashboard guide, https://www.pomerium.com/guides/kubernetes-dashboard.html.

and you used stable/kubernetes-dashboard chart in there.
that's too old.

Please update using kubernetes-dashboard/kubernetes-dashboard way.
https://github.com/kubernetes/dashboard/tree/master/aio/deploy/helm-chart/kubernetes-dashboard

and that would be useful that you can control ingress, without `kubectl apply -f docs/recipes/yml/dashboard-forwardauth.ingress.yaml`

Thanks,

**Comment by desimone** [comment]
Hi @Hokwang -- Thank you for the issue and we would very much welcome a PR with the updated recipe.
