### ISSUE TITLE
Document the Programatic refresh flow

### ISSUE THREAD

**Issue by mattotodd** [pomerium/pomerium#1518]
**Is your feature request related to a problem? Please describe.**

The docs explain the programmatic access and mention needing to refresh the token,   I cant find docs for the refresh endpoint or flow.  Is that documented?

**Describe the solution you'd like**

It would be helpful to document the refresh api mentioned here:

https://www.pomerium.io/docs/topics/programmatic-access.html#handling-expiration-and-revocation

**Describe alternatives you've considered**

**Explain any additional use-cases**

**Additional context**

**Comment by desimone** [comment]
Hey @mattotodd , thanks for making an issue! 

The documentation is [actually outdated here](https://master.docs.pomerium.io/docs/topics/programmatic-access.html#handling-expiration-and-revocation) (#1316) as we now handle session refresh work on the backend as part of the cache/databroker service. That said, scripts should still anticipate that Pomerium may fail to refresh the parent refresh_token in which case the programmatic access token will no longer work. 

Hope that helps!
