### ISSUE TITLE
Documentation is incorrect about AUTHORIZE_SERVICE_URL

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#153]
Documentation says about AUTHORIZE_SERVICE_URL:
> Example: https://access.corp.example.com or pomerium-authorize-service.pomerium.svc.cluster.local

But if I don't put `https://` is front, I get the following error:
```text
4:11PM FTL cmd/pomerium: new proxy error="authorize-service-url must be a valid https url"
```

**Comment by victornoel** [comment]
With v0.0.4

**Comment by desimone** [comment]
Thanks. This is confusing. We should also probably standardize `Authenticate Internal Service URL` to be a *url.URL as well.
