### ISSUE TITLE
Operator not writing any policies

### ISSUE THREAD

**Issue by ChipWolf** [pomerium/pomerium#1535]
## What happened?
We recently took one of our cluster configurations purposed for deployment on AWS out of cold storage, reimplemented it for bare-metal use, and deployed it to machines supplied by a new provider.

The annotations for the Pomerium operator are present on our ingresses, however, the operator doesn't appear to be generating any policy configuration so all endpoints are returning 403s.

## What did you expect to happen?
As the ingress configurations on our workloads are unchanged since a known working state, except for the addition of the `cert-manager` ingress shim and TLS; I expected the existing ingress annotations for Pomerium operator to be picked up and configure Pomerium with the policies required to authorize access to these services.

## How'd it happen?

1. Deployed Pomerium with helm-operator, as per this config:
```pomerium.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: pomerium
spec:
  releaseName: pomerium
  chart:
    repository: https://helm.pomerium.io
    name: pomerium
    version: 13.0.2
  valuesFrom:
    - secretKeyRef:
        name: pomerium-values
  values:
    ingress:
      secretName: "pomerium-tls"
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/ingress.allow-http: "false"
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/enable-global-auth: "false"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16K"
    forwardAuth:
      enabled: true
    service:
      type: NodePort
    config:
      rootDomain: example.org
    operator:
      enabled: true
```
2. Ensure an ingress is annotated correctly for Pomerium operator.
```kube-ops-view.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kube-ops-view
  namespace: monitoring
spec:
  releaseName: kube-ops-view
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kube-ops-view
    version: 1.2.1
  values:
    rbac:
      create: true
    ingress:
      enabled: true
      hostname: ops.hacksm.net
      tls:
      - hosts:
        - ops.hacksm.net
        secretName: ops-tls
      annotations:
        ingress.pomerium.io/allowed_users: '["john.smith@example.org"]'
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
```
3. No relevant logs appear, the Pomerium config is untouched, the services return 403.

## What's your environment like?

- Pomerium chart version: 13.0.2
- Server Operating System/Architecture/Cloud: Kubernetes on Ubuntu

## What's your config.yaml?

```config.yaml
shared_secret: <snip>
address: :443
certificate_file: /pomerium/cert.pem
certificate_key_file: /pomerium/privkey.pem
authenticate_service_url: https://authenticate.example.org
cookie_secret: <snip>
idp_client_id: <snip>
idp_client_secret: <snip>
idp_provider: github
idp_service_account: <snip>
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
certificate_authority_file: /pomerium/ca.pem
tracing_zipkin_endpoint: ""
grpc_address: :443
forward_auth_url: https://forwardauth.example.org
cache_service_url: https://pomerium-cache.pomerium.svc.cluster.local
databroker_storage_type: memory
```

## What did you see in the logs?

```logs
$ kubectl logs pomerium-operator-56c789744c-72vhn -n pomerium --since=24h
{"level":"info","ts":1603066073.0156434,"logger":"pomerium-operator","msg":"starting manager","component":"operator"}
{"level":"info","ts":1603066073.0157096,"logger":"pomerium-operator","msg":"waiting for leadership","component":"operator"}
I1019 00:07:53.016709       1 leaderelection.go:241] attempting to acquire leader lease  pomerium/pomerium-operator-election...
I1019 00:08:14.839730       1 leaderelection.go:251] successfully acquired lease pomerium/pomerium-operator-election
```

**Comment by ChipWolf** [comment]
The cluster hasn't been used since the chart version v10.1.4, now we're running the latest.
I can't see anything in the changelogs or upgrade processes which would indicate a cause, perhaps I've missed something?

**Comment by ChipWolf** [comment]
@travisgroth I've now managed to 'fix' this by setting `operator.config.ingressClass` to `nginx`, but I'm not sure if this is the intended configuration.

I understand now the operator adds `pomerium` as an ingress class, which must be a relatively new thing as I distinctly remember it looking for `kubernetes.io/ingress.class: nginx` previously.

**Comment by travisgroth** [comment]
Hi Chad - Yes that would be the issue.  The operator will match ingresses that either (10 have no ingress.class set, or (2) have the same ingress class as the operator set.  This is similar to how ingress controllers use the same annotation.  

Thanks for following up.  Going to close this as it's working as expected.
