### ISSUE TITLE
Okta logout error

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#1541]
## What happened?

When logging out from the dashboard screen on the authenticate service, we wind up redirected to Okta's signout and get the following error:

`{"errorCode":"invalid_client","errorSummary":"Invalid value for 'client_id' parameter.","errorLink":"invalid_client","errorId":"oaemDBAXkH3TCy9o7SQlux2Ug","errorCauses":[]}`

We are signed out of Pomerium, but not Okta.

## What did you expect to happen?

Sign out without error.  

## How'd it happen?

1. Went to [service]/.pomerium
2. Clicked sign out button
3. Saw the error above.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `v0.10.0+04c5821`
- Server Operating System/Architecture/Cloud: Kubernetes

## What's your config.yaml?

```config.yaml
address: ":80"
grpc_address: ":80"
authenticate_service_url: XXXX
authorize_service_url: XXXX
cache_service_url: XXXX
idp_provider: okta
idp_scopes: 
idp_provider_url: https://dev-XXXX.okta.com
insecure_server: true
grpc_insecure: true

idp_refresh_directory_interval: 1m
jwt_claims_headers:
- email
- name
metrics_address: ":9090"
cookie_secret: XXXX
shared_secret: XXXX
idp_client_id: XXXX
idp_client_secret: XXXX
idp_service_account: XXXX
databroker_storage_type: redis
databroker_storage_connection_string: rediss://XXXX
databroker_storage_tls_skip_verify: false    
policy:
    [SNIP]
```

## What did you see in the logs?

N/A

## Additional context

Related, I think:

https://devforum.okta.com/t/logout-redirect-page/9824/7
https://issues.apache.org/jira/browse/NIFI-7584

**Comment by pflipp** [comment]
I also have troubles on logout with [ory/hydra](https://github.com/ory/hydra). While the symptom is not exactly the same, the cause could be.
hydra returns back to pomerium which, as it cleared the session before, immediately returns back to hydra so i'm logged in again.
hydra returns the error:
> Logout failed because query parameter post_logout_redirect_uri is set but id_token_hint is missing

referencing to https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout the `id_token_hint` parameter is required when using `post_logout_redirect_uri`.

I made a [quick fix](https://github.com/pomerium/pomerium/compare/master...pflipp:cache-raw-id-token-as-id-token-hint) which saves the raw `id_token` in the session to pass it as `id_token_hint` on logout. while it solves my issue, the solution doesn't feels clean for me..

**Comment by calebdoxsey** [comment]
@pflipp I've merged a change to master that should fix the issue. It's based on your changes, so thanks for the contribution.

**Comment by pflipp** [comment]
cool, thank you for finalizing @calebdoxsey
