### ISSUE TITLE
Pomerium Docker Container - Defining IAP OIDC Client Secret , URL and ID via container env variables

### ISSUE THREAD

**Issue by robincher** [pomerium/pomerium#1553]
**Is your feature request related to a problem? Please describe.**

Hi ,

This is more of a questions (there could be existing capability that i might not know) than actual feature request.

I am attempting to set-up Pomerium in my kubernetes cluster with GitOps process, and managed to follow the quick-start guide.

Just a question, can i set these parameters as container env variables? 

```
  idp_client_id: REPLACE_ME
  idp_client_secret: "REPLACE_ME"
  idp_provider_url:
```

As  far as my humble understanding, we are unable to inject secrets into ConfigMaps, and hardcoding the above into the  yaml files with GitOps process might not be the best idea.

**Describe the solution you'd like**

Allow the above to be injected into Pomerium docker container

**Describe alternatives you've considered**

Put these parameters in the Configmap, which may not be the good practice from security perspective.

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

NA

**Comment by desimone** [comment]
Hey @robincher  -- yes it's possible to set any configuration variables [as environmental variables](https://pomerium.com/reference/#configuration-settings). See [this example](https://github.com/pomerium/pomerium/blob/master/examples/config/config.example.env)
