### ISSUE TITLE
Issue with URL Encoded strings in URI

### ISSUE THREAD

**Issue by davidcollom** [pomerium/pomerium#1559]
## What happened?
When visiting a URL with `%0A` in the URI we receive a 403 response from nginx-ingress, and no request make it to the backend service.

## What did you expect to happen?
A successful request to the backend service

## How'd it happen?

1. Visit https://web-test.example.com/random/%0A/path/ - Fail (403)
2. Visit https://web-test.example.com/?query=testing%0A1234 - Fail (403)
3. Visit https://web-test.example.com/random/ - Success (200)

## What's your environment like?

Running a deployed HELM chart in Kubernetes with the images pointing to master

## What's your config.yaml?

```config.yaml
config:
  rootDomain: example.com
  policy:
    - from: https://web-test.example.com
      to: https://web-test.example.com
      allowed_idp_claims:
        teams:
          - test-group

authenticate:
  idp:
    provider: oidc
    clientID: <>
    clientSecret: <>
    url: <>
    scopes:
    - openid
    - email
    - groups

forwardAuth:
  enabled: true

image:
  tag: master
  pullPolicy: Always
```

## What did you see in the logs?

```logs
pomerium-authorize: {"level":"info","service":"authorize","request-id":"<>","check-request-id":"<>","method":"GET","path":"","host":"forwardauth.example.com","query":"","allow":false,"status":403,"message":"forbidden","user":"<>","groups":[],"time":"<>","message":"authorize check"}
pomerium-proxy: {"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"forwardauth.example.com","path":"/verify?uri=https://web-test.example.com?query=testing%0A123","user-agent":"<>","referer":"","forwarded-for":"<>","request-id":"<>","duration":31.994513,"size":63492,"response-code":403,"response-code-details":"ext_authz_denied","time":"<>","message":"http-request"}
```

**Comment by calebdoxsey** [comment]
@davidcollom it looks like we should be using `$escaped_request_uri` instead of `$request_uri`. Could you try swapping it out in your annotations:

```
nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.localhost.pomerium.io/verify?uri=$scheme://$host$escaped_request_uri"
nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.localhost.pomerium.io/?uri=$scheme://$host$escaped_request_uri"
```

If that fixes it I will update our docs and examples.

**Comment by davidcollom** [comment]
Hi @calebdoxsey thanks for your reply. Unfortunately this caused more issues than expected, I was unable to complete the Authentication flow to the backend service with the changes suggested 😞 

It did seem a reasonable change, however it looks as though Pomerium wasn't able to decode/unescape correctly.
Quickly looking at the logs, it appears that the query string was prepended multiple times before returning with a 502 Bad Gateway response.

I tried to provide the log lines, but felt like too much redaction and very little context gained.

**Comment by desimone** [comment]
@davidcollom -- Could you provide an example URL that pomerium is tripping up on to see if we can replicate on our end?

Thanks!

**Comment by desimone** [comment]
Hey @davidcollom - Could you elaborate a bit more about the upstream application that is using newlines in query params?

**Comment by davidcollom** [comment]
> Hey @davidcollom - Could you elaborate a bit more about the upstream application that is using newlines in query params? 

Sure, the upstream is Prometheus, alertmanager and grafana. When a query to Prometheus has new lines in, is where the main issue was observed.

For the interim I've switch grafana to POST over GET requests as a means of work around for the time being.

I can try and get some logs from the proposed changes, but it could take me a while to ensure that I've truly redacted all data as it appears double encoded and appended multiple times with session and secret strings.

**Comment by desimone** [comment]
Thanks for the additional details @davidcollom !

> Sure, the upstream is Prometheus, alertmanager and grafana. When a query to Prometheus has new lines in, is where the main issue was observed.
 
Interesting! Did you notice issues with any other special characters? We experimented some with the obvious ones like spaces but did not find the same behavior. 

> For the interim I've switch grafana to POST over GET requests as a means of work around for the time being.

Glad you have a temporary workaround. 

> I can try and get some logs from the proposed changes, but it could take me a while to ensure that I've truly redacted all data as it appears double encoded and appended multiple times with session and secret strings.

Thanks -- that would be helpful if it's possible, but I understand that it may difficult due to the sensitivity of the underlying logs. In the meantime, would you be able to test the proposed fix in https://github.com/pomerium/pomerium/pull/1563?

**Comment by salekseev** [comment]
I'm encountering the same issue with another application https://kubecost.com/

**Comment by desimone** [comment]
@salekseev Do you mind providing the (redacted) url that caused the problem?

**Comment by salekseev** [comment]
> @salekseev Do you mind providing the (redacted) url that caused the problem?

Turns out it's also a grafana application on the backend...

For example:
```
https://kubecost.example.com/grafana/api/datasources/proxy/1/api/v1/query?query=sum%20(%0A%20sum(kube_persistentvolumeclaim_info)%20by%20(persistentvolumeclaim%2C%20namespace%2C%20storageclass)%0A%20%2B%20on%20(persistentvolumeclaim%2C%20namespace)%20group_right%20(storageclass)%0A%20sum(kube_persistentvolumeclaim_resource_requests_storage_bytes%7Bnamespace%3D~%22monitoring%22%7D)%20by%20(persistentvolumeclaim%2C%20namespace)%0A)%20by%20(namespace%2Cpersistentvolumeclaim%2Cstorageclass)%20%2F%201024%20%2F%201024%20%2F1024%20&time=1604452743
```

**Comment by desimone** [comment]
@salekseev  / @davidcollom / @MattiasGees I believe I have a fix. if you are able to test #1578 that would be a huge help.

Thanks!

**Comment by davidcollom** [comment]
Hey @desimone,
Just tried this on our dev cluster and all looks great! I confirmed multiple endpoints and query's.
For additional clarity I did NOT change the nginx-ingress annotations for this which was previously suggested.
