### ISSUE TITLE
(bug): X-Pomerium-* headers are not injected in master

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium#1564]
`X-Pomerium-Jwt-Assertion` and `X-Pomerium-Claim-*`  headers are not injected when `pass_identity_headers` is true in `pomerium/pomerium:master@sha256:85b9aef581ab23e70e88a82eb9b2066053c027315c8abbe6dcb90c6a96bd4bf2` docker image.

Its working correctly in v0.10.6

Thanks

**Comment by desimone** [comment]
This looks like a regression from the latest stable. Previously, we added any `X-Pomerium-*` to the _RESPONSE_ headers when being used in a forward-auth mode and I believe that logic got missed in the forward-auth refactor (#1313) .
