### ISSUE TITLE
pomerium_redirect_uri goes to https on insecure setup

### ISSUE THREAD

**Issue by jmalobicky** [pomerium/pomerium#1569]
## What happened?

Setting the server to use `insecure_server: true` keeps setting the `pomerium_redirect_uri` in http-request to use https instead of http. In the browser, a 400 Bad Request: CSRF token invalid is after selecting the user to authenticate with.

## What did you expect to happen?

Able to use localhost for verifying services locally with Docker

## How'd it happen?

1. Ran `docker run --rm -it -p 8000:80 mycompany/pomerium bash && pomerium -config config.yaml`
2. Clicked `http://localhost:8000`
3. Saw error `Bad Request: CSRF token invalid` after selecting my user to login as

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.10.6
- Server Operating System/Architecture/Cloud: Docker CE

## What's your config.yaml?

```config.yaml
authenticate_service_url: http://localhost:8000

autocert: false

# Default to :443
address: :80
insecure_server: true

idp_provider: google
idp_client_id: [client-id]
idp_client_secret: [client-secret]

cookie_secret: [cookie-secret]

policy:
  - from: http://localhost:8000/
    to: http://localhost:8181/
    allowed_domains:
      - mycompany.com
```

## What did you see in the logs?

```logs
5:23PM INF authorize check allow=false check-request-id=d04f8b12-72e9-4300-8ce7-242aa8834a1f groups=[] host=localhost:8000 method=GET path=/ query= request-id=37734d05-164e-4b32-bd51-2cbf5e067019 service=authorize status=401 user=
5:23PM INF authenticate: session load error error="Bad Request: internal/sessions: session is not found" X-Forwarded-For=["172.17.0.1"] X-Forwarded-Proto=["http"] ip=127.0.0.1 request-id=707462ac-332f-46bd-8949-be759dd711db user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
5:23PM INF http-request authority=localhost:8000 duration=5.469758 forwarded-for=172.17.0.1 method=GET path=/ referer= request-id=d04f8b12-72e9-4300-8ce7-242aa8834a1f response-code=302 response-code-details=ext_authz_denied service=envoy size=63126 upstream-cluster= user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
5:23PM INF http-request authority=localhost:8000 duration=1.553958 forwarded-for=172.17.0.1 method=GET path=/.pomerium/sign_in?pomerium_expiry=1604338117&pomerium_issued=1604337817&pomerium_redirect_uri=https%3A%2F%2Flocalhost%3A8000%2F&pomerium_signature=REDACTED referer= request-id=707462ac-332f-46bd-8949-be759dd711db response-code=302 response-code-details=via_upstream service=envoy size=820 upstream-cluster=pomerium-control-plane-http user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
5:23PM INF httputil: ErrorResponse error="Bad Request: CSRF token invalid" X-Forwarded-For=["172.17.0.1"] X-Forwarded-Proto=["http"] ip=127.0.0.1 request-id=2246d707-5111-4fe8-9f35-709b68be530e user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
5:23PM INF http-request authority=localhost:8000 duration=1.291098 forwarded-for=172.17.0.1 method=GET path=/oauth2/callback?state=REDACTED&code=REDACTED&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=mycompany.com&prompt=consent referer= request-id=2246d707-5111-4fe8-9f35-709b68be530e response-code=400 response-code-details=via_upstream service=envoy size=8039 upstream-cluster=pomerium-control-plane-http user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36"
```

## Additional context

Google callback is set to use `http://localhost:8000/oauth2/callback`

**Comment by travisgroth** [comment]
Hi @jmalobicky - we only support `https` as a scheme for the application and authentication redirects.  This is primarily for security reasons, though there are some implementation reasons as well.

If you wish to use pomerium itself in an inscure mode, you need a proxy in front of it to terminate https.  If you could share a little about the use case here we might be able to make some recommendations.

**Comment by jmalobicky** [comment]
Hello @travisgroth, the use case I was trying to operate with was a local development environment where I/other devs on the team would not need to generate certs or use of something like Let's Encrypt all for localhost. There is nginx sitting behind pomerium listening on a different port, 8181, in the config I listed. 

In production, I will have valid certificates where this is not an issue and would not use the insecure config.

Based on reading the api reference, I would have thought insecure would have disabled https and thus not forced a redirection.

If there is a different approach, I am all ears. Thanks.

**Comment by travisgroth** [comment]
For local testing, I'd recommend putting https://mitmproxy.org/ in front of pomerium.  It's the lowest friction method that I've found.

https://github.com/FiloSottile/mkcert is another good option for generating certs, though it does require you run a command for initial setup.  mitmproxy is a bit more automatic.

> Based on reading the api reference, I would have thought insecure would have disabled https and thus not forced a redirection.

Yes this is unfortunately easy to get tripped up on.  While we support the immediately surrounding transport being insecure, we still require the user/browser communication to be secure.  The `insecure` mode is primarily for environments where inter-service communication can be secured through other means like a service mesh.
