### ISSUE TITLE
Support CERTIFICATE_AUTHORITY for internal http client

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#1570]
**Is your feature request related to a problem? Please describe.**

Cannot connect to a directory sync or OIDC endpoint with a TLS certificate from a custom CA.

**Describe the solution you'd like**

The `CERTIFICATE_AUTHORITY` option should update the trusted certificates used by our http client in addition to the grpc client.  Ideally this should be a common client that is used by any components needing to make external http requests.  Directory sync and the external OIDC calls are the obvious uses.

**Describe alternatives you've considered**

Updating the system trust store to contain the custom CA.  This is often undesirable / brittle.

**Explain any additional use-cases**

N/A

**Additional context**

#1561

**Comment by jawabuu** [comment]
@travisgroth 
Would you also consider a `server_name` option similar to you `tls_server_name` config?

**Comment by travisgroth** [comment]
@jawabuu additional CA certs relatively harmless to apply to all connections, so this issue is specifically scoped that way.  

To enable server name overrides it would need to be specific to each client, which requires a bit more care and configuration options.  Would you mind opening a feature request with details?

**Comment by calebdoxsey** [comment]
Looking at the go code there may be two consequences from appending a custom CA to the root CAs:

1. HTTP/2 may be disabled by default
2. We will need to duplicate the search process for root CAs, which could result in code drift, and doesn't seem to account for windows, which uses an entirely different mechanism for root CAs.

The other option would be to replace the root CA entirely (which would be the default behaviour), but this will likely break the directory providers, so I will work on the append approach.

FWIW updating the root CA using OS mechanisms makes more sense and I would recommend users do that if they can.
