### ISSUE TITLE
Revamp settings documentation

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#1573]
Hi,

The current layout of the settings documentation is very frustrating when setting up pomerium. Especially when you break down every components and don't use the All in One setup.

It would really be appreciated if you could have **one section per component with the complete list of available settings for that component**.

I know it implies duplicating a lot of things across sections but for clarity it would be really nice.

Regards.

**Comment by desimone** [comment]
This should be addressed / superseded by https://github.com/pomerium/documentation/issues/2 where each setting will be filterable by service it's related to.
