### ISSUE TITLE
Configuration Example for integrating with an existing reverse proxy

### ISSUE THREAD

**Issue by namelivia** [pomerium/pomerium#1580]
On previous versions of pomerium there [was an example for NGINX microservices](https://0-4-0.docs.pomerium.io/docs/reference/examples.html#docker). I've read that was the proper way of integrating pomerium with an existing reverse proxy like [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy). However I've not been able to find documentation for such an scenario in the latest versions, and by replicating the 0.4.0 example with the latest image these were my findings.
I was able to successfully run the following containers at the same time:
```
80/tcp                                                                  my-webapp
443/tcp                                                                 pomerium-authorize
443/tcp                                                                 pomerium-proxy
443/tcp                                                                 pomerium-authenticate
0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                                jwilder/nginx-proxy
                                                                        jrcs/letsencrypt-nginx-proxy-companion
```
It wasn't clear to me what should go on the container environment variables and what should go on the pomerium config file, so by doing some trial and error this is what I've been able to achieve.

For the pomerium containers to run without errors on the logs I had to setup the following on the pomerium config file:
```yml
autocert: false
insecure_server: true
databroker_service_url: http://localhost:5443
```
I also filled in this value, but I'm not very sure:
```yml
authenticate_service_url: http://pomerium-authenticate:443
```

The `databroker_service_url` value seemed to be mandatory so I just put what I thought it was the default value. I'm not sure if that's ok because I've seen some lines like this on the `pomerium-authorize` container logs.
```json
{"level":"warn","error":"rpc error: code = Unimplemented desc = unknown service databroker.DataBrokerService","time":"2020-11-05T21:51:36Z","message":"sync error"}
```

The routing seems fine, when I access `http://myapp.mydomain.com` I see the request on the `jwilder/nginx-proxy` logs and also I see this on the `pomerium-proxy` logs, 172.17.0.3 is the ip of the first proxy on the docker network:
```json
{
    "level": "info",
    "service": "envoy",
    "upstream-cluster": "",
    "method": "GET",
    "authority": "myapp.mydomain.com",
    "path": "/",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "referer": "",
    "forwarded-for": "14.211.37.173,172.17.0.3",
    "request-id": "3012f463-5784-471a-8ba7-be0444066515",
    "duration": 0.304346,
    "size": 0,
    "response-code": 500,
    "response-code-details": "ext_authz_error",
    "time": "2020-11-05T16:59:29Z",
    "message": "http-request"
}
```

So it seems the request went from one proxy to another, but then it suddenly returns 500 and the logs on both `pomerium-authenticate` and `pomerium-authorize` are unchanged.
Has something changed since 0.4.0 so that example is outdated? Is there any plans to write newer documentation on this topic? If I'm able to make it work I can write about it.

**Comment by desimone** [comment]
Hey @namelivia  -- thanks for making this issue. 

> On previous versions of pomerium there [was an example for NGINX microservices](https://0-4-0.docs.pomerium.io/docs/reference/examples.html#docker). I've read that was the proper way of integrating pomerium with an existing reverse proxy like [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy). 

If you are already using nginx-proxy, yes. Otherwise, Pomerium is suitable to be used without a fronting proxy (we use Envoy to do the heavy lifting). Can you tell me a bit more about your setup? 

> However I've not been able to find documentation for such an scenario in the latest versions, and by replicating the 0.4.0 example with the latest image these were my findings.

It's still there:

https://github.com/pomerium/pomerium/blob/eb19d6e125679a179112faec03f00f28cfbdded9/examples/docker/nginx.docker-compose.yml#L1-L103

but probably out of date.


I can take a look at this and update the example to be working, if it is not.

**Comment by namelivia** [comment]
Thank you for helping me!
My setup is the following, I normally to run virtual hosts with dockerized web applications on them, it also runs `jwilder/nginx-proxy` and [docker-letsencrypt-nginx-proxy-companion](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion).That way I can point `https://app1.mydomain.com`, `https://app2.mydomain.com`, `https://app3.mydomain.com` to the host, and then route these urls to the different apps, and I was trying to add pomerium to the mix.

So I've built a test machine like that and also the pomerium containers from the example above, all containers are up and running and the logs seem to report everything is fine, with every container last message being:
```
{"level":"info","service":"envoy","name":"config","time":"2020-11-12T08:22:33Z","message":"all dependencies initialized. starting workers"}
```

My suspicion is that the problem is derived from not being able to generate https, probably I need a wildcard certificate for `*.mydomain.com` and install it for the proxy. I will try getting https working first and then I will post my findings, I don't want to create more noise than necessary.

**Comment by namelivia** [comment]
Nevermind! I got it, I read your answer [here](https://github.com/pomerium/pomerium/issues/490) and found out that `GRPC_INSECURE=TRUE` is also needed on the ` pomerium-authenticate` so it opens the connection as insecure, not just on ` pomerium-cache`, it works now!

So as a summary, what was missing for my particular case was:
- A docker network for all pomerium containers.
- Setting `databroker_service_url` to `pomerium-cache:443`.
- Setting `GRPC_INSECURE=TRUE` on the `pomerium-authenticate` container.
