### ISSUE TITLE
authenticate: endpoint for Single Sign Out with oidc frontchannel-logout

### ISSUE THREAD

**Issue by pflipp** [pomerium/pomerium#1581]
**Is your feature request related to a problem? Please describe.**

Logging out on the idP from a different client does not destroy the session on Pomerium.

**Describe the solution you'd like**

A endpoint like `/oauth2/sessions/frontchannel-logout` which just terminates the session (if it exists).

Many idPs let you register a endpoint to terminate the session within an iframe during the logout procedure.

**Describe alternatives you've considered**

OIDC describes the procedure for backchannel logout as the most reliable way for Single Sign Out (in some cases the browser might not transfer the session cookies within the iframe).
In addition it introduces much more work as it requires a way to locate the pomerium session-id from the idP session-id.

**Additional context**

https://openid.net/specs/openid-connect-frontchannel-1_0.html
https://openid.net/specs/openid-connect-backchannel-1_0.html

**Comment by desimone** [comment]
Hey @pflipp,

Thanks for making the issue, and PR! I'm not familiar with the front channel draft spec, so I'll need to spend some time with that. You mention that 

> Many idPs let you register a endpoint to terminate the session within an iframe during the logout procedure.

Would you mind linking to a few IdPs that do this, and maybe a few concrete use-cases just to help me get my head around this?

At first glance, I think this is totally doable, I just need to familiarize myself a bit more.

**Comment by pflipp** [comment]
Hi @desimone
ok, I researched the "special" Providers implemented in pomerium and it seams only Azure provides something similar: the `logoutUrl`. at least [hydra](https://www.ory.sh/hydra/docs/concepts/logout/#openid-connect-front-channel-logout-10), [connect2id](https://connect2id.com/products/server/docs/datasheet#session-mgmt) and gluu supports it but there should be more.
In standard compliant OIDC-Providers the support of frontchannel logout should be listed in the openid-configuration json
```json
{
  "frontchannel_logout_session_supported": true
}
```

The use case is quite simple:
Two independent WebApps (A & B) secured by the same idP.
WepApp A terminates the session with the `end_session_endpoint` and now the user should also get logged out in WebApp B.

With frontchannel-logout the idP would render a hidden iframe with the registered frontchannel-logout-endpoint from WebApp B, before redirecting to the `post_logout_redirect_uri` from WebApp A.

**Comment by desimone** [comment]
Thanks @pflipp !
