### ISSUE TITLE
Azure IDP cannot support login for personal Microsoft accounts

### ISSUE THREAD

**Issue by jawabuu** [pomerium/pomerium#1605]
## What happened?
Follow pomerium guide for AzureAD.
 Created an application on AzureAD  to allow any Microsoft account to login
Pomerium exits with error code 1.
~Who can use this application or access this API?
Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`
Retrieve provider url from application  endpoints
`https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`
`https://login.microsoftonline.com/common/v2.0`
Pomerium exits with error
`pomerium_1          | 11:37PM FTL cmd/pomerium error="error creating authenticate service: azure: failed creating oidc provider: identity/oidc: could not connect to azure: oidc: issuer did not match the issuerreturned by provider, expected \"https://login.microsoftonline.com/common/v2.0\" got \"https://login.microsoftonline.com/{tenantid}/v2.0\""
pomerium_pomerium_1 exited with code 1`
## What did you expect to happen?
Pomerium to run & Personal Microsoft Accounts to be able to login.
## How'd it happen?
Provider url
https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
returns mismatching issuer
"issuer": "https://login.microsoftonline.com/{tenantid}/v2.0",
## What's your environment like?

docker-compose

## What's your config.yaml?

```.env
IDP_PROVIDER=azure
IDP_PROVIDER_URL=https://login.microsoftonline.com/common/v2.0
IDP_CLIENT_ID=xxx
IDP_CLIENT_SECRET=xxxx
```

## What did you see in the logs?

```logs
`pomerium_1          | 11:37PM FTL cmd/pomerium error="error creating authenticate service: azure: failed creating oidc provider: identity/oidc: could not connect to azure: oidc: issuer did not match the issuerreturned by provider, expected \"https://login.microsoftonline.com/common/v2.0\" got \"https://login.microsoftonline.com/{tenantid}/v2.0\""
pomerium_pomerium_1 exited with code 1`
```

## Additional context

https://github.com/MicrosoftDocs/azure-docs/issues/38427#issuecomment-705892340

**Comment by desimone** [comment]
Adding some additional context.

- https://pomerium-io.slack.com/archives/CK6SVMPU0/p1605829372137500
- https://github.com/coreos/go-oidc/blob/e05c4c73b4b5f159727021bf2921c214f61b2688/oidc.go#L141
- https://github.com/coreos/go-oidc/blob/3bc5a7eb4df0b0cb7f6e9f1f082ee815c60f77df/oidc/oidc.go#L151-L152
