### ISSUE TITLE
Support Certificate Chaining for Redis Connections

### ISSUE THREAD

**Issue by Apt1tude** [pomerium/pomerium#1606]
**Is your feature request related to a problem? Please describe.**

Many users use managed redis instances in the cloud, which manage their own certificates using a set of intermediate certificates and rotate them often. Currently it looks like Pomerium will only recognize certificate chains of length 1, so whenever the provider rotates their intermediate certificate, Pomerium has to be reconfigured with the new certificate as `databroker_storage_ca_file`.

**Describe the solution you'd like**
Since providers often use trusted roots that rarely change, either verify TLS directly from system trust store, or allow the root certificate to be pinned as `databroker_storage_ca_file`. In any case this would require Pomerium to support certificate chaining to validate redis connections.

**Describe alternatives you've considered**
I'm currently pinning the intermediate CA directly, but this is not ideal as there are several of the CAs and the CAs are rotated regularly.

**Explain any additional use-cases**

This is mostly applicable for users of managed cloud redis instances. I encountered this issue on Azure, but most cloud providers support managed redis.

**Additional context**

**Comment by calebdoxsey** [comment]
@Apt1tude I'm attempting to understand the issue, so apologies if I've missed something obvious.

We rely on Go's built-in TLS capabilities, which should support certificate chaining out of the box. If you use the root CA as `databroker_storage_ca_file` does that not work?

**Comment by Apt1tude** [comment]
Yep, that's the issue. I gave the root CA another try, and it was giving this error:
```
pomerium_1  | {"level":"fatal","error":"failed to initialize directory groups: error getting all directory groups: rpc error: code = Unknown desc = redis.DialURL(): x509: certificate signed by unknown authority","time":"2020-12-09T02:33:10Z","message":"cmd/pomerium"}
```

**Comment by Apt1tude** [comment]
Ok just looked into this a bit more. I think my certificate was using wrong encoding. It seems to work after PEM conversion. Perhaps having the log reflect that it failed to read the root, instead of indicating that the redis connection failed due to unknown CA would make it easier to catch these types of errors?

Thanks for looking into this issue 🙂

**Comment by calebdoxsey** [comment]
@Apt1tude thanks for the quick response. We can work on adding a clearer error message.
