### ISSUE TITLE
Log the pomerium version

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#161]
**Is your feature request related to a problem? Please describe.**

Lately when doing tests with latest pomerium, I had to know what was the version I was using.
In the past it was possible to see this information in the logs or on the pages shown by pomerium, but with latest, there is nothing anywhere.
Since I'm running pomerium in the kubernetes, it's not simple to "run pomerium --version".

**Describe the solution you'd like**

Log the version of pomerium when they start.

**Describe alternatives you've considered**

Look better and maybe find a place where the version is actually shown :)

**Comment by desimone** [comment]
@victornoel quick fix is that the `/ping` endpoints contain the version.

I think it's worth adding to console output as well. 👍
