### ISSUE TITLE
docs : add kubernetes quick-start / guide

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#17]

**Comment by mbarrien** [comment]
Without having actually tried this myself, you should be able to set the ADDRESS environment variable to something like ":8443" to change it to use port 8443 (or whatever port you like). If you do that on the authenticate server, on the corresponding proxies you'll also have to set AUTHENTICATE_SERVICE_URL to include the port.

**Comment by hsharrison** [comment]
Thanks, that makes sense, I'll try it.

**Comment by desimone** [comment]
@hsharrison I'm closing this issue as  I've added a [quick-start guide for kubernetes](https://www.pomerium.io/guide/kubernetes.html) that might be of help. #33 

Please do open a new issue if you are having trouble. Thanks!
