### ISSUE TITLE
proxied /.pomerium/sign_out doesn't do anything

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#170]
**Describe the bug**

- Given an app protected behind `https://app.xxx.com`.
- If a user goes to `https://app.xxx.com/.pomerium/sign_out` (via GET method)
- The proxy redirects to the service but does not sign the user out

**Expected behavior**

I believe in the past it was working, but I don't know if it is expected or not.

My use case is that I want to have a "logout" button on my applications and I was making the assumption it was better to redirect to `https://app.xxx.com/.pomerium/sign_out` when clicking on it instead of having a logical dependency on the authenticate service url.

If it's expected, I think it can be acceptable to have my applications know (via configuration) that the sign out url is https://auth.xxx.com/.pomerium/sign_out.

But any case, it should be accessible via a GET request (and be redirected to the referrer I guess?), not only a POST.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.5-dirty+5525408
- Server Operating System/Architecture/Cloud: AKS

Configuration file(s): see #152

**Comment by desimone** [comment]
Thanks @victornoel  -- this is definitely a bug.
