### ISSUE TITLE
JWK key rotation

### ISSUE THREAD

**Issue by lukegb** [pomerium/pomerium#1721]
**Is your feature request related to a problem? Please describe.**

Pomerium seems to only support exposing a single static JWK at a time (which must be specified in an environment variable), which makes key rotation difficult.

In particular, I'd like to just automatically rotate my signing key (say, every 24 hours), by doing something like:

* Have a starting state in which we're using key A for signing at the moment. (keyset: *A*)
* Generate a new key B.
* Add key B to the keyset (but don't start signing with it yet). (keyset: *A*, B)
* Wait 24 hours.
* Generate a new key C and add it to the keyset. (keyset: *A*, B, C)
* Start signing with key B. Keep key A in the keyset. (keyset: *B*, C, A)
* Wait 24 hours.
* Generate a new key D, start signing with key C, remove key A from the keyset (keyset: *C*, D, B)

i.e. the keyset always contains the previous and the next key, to avoid invalidating existing JWTs until they expire, and to make existing JWTs valid as soon as we switch signing key, but avoiding synchronised network calls to the authenticate service to fetch the new JWK bundle.

I'm happy to do the key rotation logic outside of Pomerium itself, but I need the ability to give Pomerium multiple JWKs to make this work.

**Describe the solution you'd like**

I'd prefer it if JWKs could be loaded from a file - probably a JSON file on disk that's just an entire JWK Set of private JWKs. The first JWK in the set should be used for signing - the others are present only for the `/.well-known/pomerium/jwks.json` endpoint on authenticate.

`sdk-go` would need to be updated to try all the listed keys from the jwks.json endpoint, rather than [just the first one](https://github.com/pomerium/sdk-go/blob/583097deebb9dc662c6f346da8bddc31f2da9e46/sdk.go#L202) - for the dynamic key lookup it would still only need to store the key that actually worked. The JWKSEndpoint would need to be reworked to store a keyset and periodically refresh it, though.

**Describe alternatives you've considered**

* Sticking a reverse-proxy in front of authenticate to swap out the JWKS endpoint. Without updating sdk-go this is pointless, and it seems silly to update sdk-go to support a feature not supported by Pomerium itself.

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by desimone** [comment]
Hi @lukegb , thanks for the feature request. 


> Pomerium seems to only support exposing a single static JWK at a time (which must be specified in an environment variable), which makes key rotation difficult.

That's partially true. It's true that Pomerium only currently supports a single JWK at a time currently and if you supply the `signing_key` as an environmental variable, the key will be static. However, if the JWK is set as part of the configuration file (`config.yaml`) that key is hot reloadable. I understand that may not be ideal for all configurations.

> In particular, I'd like to just automatically rotate my signing key (say, every 24 hours), by doing something like:
> 
> * Have a starting state in which we're using key A for signing at the moment. (keyset: _A_)
> * Generate a new key B.
> * Add key B to the keyset (but don't start signing with it yet). (keyset: _A_, B)
> * Wait 24 hours.
> * Generate a new key C and add it to the keyset. (keyset: _A_, B, C)
> * Start signing with key B. Keep key A in the keyset. (keyset: _B_, C, A)
> * Wait 24 hours.
> * Generate a new key D, start signing with key C, remove key A from the keyset (keyset: _C_, D, B)
> 
> i.e. the keyset always contains the previous and the next key, to avoid invalidating existing JWTs until they expire, and to make existing JWTs valid as soon as we switch signing key, but avoiding synchronised network calls to the authenticate service to fetch the new JWK bundle.
> 
> I'm happy to do the key rotation logic outside of Pomerium itself, but I need the ability to give Pomerium multiple JWKs to make this work.

Can you tell me a bit more about your use-case -- just out of my own curiosity? I'd love to better understand why such a fast key rotation schedule would be required. Sounds interesting. 

> **Describe the solution you'd like**
> 
> I'd prefer it if JWKs could be loaded from a file - probably a JSON file on disk that's just an entire JWK Set of private JWKs. The first JWK in the set should be used for signing - the others are present only for the `/.well-known/pomerium/jwks.json` endpoint on authenticate.

I think this is reasonable. Currently pomerium ingests PEM/CER certificates directly but consuming a single JWKS.json bundle which could contain multiple keys would be preferable. 

The tricky bit would be how to determine which JWK to use to sign payloads. I'm worried that using the "first" key will be non-deterministic. Thoughts?

> `sdk-go` would need to be updated to try all the listed keys from the jwks.json endpoint, rather than [just the first one](https://github.com/pomerium/sdk-go/blob/583097deebb9dc662c6f346da8bddc31f2da9e46/sdk.go#L202) - for the dynamic key lookup it would still only need to store the key that actually worked. 

Yes. 

> The JWKSEndpoint would need to be reworked to store a keyset and periodically refresh it, though.

Yes. Just thinking out-loud here but one option is to  manage this using a cache-control header on the jwks endpoint, and have that value be an adjustable setting. 


> **Describe alternatives you've considered**
> 
> * Sticking a reverse-proxy in front of authenticate to swap out the JWKS endpoint. Without updating sdk-go this is pointless, and it seems silly to update sdk-go to support a feature not supported by Pomerium itself.

sdk-go is very new, so I'm happy to make improvements there an our other client libraries 👍

**Comment by desimone** [comment]
@lukegb Ping :)

**Comment by lukegb** [comment]
Whoops! Sorry, didn't mean to suddenly disappear.

Basically: I hate keys. I hate provisioning them, I hate dealing with them, I hate managing their lifecycle. If there's an opportunity to have a key that's automatically rotated so I don't need to think about it (in the sense of "oh no it got compromised, guess I need to update all these endpoints to know about the new one"), then I'll go for it.

This is mostly why I like the Let's Encrypt/ACME approach: having a relatively frequent key rotation schedule (although longer than I, and they I think, would like) keeps the grease fresh and avoids things sticking in place when rotations need to happen. Out of sight, out of mind. I mostly proposed such a fast key rotation schedule because in my opinion there's no reason such a thing *shouldn't* be possible if everything is working...

I don't mind really mind about the specific format in which keys are accepted - I hadn't looked too deeply at the spec, so even if it's multiple PEM-formatted keypairs that's fine by me. I just said JWK because that's what's on the output end, heh.

In my case: it doesn't really matter to me _that_ much whether the keys are rotated or not. I trust my network (using Tailscale, so everything is Wireguarded internally) enough to just use bodge applications into using the unencrypted plain claim headers (especially things like Grafana that already support that kind of thing in their proxy-based auth).

I might be able to find some time to contribute support as well, if that would help.

**Comment by desimone** [comment]
Hey @lukegb -- 

> Basically: I hate keys. I hate provisioning them, I hate dealing with them, I hate managing their lifecycle. 

Say no more -- I am in. :) 

> I don't mind really mind about the specific format in which keys are accepted - I hadn't looked too deeply at the spec, so even if it's multiple PEM-formatted keypairs that's fine by me. I just said JWK because that's what's on the output end, heh.

For now, we use `.pems` but I'm not opposed to eventually adding `jwks` support and would accept the enhancement. 

> I might be able to find some time to contribute support as well, if that would help.

Contribution would be very welcome. I updated the go-sdk (https://github.com/pomerium/sdk-go/pull/1) to support multiple keys as a starting point.

**Comment by wjf3121** [comment]
Kindly ping, is there an ETA for this feature?

As @lukegb pointed out, one issue of only one signing key is that during key rotation, existing non-expired JWTs signed with the old key will become invalid, which is not an expected outcome.

Maybe we can add a new `deprecated_signing_key` flag, `deprecated_signing_key` won't be used for signing payloads but its public key will be listed in `/.well-known/pomerium/jwks.json` until a expiration timestamp is reached (maybe controlled by another flag `deprecated_signing_key_valid_until`?)  so both valid payloads signed by the new key and old key can be verified.

Then during key rotation, we can simply move old key to `deprecated_signing_key`, set `signing_key` to the new key. Then remove `deprecated_signing_key` when it's past the `deprecated_signing_key_valid_until` timestamp. Thoughts?

**Comment by wjf3121** [comment]
Kindly ping:)

**Comment by desimone** [comment]
\cc @wjf3121 @lukegb check out #3828
