### ISSUE TITLE
Programmatically create policy

### ISSUE THREAD

**Issue by SimonKlausLudwig** [pomerium/pomerium#1731]
We would like to change the policy dynamically.

Bases on the user group we want to decide if a user is authorized or not. As the domain which the user tries to acess will be dynamically 'created' we need to change the policy also dynamically.

Solution: When a user tries to acess a domain a phython script or a external service will be asked if the user is allowed to access this resource. The service reply’s with a 200 or 403.

**Comment by desimone** [comment]
Hey @SimonKlausLudwig  -- Programmatic management of policy, settings, and routes is part of our enterprise offering which will be going GA shortly.
