### ISSUE TITLE
community resources [discussion]

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#174]
**Is your feature request related to a problem? Please describe.**

As part of growing a community around Pomerium, it's important to have resources, documentation, and communication methods that makes being part of the pomerium project as easy, and welcoming as possible. 

**Describe the solution you'd like**

- [x] Add [contributing docs](https://github.com/pomerium/pomerium/issues/146#issuecomment-497458827)
- [x] Add community guidelines.  
- [x] Add chat. #175 
- [x] Clearer release schedule and product planning process

**Other ideas**

- Google Groups with support and announcement? 
- Examples repository
- Support / [discussion site](https://github.com/discourse/discourse)

**Additional context**

As ever, we should looks to other great communities for ideas. Here are a few examples...

- https://golang.org/doc/contribute.html
- https://github.com/kubernetes/community/tree/master/contributors/guide
- https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md
- https://gist.github.com/PurpleBooth/b24679402957c63ec426
- https://github.blog/2012-09-17-contributing-guidelines/

**What do you think?**

What do you think we can do to improve the experience of getting involved with Pomerium?

**Comment by nareddyt** [comment]
Hey, I plan on working on the contributing docs tomorrow! That should close #146. Sorry for the delay, been traveling this week
