### ISSUE TITLE
oauth2-proxy compatibility

### ISSUE THREAD

**Issue by benmccann** [pomerium/pomerium#1756]
**Is your feature request related to a problem? Please describe.**

I'm building an application and I'd like users to be able to choose a SSO solution for it including Pomerium, oauth2-proxy, or buzzfeed/sso. These packages all descend from Bitly's oauth2_proxy.

It looks to me like `buzzfeed/sso` and `oauth2-proxy` add an `X-Forwarded-User` and `X-Forwarded-Email` to the request and then sign the request and [Pomerium adds an `X-Pomerium-Jwt-Assertion` header with signed attestation JWT](https://www.pomerium.io/docs/topics/getting-users-identity.html#verification). The fact that these SSO solutions are not using a common standard makes it more work to support them all.

**Describe the solution you'd like**

A configuration option that would add an `X-Forwarded-User` and `X-Forwarded-Email` to the request and then sign the request. This could perhaps be done on an upstream basis as different upstream services may expect different methods of verifying the user

**Describe alternatives you've considered**

We considered creating multiple SSO options for our application. We will probably support only `buzzfeed/sso` / `oauth2-proxy` since we could support both of them with the same method. I'd love to support Pomerium as well but it's hard to justify writing custom code for it. Checking the request itself is not super complicated, but generically supporting multiple identity providers, integration testing them all, etc. gets to be a fair amount of work. We'd like to keep this to a minimum

**Comment by desimone** [comment]
Hey @benmccann -- thanks for the feature request

> It looks to me like `buzzfeed/sso` and `oauth2-proxy` add an `X-Forwarded-User` and `X-Forwarded-Email` to the request and then sign the request and [Pomerium adds an `X-Pomerium-Jwt-Assertion` header with signed attestation JWT](https://www.pomerium.io/docs/topics/getting-users-identity.html#verification). The fact that these SSO solutions are not using a common standard makes it more work to support them all.

Understandable. What do you think about making these header keys configurable, that way you can set the desired key name as a configuration option?  

> **Describe the solution you'd like**
> 
> A configuration option that would add an `X-Forwarded-User` and `X-Forwarded-Email` to the request and then sign the request. This could perhaps be done on an upstream basis as different upstream services may expect different methods of verifying the user.

This is the trickier part. From my understanding, will be to handle verifying signatures. We use a different signing methodology compared to SSO/oauth2-proxy (using symmetric / request signing). Pomerium signs a custom identity JWT with an asymmetric key (whose public key is broadcasted on a jwks endpoint). Google's IAP uses a similar method as Pomerium.

- https://oauth2-proxy.github.io/oauth2-proxy/docs/features/request_signatures
- https://github.com/buzzfeed/sso/blob/master/docs/sso_config.md#request-signing
- https://cloud.google.com/iap/docs/signed-headers-howto
- https://www.pomerium.io/docs/topics/getting-users-identity.html

> **Describe alternatives you've considered**
> 
> We considered creating multiple SSO options for our application. We will probably support only `buzzfeed/sso` / `oauth2-proxy` since we could support both of them with the same method. I'd love to support Pomerium as well but it's hard to justify writing custom code for it. Checking the request itself is not super complicated, but generically supporting multiple identity providers, integration testing them all, etc. gets to be a fair amount of work. We'd like to keep this to a minimum

Totally understand. We are working towards a javascript-sdk similar to our [go-sdk](https://github.com/pomerium/sdk-go) package which hopefully will make integration easier/drop-in.

**Comment by benmccann** [comment]
> What do you think about making these header keys configurable, that way you can set the desired key name as a configuration option?

Seems fine to me

> This is the trickier part.

Ah, I was thinking the difference was just the header where the signature occurs and also that the JWT has claims that need to be verified. I missed the symmetric vs asymmetric difference.

> Google's IAP uses a similar method as Pomerium.

Hmm. It looks AWS does too: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html

Since the big guys are doing it this way it seems more likely to become the standard, so I will check if `oauth2-proxy` might be amenable to adding asymmetric JWT signing. Thanks for the help!!

> We are working towards a javascript-sdk similar to our go-sdk package which hopefully will make integration easier/drop-in.

My service is actually in Go :smile:
