### ISSUE TITLE
Example from the demo video

### ISSUE THREAD

**Issue by mongrelion** [pomerium/pomerium#1778]
I'm trying to setup Pomerium together with a reverse proxy ([Caddy](https://caddyserver.com)) but to no avail because of some infinite redirection going on.
I see that the example from the demo video successfully puts Pomerium in front of several subdomains.
Could you please share this snippet? I could use that as a starting point and if it works then submit a PR to update the documentation.

**Comment by desimone** [comment]
Hey @mongrelion -- Thanks for making the issue. Pomerium itself is a first-class reverse proxy. Is using Caddy (in addition to Pomerium) a hard requirement? Can you tell me more how you are trying to configure pomerium ?

**Comment by mongrelion** [comment]
Caddy per sé is not a hard requirement.
I guess for development it's easier to use Caddy as it takes care of the whole HTTPS certificates for you in localhost (with stubbed subdomains in the `/etc/hosts` file) which is a must otherwise the the browser will reject the cookie because it's marked as safe but the content is being served over HTTP.

I just put Pomerium as the first-class reverse proxy (after generating the certs myself) and things are working as expected:
Pomerium acting as the gatekeeper for protected apps while using Keycloak as the IdP.

Thanks for your quick response!

**Comment by desimone** [comment]
> Caddy per sé is not a hard requirement.

If not, to start I would suggest using just pomerium if possible and layer on additional proxy / infrastructure pieces as required. 

> I guess for development it's easier to use Caddy as it takes care of the whole HTTPS certificates for you in localhost (with stubbed subdomains in the `/etc/hosts` file) which is a must otherwise the the browser will reject the cookie because it's marked as safe but the content is being served over HTTP.

Well, yes an no. We also support the same auto HTTPS certificate capabilities (indeed, we use caddy's great [certmagic](https://github.com/caddyserver/certmagic) library to do it!). Check out [autocert](https://www.pomerium.io/reference/#autocert) which is what our [quick-start with docker-compose](https://www.pomerium.io/docs/quick-start/).


> I just put Pomerium as the first-class reverse proxy (after generating the certs myself) and things are working as expected:
> Pomerium acting as the gatekeeper for protected apps while using Keycloak as the IdP.
> 
> Thanks for your quick response!

🥳 Fantastic to hear!

**Comment by mongrelion** [comment]
> Well, yes an no. We also support the same auto HTTPS certificate capabilities (indeed, we use caddy's great certmagic library to do it!). Check out autocert which is what our quick-start with docker-compose.

Ditto. Even though Caddy (via certmagic) can generate certificates for local domains (localhost, .localhost and .local), it seems like Pomerium does not yet support this functionality.
While setting up `prometheus.local` with Caddy, I do get the certificate no problem.
But when I try to set things up with Pomerium, I get this error:
```log
{"level":"error","error":"subject does not qualify for a Let's Encrypt certificate: pomerium.local","time":"2021-01-16T00:12:16+01:00","message":"autocert failed to obtain client certificate"}
{"level":"fatal","error":"autocert: failed to obtain client certificate: obtain cert failed","time":"2021-01-16T00:12:16+01:00","message":"cmd/pomerium"}
```

This can be reproduced with any Pomerium config file for example by setting the auth service URL to something local:
```
authenticate_service_url: https://pomerium.local
```

:(
