### ISSUE TITLE
Kubernetes Group impersonation with OIDC

### ISSUE THREAD

**Issue by SnehaMore20** [pomerium/pomerium#1782]
## What happened?
Implemented securing Kubernetes using Pomerium and keycloak as identity provider.
Unfortunately, I could'nt find the way to grant kubernetes permission to group as per https://pomerium.io/guides/kubernetes.html#user-permissions

## What's your environment like?
Pomerium 0.11.1
kubernetes v1.16.15
Keycloak 10.0.1 (through OIDC)

## What's your config.yaml?

```config.yaml
  - from: https://k8s.example.com
    to: https://kubernetes.default.svc
    tls_skip_verify: true
    pass_identity_headers: true
    allow_spdy: true
    jwt_claims_headers: 
      - user
      - email
      - groups
      - name
    allowed_idp_claims:
      groups:
      - k8s
    kubernetes_service_account_token: ...
```

I tried hardcoding header `x-pomerium-claim-groups` given below, but still logs shows empty groups
```
      set_request_headers:
        x-pomerium-claim-groups: k8s
```
## What did you see in the logs?

```logs
{"level":"info","service":"authorize","request-id":"afcf1f47-2b86-454a-8218-7150be282477","check-request-id":"c38d8f44-1087-4aea-a7a3-ace4c23f047a","method":"GET","path":"/version?timeout=32s","host":"k8s.example.com","query":"","allow":true,"status":200,"message":"OK","user":"test@example.com","groups":[],"time":"2021-01-18T11:04:40Z","message":"authorize check"}
```
Groups are Empty here

Thanks for your help,

**Comment by SergeyLadutko** [comment]
Empty groups and mine

**Comment by desimone** [comment]
@SergeyLadutko  -- Could you provide your complete (redacted) configuration? 

Thanks!

**Comment by travisgroth** [comment]
To follow up here, we don't currently support mapping oidc claims into kubernetes impersonation headers.  That functionality only works with directory sync identity providers.

**Comment by SergeyLadutko** [comment]
forwardAuth:
  enabled: true

config:
  # routes under this wildcard domain are handled by pomerium
  rootDomain: "k8s.MY.com"
  policy:
    - from: https://test-my-pomerium.k8s.MY.com
      to: http://hello-kubernetes-first.default:80
      allowed_groups:
        - admins


extraEnv:
  IDP_SCOPES: "openid,profile,email,groups"

authenticate:
  idp:
    provider: oidc
    clientID: "k8s-pomerium"
    clientSecret: "MY secret"
    url: "https://dex.MY.com"
    serviceAccount: "pomerium-authenticate"
    scopes: openid,profile,email,groups

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS

**Comment by SergeyLadutko** [comment]
When we applied this option,
```
      allowed_idp_claims:
        groups:
        - admins
        
 everything worked.
