### ISSUE TITLE
Cloud Run example is not working

### ISSUE THREAD

**Issue by ishiijp** [pomerium/pomerium#1784]
## What happened?

I couldn't deploy pomerium image to cloud run with the following instruction
https://www.pomerium.io/guides/cloud-run.html#deploy

## What did you expect to happen?
I want to deploy the [image](gcr.io/pomerium-io/pomerium:latest-cloudrun) to cloud run

## How'd it happen?

I followed the [instruction](https://www.pomerium.io/guides/cloud-run.html#deploy) and executed the command.

> gcloud run deploy pomerium --region us-central1 --platform managed --allow-unauthenticated --max-instances 1 \
    --image=gcr.io/pomerium-io/pomerium:latest-cloudrun \
    --set-env-vars VALS_FILES="/pomerium/config.yaml:ref+gcpsecrets://${PROJECT}/pomerium-config",POLICY=$(base64 policy.yaml)

This line throws errors:

 > Error: exit status 1
> Usage:
> vals-entrypoint exec [flags]
> 
> Flags:
> -h, --help help for exec
> 
> Global Flags:
> --test run in test mode and output results of interpollation
> --vals-files string specify comma separated list of file(s) to write a secret into. format: [/path/to/file.yaml:ref+gcpsecrets://my-project-id/test]

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://y-ishii-iap-test-auth.azoom.dev 
shared_secret: xxxxx
cookie_secret: xxxxx
idp_provider: 'google'
idp_client_id: xxxxx
idp_client_secret: xxxxx
```
xxxxx is replaced with suitable values.

**Comment by ishiijp** [comment]
@travisgroth 
I can deploy it now..
I don't know why, but I think I took a mistake in config.yaml.
Maybe you can close this task

**Comment by travisgroth** [comment]
👍  @ishiijp thanks for letting me know.  closing.
