### ISSUE TITLE
Allow proxy for https site running w/ self-signed certificate

### ISSUE THREAD

**Issue by haozhou** [pomerium/pomerium#179]
**Is your feature request related to a problem?
It's not able to reverse proxy an internal https website use self-signed certificate.
The error is 6:36PM ERR http: proxy error: x509: certificate signed by unknown authority proxy=192.168.1.2:8006

**Describe the solution you'd like**
Add config parameter that ignores the certificate validation.

**Comment by alexandrem** [comment]
A `disable_ssl_cert_validation` attribute could be useful, but I'd like to be able to specify a cert/key content as well.

I'm personally looking forward to host Pomerium in Kubernetes, so that would translate to a secret name somehow. We have to think about how to expose that in a generic way however in the main policy config file by possibly injecting the full cert base64 content there.

Ideally, I think we need to rethink the way the policies and routes are managed.

**Comment by desimone** [comment]
@haozhou  

> `disable_ssl_cert_validation`

Make sense to me. A contribution that added a route level config that explicitly disabled TLS validation like this would be welcome. 

Hi @alexandrem 

I am probably misunderstanding your comment but... I think much of what you are suggesting should be possible today. 

>  I'd like to be able to specify a cert/key content as well.

Again, I'm not sure I follow. That should be possible with the certificate and certificate_key [config settings](https://www.pomerium.io/reference/#certificate-authority). Or do you mean to the proxied routes? Do you mind clarifying what you had in mind?

> I'm personally looking forward to host Pomerium in Kubernetes, so that would translate to a secret name somehow

What secret name?

> We have to think about how to expose that in a generic way however in the main policy config file by possibly injecting the full cert base64 content there.

This should be possible with environmental variables today. 

> Ideally, I think we need to rethink the way the policies and routes are managed.

Open to suggestions, do you mind expanding on that? Thanks!

**Comment by alexandrem** [comment]
Hi @desimone,
I was talking about the config for each individual proxied routes.

Global environment variable is only good if all backends are using the same self-signed certificate.

We either need to be able to specify base64 encoded cert content for the route config or to refer to a Kubernetes secret name that exists in the same namespace where Pomerium is deployed.

**Comment by desimone** [comment]
fyi @haozhou @alexandrem  this will land in `v0.1.0`  and is one `latest` Look forward to your thoughts.
