### ISSUE TITLE
telemetry/metrics: metric for certificate renewal requests count

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1825]
It looks like there's no metric for autocert renewal requests. I'd like to set up alerts for renewal failures.

**Comment by wasaga** [comment]
@travisgroth I think UI spec for this metric is missing. I think it 
- has to be per-certificate
- have a gauge of certificate status - i.e. LIVE
- have a gauge of seconds remaining to renewal

Also, Envoy exposes a handy metric `days_until_first_cert_expiring` - however it does not say you which cert specifically, its a server-wide metric.

**Comment by travisgroth** [comment]
Just to be clear, autocert metrics won't have an actual UI component.

All autocert managed certs are live so I'm not sure what a status would give us - is there something I'm not thinking of?

Useful information to me would be:

autocert_renewals_total counter with a status label for failure/success
certificate_time_to_expiration_secs gauge (this name isn't great)

@yegle anything else that makes sense?

Both metrics being done per cert or SAN entry would be ideal but I'm not sure how granularly we can hook into that logic.

**Comment by yegle** [comment]
For my use case `autocert_renewals_total` is sufficient.

I think the `certificate_time_to_expireation_seconds` is not necessary, there are tools like https://github.com/joe-elliott/cert-exporter to cover more than just Pomerium. I'll leave you to decide.

**Comment by travisgroth** [comment]
Cool thanks for the feedback!
