### ISSUE TITLE
Debian Package manager warns with every dpkg command after installing Pomerium

### ISSUE THREAD

**Issue by mologie** [pomerium/pomerium#1838]
## What happened?

I installed Pomerium on Ubuntu 20.04, but now dpkg throws warnings with every invocation:

Example:

```
$ dpkg --get-selections 
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 11140 package 'pomerium':
 missing 'Maintainer' field
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 11149 package 'pomerium-cli':
 missing 'Maintainer' field
adduser						install
alsa-topology-conf				install
alsa-ucm-conf					install
alsa-utils					install
apparmor					install
[...]
```

The cause are missing (required) maintainer fields in Pomerium packages. Please refer to Debian's packaging manual:

https://www.debian.org/doc/debian-policy/ch-controlfields.html#binary-package-control-files-debian-control

## What did you expect to happen?

The installation would succeed and my package manager would not misbehave afterwards.

## How'd it happen?

1. Download pomerium_0.12.1-1_amd64.deb and pomerium-cli_0.12.1-1_amd64.deb from GitHub releases.
2. dpkg -i on both
3. All dpkg commands began throwing warnings afterwards.

## What's your environment like?

Ubuntu 20.04, amd64; Pomerium was not run a single time at this point, merely the packages were installed.

## What's your config.yaml?

Not applicable.

## What did you see in the logs?

Not applicable, package manager logs example above.

**Comment by travisgroth** [comment]
Thanks for reporting!  Will try to release `v0.12.2` with this addressed.

**Comment by travisgroth** [comment]
@mologie sorry about the delay but v0.12.2 should be out with this addressed.

**Comment by mologie** [comment]
Awesome, thank you for the update, appreciate it!
