### ISSUE TITLE
Named cookie not present

### ISSUE THREAD

**Issue by munhozdiego** [pomerium/pomerium#184]
Hey Guys,

I've been facing the following issue:

http: named cookie not present

logs:

11:50PM DBG proxy: invalid session error="http: named cookie not present" ip=207.228.78.97 req_id=750e4025-eb67-9504-22ad-b960bd6cd804 user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1",

Has anybody seem this before ?

Here are my setup:

Port forwarding port 443 to my docker server on port 443.

My Pomerium container runs on port 443.

My config.yaml:

pomerium_debug: true 
log_level: debug

policy:
 - from: httpbin.mydomain.com
   to: http://httpbin
   allowed_users:
    - me@gmail.com

My container env vars:

IDP_PROVIDER = google
AUTHORIZE_SERVICE_URL = https://localhost
AUTHENTICATE_SERVICE_URL = https://auth.mydomain.com
AUTHENTICATE_INTERNAL_URL = https://localhost
IDP_PROVIDER_URL = https://accounts.google.com

I'm mouting my certs and config like this:

Destination /pomerium/cert.pem
Source /payload/pomerium/fullchain.pem

Destination /pomerium/config.yaml
Source /payload/pomerium/policy.yaml

Destination /pomerium/privkey.pem
Source /payload/pomerium/privkey.pem

**Comment by juankakode** [comment]
I am also having this issue, I see multiple errors with "http: named cookie not present"  and errors regarding  being unable to find bearer token. 

I am able to get to the provider login prompt, login and then when it redirects me to the app page I get an user unauthenticated error. 

I am using auth0.

**Comment by desimone** [comment]
> 11:50PM DBG proxy: invalid session error="http: named cookie not present" ip=207.228.78.97 req_id=750e4025-eb67-9504-22ad-b960bd6cd804 user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 13_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1",

The "http. named cookie not present" error indicates you aren't logged in with an identity provider. Pomerium looked for your session cookie and wasn't able to find it so it then kicks off the authentication process. Though it's technically an error, it's expected (thus under the DEBUG log level), when a user is not authenticated yet.  I can see why that's confusing though so I've got an incoming patch that should make these messages look appropriately less scary. 

@munhozdiego

Can you post your complete configuration file /environmental variables as well as a complete log dump (with secrets / sensitive data removed)? It's hard to tell but my hunch is the identity provider isn't properly configured. 

@juankakode 

Could you post your complete config and logs with sensitive data removed? Are you using the generic OIDC provider?

Thanks!

**Comment by desimone** [comment]
Closed by #186
