### ISSUE TITLE
HSTS header is present in plaintext HTTP response

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1859]
## What happened?

Looks like the plaintext HTTP server is responding HSTS header.

## What did you expect to happen?

HSTS header should not present in plaintext HTTP request.

## How'd it happen?

curl -v your-dns.run

Check the response

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.12.1-1611179121+77abb5
- Server Operating System/Architecture/Cloud: docker + official image

## What's your config.yaml?

N/A

## What did you see in the logs?

N/A

## Additional context

Per RFC 6797 8.1:

> If an HTTP response is received over insecure transport, the UA MUST ignore any present STS header field(s).

**Comment by yegle** [comment]
While you are at it, I think you should also remove `X-Frame-Options` and `X-Xss-Protection`. Any modern browser will not connect to the HTTP port beyond the first connection, and if all HTTP requests are 301 redirected away I don't see those headers could be useful.

**Comment by desimone** [comment]
Thanks for reporting @yegle

**Comment by desimone** [comment]
This is coming from the redirect server or on one of your routes?

**Comment by desimone** [comment]
@yegle  --

I'm confused. This seems to be the inverse of https://github.com/pomerium/pomerium/issues/1413
 which was fixed in https://github.com/pomerium/pomerium/pull/1416.

**Comment by yegle** [comment]
I think the fix to #1413 is incorrect per the RFC. It looks like HSTS should only present in HTTPS connection, not HTTP connection.
