### ISSUE TITLE
Using Env variable HEADERS,  get type error

### ISSUE THREAD

**Issue by ValentinPortais** [pomerium/pomerium#188]
**Describe the bug** 

Specifying headers for pomerium doesn't seems to work. 
The container crash with a type error : expected a map, got 'string'

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): 0.0.5
- Kubernetes v1.12.7-gke.10

Kubernetes env variable
```text
        - name: HEADERS
          value: X-Content-Type-Options:nosniff,X-Frame-Options:SAMEORIGIN
```

Logs(s):

```text
{"level":"info","file":"/etc/pomerium/config.yaml","time":"2019-06-19T09:50:43Z","message":"loading config from file"}
{"level":"fatal","error":"failed to load options from config: 1 error(s) decoding:\n\n* 'headers' expected a map, got 'string'","time":"2019-06-19T09:50:43Z","message":"cmd/pomerium: options"}

```

**Comment by desimone** [comment]
@ValentinPortais 

That doesn't quite look like right yaml to me. Also, `yaml` based configs are lower case.  Try something like this (sorry I can't test ATM). 

```yaml
headers: X-Content-Type-Options:nosniff,X-Frame-Options:SAMEORIGIN
```

See also:
- https://www.pomerium.io/docs/examples.html#configurations
- https://www.pomerium.io/reference/#headers


Let me know if that works.

**Comment by ValentinPortais** [comment]
@desimone 

You are referring to the key in the config.yaml.
In my example I am using the kubernetes env config variables which are all upper case.
I tried your solution in lowercase, it doesn't throw any error but it doesn't make any change aswell.

I noticed the project switch from envconfig to Viper. I tried the following env var:
`HEADERS="{\"X-Content-Type-Options\": \"nosniff\", \"X-Frame-Options\": \"DENY\"}"`
I ended up with the same error.

**Comment by desimone** [comment]
@ValentinPortais Got it. Let me look into if you can set this field as expected removing kubernetes from the equation (both via config.yaml and as an envar). Could be a regression.

**Comment by travisgroth** [comment]
We may be seeing this...https://github.com/spf13/viper/issues/523.

I can set headers via config file but not via ENV when running outside of Kubernetes.  

If Viper doesn't have a fix, this may need to be a two step parse like we do for urls and policies.

**Comment by travisgroth** [comment]
@ValentinPortais just so I'm clear - you aren't using the chart, correct?  

This pod spec syntax appears to be working with #198:

```
    env:
    - name: HEADERS
      value: '{"X-Test": "X-Value"}'
```

**Comment by travisgroth** [comment]
Made some changes and the old syntax should work now too:

```
env:
- name: HEADERS
  value: "X-Test1:X-Value1,X-Test2:X-Value2"
```
