### ISSUE TITLE
Expose (public) Signing Key for JWT

### ISSUE THREAD

**Issue by unsubtleguy** [pomerium/pomerium#189]
**Is your feature request related to a problem? Please describe.**

Hey Pomerium devs,

I'm deploying Istio (https://istio.io/) with Pomerium - I'd like to use the security features of Isto ( namely, checking JWT assertions for specific routes - https://istio.io/docs/reference/config/istio.authentication.v1alpha1/)

At the moment, I have a separate service which simply serves the public signing key, so i can check JWT assertions using the jwks_uri parameter in Istio.

**Describe the solution you'd like**

Implement the jwksuri as per openid specification (https://openid.net/specs/openid-connect-discovery-1_0.html, jwks_uri) - Or just expose a route like auth0 does (https://auth0.com/docs/jwks - their example is https://YOUR_DOMAIN/.well-known/jwks.json).

**Describe alternatives you've considered**

Handing keys out via an out of band mechanism is cumbersome - in my case, if it wasn't for an internal web service it would end up being a manual copy-paste into kubernetes manifest files for other services. 

I had a quick look through the documentation (which didn't seem to mention anything) and had a look at the routes exposed within the project and didn't see anything like this currently - Apologies if it already exists!

Thanks / Go beyondcorp!

**Comment by desimone** [comment]
Great idea, thank you @unsubtleguy  .

**Comment by desimone** [comment]
Aiming to include this in `v0.3.0`.

**Comment by muenchdo** [comment]
This would be super useful! 🙂
