### ISSUE TITLE
0.12.2 regression: Missing identity headers

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1898]
Updating to 0.12.2 seems to cause the identity headers (`X-Pomerium-Claim-Email` and `X-Pomerium-Jwt-Assertion` in my case) to be missing.

Reverting to 0.12.1 fixed the issue.

Config I used:
Environment variable:
```
....
"JWT_CLAIMS_HEADERS": "email"
...
```

Policy:
```
- from: ...
  to: ...
  pass_identity_headers: true
  ...
```

**Comment by travisgroth** [comment]
Hey @yegle - FYI, we had a release error with v0.12.2 which has been fixed.  If you upgrade to v0.12.2 it should be commit hash `2060f4e` and not contain this regression.

**Comment by desimone** [comment]
I am unable to reproduce on `master` or f3a9ab170b7c507a902cc286f381d3a4f82059f8.

- https://gist.github.com/6a322589493834ba8b3efa6ce9d04fa8
- https://gist.github.com/fb187b4d11eec862dd44b5ab77cbf7cf

**Comment by yegle** [comment]
Yes I did noticed two different docker images both labeled v0.12.2.

I pulled a new image and it now correctly passed identify headers to the back end.
