### ISSUE TITLE
Policy to do an HTTP redirect

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#1899]
**Is your feature request related to a problem? Please describe.**

It would be convenient to be able to do a simple HTTP redirect to external website. E.g. you can have `help.example.com` redirect to `https://stackoverflow.com/questions/tagged/FOO`.

**Describe the solution you'd like**

The easiest solution that I can think of is to (ab)use the `To` field in the policy to do something like this:

```
- from: https://foo.example.com
  to: http://foo.internal # reverse proxy the request
- from: https://bar.example.com
  to: -> https://stackoverflow.com/... # HTTP redirect to this external site
```

This is probably easier to implement but hard to support in the long run. Instead can we write arbitrary envoy Route configs as part of the Pomerium config? I briefly looked at Envoy's doc and it looks like this is feasible on Envoy: https://github.com/envoyproxy/envoy/blob/7adc0393221467fcae18052c1f7caf0cb6048d2e/api/envoy/api/v2/route/route_components.proto#L214

**Describe alternatives you've considered**

Run an nginx server and redirect the traffic.

**Explain any additional use-cases**

**Additional context**

**Comment by calebdoxsey** [comment]
@yegle Thanks for the request. It turns out we already recently implemented this feature. You can see the documentation here: https://master.docs.pomerium.io/reference/#redirect.

I'm going to close this issue, as I think that option should cover the request, but we can re-open if you notice something missing.

**Comment by yegle** [comment]
Ah cool, thanks!
