### ISSUE TITLE
Configure service proxying with Kubernetes CRDs

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium#1924]
It would be helpful to configure specific service proxies using Kubernetes CRDs. This would enable new services to be added without restarting or reinstalling Pomerium.

**Comment by FireDrunk** [comment]
I'm very much interested in this as well!

**Comment by travisgroth** [comment]
Though not using CRDs, we now support Ingress natively with our [ingress controller](https://docs.pomerium.io/docs/k8s/ingress.html).  Let us know if that doesn't fit your use case!
