### ISSUE TITLE
Exit service results in fatal error

### ISSUE THREAD

**Issue by ventris** [pomerium/pomerium#1935]
## What happened?
When one is breaking the running application it shuts down with an error which causes services such as systemd to set the application as failed.

I have observed this with both memory and redis datastorage.

## What did you expect to happen?
Application should exit cleanly

## How'd it happen?

1. Ran `pomerium -config config.yaml`
2. Break with `Ctrl + c`
3. Saw error `{"level":"fatal","error":"context canceled","time":"2021-02-23T07:45:47Z","message":"cmd/pomerium"}`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.12.1-1611179121+77abb53
- Server Operating System/Architecture/Cloud: Ubuntu 18.04 (4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

## What's your config.yaml?

```config.yaml
address: :443
metrics_address: :9299

authenticate_service_url: https://authenticate.example.com

certificates:
   - cert: /etc/pomerium/fullchain.pem
     key: /etc/pomerium/privkey.pem

cookie_secret: "REDACTED"

# IDP configuration
idp_provider: "google"
idp_client_id: "REDACTED"
idp_client_secret: "REDACTED"
idp_service_account: "REDACTED"

jwt_claims_headers: "user,email,groups"

policy:
  - from: https://app.example.com
    to: http://internal.server
    pass_identity_headers: true
    preserve_host_header: true
    allowed_domains:
            - example.com
```

## What did you see in the logs?

```logs
 ^C{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"warn","error":"rpc error: code = Canceled desc = context canceled","time":"2021-02-23T07:45:47Z","message":"sync error"}
{"level":"fatal","error":"context canceled","time":"2021-02-23T07:45:47Z","message":"cmd/pomerium"}
```

**Comment by travisgroth** [comment]
Hi @ventris - I'm not sure a non-zero exit from SIGINT is a problem.  However, it does appear that we're exiting non-zero even for SIGTERM, which isn't ideal.  Opened #1958 to change this.
