### ISSUE TITLE
Pass authentication / openID claims in headers 

### ISSUE THREAD

**Issue by cjwalton** [pomerium/pomerium#196]
Is it possible with Pomerium at this stage to pass user information as environment variables or HTTP headers to downstream applications? The use case here is to allow IDP authentication to a downstream application that may not be able to directly authenticate/authorize with an IDP.

Thanks!

**Comment by desimone** [comment]
Hi @cjwalton 

> Is it possible with Pomerium at this stage to pass user information as environment variables or HTTP headers to downstream applications? The use case here is to allow IDP authentication to a downstream application that may not be able to directly authenticate/authorize with an IDP. 

Yes! By default, downstream applications will see the following extra headers. 
`x-pomerium-authenticated-user-{email,groups}`. I recommend also having pomerium sign those headers for security purposes. See [signed headers](https://www.pomerium.io/docs/signed-headers.html#verification)

**Comment by desimone** [comment]
Closing because I think we've got you covered. Please reopen if I've misunderstood.
