### ISSUE TITLE
TCP service proxy breaks with "METHOD_UNSPECIFIED"  envoy error

### ISSUE THREAD

**Issue by isaacpz** [pomerium/pomerium#1972]
## What happened?
An error is thrown when I attempt to use `pomerium-cli` to connect to a proxied TCP service. 

## What did you expect to happen?
I am able to successfully connect to my proxied TCP service using `pomerium-cli`

## How'd it happen?
1. I ran `pomerium-cli tcp [snipped external ip]:27017 --listen localhost:27017 --disable-tls-verification` locally
2. Connected to `localhost:27017`
3. Connection failed. Got the errors seen in logs section below.

## What's your environment like?

- Pomerium cli 0.13.2-1614632034+0ab96c8
- Pomerium v0.13.2 installed via Pomerium-helm (chart version 16.0.1)
- Bare metal cluster using MetalLB for load balancing

## What's your config.yaml?
Note that this is values.yaml since I'm using pomerium-helm:
```config.yaml
pomerium:
  config:
    policy:
    - from: tcp+https://[external url snipped]:27017
      to: tcp://[internal url snipped]:27017
      allowed_idp_claims:
        groups:
        - admin
    rootDomain: purl snipped]
  authenticate:
    idp:
      provider: oidc
      clientID: pomerium
      clientSecret: [snipped]
      url: [snipped]
      scopes: openid,profile,email,offline_access,groups
    service:
      annotations:
        cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  proxy:
    service:
      annotations:
        cloud.google.com/app-protocols: '{"https":"HTTPS"}'
  metrics:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitor
  ingress:
    enabled: false
  service:
    type: LoadBalancer
    authorize:
      headless: false
```

## What did you see in the logs?

Pomerium-cli gives this error:
```
12:04AM INF tcptunnel: opening connection dst=[external URL snipped]:27017 proxy=[external URL snipped]:443 secure=true
12:04AM INF tcptunnel: connection closed
12:04AM ERR tcptunnel: error serving local connection error="tcptunnel: invalid http response code: 400"
```

Pomerium proxy gives this error:
```
auth/pomerium-proxy-c54797754-mghgj[pomerium]: {"level":"error","service":"envoy","name":"lua","time":"2021-03-08T08:15:09Z","message":"script log: [string \\\"function envoy_on_request(request_handle)...\\\"]:16: attempt to index a nil value"}
auth/pomerium-proxy-c54797754-mghgj[pomerium]: {"level":"info","service":"envoy","upstream-cluster":"","method":"METHOD_UNSPECIFIED","authority":"","path":"","user-agent":"","referer":"","forwarded-for":"","request-id":"","duration":0.176023,"size":11,"response-code":400,"response-code-details":"http1.invalid_url","time":"2021-03-08T08:15:09Z","message":"http-request"}
```

## Additional context

This problem is isolated to TCP routes. HTTP routes work just fine.

**Comment by calebdoxsey** [comment]
@isaacpz Are you using a load balancer or ingress in front of this? Based on the annotations a google cloud load balancer? It's possible it doesn't like the HTTP CONNECT verb.

I've not used metallb before so it's taking me a bit to setup a test case, but it'd be nice to rule out anything else that might be interfering with the traffic. Thanks.

**Comment by calebdoxsey** [comment]
@isaacpz I found this issue in the envoy repo: https://github.com/envoyproxy/envoy/issues/13114. I think we may be using an older version of envoy that doesn't have the fix. Would it be possible to try your config with a domain name instead of an IP address?

**Comment by travisgroth** [comment]
@isaacpz Another question.  Your command above shows you using ip address to set up the tunnel:

`pomerium-cli tcp [snipped external ip]:27017 --listen localhost:27017 --disable-tls-verification`

but your route is defined as such, presumably with a DNS name:

`from: tcp+https://[external url snipped]:27017`

Can you use the external URL in your `tcp` command and see how that works, or did you mean to indicate you were using the external IP in both places?

**Comment by isaacpz** [comment]
@calebdoxsey - we are not using any third party load balancers in front of this. The annotations are redundant (they are left-over from a previous installation of pomerium). I just removed them and was able to reproduce the problem.

@calebdoxsey @travisgroth That is my mistake when snipping the data - I am using the host name in both commands. I do not use an IP address in any of the commands.

**Comment by travisgroth** [comment]
@isaacpz Can you share your MetalLB configuration?  I'm not able to reproduce with a GKE cluster based on your helm configuration.  As far as I'm aware there _should_ be no difference here with MetalLB vs any other cloud provider LoadBalancer provider.

I can reproduce the proxy side error message artificially by crafting an invalid HTTP request, but that shouldn't occur with `pomerium-cli`.  I noticed the timestamps in your logs are likely from different time periods - can you confirm the cli side and server side messages are correlated?

**Comment by travisgroth** [comment]
> I can also confirm that the error messages are correlated

Thanks just wanted to double check.  

> Are there any additional steps I could take to try to gather some more rich info on the proxy side (ie debug flags)?

In the helm chart:

```
config:
  extraOpts:
    log_level: debug
```

There is a _lot_ of info with that set.  I didn't see anything in that output that might help show this kind of issue, but feel free to take a look.

Running https://docs.mitmproxy.org/stable/mitmproxytutorial-interceptrequests/ between the client and your external IP might be the best way to see what's going on with that request.

Question for you - you aren't getting the authenticate flow, correct?  It just fails right away?
