### ISSUE TITLE
authenticate/providers : GitLab support

### ISSUE THREAD

**Issue by fnkr** [pomerium/pomerium#20]
GitLab can serve as an OAuth provider, it would be nice if we could use it together with Pomerium. GitLab.com as well as self-hosted GitLab installations should be supported.

References
- [GitLab OAuth Provider Documentation](https://docs.gitlab.com/11.6/ce/integration/oauth_provider.html)
- [oauth2_proxy GitLab Provider](https://github.com/bitly/oauth2_proxy/blob/v2.2/providers/gitlab.go)

**Comment by desimone** [comment]
Implemented with #28. 

Please check out the warning in the docs / pull request regarding email validation. Hopefully this works for you. Let me know @fnkr !

Thank you again to @mbarrien for giving me some ideas on how to fix the issues I was having (and sorry for the overlapping effort here).
