### ISSUE TITLE
Potential Bug Risks and Anti-Patterns

### ISSUE THREAD

**Issue by HarshCasper** [pomerium/pomerium#2013]
## Description 

Hi 👋 

I ran DeepSource Static Code Analysis upon the Project, the results for which are available [here](https://deepsource.io/gh/HarshCasper/pomerium/). 

The Static Code Analysis Tool found potential bugs and anti-patterns in the Code, that can be detrimental at a later point in time with respect to the Project. DeepSource helps you to automatically find and fix issues in your code during code reviews. This tool looks for anti-patterns, bug risks, performance problems, and raises issues. 

Some of the notable issues are: 

- Using a deprecated function, variable, constant or field [here](https://deepsource.io/gh/HarshCasper/pomerium/issue/SCC-SA1019/occurrences)
- Calls to exit/fatal made in function using defer [here](https://deepsource.io/gh/HarshCasper/pomerium/issue/CRT-D0011/occurrences)
- Empty String tests [here](https://deepsource.io/gh/HarshCasper/pomerium/issue/CRT-A0004/occurrences)
- Unnecessary use of fmt.Sprint/Sprintf [here](https://deepsource.io/gh/HarshCasper/pomerium/issue/SCC-S1039/occurrences)
- Poor file permissions used when creating a directory [here](https://deepsource.io/gh/HarshCasper/pomerium/issue/GSC-G301/occurrences)

There are plenty of other issues in relation to Bug Discovery and Anti-Patterns which you would be interested to take a look at.

If you would like to integrate DeepSource to autofix some of the commonly occurring issues, I can help you set that up :)

**Comment by desimone** [comment]
Thanks @HarshCasper.

These look very similar (the same?) as the checks run as part of `golangci-lint` but have explicitly ignored for [various reasons](https://github.com/pomerium/pomerium/blob/master/.golangci.yml).
