### ISSUE TITLE
Getting access to Slack?

### ISSUE THREAD

**Issue by eddiewang** [pomerium/pomerium#2014]
Hi there,

I tried to join: http://slack.pomerium.io/

Not sure if this is meant to be a private channel, but getting this error:
![image](https://user-images.githubusercontent.com/2057997/112002094-8b119680-8aed-11eb-9b70-bb63f831a296.png)

**Comment by desimone** [comment]
Hey @eddiewang  -- looks like there was a change that broke our invite bot https://github.com/rauchg/slackin/issues/417

For the time being, this link should work: https://join.slack.com/t/pomerium-io/shared_invite/zt-o2ith4qr-_qYANnwpW09p1R_~fYPP4w
