### ISSUE TITLE
Pass username in proxy header

### ISSUE THREAD

**Issue by erikespinoza** [pomerium/pomerium#2025]
**Is your feature request related to a problem? Please describe.**

I have a closed source app that can process user auth via http headers. I sent the headers by setting jwt_claims_headers to user. Unfortunately this prepends authentication method to the username. Is there a way to turn this off?

Ex:

```
x-pomerium-claim-user: oidc/username
```

**Describe the solution you'd like**

Header sends just username without ```oidc/```

**Describe alternatives you've considered**

I am considering using oidc to pomerium and oidc from the app. Would prefer to skip that if possible.

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by travisgroth** [comment]
Hi @erikespinoza - thanks for opening this issue.  Yes, I think this is something we can change for the v0.14 release.

**Comment by erikespinoza** [comment]
That's awesome. Thanks!
