### ISSUE TITLE
Identity verification failed. No attestation JWT!

### ISSUE THREAD

**Issue by karlbateman** [pomerium/pomerium#2080]
## What happened?

First let me start by saying, this is a great project. Kudos for making such a feature rich IAP!

I've been using the [NGINX] recipe which I've configured with [Google] and [Auth0] IdP's. I have everything running fine locally without issue but I'm not seeing the signed identity token information. Because this is not included, I'm unable to assert a users identity details programmatically.

I'm guessing this is because the `signing_key`  isn't set in the Pomerium configuration YAML file. It's not clear from the documentation how to explicitly set this value, or what should be Base64 encoded.

This isn't really a bug, more a request for clarity on the process of getting/asserting user details.

## What did you expect to happen?

After signing in, the users identity details should be displayed.

## How'd it happen?

Follow the [NGINX] recipe adding [Google] and [Auth0] IdP configuration details.

## What's your environment like?

Using the `master` branch within the [examples/nginx](https://github.com/pomerium/pomerium/tree/master/examples/nginx) with the configuration below and `docker-compose up`.

## What's your config.yaml?

This configuration was updated to include settings for [Auth0] IdP.

```config.yaml
# Main configuration flags : https://www.pomerium.io/docs/reference/reference/

pomerium_debug: true
address: :80
cookie_secret: YVFTMIfW8yBJw+a6sYwdW8rHbU+IAAV/SUkCTg9Jtpo=
shared_secret: 80ldlrU2d7w+wVpKNfevk6fmb8otEx6CqOfshj2LwhQ=

idp_provider: auth0
idp_provider_url: "REDACTED"
idp_client_id: "REDACTED"
idp_client_secret: "REDACTED"
idp_service_account: "REDACTED"

insecure_server: true
forward_auth_url: http://fwdauth.localhost.pomerium.io
authenticate_service_url: https://authenticate.localhost.pomerium.io

policy:
  - from: https://verify.localhost.pomerium.io
    to: https://httpbin
    allowed_domains:
      - krb.dev
    pass_identity_headers: true
```

[NGINX]: https://www.pomerium.com/guides/nginx.html#background
[Google]: https://www.pomerium.com/docs/identity-providers/google.html
[Auth0]: https://www.pomerium.com/docs/identity-providers/auth0.html

**Comment by desimone** [comment]
Thanks for your kind words @karlbateman !

> I'm guessing this is because the `signing_key` isn't set in the Pomerium configuration YAML file. It's not clear from the documentation how to explicitly set this value, or what should be Base64 encoded.

If you are running in all in one mode, a signing_key will be automatically generated on each restart. 

It is a base64 encoded string. See the [reference docs](https://www.pomerium.io/reference/#signing-key) and the [getting a user identity](https://www.pomerium.io/docs/topics/getting-users-identity.html#verification) guide. 


> ## How'd it happen?
> Follow the [NGINX](https://www.pomerium.com/guides/nginx.html#background) recipe adding [Google](https://www.pomerium.com/docs/identity-providers/google.html) and [Auth0](https://www.pomerium.com/docs/identity-providers/auth0.html) IdP configuration details.
> 
> ## What's your environment like?
> Using the `master` branch within the [examples/nginx](https://github.com/pomerium/pomerium/tree/master/examples/nginx) with the configuration below and `docker-compose up`.

The assertion header is not being sent to the upstream because Pomerium is being used as an external authorization provider for nginx (e.g. sometimes called forward-auth).  That is to say, the request is coming to nginx. nginx is asking pomerium if the request is valid, but the assertion header which is typically added in flight as a _request_ header is not then being added by nginx to the upstream request. 

This should be possible via the `ngx_http_auth_request_module ` module using `auth_request_set` but it's been a while since I modified the nginx configurations directly. 

Hope that helps!

**Comment by karlbateman** [comment]
Thanks for getting back to me @desimone, I've tried adding `auth_request_set $auth_resp_x_pomerium_jwt_assertion $upstream_http_x_pomerium_jwt_assertion;` to the `proxy.conf` but I'm still unable to get user information. I'm hoping there maybe someone else who is using Pomerium in a similar way and who has a solution 😄

**Comment by pingssgp** [comment]
@karlbateman this may be relevant. I'm trying to set up a simple local development environment with a local OIDC IDP, following the instructions here : https://www.pomerium.io/guides/local-oidc.html

I am facing the same issue as in your last post. The user is able to authenticate with the IDP. However, the next step fails as you describe. The verify service says it's unable to connect:

```
couldn't get json web key: Get 
"https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json":
 dial tcp 127.0.0.1:443: connect: connection refused
```

Manually downloading the `jwks.json` file from the authenticate service gives me this:

```
$ wget https://authenticate.localhost.pomerium.io:443/.well-known/pomerium/jwks.json --no-check-certificate
--2021-04-14 10:18:09--  https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json
Resolving authenticate.localhost.pomerium.io (authenticate.localhost.pomerium.io)... 127.0.0.1
Connecting to authenticate.localhost.pomerium.io (authenticate.localhost.pomerium.io)|127.0.0.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14 [application/json]
Saving to: ‘jwks.json’

jwks.json 100%[======>]      14  --.-KB/s    in 0s      

2021-04-14 10:18:09 (9.63 MB/s) - ‘jwks.json’ saved [14/14]

$ cat jwks.json 
{"keys":null}
```

However, I can follow the example in this ticket (https://github.com/pomerium/pomerium/issues/1042) and get the JWT in the `X-Pomerium-Jwt-Assertion` header.

**Comment by desimone** [comment]
@karlbateman  / @pingssgp 

Sorry to have misdirected you a bit. The original docs are correct and your original assumption is correct. 

> I'm guessing this is because the signing_key isn't set in the Pomerium configuration YAML file.


 if `signing_key`is not set explicitly the authenticate service will not serve the `jwks` endpoint. 

> If no certificate is specified, one will be generated and the base64'd public key will be added to the logs. Note, however, that this key be unique to each service, ephemeral, and will not be accessible via the authenticate service's `jwks_uri` endpoint.


>  It's not clear from the documentation how to explicitly set this value, or what should be Base64 encoded.

I'll make a PR that adds instructions on how to generate the signing key for the various supported formats. EC (P-256 or Ed25519) curves are suggested for performance reasons over RSA> 

See :
- https://www.pomerium.io/docs/topics/getting-users-identity.html#verification
-  https://github.com/pomerium/pomerium/blob/master/scripts/generate_self_signed_signing_key.sh

Any base64 key of the above should work. Hope that helps.

**Comment by desimone** [comment]
> couldn't get json web key: Get  "https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json":
 dial tcp 127.0.0.1:443: connect: connection refused

and 

> We tried to verify the incoming user, but failed with the following error:
  couldn't get json web key: 
    Get "https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json":
      dial tcp 0.0.0.0:443: connect: connection refused


This error occurs because when `verify` tries to grab `authenticate`'s jwks endpoint, it makes an external call, checks the DNS, gets localhost, then tries to dial `127.0.0.1:443` or `0.0.0.0:443` is probably getting rejected by your firewall (for good reason). Which is almost always going to be the case in a docker environment. 

I'm not sure of a great way around this without using a real, publicly accessible domain instead of `authenticate.localhost.pomerium.io`.  I'm open for suggestions!

**Comment by calebdoxsey** [comment]
I believe [`aliases`](https://docs.docker.com/compose/compose-file/compose-file-v3/#aliases) can be used in docker-compose to map `authenticate.localhost.pomerium.io` in the container to the other docker container. Kubernetes can do something similar with [`hostAliases`](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/).
