### ISSUE TITLE
One domain to use as --pomerium-url for all proxys

### ISSUE THREAD

**Issue by bl0m1** [pomerium/pomerium#2082]
## What happened?

I try to use pomerium-cli to forward a tcp service with the `--pomerium-url=authenticate.mydomain.com `. However this request will fail with a `route_not_found` error

## What did you expect to happen?

I expect my traffic to be forwarded towards my backend as long as the host applied as the last part of my command (host and port) is configured  in the policy section.

## How'd it happen?

1. Ran `pomerium-cli tcp --pomerium-url=https://authenticate.xxx.xx:443 mysecrethost:22`
2. Ran `used ssh towards the local endpoint showing up as output in the previous command`
3. Saw error 

    ```bash
    ❯ ssh mysecrethost
    6:39PM INF tcptunnel: opening connection dst=mysecrethost:22 proxy=authenticate.xxx.xx:443 secure=true
    6:39PM INF tcptunnel: connection closed
    tcptunnel: invalid http response code: 421
    kex_exchange_identification: Connection closed by remote host
    ```

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.13.5-1617718510+403718c
- Server Operating System/Architecture/Cloud: ubuntu 20.04, bare metal

## What's your config.yaml?

```config.yaml
# See detailed configuration settings : https://www.pomerium.io/docs/reference/reference/

# Specify ports:
address: :443
metrics_address: :9299

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://authenticate.xxx.xx
forward_auth_url: https://forwardauth.xxx.xx

#Shared key
shared_key: REDUCTED
shared_secret: REDUCTED
cookie_secret: REDUCTED

# Certificates
certificates:
  - cert: "/etc/letsencrypt/live/authenticate.xxx.xx/fullchain.pem"
    key: "/etc/letsencrypt/live/authenticate.xxx.xx/privkey.pem"

#IDP
idp_provider: google
idp_client_id: "REDUCTED"
idp_client_secret: "REDUCTED"
idp_service_account: "REDUCTED"

# https://www.pomerium.io/configuration/#policy
policy:
- from: tcp+https://mysecrethost:22
  to: tcp://mysecrethost:22
  allowed_groups:
    - GROUP/REDUCTED
```

## What did you see in the logs?

```logs
Apr 12 16:46:45 pomerium pomerium[100169]: {"level":"info","service":"envoy","upstream-cluster":"","method":"CONNECT","authority":"authenticate.XXX.XX:22","path":"","user-agent":"Go-http-client/1.1","referer":"","forwarded-for":"xxx.xx.xxx.xx","request-id":"9151455d-e9fe-43df-b3d3-5d4345c6cdcf","duration":0.376168,"size":0,"response-code":421,"response-code-details":"route_not_found","time":"2021-04-12T16:46:45Z","message":"http-request"}
```

## Additional context

The reason for not running a DNS for each host is that we use ansible and want to be able to use the same inventory when running playbooks over the Pomerium proxy. We could configure DNS to show different records for our internal DNS however this is quite hard to troubleshoot when clients having issues.

Worth saying is that if i point another FQDN towards my poermium servers external IP without mentioning the FQDN anywhere in configuration, In my example I used proxy.XXX.XX and everything worked as I wanted. However as soon as I added the FQDN in my configuration (under the policy section) I started to get the `route_not_found` error again. I assume this could have something to do with vhosts. When the FQDN isn't mentioned within configured it seems to match the default host which seems to perform a wildecard match based on the host header.

I can run a separate FQDN as my proxy record however would rather se this as a supported configuration (for tcp backends) and maybe add a "proxy_service_url" field to the configuration or similar.

This issue is a bit hard to explain but I hope you guys get it. In case of any questions or confusion just let me know and I'll do my best to provide all information needed

**Comment by travisgroth** [comment]
Hi @bl0m1,

To give you an idea of what's happening internally, in case it helps:

By default, pomerium-cli connects to the `destination` and requests a tunnel to `destination`.  This assumes your `from` parameter is a resolvable DNS record.  In the event that it is not, pomerium-cli can connect to `--pomerium-url` and request a tunnel to `destination`.  In this case, you could have `proxy.localhost.pomerium.io` pointing at your proxy and run `pomerium-cli tcp --pomerium-url https://proxy.localhost.pomerium.io mysecrethost:22`.  

Going further, given a policy list like so:

```
policy:
  - from: host1:22
    ...
  - from: host2:22
    ...
  - from: host3:22
   ...
```

you should be able to connect to each one in that configuration by specifying `pomerium-cli tcp --pomerium-url https://proxy.localhost.pomerium.io [host1|host2|host3]:22`.  It looks like you tried something similar, but it didn't quite work as desired.  Can you describe the situation in more detail?  

FWIW, `--pomerium-url=authenticate.mydomain.com` in particular will overlap with your authenticate hostname, which does result in an error.  Any other name that points at the proxy should be okay, though.

**Comment by bluecmd** [comment]
> FWIW, --pomerium-url=authenticate.mydomain.com in particular will overlap with your authenticate hostname, which does result in an error. Any other name that points at the proxy should be okay, though.

Can't the authenticate hostname also handle these tunnel requests? I think that's the confusion here, having to set up a dummy name instead of just using the authenticate hostname that is already there would be less confusing I think.

**Comment by travisgroth** [comment]
> Can't the authenticate hostname also handle these tunnel requests? I think that's the confusion here, having to set up a dummy name instead of just using the authenticate hostname that is already there would be less confusing I think.

This is up to envoy's routing behavior.  I _believe_ it considers the `Host` header for the incoming request first and will match the authenticate route with no chance to match the internal `CONNECT` target of the request.

**Comment by bl0m1** [comment]
> > Can't the authenticate hostname also handle these tunnel requests? I think that's the confusion here, having to set up a dummy name instead of just using the authenticate hostname that is already there would be less confusing I think.
> 
> This is up to envoy's routing behavior. I _believe_ it considers the `Host` header for the incoming request first and will match the authenticate route with no chance to match the internal `CONNECT` target of the request.

Roger, that will work for us. However we are a bit worried about the future if we build our infrastructure around Pomerium. Would it be acceptable if I open a PR adding this scenario to the documentation?

**Comment by travisgroth** [comment]
> Would it be acceptable if I open a PR adding this scenario to the documentation?

More docs are always welcome if you think there's something worth calling out.  

> However we are a bit worried about the future if we build our infrastructure around Pomerium

Can you elaborate on the concern here?

**Comment by travisgroth** [comment]
> The use case for us is to have one pomerium-url where you can access all tcp proxsys. I meant that I'm a bit worried using an undocumented feature as the core feature to switch from a traditional VPN to a more moderna proxy setup. However since you guys allow pr's and seems to generally respond on questions I'm more than happy and will continue working on our implementation :)

Got it.  The routing behavior in a standard configuration - using a DNS name (or names) associated with the proxy service and distinct from `authenticate` - is understood/documented/tested.  The matching of the `authenticate` service given the overlapping host header isn't surprising. 

Conversely, if TCP proxying _happened_ to work with conflicting routing information, I'd be worried about relying on that behavior.

**Comment by bluecmd** [comment]
When using Autocert this behavior (using an unmapped service) seems hard/impossible to tap into. Is there a way to make Pomerium include a domain for this kind of usage in its certificate list to Let's Encrypt?
