### ISSUE TITLE
URLs won't load in browser if I don't type https

### ISSUE THREAD

**Issue by trydalch** [pomerium/pomerium#2083]
## What happened?
I cannot load webpages of a newly added domain without typing the protocol.

## What did you expect to happen?
Be able to just type the domain and have it load the web page.

## How'd it happen?

1. Added the new policy document to the pomerium config file
2. Restarted the pomerium container to force a reload of the config.
3. Navigated to `subdomain.domain.com`

When I added https in front of the domain, it loaded no problem.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): Unsure. Tried to exec into the docker container, but it doesn't have `sh` in the path.
- Server Operating System/Architecture/Cloud: Docker. Image: pomerium/pomerium:latest

## What's your config.yaml?

```config.yaml
# @format

# See detailed configuration settings : https://www.pomerium.io/docs/reference/reference/

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://authenticate.domain.com

# certificate settings:  https://www.pomerium.io/docs/reference/certificates.html
autocert: true

autocert_dir: /data/pomerium/autocert

# REMOVE FOR PRODUCTION
autocert_use_staging: false

# identity provider settings : https://www.pomerium.io/docs/identity-providers.html
idp_provider: auth0
idp_provider_url: https://*****.auth0.com
idp_client_id: *****
idp_client_secret: *****
idp_service_account: *****
# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: *******

# https://www.pomerium.io/configuration/#policy
policy:
  - from: https://sub1.domain.com
    to: http://server2:9000
    allowed_users:
      - my.email@provider.com
    pass_identity_headers: true

  - from: https://sub2.domain.com
    to: http://server2:7000
    allowed_users:
      - my.email@provider.com
    pass_identity_headers: true

  - from: https://sub3.domain.com
    to: http://server2:8001
    allowed_users:
      - my.email@provider.com
    pass_identity_headers: true

  - from: https://sub4.domain.com
    to: http://server2:8080
    allow_public_unauthenticated_access: true
    pass_identity_headers: true

  - from: https://sub5.domain.com
    to: https://server1
    allow_public_unauthenticated_access: true
    # allowed_users: 
    #   - my.email@provider.com
    # pass_identity_headers: false
    tls_skip_verify: true

# These last two urls are the ones I've just added and had this problem with.
  - from: https://sub6.domain.com
    to: http://server2:8888
    allowed_groups: ["Family"]
    
  - from: https://plex.domain.com
    to: http://server3:32400
    allow_public_unauthenticated_access: true

```

## What did you see in the logs?
Unsure where to get them as I'm unable to exec into the container, and also don't see them in the mounted volume.
```logs

```

**Comment by calebdoxsey** [comment]
@trydalch by default your browser will attempt an HTTP connection to the domain. We support redirecting to HTTPS urls with the [http_redirect_addr](https://www.pomerium.io/reference/#http-redirect-address) setting. Does this work for you? Or did you have something else in mind?

**Comment by trydalch** [comment]
I hadn't seen that. That's perfect. Thank you.
