### ISSUE TITLE
controlplane: re-revert recommended defaults / best practices 

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2085]
For my own reference later - https://www.envoyproxy.io/docs/envoy/v1.17.0/version_history/current#deprecated:

>cluster: HTTP configuration for upstream clusters has beem reworked. HTTP-specific configuration is now done in the new http_protocol_options message, configured via the cluster’s extension_protocol_options. This replaces explicit HTTP configuration in cluster config, including upstream_http_protocol_options common_http_protocol_options

I guess we should just wait for 1.17 and then re-apply this change.  No sense in reworking it for a deprecated protobuf.  🤷

_Originally posted by @travisgroth in https://github.com/pomerium/pomerium/issues/1735#issuecomment-754767384_

**Comment by desimone** [comment]
Now that we have migrated to `v0.17` it makes sense to try these again. 

Related:
- https://github.com/pomerium/pomerium/pull/1734
- https://pomerium-io.slack.com/archives/CK6SVMPU0/p1617712008014100

**Comment by sc7565** [comment]
hi @calebdoxsey, I do realize this https://github.com/pomerium/pomerium/pull/1735 was brilliantly done by you and would be grateful if you can create/update code with defaults. I am not so pro-efficient with go. Tried locally but seems I am doing something wrong. Thanks once again
