### ISSUE TITLE
Would it be possible to drop tun.cfg.dstHost from jwtCacheKey

### ISSUE THREAD

**Issue by bl0m1** [pomerium/pomerium#2100]
**Is your feature request related to a problem? Please describe.**
Running Ansible through Pomerium-cli causes hundreds of popus a day, See #2082 

**Describe the solution you'd like**

Currently the `tcptunnel` `jwtCacheKey` using both destination host, proxyhost and tlsconfig. Would it be possible to remove destination host and only have proxyhost here? We have tested the following patch with great success.

```patch
diff --git a/internal/tcptunnel/tcptunnel.go b/internal/tcptunnel/tcptunnel.go
index b4919f9..782d06b 100644
--- a/internal/tcptunnel/tcptunnel.go
+++ b/internal/tcptunnel/tcptunnel.go
@@ -214,7 +214,7 @@ func (tun *Tunnel) run(ctx context.Context, local io.ReadWriter, rawJWT string,
 }
 
 func (tun *Tunnel) jwtCacheKey() string {
-       return fmt.Sprintf("%s|%s|%v", tun.cfg.dstHost, tun.cfg.proxyHost, tun.cfg.tlsConfig != nil)
+       return fmt.Sprintf("%s|%v", tun.cfg.proxyHost, tun.cfg.tlsConfig != nil)
 }
 
 func deBuffer(br *bufio.Reader, underlying io.Reader) io.Reader {
```

This allows us to use ssh helper script https://www.pomerium.io/guides/tcp.html#setup with a `--pomerium-url` set without getting a popup a day for every destination host you would like to proxy traffic towards.

We have considered the security perspective and since the `tun.cfg.proxyHost` is used for connections we are unable to come up with any negative impact.

**Describe alternatives you've considered**

- Running a browser inside the users shell to try "mute" the popups for each new host accessed thru the proxy.

- We have also discussed using a "jumphost" to proxy ssh thru meaning we only allow pomerium to talk to our jumphost and the jumphost to be an additional proxy jump inside our end users ssh configs. However we do not like this singel point of failure and there is a few security concerns since you need to forward your ssh key etc.

**Explain any additional use-cases**

The users would only need one authorisation popup per work day.

**Additional context**

This together with the feature/bug discussed in #2082 creates a synergy and a really seamless experience for end users.

**Comment by calebdoxsey** [comment]
Implemented with the above PR.
