### ISSUE TITLE
internal/sessions: handle extremely large sessions (e.g. Azure)

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#211]
**Describe the bug** 
Some providers, such as azure, return _very_ large access and id tokens. This can cause an issue if the compressed, and encrypted pomerium cookie then exceeds 4096 bytes (supported by all browsers). 

This can cause a redirect loop in pomerium because the cookie will fail to set, and restart the auth process. 

**To Reproduce**:

https://thumbs.gfycat.com/VelvetyTintedIndianpalmsquirrel-mobile.mp4

**Expected behavior**

Pomerium should detect and handle large cookies.  

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.5-dirty+d16978b
- Server Operating System/Architecture/Cloud: Currently only experienced with Azure. 

**Additional context**

Azure in particular (ab)uses `access_tokens` to store a bunch of duplicated identity data. 

See:
- #209 
- #210

**Comment by sbilly** [comment]
I have same issue. Pomerium returns error 500.

![image](https://user-images.githubusercontent.com/123563/60763604-5c9a2080-a0aa-11e9-94bc-95bdd1ba8a27.png)

- Pomerium version (retrieve with pomerium --version): v0.0.5+28efa33
- Server Operating System/Architecture/Cloud: Ubuntu 16.04 + Azure

**Comment by desimone** [comment]
Hi @sbilly !
Sorry about this. Unfortunately this is a known issue with Azure right now which typically returns very, very large session cookies. I'm curious, are you seeing this on every login, or do some of the requests successfully authenticate if you try enough times? 

In my particular case, my session tends to be very close to the [4096](http://browsercookielimits.squawky.net/) byte cutoff so about 75% of my login attempts work.

**Comment by sbilly** [comment]
I have tried 10 times.
It failed with the HTTP-500 error every time, and could not login at all.

![image](https://user-images.githubusercontent.com/123563/61093441-1e6f7900-a47d-11e9-8a71-3dd92cd48a89.png)

**Comment by desimone** [comment]
Hi @sbilly -- thanks for trying. We are going to have to implement a session chunking strategy to fix this for Azure.
