### ISSUE TITLE
HSTS header for external control plane endpoints

### ISSUE THREAD

**Issue by vsdesai** [pomerium/pomerium#2110]
**Is your feature request related to a problem? Please describe.**
We would like to see HSTS header added to the domains/endpoints that are exposed to the internet for the control plane. More specifically the proxy service and authenticate service currently do not return HSTS header, while the managed routes do. 

Was it a conscious choice to leave it out for the proxy/authenticate service? If yes, we would like to learn the reason behind it.

**Describe the solution you'd like**
Have HSTS header in proxy and authenticate service response if some user or external scanning tool issues GET request against these service endpoints.

**Comment by calebdoxsey** [comment]
@vsdesai I'm seeing these headers when I go to `/.pomerium`. Looking at the code, it should be adding the `SetResponseHeaders` to all responses, even those fielded by the control plane instead of a backend service. Was there a specific URL that doesn't have them?

**Comment by vsdesai** [comment]
The URL in question here is the base URL for the canonical name of the proxy and authenticate service that are resolvable from internet.

For example, our setup looks like this:

- pomerium proxy has a DNS (A record) name proxy.xyz.com
- authenticate service has a DNS (A record) name proxy-authenticate.xyz.com
- CNAME record for internal app that we want to allow access through pomerium: myapp.xyz.com >> CNAME >> proxy.xyz.com

Accessing https://myapp.xyz.com returns HSTS header as expected

Accessing https://proxy.xyz.com or https://proxy-authenticate.xyz.com does not return HSTS header

**Comment by calebdoxsey** [comment]
@vsdesai Are these 404 responses? I'm not sure the headers are added if no routes match at all.

**Comment by vsdesai** [comment]
Yes, they return 404

**Comment by vsdesai** [comment]
To provide some context, the lack of HSTS header from URLs that are hosted on our domain and accessibly from internet (even though they return 404) are deemed as lower security standard by the scanning tools.

**Comment by calebdoxsey** [comment]
OK that makes sense. I think we can update the code to set these headers on error pages too.

**Comment by calebdoxsey** [comment]
@vsdesai I updated the code to set these headers on local replies from envoy. It's also being backported to the 0.14 branch.
