### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [pomerium/pomerium#2125]
It has been noticed that while using codecov/codecov-action@v1.3.1 your token d82eb1d7-5990-4a31-baa4-156473402105 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by travisgroth** [comment]
Hi - thank you for the notice.  These credentials are not considered secret by codecov and were in plaintext for historical reasons.  That said, we're moving off the platform anyway.
