### ISSUE TITLE
`kubectl exec` fails with: http: proxy error: http2: invalid Upgrade request header: ["spdy/3.1"]

### ISSUE THREAD

**Issue by pmahoney** [pomerium/pomerium#2126]
## What happened?

`kubectl exec somepod -- sh` failed with:

```
Error from server:

# (blank output above)
```

Note that other `kubectl` commands work to prove that the k8s api proxy is working in general.

## What did you expect to happen?

A remote shell to be established.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): docker image `pomerium/pomerium:git-8924b1a5`

I'm using this image to work around an [issue](https://github.com/pomerium/pomerium/issues/2076) until 0.14 is released.

- Using Pomerium helm chart v18.0.0

- Server Operating System/Architecture/Cloud:

Linux / x86_64 / kubernetes (EKS) on AWS

## What's your config.yaml?

```config.yaml
  - allow_spdy: true
    allowed_domains:
    - example.com.com
    allowed_groups:
    - team@example.com
    from: https://kubernetes-api.example.com
    kubernetes_service_account_token: xxx
    tls_custom_ca: xxx
    tls_server_name: kubernetes
    to: https://xxx.eks.amazonaws.com
```

## What did you see in the logs?

```logs
{"level":"debug","service":"envoy","name":"pool","time":"2021-04-24T21:45:00Z","message":"[C303] using existing connection"}
{"level":"debug","service":"envoy","name":"pool","time":"2021-04-24T21:45:00Z","message":"[C303] creating stream"}
{"level":"debug","service":"envoy","name":"router","time":"2021-04-24T21:45:00Z","message":"[C638][S11473953816453689929] pool ready"}
{"level":"debug","service":"envoy","name":"http2","time":"2021-04-24T21:45:00Z","message":"[C281] stream closed: 0"}
{"level":"debug","time":"2021-04-24T21:45:00Z","message":"pkg/cryptutil: added custom certificate authority"}
{"level":"debug","time":"2021-04-24T21:45:00Z","message":"pkg/cryptutil: added custom certificate authority"}
{"level":"debug","service":"envoy","name":"filter","time":"2021-04-24T21:45:00Z","message":"tls inspector: new connection accepted"}
2021/04/24 21:45:00 http: proxy error: http2: invalid Upgrade request header: ["spdy/3.1"]
{"level":"debug","service":"envoy","name":"client","time":"2021-04-24T21:45:00Z","message":"[C303] response complete"}
```

## Additional context

The `kubectl exec` command uses [the deprecated SPDY protocol](https://github.com/kubernetes/kubernetes/issues/7452), and I was under the impression that this is supported (see https://github.com/pomerium/pomerium/pull/1203).

Notably SPDY support is difficult to come by, for example current versions of [ingress-nginx](https://kubernetes.github.io/ingress-nginx/) and AWS ALB (application load balancer) do not support it. So I have configured my cloud (AWS in my case) with a TCP balancer (NLB) direct to pomerium-proxy.

**Comment by calebdoxsey** [comment]
@pmahoney I just merged a fix which should make `kubectl exec` work.

We support SPDY through envoy, but due to issues with how Kubernetes parses group headers, we ended up re-proxying the request through the Go control plane. Unfortunately out of the box the Go HTTP reverse proxy doesn't support SPDY, because it will use HTTP/2 first. The PR above should fix this. (I was able to `kubectl exec` a busybox pod and interact with it)

When you get a chance could you try the fix? If you're still seeing problems, feel free to re-open the issue.

**Comment by pmahoney** [comment]
@calebdoxsey Yes, I can confirm it works for me as well. Thank you!

I had to clear my local pomerium-cli cache first.
