### ISSUE TITLE
internal/config: refactor viper instance scope

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#213]
After seeing all the viper.Reset() calls in the tests, I'm thinking we should make an instance of viper instead of using the default singleton.  This would keep every viper instance scoped to an Options struct - which would reduce the chances of errors and allow Parallel() calls in many cases that we avoid now.  

I think stashing the instance of viper in the struct or passing it to the parseXXXX() methods would be all that is needed.

_Originally posted by @travisgroth in https://github.com/pomerium/pomerium/pull/202_

**Comment by desimone** [comment]
\cc @travisgroth Do you remember the context for this one. I've completely lost it.

**Comment by travisgroth** [comment]
Yes, the comment more or less captures it.  The idea being we move to a viper instance so tests are potentially less brittle.  We have to be a little careful to reset state as-is because config uses the viper global singleton.
