### ISSUE TITLE
deployment: prepare v0.1.0 release

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#214]
Before tagging

- [x] Review and update examples 
- [x] Review and update dockerfiles
- [x] Review and update docs
- [x] Review and update changelog
- [x] Review and update upgrading guide

After tagging
- [x] Update github release docs
- [x] Publish tagged version of documentation (
- [x] Review and update helm-charts (merge after tag)

**Comment by victornoel** [comment]
@desimone I will be testing current master now, if you want to wait for potential feedbacks before doing release, it's possible :)

**Comment by victornoel** [comment]
@desimone ok I see I was too late, anyway, this seems to work as expected for the issues I was involved in ;)

**Comment by victornoel** [comment]
@desimone @travisgroth but I don't see any image tagged v0.1.0 in docker hub though

**Comment by travisgroth** [comment]
Looks like the arm images are tagged, but not amd64 for some reason.

**Comment by desimone** [comment]
arm64 image should now be there.

**Comment by victornoel** [comment]
@desimone I confirm, it works, I'm using it :)

**Comment by desimone** [comment]
Annnd that should do it!
