### ISSUE TITLE
cmd: add the envoy version to the FullVersion()

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2201]
Maybe we should add the envoy version to the FullVersion() build as well.... thoughts?

_Originally posted by @desimone in https://github.com/pomerium/pomerium/pull/2193#r630584169_

**Comment by travisgroth** [comment]
Rather than include the envoy version specifically in FullVersion, let's add EnvoyVersion and GoVersion as separate outputs.

* print these when running `pomerium -version`
* track these as info metrics

**Comment by desimone** [comment]
Maybe `version.Go()` and version.Envoy()`
