### ISSUE TITLE
Configurable command to open a browser window

### ISSUE THREAD

**Issue by gvolpe** [pomerium/pomerium#2239]
**Is your feature request related to a problem? Please describe.**

The [documentation](https://www.pomerium.io/guides/kubernetes.html#kubectl) says:

> Pomerium uses a custom Kubernetes exec-credential provider for kubectl access. This provider will open up a browser window to the Pomerium authenticate service and generate an authorization token that will be used for Kubernetes API calls.

I don't know exactly what's the command `pomerium` uses to open that browser window but I assumed it's `xdg-open` in X sessions and the related tool in other environments. 

This is problematic when running different instances of a browser with different profiles, as by default it will open a browser tab in the default profile and there is no way to customize how this is done AFAIK. 

**Describe the solution you'd like**

A configuration property or an environment variable dictating how to open a browser window should suffice. E.g., with Firefox it could be something like this.

```
POMERIUM_OPEN_BROWSER='firefox -p "custom-profile" -new-tab $1' kubectl get pods
```

**Describe alternatives you've considered**

I tried setting the `BROWSER` environment variable to the aforementioned command before invoking `kubectl` but `xdg-open` ignores it and defaults to the value set by `xdg-settings get default-web-browser`, which is `firefox.desktop` in my case.

**Comment by desimone** [comment]
This should be fixed with https://github.com/pomerium/pomerium/pull/2617. If not please reopen @gvolpe :)

**Comment by gvolpe** [comment]
Thank you! 🚀
