### ISSUE TITLE
allowed_idp_claims not working with the latest changes

### ISSUE THREAD

**Issue by vsdesai** [pomerium/pomerium#2241]
## What happened?
allowed_idp_claims based authorization policy has stopped working for us. 

This was working at least until commit# 5b1b6e5. With commit# 96b9702, it doesn't work anymore.

## What did you expect to happen?
allowed_idp_claims should be able to look at claims from AccessToken and make authorization decision based on that

## How'd it happen?

We are using PindID (OIDC) as IdP and relying on custom claims passed in the AccessToken to make authorization decision. With the new version of pomerium, we are getting "response-code":403,"response-code-details":"ext_authz_denied" even when the claim is present in token.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.14.0-34-g425d6b86+425d6b86
- Server Operating System/Architecture/Cloud: RHEL 7.6 x86_64

## What's your config.yaml?

services: "all"
authenticate_service_url: <scrubbed>

pomerium_debug: false
address: :8443

databroker_storage_type: redis
databroker_storage_connection_string: redis+sentinel://<scrubbed>

cookie_expire: 16h

certificates:
    - cert: <scrubbed>
      key: <scrubbed>

shared_secret: <scrubbed>
cookie_secret: <scrubbed>

idp_provider: "oidc"
idp_provider_url: <scrubbed>
idp_client_id: <scrubbed>
idp_client_secret: <scrubbed>
idp_scopes: "openid email profile"
signing_key: <scrubbed>

policy:
  - from: <scrubbed>
    to: <scrubbed>
    allow_any_authenticated_user: false
    allowed_idp_claims:
        privilegeLevels:
          - Level_1
  - from: <scrubbed>
    to: <scrubbed>
    allow_any_authenticated_user: false
    allowed_idp_claims:
        privilegeLevels:
          - Level_2

## What did you see in the logs?
{"level":"info","service":"authorize","request-id":"3cbd82f3-d347-45d1-ae04-47ae7b192dd9","check-request-id":"3c093287-7ad0-4f5a-83c9-b6244151c61c","method":"GET","path":"/","host":"<scrubbed>","query":"","allow":false,"deny":null,"user":"<scrubbed>","email":"","databroker_server_version":4704621818127022095,"databroker_record_version":1428,"email-address":"<scrubbed>","uuid":"<scrubbed>","privilege-levels":"Level_1","event":"AuthorizeUser","time":"2021-05-26T14:58:24-04:00","message":"authorize check"}
{"level":"info","service":"envoy","upstream-cluster":"","method":"GET","authority":"<scrubbed>","path":"/","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0","referer":"","forwarded-for":"<scrubbed>","request-id":"3c093287-7ad0-4f5a-83c9-b6244151c61c","duration":13.516363,"size":11212,"response-code":403,"response-code-details":"ext_authz_denied","event":"ProxiedRequest","time":"2021-05-26T14:58:25-04:00","message":"http-request"}

**Comment by calebdoxsey** [comment]
@vsdesai I think this should be fixed on master. Let me know if its still not working for you.

We did a major refactor of how policy is evaluated and the code I wrote convert legacy policy into the new format didn't do it right. Thanks for catching this.

**Comment by vsdesai** [comment]
Thanks for the follow up. We will try out the fix and report back.

**Comment by vsdesai** [comment]
Confirmed it is now working as expected. Thank you.
