### ISSUE TITLE
JWT Assertion has exp claim with floating point value

### ISSUE THREAD

**Issue by branchmispredictor** [pomerium/pomerium#2248]
## What happened?

Pomerium provided a JWT assertion (`x-pomerium-jwt-assertion`) with a floating point exp claim to a downstream service:

Anonymized JWT that was received by my downstream service in the HTTP header:
```
{
  "aud": "vikunja.domain.test",
  "email": "email-address@gmail.com",
  "exp": 1622350222.710636,
  "given_name": "first-name",
  "groups": [],
  "iat": 1622349711,
  "iss": "authenticate.domain.test",
  "jti": "7ab3c360-xxxx-xxxx-xxxx-9871579c1fee",
  "sub": "11xxxxxxxxxxxx249",
  "user": "11xxxxxxxxxxxx249"
}
```

## What did you expect to happen?

An `exp` with a whole number representation (e.g. `1622350222`). I am not sure if this was introduced by my upgrade from v12 to 14.4, or if this was simply a time-based issue as exp is always changing.

## How'd it happen?

Visited service in browser behind pomerium proxy, auth failed as deserializing the jwt failed due to an expectation that exp would be a whole number and not a float.

## What's your environment like?

- Pomerium version: pomerium/pomerium:v0.14.4
- Server Operating System/Architecture/Cloud: docker

## What's your config.yaml?
N/A

## What did you see in the logs?

Pomerium logs are N/A. Downstream service log line: `2021-05-30T04:45:22.555923747Z: ERROR   ▶ identityawareproxy/1 07f json: cannot unmarshal number 1.622350222545325271e+09 into Go struct field IAPClaims.exp of type int64`

## Additional context

I know with JSON the number format is not well defined, but the most common golang jwt library seems to assume exp should be a whole number: https://github.com/dgrijalva/jwt-go/blob/master/claims.go#L20. Using pomerium jwt assertions as auth used to work for this service when the exp was provided as a whole number. If this is an unintended regression, I'd appreciate a fix, but if having a floating point exp is intended behavior, please let me know and I will update the downstream service to not use the default exp-is-an-int behavior.

Thanks!

**Comment by desimone** [comment]
This should be in unix seconds. 

```
      A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1,
      2013 Edition [POSIX.1] definition "Seconds Since the Epoch", in
      which each day is accounted for by exactly 86400 seconds, other
      than that non-integer values can be represented.  See RFC 3339
      [RFC3339] for details regarding date/times in general and UTC in
      particular.

```

https://github.com/square/go-jose/blob/3a5ee095dcb5030a9de84fb92c222ac652fff176/jwt/claims.go#L41-L120
