### ISSUE TITLE
codec_type: `http1` / `auto` returns `METHOD_UNSPECIFIED`

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2271]
## What happened?

I get a protocol error when setting `code_type` explicitly.  Both `http1` and `auto` do not seem to be working.

## What did you expect to happen?

No error.  This is surprising because I would assume I am _already_ running with implied `http1` in all in one mode..

## How'd it happen?

1. Go to `https://verify.localhost.pomerium.io`
2. Error

<img width="1336" alt="Screen Shot 2021-06-06 at 1 16 59 PM" src="https://user-images.githubusercontent.com/1544881/120938777-7c3c8800-c6c9-11eb-90dd-59cc1269e9af.png">

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 744e2c79
- Server Operating System/Architecture/Cloud: From source, M1, Safari

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://authenticate.localhost.pomerium.io
codec_type: http1

policy:
  - from: https://verify.localhost.pomerium.io
    to: http://localhost
    allowed_domains:
      - pomerium.com
      - gmail.com
    pass_identity_headers: true
```

## What did you see in the logs?

```logs.json
{
  "level": "info",
  "peer": "127.0.0.1:54254",
  "server_version": 15303628973844742000,
  "record_version": 19,
  "time": "2021-06-06T13:15:40-07:00",
  "message": "sync"
}
{
  "level": "info",
  "service": "envoy",
  "upstream-cluster": "",
  "method": "METHOD_UNSPECIFIED",
  "authority": "",
  "path": "",
  "user-agent": "",
  "referer": "",
  "forwarded-for": "",
  "request-id": "",
  "duration": 0.18475,
  "size": 11,
  "response-code": 400,
  "response-code-details": "http1.codec_error",
  "time": "2021-06-06T13:15:42-07:00",
  "message": "http-request"
}
{
  "level": "info",
  "service": "envoy",
  "upstream-cluster": "",
  "method": "METHOD_UNSPECIFIED",
  "authority": "",
  "path": "",
  "user-agent": "",
  "referer": "",
  "forwarded-for": "",
  "request-id": "",
  "duration": 0.162667,
  "size": 11,
  "response-code": 400,
  "response-code-details": "http1.codec_error",
  "time": "2021-06-06T13:15:42-07:00",
  "message": "http-request"
}
{
  "level": "info",
  "service": "envoy",
  "upstream-cluster": "",
  "method": "METHOD_UNSPECIFIED",
  "authority": "",
  "path": "",
  "user-agent": "",
  "referer": "",
  "forwarded-for": "",
  "request-id": "",
  "duration": 0.178875,
  "size": 11,
  "response-code": 400,
  "response-code-details": "http1.codec_error",
  "time": "2021-06-06T13:15:42-07:00",
  "message": "http-request"
}
```

## Additional context

- https://github.com/pomerium/pomerium/issues/2150
- https://github.com/pomerium/pomerium/pull/2156

**Comment by xlejo** [comment]
Same here. Running in Kubernetes (K3S 1.21) behind Nginx Ingress.

**Comment by calebdoxsey** [comment]
This is caused by the interaction between the codec type option and the addition of using ALPN to switch to HTTP/2 automatically.
