### ISSUE TITLE
Pomerium Seems to grab a random 100 groups when user has more than 100 groups in Azure

### ISSUE THREAD

**Issue by megalan247** [pomerium/pomerium#2299]
## What happened?
Hey everyone. We use Pomerium pretty extensively and it is an amazing product! Unfortunately we are having some problems with a large number of groups in Azure. Seemingly randomly, when a user is assigned to over 100 groups in Azure, Pomerium will show in the user info endpoint only 100 of the groups they are assigned to. This list of 100 groups seems to change after a while, but it is rarely the full list. Very occasionally (especially after cleaning the databroker redis and restarting pomerium) it will show all the groups. But then if you wait a while it will revert back to 100 groups again.

It is strange because the full group list is there at first, and then it disappears (especially triggerable after you login with the same user on another PC)
## What did you expect to happen?
I expect pomerium to always discover all groups a user is assigned to
## How'd it happen?

1. Start pomerium connected to Azure AD with many groups and group assignments
2. Login to Pomerium and check user info endpoint
3. After a while (any time between 5 and 30 minutes or so) go back to the user info endpoint and you will see only 100 groups in the list.
4. Users are also not able to login to applications and are presented with a 401

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.14.5
- Server Operating System/Architecture/Cloud: Docker (Ubuntu)

## What's your config.yaml?

```config.yaml
---
authenticate_service_url: https://pomerium.example.com
address: ":8080"
insecure_server: true
idp_provider: azure
idp_provider_url: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/v2.0
idp_client_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
jwt_claims_headers: email
timeout_read: 1210s
timeout_write: 1210s
timeout_idle: 1210s
idp_refresh_directory_interval: 1h
idp_refresh_directory_timeout: 5m
policy:

- title: Prometheus
  from: https://prometheus.example.com/
  to: https://prometheus.example.com/
  allowed_groups:
  - groupname1

- title: Karma
  from: https://alertmanager-dashboard.example.com/
  to: https://alertmanager-dashboard.example.com/
  allowed_groups:
  - groupname2

- title: Alertmanager
  from: https://alertmanager.example.com/
  to: https://alertmanager.example.com/
  allowed_groups:
  - groupname3

- title: Grafana
  from: https://grafana.example.com/
  to: https://grafana.example.com/
  allowed_groups:
  - groupname4
  - groupname5
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

## Additional context

The below environment vars are also set
      IDP_CLIENT_SECRET: "{{ pomerium_idp_client_secret }}"
      COOKIE_SECRET: "{{ pomerium_cookie_secret}}"
      IDP_SERVICE_ACCOUNT: "{{ pomerium_idp_service_account }}"
      FORWARD_AUTH_URL: "https://pomerium.example.com"
      DATABROKER_STORAGE_TYPE: "redis"
      DATABROKER_STORAGE_CONNECTION_STRING: "{{ pomerium_redis }}"
      SHARED_SECRET: "{{ pomerium_cookie_secret }}"
      INSECURE_SERVER: "true"
      METRICS_ADDRESS: "0.0.0.0:9090"

**Comment by Seros** [comment]
Hi ^^
I'm from the same company as @megalan247 and I digged a bit into this as I'm affected by this as well. It seems that for grabing the initial user data the application gathers the groups of the member as well but without using the pagination. At https://github.com/pomerium/pomerium/blob/master/internal/directory/azure/azure.go#L126 the /transitiveMemberOf endpoint is called but this only returns the first 100 groups the user is a member of. So if there are more than 100 groups it should behave the same way as it gathers the deltas for groups and users and calling the @odata.nextLink from the response to get the next page of groups. 

Not sure if it was left intentionally but don't see a reason to have it not included. 

A reason to have it is just that gathering all the deltas can take some time after Pomerium got restarted for whatever reason depending on the number of groups, users and changes of these. Our initial delta takes more than 5mins which leads to a delay of having all the groups of a user.

In case you see this as a valid point and would like to have this changed, I can support with an PR. Thanks a lot!

**Comment by calebdoxsey** [comment]
Hi @Seros 

Thanks for digging in. This is extremely helpful and does look like an oversight when we introduced syncing of a single user's groups. (to speed up initial sync)

It should be straightforward to fix and I can take a look today. I think it should also be easy to backport to 0.14.
