### ISSUE TITLE
machine to machine authentication

### ISSUE THREAD

**Issue by kschu91** [pomerium/pomerium#2307]
**Is your feature request related to a problem? Please describe.**

Pomerium looks like a great product and we were very close on using it in our project. But unfortunately we stumbled upon the same issues that others already had:
Machine 2 machine authentication is not possible with pomerium which is unfortunately the only downside of pomerium.

The client credentials flow is a common approach to achieve that.

Issues that were already discussing this in the past:
- #1130 
- #524

Assuming the following use case:
- a machine or service (eg. a serverless function like aws lambda or any piece of code running somewhere in the world) needs to call an API endpoint sitting behind pomerium-proxy
- to achieve that, the machine or service issues an access token using the client credentials flow from the same IDP pomerium is using (just with a different client)
- the machine or service sends the issued JWT Bearer token as Authorization header when calling the API endpoint

**Describe the solution you'd like**
- pomerium recognizes the token and verifies the JWT token using the keys of the IDP
- pomerium ensures the audience in the token matches, if the aud claim has been provided
- pomerium authorizes the request and forwards it to the respective upstream

**Alternatives**
Maybe an alternative is to use mTLS to authenticate machines. mTLS is already supported by pomerium but as I understood it, just as an additional security layer.
When using this for authenticating machine 2 machine communication it would be required to authenticate and authorize a request using mTLS only.
You could achieve that by adding an additional entry point in your cluster and bypass pomerium for machine 2 machine traffic and then handling the mTLS by anything else. But that is not a nice solution.

**Comment by desimone** [comment]
Hey @kschu91 --

Machine to machine support  is coming in the very soon to be publicly announced enterprise version of Pomerium. Feel free to reach out @ bdd {at} pomerium.com and I'd be happy to share more details.

**Comment by kj187** [comment]
That is quite a pity that this is a pure enterprise feature. I'm actually super happy with Pomerium, but because of the missing feature in the open source variant, I will probably look for an alternative ;-(
