### ISSUE TITLE
[google] Force login choice instead of using an already logged in account

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#231]
**Describe the bug**

Given:
- an app protected by pomerium configured to use the google identity provider for a given domain
- a user already logged with a google account that is not one of the above domain

When the user accesses the app:
- the authenticate service redirects to google auth page
- google directly consider the user as logged in with the first incorrect identity
- google shows a 403 error saying `Error: org_internal` 

**Expected behavior**

I would expect (if it's actually possible) to have google propose to log into another identity in that case.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.1.0
- Server Operating System/Architecture/Cloud: Google Cloud Identity Provider

**Comment by victornoel** [comment]
@desimone I think something like that: https://stackoverflow.com/questions/23436617/force-google-to-show-account-chooser-and-consent-screen

Should solve the problem

**Comment by victornoel** [comment]
I tried to modify `prompt` to `select_account+consent` in the url and it seems to work as expected.

**Comment by desimone** [comment]
This is actually the default behavior I am seeing; I'm not able to reproduce.

Here's what I am doing (in a fresh incognito window).

1. Log into my pomerium.io email (this user has access).
2. Log into my gmail email (this user does not have access). [See](https://user-images.githubusercontent.com/1544881/61406884-a694ba80-a891-11e9-966b-387583f72bea.png)
3. Try to access a protected domain `httpbin.corp.some.example..com`
4. I am given a choice of which user to login with.

  <img width="462" alt="Screen Shot 2019-07-17 at 12 49 54 PM" src="https://user-images.githubusercontent.com/1544881/61406883-a5fc2400-a891-11e9-8ed0-250250d2c6cc.png">

**Comment by victornoel** [comment]
@desimone to reproduce this, you need to be logged in only with your personal account and not the pomerium one, and then connect to the app: because only one user is connected, google does not show the login choser.

**Comment by desimone** [comment]
@victornoel Maybe I'm just (un)lucky? 
https://youtu.be/byB9zJ8FpIs

**Comment by victornoel** [comment]
When I do that, I don't get up to the pomerium error page, but to an error
page from Google that says the client ID used does not accept other
organisations to connect. Maybe that's where is the difference?
Tomorrow I will try the image from the PR you opened and see if it fixes
the problem in my environment and get back to you :)

Le jeu. 18 juil. 2019 à 19:54, Bobby DeSimone <notifications@github.com> a
écrit :

**Comment by victornoel** [comment]
@desimone so, without surprise, if I use the image from #232, everything works as I expect:
- if i'm not logged at all, I get the login page from google
- if I'm logged in one account (gmail account), I get the profile chooser, where I can choose to login with another user if desired
- if I'm logged with two account (gmail + corp), I get the profile choose too.

To me, this is the solution to this issue, and I don't think it introduce any counter-intuitive behaviour (especially if, as your experimentations seems to show, there are some cases when even with only one account logged in, google would show the profile chooser).

**Comment by desimone** [comment]
@victornoel I agree; though I was a bit surprised by the default behavior on my end.
