### ISSUE TITLE
SPA X-Requested-With / 401 response

### ISSUE THREAD

**Issue by patrickfnielsen** [pomerium/pomerium#2310]
**Is your feature request related to a problem? Please describe.**
No related problem.

**Describe the solution you'd like**
When using a SPA you have to send the "X-Requested-With" header with all requests to get a 401 back, instead of the default redirect.

It's not recommended to use X-Requested-With to detect ajax requests, and I think we should consider alternative solutions.

**Describe alternatives you've considered**
I see a few alternative solutions:

- Have an config option we can set in the policy to return 401 and not 302
   - That way we can say any policy related to our API should return 401
   - Has the benefit of our application not knowing anything about the proxy
- Have a custom x-pomerium-spa: true - or similar - header we can send from our SPA to explicit request 401s back
- Use the accept header, so if we only accept "application/json", dont send a redirect back to us.
   - This might need to be configurable to prevent it breaking anything
   - Again, has the benefit of our application not knowing about the proxy

**Additional context**
Note that adding the X-Requested-With header makes the request "unsafe" (as defined by CORS), and will trigger a preflight request, which may not be desirable.

See [https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests ](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests ) for more

**Comment by travisgroth** [comment]
Hi @patrickfnielsen,

We just recently tried to address this in `v0.14.6` via https://github.com/pomerium/pomerium/pull/2298.  We are using the same solution you suggested - inspecting the `Accept` type for indications that the client wouldn't handle a redirect correctly.  `application/json` is one of the types we suppress redirects for.

If you're having issues with that feature on `v0.14.6`, please let us know.

**Comment by patrickfnielsen** [comment]
I was sure I checked other issues for references must have missed it, and of course I also managed to missed the v0.14.6 release.

I'll give it a test tomorrow, thanks for help and quick response!

**Comment by travisgroth** [comment]
👍
