### ISSUE TITLE
Permission denied failed to measure envoy process metrics

### ISSUE THREAD

**Issue by nicolastakashi** [pomerium/pomerium#2345]
## What happened?
I'm running a Pomerium instance as a non-root user and I get the error regarding permission denied to access the `/proc` directory

## What did you expect to happen?

Scrape metrics regarding the process with a non-root user

## How'd it happen?

1. Run the pomerium as a system.d service as a non-root user
2. Check the service logs
3. Saw error

## What's your environment like?

- Pomerium version 0.14.7:
- Server Operating CentOS 7:

## What's your config.yaml?
N/A

## What did you see in the logs?
```
{"level":"error","error":"open /proc/17988/fd: permission denied","time":"2021-07-08T09
:33:09Z","message":"failed to measure envoy process metrics"}
```
## Additional context
This can be a little tricky, especially when we have security requirements to not run a process as the root user.

**Comment by alexfornuto** [comment]
For additional context, when you say "system.d service as a non-root user", are you saying that you invoke the service with `systemctl --user`, or are you referring to the default behavior of our rpm package?

**Comment by travisgroth** [comment]
Hi @nicolastakashi,

Chances are there's another error above that one.  Unfortunately our current envoy build is not compatible with CentOS 7.  Here's an example of the message you should check for:

> Jul  8 19:25:21 cent7 pomerium: {"service":"envoy","name":"envoy","time":"2021-07-08T19:25:21Z","message":"/tmp/pomerium-embedded-files/envoy-3932374839/envoy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/pomerium-embedded-files/envoy-3932374839/envoy)"}

We'd recommend upgrading to CentOS 8 or using docker at this time.

**Comment by nicolastakashi** [comment]
> For additional context, when you say "system.d service as a non-root user", are you saying that you invoke the service with `systemctl --user`, or are you referring to the default behavior of our rpm package?

When I have a service running like an example below.

```
[Unit]
Description="Pomerium - identity-aware access proxy."
Documentation=https://www.pomerium.io/
Requires=network-online.target
After=network-online.target
ConditionFileNotEmpty=/etc/pomerium/config.yml

[Service]
User=pomerium
Group=pomerium
PrivateTmp=true
ExecStart=/usr/bin/pomerium -config /etc/pomerium/config.yml
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by nicolastakashi** [comment]
> Hi @nicolastakashi,
> 
> Chances are there's another error above that one. Unfortunately, our current envoy build is not compatible with CentOS 7. Here's an example of the message you should check for:
> 
> > Jul  8 19:25:21 cent7 pomerium: {"service":"envoy","name":"envoy","time":"2021-07-08T19:25:21Z","message":"/tmp/pomerium-embedded-files/envoy-3932374839/envoy: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/pomerium-embedded-files/envoy-3932374839/envoy)"}
> 
> We'd recommend upgrading to CentOS 8 or using docker at this time.

Yeah, Dude!
After I search a little bit more I could find that logline, I'll try one of the approaches mentioned by you.

**Comment by travisgroth** [comment]
Great thanks for the follow up.
