### ISSUE TITLE
🐛  in v0.15.0 with GCP cloud run

### ISSUE THREAD

**Issue by oliverxchen** [pomerium/pomerium#2454]
## What happened?

A configuration that was previously working using the `latest` tag stopped working, with requests resulting in 401s with the message:

```
Error: Unauthorized
Your client does not have permission to the requested URL /.
```

## What did you expect to happen?

Request should have gone through, like before.

## How'd it happen?

1. Ran a deployment using terraform after v0.15.0 was released.
2. In a browser, go to any subdomain protected by pomerium.
3. Saw the error message:
    ```
    Error: Unauthorized
    Your client does not have permission to the requested URL /.
    ```
4. When I pin the version to v0.14.7 and redeploy, everything works again. 

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.15.0
- Server Operating System/Architecture/Cloud: GCP, Cloud Run, using the docker image at `gcr.io/pomerium-io/pomerium:latest-cloudrun` (run on Aug 8, 2021)

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://authn.XXXXXX.XXXXXX.com
shared_secret: XXXXXX
cookie_secret: XXXXXX
idp_provider: "google"
idp_client_id: XXXXXX
idp_client_secret: "XXXXXX"
```

## What did you see in the logs?

```logs
Info 2021-08-08 21:26:15.247 HKT GET 302 2.06 KB 232 ms Chrome 92 https://authn.<subdomain>.<domain>.com/oauth2/callback?state=<redacted>&code=<redacted>&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=<domain>.com&prompt=consent
Info 2021-08-08 21:26:15.326 HKT GET 302 3.41 KB 12 ms Chrome 92 https://authn.<subdomain>.<domain>.com/.pomerium/sign_in?pomerium_expiry=1628429471&pomerium_issued=1628429171&pomerium_redirect_uri=https%3A%2F%2Flib.<subdomain>.<domain>.com%2F&pomerium_signature=<redacted>
Info 2021-08-08 21:26:15.401 HKT GET 302 1.52 KB 13 ms Chrome 92 https://lib.<subdomain>.<domain>.com/.pomerium/callback/?pomerium_expiry=1628429475&pomerium_issued=1628429175&pomerium_redirect_uri=https%3A%2F%2Flib.<subdomain>.<domain>.com%2F&pomerium_session_encrypted=<redacted>&pomerium_signature=<redacted>
Warning 2021-08-08 21:26:15.502 HKT GET 401 1.25 KB 43 ms Chrome 92 https://lib.<subdomain>.<domain>.com/
Warning 2021-08-08 21:26:15.730 HKT GET 401 1.26 KB 30 ms Chrome 92 https://lib.<subdomain>.<domain>.com/favicon.ico
```

## Additional context

I'm also getting log messages:

```logs
failed to measure envoy process metrics
```

but these are also appearing in the working version 0.14.7 so I don't think this is causing the problem.

**Comment by travisgroth** [comment]
Hi - a few questions:

- are your policies using groups, claims or users?  Can you share some samples of route definitions that no longer work?
- are there any messages related to directory or OIDC provider?
- are you using the GCP serverless integration with upstream endpoints or no?

**Comment by oliverxchen** [comment]
Thanks, @travisgroth. Apologies for my late reply:

* the policies allow access by anybody in a domain. The terraform config is:

```terraform
            - from: https://lib${local.domain}
              to: ${google_cloud_run_service.apidocs.status[0].url}
              allowed_domains:
                - domain.com
              enable_google_cloud_serverless_authentication: true
```

* I don't think there are any log messages related to directory or OIDC provider, the closest is this:

```log
"refreshing directory users"
```

* I'm not sure what "upstream endpoints" are, so I'm assuming no...

**Comment by Mistic92** [comment]
We just noticed the same issue today. Looks like pomerium service is not using service to service headers properly to send requests.
