### ISSUE TITLE
Securing a private Docker registry

### ISSUE THREAD

**Issue by sandeep-khanna** [pomerium/pomerium#251]
Can Pomerium be used to provide a secure access to a private Docker registry?

Here are a few relevant articles:
* [Deploying a private Docker registry](https://docs.docker.com/registry/deploying/)
* [Using a nginx proxy for Docker registry authentication](https://docs.docker.com/registry/recipes/nginx/)
* [Configuring a Docker registry](https://docs.docker.com/registry/configuration/#auth)
* [Using an external token service for Docker registry authentication](https://docs.docker.com/registry/spec/auth/token/)

**Comment by travisgroth** [comment]
Hi @sandeep-khanna - thank you for your interest!

As is, Pomerium is more designed for end user access than service to service access. Docker registries can fall into both of those buckets, but the network request patterns are more similar to service-to-service, which makes it tricky to use Pomerium currently.  There are [service-to-service capabilities](https://www.pomerium.io/docs/reference/programmatic-access.html) but I don't think they would work well for end user scale.

The token service protocol outlined in the docker documentation seems interesting but is _very_ application specific.  What might be more appropriate is to build a credential helper for docker cli/engine.  It would be similar to the one used for GCR and handle storing credentials and helping follow OIDC flow, and occasional token refresh.  If it handled both user and programmatic modes, that would probably fit your target use case.

This isn't currently on the roadmap, but we'd be open to advising/assisting if you were interested in working on it.
