### ISSUE TITLE
Built-in SSH relay server

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#2596]
The Chrome ssh client addon (https://chrome.google.com/webstore/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd) has a ssh-relay protocol (https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/relay-protocol.md) that support relaying SSH connections over HTTP.

It's possible to run other open source relay server implementations (e.g. https://github.com/hazaelsan/ssh-relay and https://github.com/zyclonite/nassh-relay) behind Pomerium and point the Chrome SSH client to Pomerium, but it would be awesome if Pomerium has a built-in relay server.

The configuration can have a special support for ssh:

```
- from: ssh+https://ssh-relay.example.com:8022
  to: ssh://server:22
```

**Comment by yegle** [comment]
FWIW I'm aware of https://www.pomerium.com/guides/tcp.html, but my primary SSH client is a Chromebook and cannot easily run `pomerium-cli`.

**Comment by alexfornuto** [comment]
@yegle I can't speak to the technical challenges of the proposed solution here, but I can add my user experience. I use the Linux development environment on my Chromebook to run `pomerium-cli` and use proxied SSH connections, not to mention RDP sessions using Remmina as a client. It's more overhead than an in-Chrome solution just for SSH, but I had the environment installed anyway.

One thing to note: The IdP sign-in uses a browser in the Linux environment, so I get the strange experience of Firefox opening in my Chromebook when making a first connection to a route.
