### ISSUE TITLE
Invalid example reference in kubernetes_gke.sh

### ISSUE THREAD

**Issue by bweston92** [pomerium/pomerium#263]
https://github.com/pomerium/pomerium/blob/dee126f4dc9e57553ed4421e84aa746b686f3615/scripts/kubernetes_gke.sh#L31

There is no example directory in `/docs/docs`

**Comment by e9169** [comment]
Yes, please, solve this as soon as possible since the yaml files are really useful for other environments, cloud providers and for testing. Thank you.
