### ISSUE TITLE
Pomerium making hundreds of requests to Github API, exhausting the quota

### ISSUE THREAD

**Issue by dginther** [pomerium/pomerium#2666]
## What happened?
It appears that Pomerium, when confronted with a Github Org with MANY teams, makes hundreds of requests for 5 results at a time, to determine what group a user is in. I believe the code that is doing this is here:
https://github.com/pomerium/pomerium/blob/8a8dcdf49117e83d1b35757c6fee3858d7e16ed9/internal/identity/oauth/github/github.go#L170

Authenticated users get 5000 requests per hour and our quota was exhausted in less than an hour. We have a large Org with over 2300 teams. 

![Screen Shot 2021-10-07 at 9 27 49 AM](https://user-images.githubusercontent.com/4662758/136415834-f94682cd-c809-49a5-ba35-1469baa1bfd7.png)
I stopped the Pomerium container this morning at 8:15, you can see the difference easily.

## What did you expect to happen?
Pomerium should use paginated results when retrieving items from the Github API to avoid exhausting the quota. Perhaps instead of using just httputil, the google go-github module could be used to make this easier: https://github.com/google/go-github

## How'd it happen?

1. Have a large Github Org with many teams
2. Have Pomerium configured
3. Use Pomerium
4. See Pomerium exhaust the Github API quota in less than an hour

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.14.7
- Server Operating System/Architecture/Cloud: EKS

## What's your config.yaml?

N/A

## What did you see in the logs?

N/A

**Comment by travisgroth** [comment]
Hi @dginther - FYI you may be able to mitigate this somewhat by decreasing the sync frequency: https://www.pomerium.com/reference/#identity-provider-refresh-directory-settings.

**Comment by dginther** [comment]
I will tell the team that is now handling this and they can give it a try. Thanks!
