### ISSUE TITLE
Docs: Update Console Docs re: Upstream/Downstream CA

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/pomerium#2716]
Update the docs and inline copy to better differentiate settings that provide CA certs for user <-> Pomerium connections from Pomerium <-> Service connections.

**Comment by alexfornuto** [comment]
Assigning to @travisgroth to move to the console repo and assign/process through Dev processes.

**Comment by alexfornuto** [comment]
@travisgroth / @alexfornuto to write copy to provide to Console

**Comment by alexfornuto** [comment]
The copy updates are [applied](https://github.com/pomerium/pomerium/pull/3026) to the source, so I think we can close this issue while we wait for https://github.com/pomerium/pomerium-console/pull/2327 to be finished, ya?

**Comment by travisgroth** [comment]
👍
