### ISSUE TITLE
Using Pomerium as Kubernetes ingress controller

### ISSUE THREAD

**Issue by fiahil** [pomerium/pomerium#273]
Note, this has been discussed here #94

**Is your feature request related to a problem? Please describe.**

I'm using Pomerium inside a Kubernetes cluster with nginx-ingress as the ingress-controller. Currently, requests are proxied twice (first Nginx, and then Pomerium proxy) and pomerium policies look a lot like ingress definitions.

**Describe the solution you'd like**

Ideally, we would like to choose between two solutions:
- Use Pomerium as external authentication/authorization service for an existing ingress-controller (ingress-nginx, traefik, ambassador)
- Use Pomerium as ingress controller by leveraging existing proxies or load balancers like Envoy

**Describe alternatives you've considered**

I've been testing multiple ingress controllers, and the most suitable alternatives would be Kong or Ambassador. Although, authentication and authorization is not their main focus and it's not readily available in their open source version.

**Additional context**

In our use case, we manage multiple clusters with identical architecture. We love the portability provided by kubernetes, and we value flexible solutions with completely automated deployment. We also prefer kubernetes-native solutions that use existing resources (Ingress) and annotations, or ones that create their own CRD with a well-defined API, over special snowflakes that use their own domain language or yaml in text fields.

**Comment by desimone** [comment]
Thank you for writing up this issue @fiahil ; Will investigate and hopefully have some updated thoughts on this soon. 

\cc @travisgroth

**Comment by travisgroth** [comment]
@fiahil FYI - https://github.com/pomerium/pomerium/issues/425#issuecomment-567039741

**Comment by travisgroth** [comment]
@fiahil first RC of the pomerium operator has been integrated into our helm chart at https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/README.md#pomerium-operator-experimental

https://github.com/pomerium/pomerium-operator#using
https://github.com/pomerium/pomerium-operator/releases

Not a full ingress controller at this time, as it leverages forward auth.  The plan is to move towards a full ingress controller, but that depends on a few factors.  Please report any issues or suggestions!  

If you don't mind, we'll close this out and can shift further features/improvements into the operator repo.
