### ISSUE TITLE
Incorrect TLS certificate can be selected with databroker on alternate port

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#2740]
## What happened?

TLS connections can be terminated by a fallback/incorrect certificate rather than a certificate matching the databroker hostname when the following conditions are true:

- there are 2+ certificates in the `certificates` configuration key
- the databroker certificate is not first in the `certificates` list
- databroker is running on an alternate port such as `:8443`

I suspect this can happen with Authorize as well.

## What did you expect to happen?

If there is an available certificate valid for the databroker hostname, it should be used to terminate TLS connections.  

## How'd it happen?

1. Start databroker with a `databroker_service_url` like `https://databroker.localhost.pomeriujm.io:8443`
2. Add a certificate ahead of the databroker certificate in `certificates`
3. run `openssl s_client -connect databroker.localhost.pomerium.io:8443 | openssl x509 -text`
4. The first certificate in `certificates` is presented

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `v0.15.5`
- Server Operating System/Architecture/Cloud: OSX

## What's your config.yaml?

Cert setup:
```bash
mkcert testhost
mkcert databroker.localhost.pomerium.io
```

Config:
```config.yaml
grpc_address: :8443
services: databroker
databroker_service_url: https://databroker.localhost.pomerium.io:8443
certificates:
  - cert: testhost.pem
    key: testhost-key.pem
  - cert: databroker.localhost.pomerium.io.pem
    key: databroker.localhost.pomerium.io-key.pem
shared_secret: [redacted]
idp_client_id: [redacted]
idp_client_secret: [redacted]
idp_provider: [redacted]
idp_provider_url: [redacted]
```

## What did you see in the logs?

Nothing logged that would be useful.  https://github.com/pomerium/pomerium/blob/3003e431a8eb9496728d2f6ecec71f1ebef573ba/config/envoyconfig/listeners.go#L639 doesn't get an error if the matching fails.

## Additional context

I suspect `authorize` is impacted by this as well given the amount of with listener setup logic shared.

**Comment by calebdoxsey** [comment]
I believe this was fixed with https://github.com/pomerium/pomerium/pull/2760.

```
	chains, err := b.buildFilterChains(cfg.Options, cfg.Options.Addr,
	chains, err := b.buildFilterChains(cfg.Options, cfg.Options.GRPCAddr,
```
