### ISSUE TITLE
logs filled with "get cert" error

### ISSUE THREAD

**Issue by szymonpk** [pomerium/pomerium#2748]
## What happened?

My logs are filled with the following error:

```
{"level":"error","error":"open /data/autocert/certificates/acme-v02.api.letsencrypt.org-directory/domain/domain.crt: no such file or directory","domain":"domain","time":"2021-11-04T12:04:00Z","message":"get cert"}
```

See 'Additional context' section.

## What did you expect to happen?

No errors in logs.

## How'd it happen?

n/a

## What's your environment like?

- Pomerium version 0.15.5
- EKS 1.18

## What's your config.yaml?

n/a

## What did you see in the logs?

```logs
{"level":"error","error":"open /data/autocert/certificates/acme-v02.api.letsencrypt.org-directory/domain/domain.crt: no such file or directory","domain":"domain","time":"2021-11-04T12:04:00Z","message":"get cert"}
```

## Additional context

This was already fixed by https://github.com/pomerium/pomerium/pull/2584/files, but it was never backported to 0.15.x, this commit is only in master branch. Could you please include it in 0.15.x?

**Comment by travisgroth** [comment]
Hi - backported here https://github.com/pomerium/pomerium/pull/2750.

It will go out soon in the next patch release.

**Comment by szymonpk** [comment]
Thank you!
