### ISSUE TITLE
Unable to use `oidc` when `access_type` is not allowed to be set

### ISSUE THREAD

**Issue by bluecmd** [pomerium/pomerium#2773]
## What happened?

I tried to use OIDC to interface to a OIDC provider that does not allow setting `access_type` to the `/authorize` endpoint.

## What did you expect to happen?

There would be a way to change the default `access_type=offline` to allow not sending this parameter.

## How'd it happen?

1. Configured the `idp_*` settings.
2. OIDC provider sends error "Unsupported request parameter"

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `pomerium: 0.15.4-1634234692+20e21964`
- Server Operating System/Architecture/Cloud: Debian 11

## What's your config.yaml?

```config.yaml
idp_provider: "oidc"
idp_provider_url: "https://...."
idp_client_id: oidc-...
idp_client_secret: ......
idp_service_account: ""
idp_scopes:
  - openid
```

## What did you see in the logs?

N/A.

## Additional context

I believe this is the relevant code:
https://github.com/pomerium/pomerium/blob/ac8ae3ef5b4d26e0a365adb2c889982d24e183c2/internal/identity/oidc/oidc.go#L112-L115

The field `idp_request_params` could be possibly used, e.g. by setting `access_type: ""`, but I am not sure how the `omitempty` works with maps.
https://github.com/pomerium/pomerium/blob/a5034aabaeed210f30e2c1b34d6becebbb342201/config/options.go#L161

I applied the following patch locally and it makes the integration with the OIDC work correctly:
```patch
diff --git a/internal/identity/oidc/oidc.go b/internal/identity/oidc/oidc.go
index 2ea0484f..14a565e0 100644
--- a/internal/identity/oidc/oidc.go
+++ b/internal/identity/oidc/oidc.go
@@ -27,7 +27,7 @@ const Name = "oidc"
 
 var defaultScopes = []string{go_oidc.ScopeOpenID, "profile", "email", "offline_access"}
 
-var defaultAuthCodeOptions = []oauth2.AuthCodeOption{oauth2.AccessTypeOffline}
+var defaultAuthCodeOptions = []oauth2.AuthCodeOption{}
 
 // Provider provides a standard, OpenID Connect implementation
 // of an authorization identity provider.
```

**Comment by desimone** [comment]
I think it makes sense to keep offline as the default as that preserves the current functionality, and is the optimal pomerium operating model (otherwise we can't do session refresh and sessions will expire after ~1 hr).

Maybe the easiest fix here is encourage users to set `access_type` to be `online` (the default when not set for the oauth2 package), and drop the `offline` value if so. 

Actually, that makes me wonder. Does this work if you set [provider request params](https://www.pomerium.io/reference/#identity-provider-request-params) for `access_type` to `online` ?

**Comment by bluecmd** [comment]
> Actually, that makes me wonder. Does this work if you set [provider request params](https://www.pomerium.io/reference/#identity-provider-request-params) for `access_type` to `online` ?

No, if `access_type` is explicitly set, the authorize request is rejected on this particular IdP.

**Comment by desimone** [comment]
Taking another look at the [OpenID Connect spec](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess), and how various identity providers implement "offline" (e.g. refresh-able sessions), we should probably _not_ be setting a default request param for `access_type` for any provider except Google. 


## related

- https://github.com/int128/kubelogin/issues/405

**Comment by desimone** [comment]
https://github.com/pomerium/pomerium/pull/2782 should fix the default behavior. Let me know know if that does the trick, @bluecmd
