### ISSUE TITLE
Disable service config

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#280]
**Describe the bug** A clear and concise description of what the bug is.

See also https://github.com/uswitch/kiam/pull/205

It looks like pomerium send repeated DNS query to `_grpc_config.$HOSTNAME` and `_grpclb._tcp.$HOSTNAME`. This might be useful in a Kubenetes deployment but definitely not useful for personal users.

**To Reproduce** Steps to reproduce the behavior:

1. Run Pomerium
2. Check DNS server query log.

**Expected behavior**

Pomerium should only send DNS queries of identity providers.

Instead it sends a lot of TXT queries to domain names with _grpc prefix.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): latest head version as of now.
- Server Operating System/Architecture/Cloud: Linux/Docker container

Configuration file(s):

```text
# Paste your configs here
# Be sure to scrub any sensitive values
```

Logs(s):

```text
# Paste your configs here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by travisgroth** [comment]
As with kiam, we don't use this either right now.  Looks easy enough to turn off.

**Comment by desimone** [comment]
Is there a downside to turning this off? Why would this be the default functionality?

**Comment by travisgroth** [comment]
From working on the DNS round robin changes, my understanding was that this was an experimental feature that wasn't fleshed out yet.  It may have gotten further but I couldn't find enough information to use it properly.

https://github.com/grpc/grpc/blob/master/doc/service_config.md#architecture

`TODO(roth): Design how the service config will be encoded in DNS.`

These queries are trying to find configuration for Authorize and Authenticate services, which may be on $HOSTNAME.  This is not a consequence of identity provider lookup.  The client side load balancing plugin seems to have it turned on in addition to pure DNS A record based discovery.

I don't think the query is harmful, but I don't think it's doing anything useful in any real world deployments.  When this is a better understood mechanism, we can turn it back on or make it configurable.

**Comment by yegle** [comment]
Hmm, it looks like the change only disables DNS query for `_grpc_config.$HOSTNAME`. The SRV DNS query for `_grpclb._tcp.$HOSTNAME` still exist and I can't easily identify the source of these queries.

Example FQDN: 

`_grpclb._tcp.pomerium.your-dns.run`

**Comment by yegle** [comment]
It looks like this is related to https://www.pomerium.io/docs/reference/reference.html#grpc-client-dns-roundrobin setting. Disabling this setting will stop the SRV DNS query to `_grpclb._tcp.$HOSTNAME`.

The document seems to suggest to not disable the setting. Is it really the case?

**Comment by travisgroth** [comment]
Sort of surprising, though I admit the SRV record behavior in the GRPC library doesn't seem very well documented.  Unsure if that's expected or not.  The desired functionality is to support client side A record based load balancing.

>The document seems to suggest to not disable the setting. Is it really the case?

That would disable using client side / DNS based load balancing to the Authorize and Authenticate services.  Depending on your deployment model, this may or may not be an issue.  In most deployments, having it enabled ranges from harmless to helpful - by supporting RR A Record load balancing.  

If you're concerned with the TXT DNS queries, you could turn it off.  On kubernetes and docker swarm, it wouldn't be recommended in production for scaling reasons.  For low traffic or non-HA deployments, it won't matter much.
