### ISSUE TITLE
Gracefully handle API calls from SPA through Pomerium

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#281]
**Is your feature request related to a problem? Please describe.**

When a Single Page Application (SPA) + its API is protected by pomerium, two types of HTTP requests happen:
- page loading by the browser (the html + spa code)
- API calls by the SPA itself from Javascript

While the first one works nicely with pomerium (i.e., when not auth, the browser redirects with 302 the user to authentication and then back to the page), the second has some undesired caveats currently.

In particular:
- When the session expires, an API call will get as a response a 302 redirect, which results in a redirect to authentication, which is of course not presented to the user (since it's happening in javascript)
- Sometimes, the browser sends an OPTIONS request to the authentication service, that then responds with a 302: this is not an expected answer for OPTIONS.

So while the SPA-related behaviour seems to work as expected, the API-related one does not: when a session ends, the SPA can't detect properly that it needs to make authentication happen again by explicitly redirecting the user to the authentication page.

As a side note, this mean that the SPA is aware it is served from authenticating proxy and that it has to do something specific when it detects the situation:
- one idea is to simply reload the page and let the browser take over (for the record, this means that the browser shouldn't rely on its cache for loading the SPA, this is a known problem in the SPA world)
- another idea is to use more complex authentication schema that gives even more control on the authentication to the SPA. It's not clear if this is out of scope of the present issue or not.

More details on the matter here:
- https://pomerium-io.slack.com/archives/CK6SVMPU0/p1566836804003000
- https://pomerium-io.slack.com/archives/CK6SVMPU0/p1566839236007300
- Recommended authentication scheme for SPAs: https://auth0.com/blog/oauth2-implicit-grant-and-spa/

**Describe the solution you'd like**

Concerning the first point, the original need is for the SPA (when making API calls) being capable of detecting that the session was terminated and that authentication should happen.

I would expect something like getting a 401 instead of a 302 when this happens. This presupposes that pomerium is able to consider differently normal browser page loading from API calls.

One option for this is to consider that if the request has the pomerium cookie, it is browser-based pag eloading, and if it has an authentication header (containing the jwt token normally available to the backend I suppose?), then it is an API call.

This solution implies though that there is the need for the frontend to become aware of the jwt token, either it being provided by the backend (extracted from the cookie) or by pomerium itself (this is where we enter the world of advanced authentication scheme for SPA I think).

The more "standard" the solution, the better. This means defining what is a standard solution, and I'm not sure this proposition contains such a solution :)

**Describe alternatives you've considered**

Just make the assumption in the SPA that any 302 answer means that we got de-authenticated. The problem with this is that this ties the SPA implementation too much to pomerium behaviour and a more standard solution would be preferred.

**Explain any additional use-cases**

Another use case would be to protect an API without the SPA part. This would be a bit different because we couldn't rely at all on the initial explicit authentication by the user via redirect during SPA page loading by the browser.

**Comment by victornoel** [comment]
@desimone the more I think about it, and the more I wonder if the "right" way to handle this is to consider API as a separate type of protected routes.

OAuth2 proposes many authentication flow, and protecting an API can fall in two different flows:
- calling with an application identity
  - we authorize certain applications (or groups of applications) to be able to access the API
  - the call is made by the application itself
  - the application retrieved a `client credetials` type of token to do this
- calling with a user identity
  - we authorize certain users to call this API
  - the call is made from another applications on behalf of the user
  - the application has a token for the user

See for example https://docs.microsoft.com/en-us/azure/active-directory/develop/web-api that explains those two scenarios (I'm currently working with AAD, hence this documentation, btw I just realised AAD has two versions that implements OAuth2 a bit differently… thx microsoft).

The important point in all of this is that the way to validate the token is not via a web redirection where the user has to do something, but the token is in the request, and there has to be some validation to be done with this request, both to validate the identity and the access rights.

I don't know if this is out of scope of pomerium or not, but this clearly extends the scope compared to the current situation.

**Comment by victornoel** [comment]
@desimone also if possible, it would be great to have a short-term fix for this situation: because of the way HTTP and the browser work, from the SPA, it is impossible to detect the 302.

What happens in practice currently is:
- the SPA does the XHR request to the protected API
- pomerium answers with 302
- the browser does an OPTIONS on the url
- pomerium does not care about it and anwer a 302
- the browser complains that CORS is not enabled and stops the request
- from the POV of the SPA, the request just errored and there is no information about the fact there was some redirections or that an OPTIONS failed

3 steps:
- I think that at least pomerium should properly handle CORS for the authenticate service: with this, at least we can detect that the response we get is an HTTP page from the IdP or something like that. This is a hack, but it's better than nothing.
- Next, if pomerium can detect in a way or another (how?!) that i's an XHR request, then even better would be not do redirections as discussed and answer 401.
- Last, introduce something as proposed in my previous comment.

**Comment by victornoel** [comment]
@desimone I saw you now support to pass the session via an Authorization token or a query parameter. I was wondering two things in relation to the present issue:
- how is the caller expected to retrieve the session at first? Via the cookie set by pomerium only?
- do you have some plan to allow the caller to express that it doesn't want to be redirected in case of unauthentication or unauthorization? I was thinking at first that if the caller user a header, then pomerium would assume it's not a browser calling but a SPA or similar, but I'm not sure that's what was introduced…

Thanks

**Comment by desimone** [comment]
> do you have some plan to allow the caller to express that it doesn't want to be redirected in case of unauthentication or unauthorization? I was thinking at first that if the caller user a header, then pomerium would assume it's not a browser calling but a SPA or similar, but I'm not sure that's what was introduced…

Yes. With forward-auth support we now have a special query param that when added to a request will tell pomerium to simply return unauthorized instead of starting the redirect loop. I think this may work well for your usecase? 

https://github.com/pomerium/pomerium/blob/a96aec57d58797e8fa6b5ca196e04e0186b1fa6c/proxy/middleware.go#L105-L110

It still needs to be documented, but that's the gist of it. 

> how is the caller expected to retrieve the session at first? Via the cookie set by pomerium only?

I'm rethinking programatic access. I'd like the process to be as similar to the normal auth flow as possible. I'm thinking we could show the token to the user on the dashboard and allow them to use that to make subsequent requests (but it will be on the client to reupdate the session, like today). Or simply copy the contents of the cookie to either the authorization bearer header / query param and leave it up to the user to locally persist any updates (following and IDP for example).

**Comment by victornoel** [comment]
> Yes. With forward-auth support PR, we added a special query param that when added to a request will tell pomerium to simply return unauthorized instead of starting the redirect loop. I think this may work well for your usecase?

Indeed, it should cover my use case yes. The header option (`x-pomerium-auth-no-redirect`) would be maybe more elegant to avoid conflicting with potential existing query parameters for the proxied service, but right now it's not a real issue. It would enables me to do things I wasn't able to before, namely detect at the client (js) level that we got unauthenticated and that the browser should take over to re-authenticate.

In the longer term, there should be a way of handling this so that the client doesn't have to bother about passing a pomerium-specific option. In terms of separation of concerns, the responsibility of choosing between redirecting or not should be at the level of pomerium's configuration maybe... if there was some way to express something like this, it would maybe be a good solution (the vocabulary is not good, don't fixate on it):
```
policy:
  - from: https://app.corp.beyondperimeter.com
    to: http://service1
    allowed_domains:
      - pomerium.io
    auth-rule:
      default: redirect
      except:
        # example uses regex, but there may already exist a better way of specifying path matching that I'm unaware of
        - ^/api/
  - from: https://api.corp.beyondperimeter.com
    to: http://service2
    allowed_domains:
      - pomerium.io
    auth-rule:
      default: refuse
```

> For now, yes but I'm rethinking programatic access. I'd like the process to be as similar to the normal auth flow as possible. I'm thinking we could show the token to the user on the dashboard and allow them to use that to make subsequent requests (but it will be on the client to reupdate the session, like today). Or simply copy the contents of the cookie to either the authorization bearer header / query param and leave it up to the user to locally persist any updates (following and IDP for example).

To be honest, I'm not totally clear about which use case would be covered by this discussion on the matter of retrieving a session token and using it passed as a header, maybe this is even out of the scope of this issue. I think there is or will be some need for retrieving session token programmatically, first by bringing a user through the process of authentication, and then using it programmatically to do API calls but it's a bit out of my knowledge and experience for now, so maybe don't take my rambling on this matter too seriously :)
 
What currently concerns me is the first point of discussion about redirecting vs returning 401, and I think this is the gist of this present issue. In conclusion:
- the current implemented solution where the client explicitly ask for no redirect is good enough for now, but imposes too much knowledge on the client code about knowing that pomerium is protecting the proxied app.
- a solution at the level of pomerium's configuration, similar to what I imagined above with the policy and `auth-rule`, would fully solve the current issue IMHO.

**Comment by desimone** [comment]
> Indeed, it should cover my use case yes. The header option (x-pomerium-auth-no-redirect) would be maybe more elegant to avoid conflicting with potential existing query parameters for the proxied service, but right now it's not a real issue. It would enables me to do things I wasn't able to before, namely detect at the client (js) level that we got unauthenticated and that the browser should take over to re-authenticate.

Glad to hear this partially solved your use-case. I'm looking forward to hearing how `v0.4.0` is working thus far.

> In the longer term, there should be a way of handling this so that the client doesn't have to bother about passing a pomerium-specific option. In terms of separation of concerns, the responsibility of choosing between redirecting or not should be at the level of pomerium's configuration maybe... if there was some way to express something like this, it would maybe be a good solution (the vocabulary is not good, don't fixate on it):

In short, I agree.  I like the approach you've laid out, as it keeps the downstream application completely agnostic to what the proxy is doing. I'm less thrilled about doing any type of url parsing or matching. I want to think a little bit more about it, but I think what you've outlined is a very reasonable approach. 


> What currently concerns me is the first point of discussion about redirecting vs returning 401, and I think this is the gist of this present issue. In conclusion:
> 
> * the current implemented solution where the client explicitly ask for no redirect is good enough for now, but imposes too much knowledge on the client code about knowing that pomerium is protecting the proxied app.
> * a solution at the level of pomerium's configuration, similar to what I imagined above with the policy and `auth-rule`, would fully solve the current issue IMHO.

I am in complete agreement.
