### ISSUE TITLE
Claims are not being passed through the Proxy

### ISSUE THREAD

**Issue by bryonbrill** [pomerium/pomerium#2823]
## What happened?
There are no claims passed into the jwt token when user authenticates into to a basic Webpage located in the back end.
## What did you expect to happen?
Claims to appear inside the jwt token from Pomerium.
## How'd it happen?
I configured Pomerium inside of docker and setup my Identity Provider using setup instructions that were on Pomeriums website.

## What's your environment like?

- Pomerium version: 0.15.2
- Server Operating System/Architecture/Cloud: 2 Ubuntu 20.04 systems inside of Azure with 1 that has Pomerium setup and another a Nginx web server hosting a single HTML page.
1. Pomerium running inside a docker container
2. Setup IdP against Azure with all required information
3. Authentication is working fine and passes user into the proxied page sitting on the backend.
4. The backend is running nginx web server, and has a plain HTML page with some text on it.
5. The **/.Pomerium** page shows that Pomerium has and can see the claims
![image](https://user-images.githubusercontent.com/14927066/146214869-faf27746-ba9e-4e44-8b4c-f74e3ef93364.png)
6. Microsoft Graph is setup with permissions properly

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://authenticate.mywebsite/oauth2/callback

idp_provider: azure
idp_provider_url: "https://login.microsoftonline.com/<IDHERE/v2.0"
idp_client_id: REPLACED
idp_client_secret: REPLACED
directory_id: "https://login.microsoftonline.com/<ID Here>/v2.0/.well-known/openid-configuration"

cookie_secret: REPLACED
shared_secret: REPLACED

certificates:
  - cert: "/etc/ssl/certs/server.crt"
    key: "/etc/ssl/certs/server.key"

pomerium_debug: true

jwt_claims_headers:
- email
- groups
- user

programmatic: true

# https://pomerium.com/reference/#routes
policy:
  - from: https://mywebsite
    to: http://InternalServerIP:8080
    allowed_domains: mydomain.net
    pass_identity_headers: true
    pass_identity_headers: X-Pomerium-Claim-*
    pass_identity_headers: X-Pomerium-Jwt-Assertion
  - from: https://mywebsite
    to: http://InternalServerIP:8081
    allowed_domains: mydomain.net
    pass_identity_headers: true

```

## What did you see in the logs?
Nothing that tells me anything specific.

## Additional context
The returned JWT in headers only returns basic information, not any additional Claims information
![image](https://user-images.githubusercontent.com/14927066/146218096-94fcf571-79e3-435b-9420-84dd56b11e39.png)

**Comment by calebdoxsey** [comment]
@bryonbrill I believe you also have to add the corresponding claims to the Azure AD configuration. Have you done that?

Under App Registration -> Token Configuration -> Add Optional Claim

![Screenshot-20211229151245-796x394](https://user-images.githubusercontent.com/395272/147707264-c69066b3-fc15-4efa-ad93-ce98c89caf7a.png)

**Comment by bryonbrill** [comment]
Yes I do have the Optional Claims defined.
![image](https://user-images.githubusercontent.com/14927066/147756068-af428014-ff7a-42f4-b0c0-bd9c13b23c76.png)
They are also showing up when I visit  https://myurlhere/.pomerium/
![image](https://user-images.githubusercontent.com/14927066/147756205-9f15ac0a-3aa2-433b-9079-9a78cf590f19.png)
But nothing in the cookie when I successfully authenticate into the basic HTML page I have.
![image](https://user-images.githubusercontent.com/14927066/147756326-4e8373f8-2ce2-4d20-b890-1d63ba2d38e8.png)
Above image for jwt.io I grabbed this from the Cookie Response headers.

**Comment by calebdoxsey** [comment]
@bryonbrill The JWT is passed in the `X-Pomerium-Jwt-Assertion` header. We also use a JWT for the cookie, but its only used for the session id. We sometimes use the httpbin.org (http://httpbin.org/headers) site to see if the request header is at we expect it. You can test this with a route like:

```yaml
from: https://httpbin.localhost.pomerium.io
to: https://httpbin.org
allow_any_authenticated_user: true
```

**Comment by bryonbrill** [comment]
So I did enable the to: in my config for pomerium to point to https://httpbin.org and was able to then find the Request Inspection and fetched the headers. They are returning properly. Even when I visit https://mysite.com/headers the output is correct.
When I switch back to my local server config I still am not seeing the headers. Is this something that requires logic on the backend (nginx)webserver to be able to see/consume? There has to be something missing. I know a blank html page is not claims aware. What is missing here?

**Comment by desimone** [comment]
@bryonbrill 

> When I switch back to my local server config I still am not seeing the headers. Is this something that requires logic on the backend (nginx)webserver to be able to see/consume? There has to be something missing. I know a blank html page is not claims aware. What is missing here?

Could you elaborate? The local web server would need to be able to inspect (or echo back) the incoming **request** headers.

**Comment by bryonbrill** [comment]
Could you elaborate? The local web server would need to be able to inspect (or echo back) the incoming request headers.

So we have tried using JavaScript to echo the headers, that did not work. I believe it is a bit more involved than just echoing the headers.

We are going to attempt using the example with nginx to see if we can get the headers come across properly. 

However, internally, if the web server is springboot, nginx, or even IIS for that matter it should still receive them with the forward in the configs for headers.

Finally, I think/believe the documentation or the way that Pomerium is holding the headers is a bit skewed or off. Since it is failing to pass the headers through as it should be seen in the JWT as my OP with the current configuration.

**Comment by bryonbrill** [comment]
Update. So, apologies from my end. I went through your example with nginx mentioned here: https://github.com/pomerium/pomerium/tree/master/examples/nginx
Then was able to find another docker container, with some assistance of a colleague, that does receive the headers properly. 
With the additional docker container which has its own little web server on the backend for echoing http-https headers is called: **mendhak/http-https-echo:23** https://github.com/mendhak/docker-http-https-echo 

It may be nice to include this in a future instruction set just as an alternative. 
My config.yaml file now was as simple as: 
![image](https://user-images.githubusercontent.com/14927066/152989648-35fa3da6-e870-4664-8199-19c530e0f7b3.png)

and not of course the final version, but the docker-compose.yaml file:
![image](https://user-images.githubusercontent.com/14927066/152989997-ba72c60e-1cc6-4d90-b09c-ac504e2637d6.png)

Then the echo container webserver returns what was expected.:
![image](https://user-images.githubusercontent.com/14927066/152990147-d4bcf206-3689-442e-8035-7ca59468f17a.png)
Thanks for your patience, everyone! I believe this can be closed now.

**Comment by desimone** [comment]
Great -- glad you got things working @bryonbrill !
