### ISSUE TITLE
Envoy segfault on startup in LXC Container

### ISSUE THREAD

**Issue by Bubby4j** [pomerium/pomerium#2838]
## What happened?
During startup Envoy has a segfault, causing Pomerium to not function.

## What did you expect to happen?
Pomerium & Envoy to start normally.

## How'd it happen?

1. Created an LXC container (TurnKey Linux, Debian based) on my Proxmox host.
2. Installed & configured the latest version of Pomerium via apt per the instructions into this container.
3. Started the service and received this error.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): pomerium: 0.15.8-1639756984+edf05960 envoy: 1.19.1+c5ecc1e167273edac76f6c07f980ed5a728f4b7e077679d74cfbc59c087933e5
- Server Operating System/Architecture/Cloud: Debian GNU/Linux 10 (buster) (Turnkey linux) LXC container running on Proxmox VE

## What's your config.yaml?

```config.yaml
address: :443

authenticate_service_url: https://pom-sso.campus.MYORG.EXAMPLE

insecure_server: true

shared_secret: "[redacted]"
cookie_secret: "[redacted]"
idp_provider: "azure"
idp_provider_url: "https://login.microsoftonline.com/[redacted]/v2.0"
idp_client_id: "[redacted]"
idp_client_secret: "[redacted]"

policy:
  - from: https://cam.MYORG.EXAMPLE
    to: http://cam.campus.MYORG.EXAMPLE:81
    allowed_users:
      - fake_test@MYORG.EXAMPLE
```

## What did you see in the logs?

```logs
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"Caught Segmentation fault, suspect faulting address 0x0"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"Backtrace (use tools/stack_decode.py to get line numbers):"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"Envoy version: a2a1e3eed4214a38608ec223859fcfa8fb679b14/1.19.1/Clean/RELEASE/BoringSSL"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#0: __restore_rt [0x7fe071205730]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#1: [0x557d2280e4d4]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#2: [0x557d2281e6a6]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#3: [0x557d228269db]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#4: [0x557d22821c6e]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#5: [0x557d22820ce5]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#6: [0x557d2281c6a5]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#7: [0x557d228125af]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#8: [0x557d22810442]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#9: [0x557d228102be]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#10: [0x557d2286bde8]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#11: [0x557d229a0a38]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#12: [0x557d228b183a]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#13: [0x557d22311e9d]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#14: [0x557d22311a03]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#15: [0x557d22312418]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#16: [0x557d21af081a]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#17: [0x557d21af0585]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#18: [0x557d21ae8b57]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#19: [0x557d21ae7378]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#20: [0x557d20381694]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#21: [0x557d20380a80]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#22: [0x557d2038218e]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#23: [0x557d20382303]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#24: [0x557d2037e91c]"}
Dec 20 23:07:49 pom-sso pomerium[128]: {"level":"error","service":"envoy","name":"backtrace","time":"2021-12-20T23:07:49-06:00","message":"#25: __libc_start_main [0x7fe07105609b]"}
Dec 20 23:07:50 pom-sso pomerium[128]: {"level":"fatal","pid":394,"time":"2021-12-20T23:07:50-06:00","message":"envoy: subprocess exited"}
```
Full log: [pomerium-envoy-crash.log](https://github.com/pomerium/pomerium/files/7749774/pomerium-envoy-crash.log)

## Additional context
envoy-config.yaml: `{"node":{"id":"pomerium", "cluster":"pomerium"}, "staticResources":{"clusters":[{"name":"pomerium-control-plane-grpc", "type":"STATIC", "connectTimeout":"5s", "loadAssignment":{"clusterName":"pomerium-control-plane-grpc", "endpoints":[{"lbEndpoints":[{"endpoint":{"address":{"socketAddress":{"address":"127.0.0.1", "portValue":36165}}}}]}]}, "http2ProtocolOptions":{}}]}, "dynamicResources":{"ldsConfig":{"ads":{}, "resourceApiVersion":"V3"}, "cdsConfig":{"ads":{}, "resourceApiVersion":"V3"}, "adsConfig":{"apiType":"DELTA_GRPC", "transportApiVersion":"V3", "grpcServices":[{"envoyGrpc":{"clusterName":"pomerium-control-plane-grpc"}}]}}, "statsConfig":{"statsTags":[{"tagName":"service", "fixedValue":"pomerium"}]}, "layeredRuntime":{"layers":[{"name":"static_layer_0", "staticLayer":{"overload":{"global_downstream_max_connections":50000}}}]}, "admin":{"accessLogPath":"/dev/null", "profilePath":"/dev/null", "address":{"socketAddress":{"address":"127.0.0.1", "portValue":9901}}}}`

I tried running the `tools/stack_decode.py` tool to get a better idea what Envoy might be having trouble with, but I don't have much experience with natively compiled languages and wasn't able to produce a useful result - I'm sure I'm doing something wrong so if there's anything else I can do to provide useful information please let me know.

**Comment by calebdoxsey** [comment]
I've not attempted to run Pomerium within LXC so there may be some incompatibility there we've not seen before. LXC can restrict OS-level functionality in various ways that Envoy may not like and perhaps that's whats leading to the segmentation fault. We will need to do further investigation.

Looking at the config you have `insecure_server` with `address: :443`. Was that intentional? This would indicate you're attempting to serve HTTP over the HTTPS port which may cause other problems.

Also since you're binding :443 are you running as root?

**Comment by Bubby4j** [comment]
> I've not attempted to run Pomerium within LXC so there may be some incompatibility there we've not seen before. LXC can restrict OS-level functionality in various ways that Envoy may not like and perhaps that's whats leading to the segmentation fault. We will need to do further investigation.
> 
> Looking at the config you have `insecure_server` with `address: :443`. Was that intentional? This would indicate you're attempting to serve HTTP over the HTTPS port which may cause other problems.
> 
> Also since you're binding :443 are you running as root?

I also tried changing to :80 but behavior is the same.

I did follow the instructions "To run on :443 set AmbientCapabilities=CAP_NET_BIND_SERVICE" per https://www.pomerium.com/docs/install/binary.html so in theory it shouldn't need to run as root, but I also tried running it directly as root and saw similar behavior.

I can try playing around with relaxing some of the LXC container restrictions to see if that makes a difference.

**Comment by Bubby4j** [comment]
I changed the container from unprivileged to privileged but Envoy still crashed, and this time there's no stack trace from Envoy, so likely not as simple as I had hoped. I know LXC has other settings which can further decrease isolation and security, though of course it would be a bad idea to run in production like that, so at this point I'm thinking that I'll just run it in a VM instead of a container though it's less efficient.

The provided Docker support would be convenient, though my use case is very simple (small business) so I didn't want to set up infrastructure for Docker.

**Comment by JeffMatson** [comment]
I've been converting some of my VMs into unprivileged containers and am running into the exact same issue from what I can tell.

Following this thread. If I manage to come up with a solution, I'll follow up. Although so far, no luck.

**Comment by travisgroth** [comment]
> I changed the container from unprivileged to privileged but Envoy still crashed, and this time there's no stack trace from Envoy, so likely not as simple as I had hoped. I know LXC has other settings which can further decrease isolation and security, though of course it would be a bad idea to run in production like that, so at this point I'm thinking that I'll just run it in a VM instead of a container though it's less efficient.

Can you share the complete logs from this crash?  If there's no stack trace I suspect something else is going on.

> I did follow the instructions "To run on :443 set AmbientCapabilities=CAP_NET_BIND_SERVICE" per https://www.pomerium.com/docs/install/binary.html so in theory it shouldn't need to run as root, but I also tried running it directly as root and saw similar behavior.

How did you apply the NET_BIND_SERVICE capability?  I'm not sure if doing so via systemd unit file in the VE will work.  I'm not very familiar with LXC but I suspect it's not that simple.

**Comment by travisgroth** [comment]
Closing pending additional info.
