### ISSUE TITLE
Identity Provider AD onPremise

### ISSUE THREAD

**Issue by fabioce** [pomerium/pomerium#2843]
Hi,
I'm seeing the "zero trust" solution with Pomerium, but in this documentation:
https://www.pomerium.com/docs/identity-providers/
I don't understand if I can autenticate with an AD onPremise.
Can you help me to understand?
Thanks

**Comment by desimone** [comment]
Hey @fabioce -- we support on premise versions of active directory that use OpenID Connect which has shipped since Windows Server 2016 as I understand. Hope that helps.
