### ISSUE TITLE
How do ignore invalid Certificatesof proxy service?

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2850]
**This is a question, no bug or feature requests**

if backend service Certificates is expired or Self-signed  certificate, How to provide normal service？

in my case, backend service using  Self-signed  certificate， but pomerium Not working properly。

**Comment by alexfornuto** [comment]
You can use `tks_skip_verify`: https://www.pomerium.com/reference/#tls-skip-verification
If you have further questions on using this route config option, please open a thread in our [support forums](https://discuss.pomerium.com/c/support/9).
