### ISSUE TITLE
0.16.0: crashloop when cert request was rate limited by Let's Encrypt

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#2852]
## What happened?
One of my certificates is due to refresh but due to my misconfig on other parts of the system, the `/.well-known/` URL was returning 404, this failed the cert renew process and apparently caused crashloop of Pomerium. Eventually the crashloop triggered the rate limiting on Let's Encrypt.

## What did you expect to happen?
1. A temporary failure to get certificate should not crashloop Pomerium
2. A crashlooping Pomerium should not cause excessive requests to renew certificate (exponential back off of retrying the renewal of certificate should be followed even after Pomerium restarts).

## How'd it happen?

1. Update to 0.16.0
2. Wait for one cert to expire, but misconfig your system so the renew request never finishes
3. Now Pomerium should start crashlooping and eventually you can see rate limit errors from let's Encrypt.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.16.0
- Server Operating System/Architecture/Cloud: docker on Debian

## What's your config.yaml?

I guess the only important bit is I have environment `AUTOCERT_MUST_STAPLE` set to 1.

## What did you see in the logs?

```logs
ERR delta config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) https-ingress: OCSP response is required for must-staple certificate name=config service=envoy
```

Rate limit error from let's Encrypt:

```log
WRN renew client certificated failed, use existing cert error="[dns.apkay.com] Renew: [foo.example.com] creating new order: attempt 1: https://acme-v02.api.letsencrypt.org/acme/new-order: HTTP 429 urn:ietf:params:acme:error:rateLimited - Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/ (ca=https://acme-v02.api.letsencrypt.org/directory)" service=autocert-manager
```

## Additional context

Reverting to 0.15.8 will stop the crashlooping. The crash behavior seems to be related to #2777

**Comment by yegle** [comment]
One easy way to misconfigure and trigger this is to set up a route for foo.bar.com (a domain you don't own and does not resolve to the ip of your Pomerium instance).

**Comment by calebdoxsey** [comment]
@yegle this does appear related to #2777. We are fatally exiting because Envoy is rejecting our Listener configuration. This made sense for port binding issues, but doesn't make sense for this case, since eventually `autocert` will generate a correct configuration.

We need to do some investigation and discussion about whether we should revert the change, modify it to make it more restrictive, or come up with some other mechanism to better detect fatal errors. We may also want to modify how autocert generates configuration so it never send the bad configuration in the first place.
