### ISSUE TITLE
Pomerium based Grafana JWT auth not working

### ISSUE THREAD

**Issue by ramzcode** [pomerium/pomerium#2887]
using the latest version of Pomerium Helm and grafana(prometheus community stack).

authentication redirection not working and it says

{
"message": "invalid API key"
}

**Comment by travisgroth** [comment]
Hi @ramzcode,

Unlike many projects on GitHub, Pomerium does not use its bug tracker for general discussion or asking questions. We only use our bug tracker for tracking bugs, feature requests, and proposals. We use Discuss at <https://discuss.pomerium.com/> to answer and archive support questions for users that may not be as comfortable with GitHub as developers.

If you believe you've found a bug please fill out the full bug template and provide as much detail as possible for reproduction.

For asking questions, see:

- [Discuss Forums](https://discuss.pomerium.com/). Specifically, search the [support category](https://discuss.pomerium.com/c/support/9) to see if your question has already been addressed. If not, open a new topic and follow the support template provided.
- [Community - Get Help](https://www.pomerium.com/docs/community/#get-help).
