### ISSUE TITLE
integration: tests are failing due to verify not starting

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#2894]
## What happened?

The integration tests are failing because the verify image can't start.

## What did you expect to happen?

The integration tests to pass.

## How'd it happen?

Create a PR.

## What's your environment like?

Github CI

## What's your config.yaml?

N/A

## What did you see in the logs?

```logs
verify_1                           | {"level":"info","project-id":"*detect-project-id*","time":"2022-01-04T00:19:46Z","message":"connecting to firestore"}
verify_1                           | {"level":"fatal","error":"failed to create firestore client: fetching creds: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","time":"2022-01-04T00:19:46Z"}
verify-ready_1                     | 2022/01/04 00:19:44 Waiting for: http://verify:80/
```

## Additional context

See https://github.com/pomerium/verify/issues/5

**Comment by alexrudd2** [comment]
Can confirm this happens on a live install.  It's still a testing environment and not production, so if you'd like anything more, let us know.  @EdgardGomez
