### ISSUE TITLE
identity: investigate whether `idp_provider_url` needs to be unique for sync and auth flow

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2904]
More investigation needs to be done confirm my understanding as to whether those provider URLs would ever need to be set to something else. It looks like Google's API does support different directory sync endpoints.

https://github.com/pomerium/pomerium/blob/6916352aaaefd3aa046728c712a1bfe2837333bb/internal/directory/google/google.go#L244-L246

_Originally posted by @desimone in https://github.com/pomerium/pomerium/issues/2866#issuecomment-1003254526_

**Comment by travisgroth** [comment]
It looks like this is only impacting google.  Docs update should properly update this.  Waiting to see if other providers have issues but it doesn't appear that will be the case from a review of the code.
