### ISSUE TITLE
how to get tcp access logs?

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#2926]
## What happened?
cann't find any tcp access logs

## What did you expect to happen?
get tcp protocol access logs

## How'd it happen?
only http access logs

**Comment by travisgroth** [comment]
Hi,

As mentioned in https://docs.pomerium.io/docs/community/#get-help and the issue templates, please see our [discussion forums](https://discuss.pomerium.com/) for help using Pomerium.
