### ISSUE TITLE
Synology nginx throws 502s / "peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream"

### ISSUE THREAD

**Issue by cmmichael** [pomerium/pomerium#295]
**Describe the bug** A clear and concise description of what the bug is.

I'm running Synology (DSM 6.2.2-24922 Update 3), and Pomerium in a docker container per the Pomerium guide. My setup was working just fine, but roughly at the time of receiving / installing the latest update, I started getting intermittent 502 errors.

In nginx error logs:

```
2019/09/01 22:39:02 [error] 20059#20059: *8436 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking to upstream, client: 192.168.1.1, server: _, request: "POST /api/v2/auth/login HTTP/2.0", upstream: "https://127.0.0.1:32443/api/v2/auth/login", host: "$HOSTNAME", referrer: "$HOSTNAME" 
```

This log example is from the auth URL, but this also happens with application URLs.

There is no trace of the request in the Pomerium log; I only see one other request within a minute for the /favicon.

This problem appears to go away when I forward 443 directly to the exposed Pomerium port.

**To Reproduce** Steps to reproduce the behavior:

I'm not sure how reproducible the bug is. It appears to happen intermittently, but frequently, in my case when visiting any URL routed through nginx / Pomerium.

**Expected behavior**

I should be getting 200s :)

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.2.1+47f7a44
- Server Operating System/Architecture/Cloud: Synology (DSM 6.2.2-24922 Update 3), 
nginx version: nginx/1.15.7
Docker version 18.09.6, build 8cdf373
 
Configuration file(s):

```text
authenticate_service_url: https://auth.$DOMAIN
authorize_service_url: https://localhost
authenticate_internal_url: https://localhost
override_certificate_name: "$DOMAIN"

shared_secret: $SHARED_SECRET
cookie_secret: $COOKIE_SECRET

idp_provider: google
idp_client_id: $CLIENT_ID
idp_client_secret: $SECRET

metrics_address: :9090

#tracing_jaeger_collector_endpoint: http://jaeger:14268
#tracing_jaeger_agent_endpoint: jaeger:6831
#tracing_enabled: true
#tracing_provider: Jaeger
#tracing_debug: true

# Defaults: TIMEOUT_READ_HEADER=10s TIMEOUT_READ=30s TIMEOUT_WRITE=0 TIMEOUT_IDLE=5m
# added in desperation
timeout_read: 60s
timeout_read_header: 20s


policy:
- from: https://httpbin.$DOMAIN
  to: http://httpbin
  allowed_users:
    - $USERNAME
```

Logs(s):

See above.

**Additional context**

**Comment by desimone** [comment]
@cmmichael 
This sounds like the nginx reverse proxy isn't working as expected. Do you mind posting a domain-name redacted screenshot of what your reverse proxy tab looks like in the synology control panel?

By any chance were the certificates updated on either nginx / pomerium recently?

**Comment by cmmichael** [comment]
I agree that the problem seems to lie with nginx rather than Pomerium. I'm not sure if this was somehow a change with the DSM update, or some unique state I got myself into because I tinkered with Synology's nginx a while back. (Or equally likely, I'm just doing something stupid).

I did change my certificates recently to add a few more wildcard domains; they mostly mirror the LetsEncrypt instructions on the guide, except I had ec-384. After the error started happening, I switched to ec-256. 

Here's the reverse proxy tab:
 
![image](https://user-images.githubusercontent.com/5606405/64130566-24088180-cd91-11e9-83a0-d4cf07fd4c4d.png)

I didn't quite manage to get pomerium to send traces to jaeger. I'm happy to give that another go later this week if that would be useful. (Or better yet, add jaeger tracing to Synology's nginx)

My workarounds for others that stumble into this: 
(1) Forward router 443 directly to the Pomerium port (my current workaround, which works like a charm)
(2) Install an nginx container to sit in front of Pomerium, if that's somehow a more secure configuration (e.g. if nginx is hardened against some attacks).

**Comment by desimone** [comment]
Related to points 1 and 2, If your current workaround is working for you, your setup is totally okay in my book, and is how I personally run pomerium on my synology device. The guide uses nginx in the spirit of using the pre-existing synology tools where possible (e.g. why we also use synology's docker interface and not docker-compose). But nginx is not a requirement at all.  

I don't think putting pomerium behind another load balancer is more secure. Go's http stack is capable and suitable for production workloads.  

> The days of needing NGINX in front of all Go services are gone... --- [Cloudflare - So you want to expose go on the internet](https://blog.cloudflare.com/exposing-go-on-the-internet/) 
 
> I agree that the problem seems to lie with nginx rather than Pomerium.

My hunch is that this is a certificate issue but it's difficult to debug with all the possible range of configurations possible between the client, nginx, and pomerium.

Very interested to hear if are able to narrow that down. Is the connection 502'ing only on the authenticate* urls?
