### ISSUE TITLE
JWT Debugger Icon Not Visible in FF

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/pomerium#2955]
## What happened?

When viewing the `.pomerium` endpoint in FF, the JWT debugger icon is not visible, though the link is still there.

## What did you expect to happen?
I expected it to look the same as it does in Chrome:
![image](https://user-images.githubusercontent.com/2349184/150552866-bb27a48a-3197-4e45-9dc6-40fd5f66a43f.png)

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
  pomerium: 0.16.0-1640214477+45a348de
  envoy: 1.19.1+c5ecc1e167273edac76f6c07f980ed5a728f4b7e077679d74cfbc59c087933e5

- Server Operating System/Architecture/Cloud: k3s with our Helm chart

**Comment by travisgroth** [comment]
From discussion - we've been talking about rewriting this page already so we should address this bug as part of the rewrite.

**Comment by travisgroth** [comment]
This was removed as part of the rewrite.  We can add a new issue if we want to re-add the feature.

**Comment by alexfornuto** [comment]
@travisgroth Was the removal of this feature discussed somewhere?

**Comment by travisgroth** [comment]
@alexfornuto no, I don't think it was an explicit decision so much as lost along the way.  Discussed if we should re-add with @desimone and we decided against it for now.
