### ISSUE TITLE
docs: add section discussing threat model

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#296]
**Is your feature request related to a problem? Please describe.**

Pomerium does not have a page describing how the project views security trade-offs and what threats we consider within our security model. 

**Describe the solution you'd like**

We should have such a document. 

**Describe alternatives you've considered**

NA

**Explain any additional use-cases**

NA

**Additional context**

- [Kubernetes Threat model](https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Threat%20Model.pdf)
- https://github.com/pomerium/pomerium/issues/197#issuecomment-528120315
- https://github.com/pomerium/awesome-security-audits
- [vault's security model](https://www.vaultproject.io/docs/internals/security.html)

**Comment by desimone** [comment]
Current state is draft. See google docs.

https://docs.google.com/document/d/1rcieiLEEYN_k0I47CsGklY5t-K1NqHCKDF5gsW8UXJg/edit#

Need to dive deeper into :

- who the threat actors are, and how they are likely to attack pomerium
- what those mitigations are

**Comment by travisgroth** [comment]
@desimone to hit publish
