### ISSUE TITLE
device identity: safari respond with operation "cannot be completed" on m1 mac

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#2982]
## What happened?

I cannot register or authenticate on my m1 mac using safari Version 15.2 (17612.3.6.1.6); I previoulsy was able to complete this workflow. 

## What did you expect to happen?

To enroll or authenticate

## How'd it happen?

1. Go to device policy protected route (see config).
2. Get redirected to `https://authenticate.int.nas.bdd.io/.pomerium/webauthn`
3. Cannot complete registration 

### User details

<img width="1177" alt="Screen Shot 2022-01-28 at 4 22 36 PM" src="https://user-images.githubusercontent.com/1544881/151638680-3a0f8556-ac9a-44dd-bf62-12eaa0df295d.png">
<img width="1177" alt="Screen Shot 2022-01-28 at 4 22 33 PM" src="https://user-images.githubusercontent.com/1544881/151638688-67cf9b65-ef69-45d4-83cc-a0c3ab2bde54.png">

### On registration attempt

<img width="1177" alt="Screen Shot 2022-01-28 at 4 22 45 PM" src="https://user-images.githubusercontent.com/1544881/151638709-fb7b9de6-a314-42bd-be7c-08b023955c39.png">

<img width="709" alt="Screen Shot 2022-01-28 at 4 22 52 PM" src="https://user-images.githubusercontent.com/1544881/151638703-caee5f21-97fa-4d0b-bf84-f17e8a618acd.png">

<img width="615" alt="Screen Shot 2022-01-28 at 4 22 56 PM" src="https://user-images.githubusercontent.com/1544881/151638699-8eb24ca4-6165-46aa-a9be-76dcfb2f7282.png">

### On authentication attempt 

<img width="603" alt="Screen Shot 2022-01-28 at 4 24 18 PM" src="https://user-images.githubusercontent.com/1544881/151638734-01c77ceb-8b21-4b89-8093-2304baa2d411.png">

## What's your environment like?

Core
0.16.1-1642799763+ d20a14fb
Enterprise
v0.15.0+ 4af4bf8

## What's your config.yaml?

```ppl
allow:
  or:
    - email:
        is: bobbydesimone@gmail.com
deny:
  not:
    - device:
        approved: 1
```

## What did you see in the logs?

<img width="655" alt="Screen Shot 2022-01-28 at 4 25 11 PM" src="https://user-images.githubusercontent.com/1544881/151638784-46c1e9fb-431e-42f2-b980-0b021ed4ee28.png">

Says I cancelled something (but I havent!) in the console

```logs
Unhandled Promise Rejection: NotAllowedError: This request has been cancelled by the user.
```

**Comment by calebdoxsey** [comment]
I am able to reproduce this. It appears safari does not support webauthn for platform keys. https://discussions.apple.com/thread/251080288

**Comment by calebdoxsey** [comment]
I suspect the `any` type in your database is corrupted. There was a bug months ago that resulted in the `any` type requiring platform keys. AFAIK this bug is now fixed, but if the type is wrong in the database there's nothing that would catch that. I guess we could create a new migration to ensure the types are correct.

**Comment by calebdoxsey** [comment]
We should improve the error message for safari.

**Comment by travisgroth** [comment]
@desimone to check on his local database contents to confirm.

**Comment by desimone** [comment]
i have not been able to reproduce since I cleaned existing devices from my environment.
