### ISSUE TITLE
URL Hmac validate failed in insecure mode

### ISSUE THREAD

**Issue by vanhtuan0409** [pomerium/pomerium#3021]
## What happened?

Running pomerium in insecure mode (reversed proxy also no TLS). Trying to sign in or sign out via `.pomerium/sign_{in|out}` got error `internal/urlutil: hmac failed`

Is TLS strictly required for pomerium to work correctly?

## What did you expect to happen?

Able to successfully sign in/sign out

## How'd it happen?

1. Go to authenticate url
2. Click on Logout button
3. Saw error `internal/urlutil: hmac failed`

## What's your environment like?

- Pomerium version: `v0.16.2`
- Server Operating System/Architecture/Cloud: Linux running in K3s

## What's your config.yaml?

```config.yaml
authenticate_service_url: http://auth.baphouse.internal
forward_auth_url: http://fwdauth.baphouse.internal

services: all
address: ":80"
metrics_address: ":9090"
dns_lookup_family: V4_ONLY
insecure_server: true
grpc_insecure: true

shared_secret: #redacted
cookie_secret: #redacted
cookie_secure: false

jwt_claims_headers:
  - email
  - groups
  - user

routes:
  - from: http://httpbin.baphouse.internal
    to: http://httpbin.default
    allow_any_authenticated_user: true
    pass_identity_headers: true
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - from: http://k3s.baphouse.internal
    to: http://homelab-kubernetes-dashboard.kubernetes-dashboard
    pass_identity_headers: true
    allow_any_authenticated_user: true
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

```

## Additional context

Pomerium is currently hardcoded the scheme to be `https`

https://github.com/pomerium/pomerium/blob/master/internal/urlutil/url.go#L88

**Comment by travisgroth** [comment]
Hi,

TLS is required between user browsers and whatever proxy defines the edge of your network.  Using Pomerium with only `http` across the internet is not secure.
