### ISSUE TITLE
When a user is added to a large number of groups, the X-Pomerium-Jwt-Assertion header gets very large

### ISSUE THREAD

**Issue by megalan247** [pomerium/pomerium#3069]
**Is your feature request related to a problem? Please describe.**

When the user is added to a large number of groups, the X-Pomerium-Jwt-Assertion header gets very large as it contains the groups of the user even if the jwt_claims_headers option only contains "email". This then causes problems due to large header sizes (applications often cannot handle very large HTTP headers)

**Describe the solution you'd like**

Only add groups into the x-pomerium-jwt-assertion header if it is requested in the jwt_claims_headers option

**Comment by travisgroth** [comment]
Related:

https://github.com/pomerium/pomerium/issues/1750
https://github.com/pomerium/pomerium/issues/2730
