### ISSUE TITLE
proxy: add host to request logger middleware 

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#308]
**Is your feature request related to a problem? Please describe.**

When parsing the logs of pomerium proxy, it is not possible to match a given log to a route of the policy.
For example, here is a log:
```json
{
  "level":"debug",
  "fwd_ip":"10.242.5.10",
  "ip":"10.242.5.20",
  "user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
  "referer":"https://app.corp.xxx.com/page",
  "req_id":"331f76cd-987f-d6cb-2a9e-cfb34fdeab0b",
  "duration":157.584014,
  "size":195,
  "status":200,
  "email":"user@xxx.com",
  "group":"all@xxx.com,tech@xxx.com",
  "method":"GET",
  "service":"proxy",
  "url":"/api/path/1",
  "time":"2019-09-16T13:45:06Z",
  "message":"http-request"
}
```

The policy contains this:
```yaml
- from: https://app.corp.xxx.com
  to: http://app.ns.svc.cluster.local:80
  allowed_groups:
    - tech@xxx.com
```

**Describe the solution you'd like**

The log should contain an information to know which was the route used (the from of the route, `https://app.corp.xxx.com`) or the url that received the request (`https://app.corp.xxx.com/api/path/1`).

**Describe alternatives you've considered**

Parsing the `referer` gives some information, but in general this is not reliable as the request could be coming from another domain or no referer could be specified in the request.

**Comment by desimone** [comment]
Thanks @victornoel good catch. From what I understand, [host may not always be available](https://groups.google.com/d/msg/golang-nuts/4VqItLnch8U/IcTXnRWilrkJ) but we can try to include it in the main log handler.

What do you think of something like the following? 
```diff
{
  "level": "debug",
  "ip": "192.168.1.1",
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36",
  "referer": "https://httpbin.corp.beyondperimeter.com/",
  "req_id": "76717e36-bfe2-5e9c-8bb0-22ab8695471c",
  "duration": 173.270585,
  "size": 3760,
  "status": 200,
  "email": "bdd@pomerium.io",
  "group": "admins@pomerium.io,everyone@pomerium.io,support@pomerium.io",
  "method": "GET",
  "service": "all",
+ "host": "httpbin.corp.beyondperimeter.com",
+  "path": "/spec.json",
  "time": "2019-09-16T20:19:59-07:00",
  "message": "http-request"
}
```

**Comment by victornoel** [comment]
@desimone that seems good yes, but I don't understand what you mean by `host may not always be available`: pomerium proxy HAS to know what is the requested host to be able to route the request, no? If host is unavailable, we have a bigger problem than logging :)

**Comment by victornoel** [comment]
@desimone also, to be completely clear: I don't think we should log the request's host, but I think we should log the host used by pomerium proxy to know which route to use in the policy.

**Comment by desimone** [comment]
> @desimone that seems good yes, but I don't understand what you mean by host may not always be available: pomerium proxy HAS to know what is the requested host to be able to route the request, no? If host is unavailable, we have a bigger problem than logging :)

Ha, very true. I was thinking too much about go and not enough about the context. As you point out, pomerium will have access to `request.Host` for any routed domain 😅 

> @desimone also, to be completely clear: I don't think we should log the request's host, but I think we should log the host used by pomerium proxy to know which route to use in the policy.

Do you mean the Source (`httpbin.corp.example.com`) or the Destination(`httpbin.local`)? The PR would record the source but not the destination.

**Comment by victornoel** [comment]
> Do you mean the Source (httpbin.corp.example.com) or the Destination(httpbin.local)? The PR would record the source but not the destination.

@desimone ah sorry for the confusion, yes I meant the source. But what also meant is that, if for some reason, whichever it is (a bug, a more advanced feature that does not exists yet, etc), pomerium decide to use a route that is NOT based on the `request.Host` of the underlying http server, I want the logs to reflect this decision, so to contain the source of the route to which the request was forwarded.

One rational for this would be for audit purpose in case of  a bug: I would like to know where the request actually went, not where it was supposed to go :)

That being said, for now, maybe considering that `request.Host` always reflects the chosen route is good enough.
