### ISSUE TITLE
In production deployments, how to deploy each component separately?

### ISSUE THREAD

**Issue by cfanbo** [pomerium/pomerium#3095]
**Is your feature request related to a problem? Please describe.**

Pomerium is composed of 4 logical components，how to deploy each component and what is the configuration content used by each component? i didn't find any relation document。
https://www.pomerium.com/docs/architecture.html  
https://github.com/pomerium/pomerium/tree/main/examples

**Describe the solution you'd like**
deploy each component

**Comment by alexfornuto** [comment]
Hi @cfanbo - You've identified a gap where our documentation could be better.

The short version is: set the [service mode](https://www.pomerium.com/reference/#service-mode) key to determine which instance will serve as which component. Otherwise they will each act in "all-in-one" mode.

I think this deserves a short article or guide describing this in more detail. What do you think?

**Comment by cfanbo** [comment]
Here are four different configuration files, each file content is different, dependencies between them，has some dependencies  wrong when service startup, each service is a controlPlane, I don't know what to do。

Where should the route configuration items be in the file？

```
proxy.yaml
services: proxy
address: 443
...

authenticate.yaml
services: authenticate 
address: 5443
...

authorize.yaml
services: authorize 
address: 5443
...


databroker.yaml
services: databroker 
address: 5443
```

**Comment by calebdoxsey** [comment]
Hi @cfanbo 

You can also run pomerium in all-in-one mode if you plan on using it on a single machine. I don't know if we have any examples of setting up independent services, though the Helm chart will do this by default. We also have an integration test that you could look at: https://github.com/pomerium/pomerium/blob/main/integration/clusters/oidc-multi/compose.yml.

Most of the properties in the configuration file are shared between services. I believe routes will need to be defined for all of them except the databroker.

**Comment by alexfornuto** [comment]
@cfanbo The [Reference Page](https://docs.rtfm.life/reference/) is sorted on the left to answer the question of what keys go where. When using split service mode with multiple configs:
- [Shared settings](https://docs.rtfm.life/reference/#shared-settings) belong in each config file.
- [Authenticate Service](https://docs.rtfm.life/reference/#authenticate-service) keys go in the config file with `services: authenticate`.
- etc.

Does this clarify things?
