### ISSUE TITLE
Additional parameter in Auth0

### ISSUE THREAD

**Issue by HighWatersDev** [pomerium/pomerium#3124]
Currently, I set up Auth0 IdP with Pomerium but my authentication with Auth0 wouldn't work. It took me several hours to figure out but once I switched JWT signature algorithm to RS256, it worked right away. I think it'd be helpful to add that to the documentation for clarity

![image](https://user-images.githubusercontent.com/37680855/157377183-8a9d5858-bc61-407c-80b6-03b15bc01acd.png)

**Comment by alexfornuto** [comment]
Hi @HighWatersDev! Thanks for making this issue. I created a new test application in Auth0, and when I opened up Advanced Settings it was already set to use RS256.

![auth0](https://user-images.githubusercontent.com/2349184/157727894-0a1da8da-624b-4317-b71c-d2ca00aefd30.png)
 
I'm happy to note that this needs to be set in our docs, but I also want to better understand how your config came to the point where this needed to be set. Did you previously change this value, or any other values not specified in our current doc? When you went back to adjust it, what was the previous value for this option?

**Comment by alexfornuto** [comment]
@HighWatersDev the issue was closed with the merging of the related PR, but I'd still be interested in hearing back from you on the questions above. This situation confuses me.

**Comment by HighWatersDev** [comment]
I have to admit I might have changed that while troubleshooting. Sorry for the confusion this issue might have caused. After the initial issue was resolved via a separate PR, I encountered a separate issue and noticed that the JWT signature algorithm was the culprit. I thought creating this issue would save someone else in the future some troubleshooting time.
