### ISSUE TITLE
Add name claim to JWT payload

### ISSUE THREAD

**Issue by alexfornuto** [pomerium/pomerium#3216]
**Is your feature request related to a problem? Please describe.**

Some systems (Like Grafana) require a name claim in order to auto-create new users based on the JWT payload. While we're not intending to be an Identity Provider for upstream services, there's no harm and only benefit from it.

**Describe the solution you'd like**

Include the 'name' claim in the JWT payload when provided by the IdP.

**Describe alternatives you've considered**

In the example situation of Grafana, the workaround is to use `X-Pomerium-Claim-` headers to provide additional data, but then you also have to entirely switch away from using JWT auth. [This blog post](https://linuxblog.xyz/posts/grafana-auth-proxy/) details what that would look like.

**Explain any additional use-cases**

I doubt this will be the last upstream service that would benefit from a slightly more expanded JWT payload.

**Comment by sarasensible** [comment]
For the record the name claim is not required it will still create a user without the Name field populated.  The workaround is to set extraEnv.JWT_CLAIMS_HEADERS equal to email,name as discussed in https://discuss.pomerium.com/t/grafana-auto-sign-up-with-pomerium-identity/97/3

**Comment by travisgroth** [comment]
@alexfornuto it looks like setting `name` in https://docs.pomerium.io/reference/#jwt-claim-headers should also add the claim in to the assertion JWT.  Could you test that in your setup?

**Comment by alexfornuto** [comment]
I have tested and confirmed this. It was not documented as doing so, which will be resolved by #3226. Up to you if it should be included by default or not.

**Comment by alexfornuto** [comment]
From discussion, worth adding by default to reduce complexity for user config.
