### ISSUE TITLE
crashloop if autocert cannot grab a cert for a route

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3221]
## How'd it happen?
I have pomerium in a test environment, where an upstream nginx forwards most traffic based on a different domain.  I haven't figured out how to have **autocert** work through nginx, so every now and then (outside working hours) I re-route gateway traffic from nginx directly to pomerium.  It grabs the certs, stores them, and then I give nginx the traffic back.

This worked fine until I discovered a typo in a route and corrected it, and updated the docker swarm service.

## What did you expect to happen?
Pomerium to boot and serve traffic for other domains, with an error only for the typo domain / autocert failure.

## What happened?
pomerium completely fails to start and I have to restore old config.  

## What's your environment like?

- Pomerium version: `0.17.1-1648674931+9fd09459` (all-in-one)
- Server Operating System/Architecture/Cloud: docker swarm

## What's your config.yaml?

```
autocert: true

--  - from: https://typo-name.my-domain.com
++ - from: https://name.my-domain.com
    to: http://name.my-domain.com
    pass_identity_headers: true
    allowed_groups:
    - group@my-domain.com
```

## What did you see in the logs?

```
{"level":"info","time":"2022-03-31T13:22:25-05:00","logger":"acme_client","msg":"trying to solve challenge","service":"autocert","identifier":"name.my-domain.com","challenge_type":"http-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
<...>
{"level":"error","time":"2022-03-31T13:22:27-05:00","logger":"acme_client","msg":"challenge failed","service":"autocert","identifier":"name.my-domain.com","challenge_type":"http-01","problem":{"type":"urn:ietf:params:acme:error:unauthorized","title":"","detail":"Invalid response from https://name.my-domain.com/.well-known/acme-challenge/KS_3dqR_BVqyOC2PoXPOwmGXkcVB9EoYfmU4BbGJgLk [99.126.152.56]: 502","instance":"","subproblems":[]}}
```
Sorry I don't have the docker service logs during the crashloop, it fails so fast I can't grab them easily.

## Additional context

pomerium hot-reload has never worked for me, probably since docker doesn't pass up underlying filesystem events.  But I'm actually glad it doesn't, because pomerium crashes _hard_ on something as small as an invalid route (typo, or http/https) and I haven't found any way to test for valid config.  I'm going to file a separate issue for that.

**Comment by calebdoxsey** [comment]
Hi @alexrudd2 , 

I agree that the current behavior is subpar, but unfortunately because of certificate stapling we have to be careful about never serving an invalid (self-signed, or wrongly named certificate) because it can end up being stapled by the browser which is very annoying to fix. (you have to go to a chrome-internals page to clear the HSTS cache)

At first glance it seems like we could at least serve all the other routes that are valid, but unfortunately that also results in the same issue. We'll end up serving a 404 page with a self-signed certificate.

It may be possible to kill the connection or return some other error that avoids the stapling. We need to do more research about alternative solutions.

**Comment by alexrudd2** [comment]
Thanks for the consideration, and apologies for not being well-informed on HSTS.

Agreed that the optimal response is a `503` or `500` with some sort of certificate/config that doesn't cause OCSP stapling problems.  However, if that's tricky what about _no response at all_?  After all, the current behavior is _not_ "pomerium serves all valid routes except one with a bad certificate."
 It's "pomerium crashes, serving nothing whatsoever."  Unless there's something else I'm missing?

**Comment by desimone** [comment]
We may want to rethink setting HSTS by default. 🤔

**Comment by alexrudd2** [comment]
Has there been any update here?

We (finally) put pomerium into limited production use, and got bitten hard during the deploy.  After fighting it for a few hours, I ended up having to disable autocert and use a wildcard cert.

**Comment by desimone** [comment]
Thanks for circling back with your experience. Having been bit by this myself, I think it's worth the breaking change to remove the HSTS / certificate pinning by default behavior. It's way too much of a foot-gun / point of frustration for initial users.

**Comment by alexrudd2** [comment]
FWIW, it wasn't (yet?) the stapling that caused problems.  It was the fact the pomerium straight up crashes on boot in many scenarios.

We had an internal meeting today writing up our deploy experience and hope to reach out with more concrete information soon.  Not sure if GitHub issues are best, or we should got through the Enterprise support.  

Overall we're glad to be making the switch from our old systems.

**Comment by calebdoxsey** [comment]
I no longer see this behavior with main. Pomerium starts even if we're unable to retrieve a certificate for one of the routes.
