### ISSUE TITLE
Forward Auth is not working anymore (0.17.1)

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/pomerium#3245]
## What happened?
Forward Auth is not working anymore! .. If you use https://forwardauth.mydomain.com/verify?uri=https://demo2.mydomain.com running Pomerium 0.17.1 then you would get a 404 as shown below:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/8362784/162159411-fb720c35-4e79-4ea1-a40e-7d617d2e517d.png">

The same 404 would happen if you call the auth sign in URL https://forwardauth.mydomain.com/?uri=https://demo2.mydomain.com

Needless to say that all my Ingresses using Nginx and Forwardauth via Pomerium are broken now! For us this is an extremely urgent issue!

Please note that in versions below 0.17 everything was working just fine with Forward Auth!

## What did you expect to happen?
Forward auth to be working as expected

## How'd it happen?
Check above!

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.17.1`
- Server Operating System/Architecture/Cloud: AWS / EKS / Helm

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :80
grpc_address: :80
authenticate_service_url: https://pomerium.mydomain.com
authorize_service_url: http://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: http://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: oidc
idp_scopes: [openid profile email groups offline_access]
idp_provider_url: https://myidp.domain.com
insecure_server: true
grpc_insecure: true
forward_auth_url: https://forwardauth.mydomain.com
idp_client_id: REDACTED
idp_client_secret: REDACTED
idp_service_account: pomerium-authenticate
databroker_storage_tls_skip_verify: true    
routes:
  - allow_spdy: true
    allow_websockets: true
    allowed_idp_claims:
      groups:
      - Group A
      - Group B
    from: https://dashboard.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    to: http://kubernetes-dashboard.kube-system.svc:443
  - allow_spdy: true
    allow_websockets: true
    allowed_idp_claims:
      groups:
      - Group A
      - Group B
    cors_allow_preflight: true
    from: https://kubernetes.mydomain.com
    kubernetes_service_account_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_skip_verify: true
    to: https://kubernetes.default.svc
  - from: https://pomerium.mydomain.com
    to: http://pomerium-authenticate.pomerium.svc.cluster.local
    allow_public_unauthenticated_access: true
```

## What did you see in the logs?
Nothing relevant

## Additional context
My secure ingress:
```ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 0-secure-ingress
  labels:
    app: demo
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://forwardauth.mydomain.com/verify?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-signin: "https://forwardauth.mydomain.com/?uri=https://$host$request_uri"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # ingress.pomerium.io/allow_any_authenticated_user: "true"
    ingress.pomerium.io/path_regex: "true"
    ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Group X", "Group Y"]}'
spec:
  ingressClassName: nginx
  rules:
  - host: demo2.mydomain.com
    http:
      paths:
      - path: /.*/admin
        pathType: ImplementationSpecific
        backend:
          service:
            name: demo-project
            port:
              number: 8080
```

**Comment by travisgroth** [comment]
I'm not able to reproduce this with an existing route on v0.17.1.  Without a helm values overrides and other details, it's hard to try the exact configuration.  That said, simple config testing forward auth endpoint directly:

```config.yaml
###
# IDP and cookie_secret/shared_secret removed
###

address: :80
certificate_authority_file: rootCA.pem
insecure_server: true
grpc_insecure: true
forward_auth_url: https://forwardauth.localhost.pomerium.io

authenticate_service_url: https://authenticate.localhost.pomerium.io
certificates:
  - cert: cert.pem
    key: key.pem

routes:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin.org
    pass_identity_headers: true
    policy:
      - allow:
          and:
            - domain:
                is: pomerium.com
```

- `curl 'http://forwardauth.localhost.pomerium.io/?uri=https://foo'` will return 302 regardless of whether `foo` is defined as a route so I'm not sure how you'd get a 404 there:

  ```bash
  curl 'http://forwardauth.localhost.pomerium.io/?uri=https://foo' -I
  HTTP/1.1 302 Found
  content-type: text/html; charset=utf-8
  location: https://authenticate.localhost.pomerium.io/.pomerium/sign_in?pomerium_callback_uri=https%3A%2F%2Ffoo&pomerium_expiry=1649415706&pomerium_forward_auth=forwardauth.localhost.pomerium.io&pomerium_issued=1649415406&pomerium_redirect_uri=https%3A%2F%2Ffoo&pomerium_signature=JyPyOJU_5Yy3j42cLPZZvX9iOjVdbBZ9dbMEqIIS7JY%3D
  vary: Accept-Encoding
  x-pomerium-intercepted-response: true
  date: Fri, 08 Apr 2022 10:56:46 GMT
  x-envoy-upstream-service-time: 0
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-frame-options: SAMEORIGIN
  x-xss-protection: 1; mode=block
  server: envoy
  transfer-encoding: chunked 
  ```
- `curl 'http://forwardauth.localhost.pomerium.io/verify?uri=https://foo'` will return a 404 if the route isn't defined.

  ```bash
  curl 'http://forwardauth.localhost.pomerium.io/verify?uri=https://foo' -I
  HTTP/1.1 404 Not Found
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-frame-options: SAMEORIGIN
  x-xss-protection: 1; mode=block
  x-pomerium-intercepted-response: true
  date: Fri, 08 Apr 2022 10:54:47 GMT
  server: envoy
  transfer-encoding: chunked
  ```
- `curl 'http://forwardauth.localhost.pomerium.io/verify?uri=https://httpbin.localhost.pomerium.io'` will return 401 if the route is defined

  ```bash
  curl 'http://forwardauth.localhost.pomerium.io/verify?uri=https://httpbin.localhost.pomerium.io' -I
  HTTP/1.1 401 Unauthorized
  strict-transport-security: max-age=31536000; includeSubDomains; preload
  x-frame-options: SAMEORIGIN
  x-xss-protection: 1; mode=block
  x-pomerium-intercepted-response: true
  date: Fri, 08 Apr 2022 10:58:11 GMT
  server: envoy
  transfer-encoding: chunked
  ```

I suspect your logs do contain more information.  Have you checked the ingress controller and/or nginx?

Given your lack of TLS secret on the Ingress spec, could [this](https://github.com/pomerium/ingress-controller/issues/177) be the problem?

**Comment by sherifkayad** [comment]
@travisgroth I guess https://github.com/pomerium/ingress-controller/issues/177 could be the isssue .. I can't say for sure if the Pomerium Ingress Controller is rejecting the route and hence causing this route not to be found in the Pomerium list of routes, however, that looks legit yeah.

I tried with statically defined routes in my config and I think that's working fine. We could probably close this one and wait for a solution for https://github.com/pomerium/ingress-controller/issues/177

**Comment by travisgroth** [comment]
> I can't say for sure if the Pomerium Ingress Controller is rejecting the route

This should be logged by the ingress controller.

In any event, closing since it appears to be related to the ingress side of things.
