### ISSUE TITLE
Mismatch between .pomerium session info and JWT served

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3270]
## What happened?
Pomerium is telling me that I'm logged in at the `.pomerium` endpoint , but serving a JWT (and enforcing access permissions) based on another user.

## What did you expect to happen?
JWT should match `.pomerium` and should be updated if I logout/switch users.

## How'd it happen?

1. Other user (J) logged in to a resource behind pomerium
2. I went to our landing page and noticed J was logged in.  I logged them out with `.pomerium/log_out`
3. I then selected my account from the Google SSO
4. I observed that `/.pomerium` shows my user info correctly,
![Screen Shot 2022-04-13 at 11 19 23 AM](https://user-images.githubusercontent.com/52292902/163225570-e9d5f57c-50d5-4cea-8a10-0a0143334106.png)
5. I got a 403 when trying to access routes to which I have access.
6. The decoded JWT served at `/.pomerium/jwt` still matches the previous user.
![Screen Shot 2022-04-13 at 11 21 12 AM](https://user-images.githubusercontent.com/52292902/163225879-8b9d4311-4142-4590-8322-467e55d76943.png)

## What's your environment like?
Pomerium version `0.17.1-1648674931+9fd09459` behind an `nginx` proxy
docker swarm 2.10 on ubuntu 20.04 LTS

## What's your config.yaml?
<details><summary>config.yaml</summary>

```
# pomerium_debug: true # optional, default is false
#service: "all"
# log_level: info # optional, default is debug

authenticate_service_url: https://authenticate.<mydomain>
autocert: true

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
shared_secret: <>
cookie_secret: <>
signing_key: <>

jwt_claims_headers:
- name
- email
- picture
- groups
- given_name
- family_name

# Use redis databroker backend
databroker_storage_type: redis
databroker_storage_connection_string: redis://base_pomerium-redis:6379

# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_client_id: <>
idp_client_secret: <>
idp_service_account: <>
# Proxied routes and per-route policies are defined in a routes block
routes:
  <correctly configured routes>
```
</details>

## What did you see in the logs?

Can't get the logs since they're behind pomerium which is blocking my access o_0

**Comment by alexrudd2** [comment]
OK, I was able to get some logs from docker itself, although they tend to be out of order.

```
{"level":"info","server_version":17766254614281865131,"record_version":27418,"time":"2022-03-31T13:23:20-05:00","message":"sync"}
{"level":"info","X-Forwarded-For":["10.0.0.2"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"synthetic-monitoring-agent/v0.8.1-0-gd1eda4d (linux amd64; d1eda4dab9e72527b45ddf9fb208997a1a8049a4; 2022-03-29 16:00:37+00:00; +https://github.com/grafana/synthetic-monitoring-agent)","referer":"https://<ip>","request-id":"69a4e085-c375-4f3f-8dab-b3f9648c9d68","error":"Bad Request: internal/sessions: session is not found","idp_id":"9A7aNMdiYfQCuss3KbYhChcSrnYb4fhF2NrBnTKUnQdH","time":"2022-03-31T13:23:26-05:00","message":"authenticate: session load error"}
{"level":"info","service":"envoy","upstream-cluster":"pomerium-control-plane-http","method":"GET","authority":"authenticate.<mydomain>","path":"/.pomerium/sign_in","user-agent":"synthetic-monitoring-agent/v0.8.1-0-gd1eda4d (linux amd64; d1eda4dab9e72527b45ddf9fb208997a1a8049a4; 2022-03-29 16:00:37+00:00; +https://github.com/grafana/synthetic-monitoring-agent)","referer":"https://99.126.152.56","forwarded-for":"10.0.0.2","request-id":"69a4e085-c375-4f3f-8dab-b3f9648c9d68","duration":58.243367,"size":938,"response-code":302,"response-code-details":"via_upstream","time":"2022-03-31T13:23:26-05:00","message":"http-request"}
{"level":"info","service":"authorize","request-id":"aa4df8f0-222d-4dc8-bb4e-97e12ad5a465","check-request-id":"82030b4d-f08e-47ac-9f33-84e5ceae3bc4","method":"GET","path":"/api/users/2","host":"<route for which A has access>","query":"","session-id":"658a3180-6f91-46dc-ba1a-89e1812f4e9e","allow":true,"allow-why-true":["groups-ok"],"deny":false,"deny-why-false":["valid-client-certificate-or-none-required"],"user":"114572631035622906923","email":"a@<mydomain>","databroker_server_version":17766254614281865131,"databroker_record_version":27426,"time":"2022-03-31T13:23:29-05:00","message":"authorize check"}
```

**Comment by desimone** [comment]
Hey @alexrudd2 -- Are you deploying two totally different instances of Pomerium (with different configurations) or are you deploying multiple instances with a shared configuration in a high availability setup with a shared redis instance?

**Comment by alexrudd2** [comment]
> Hey @alexrudd2 -- Are you deploying two totally different instances of Pomerium (with different configurations) or are you deploying multiple instances with a shared configuration in a high availability setup with a shared redis instance? 

Shared config with shared redis.  The intent is to use ability to use docker's auto-rollback strategy for updates.

**Comment by calebdoxsey** [comment]
This can happen when the authenticate endpoint is managing a different session from the route. You get logged out of one without getting logged out of the other. (due to multiple oidc support)

**Comment by calebdoxsey** [comment]
> I went to our landing page and noticed J was logged in. I logged them out with .pomerium/log_out

The url is `/.pomerium/sign_out`. Using the proper URL results in the correct behavior.
