### ISSUE TITLE
[Auth0] failed to refresh directory users and groups

### ISSUE THREAD

**Issue by imlonghao** [pomerium/pomerium#3331]
## What happened?

Refresh directory users and groups failed.

I can't see my groups info in `https://{authenticate_service_url}/.pomerium/`

## What did you expect to happen?

Refresh directory users and groups success.

I can see my groups info in the dashboard.

## How'd it happen?

1. Create Applications on Auth0 as the [docs](https://www.pomerium.com/docs/identity-providers/auth0.html) said
2. Create a test user and test role, and assign the test user to that role
3. `docker-compose up -d` then see the following error in logs

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):

pomerium/pomerium:v0.17.3

- Server Operating System/Architecture/Cloud:

VPS and Docker

## What's your config.yaml?

```config.yaml
# See detailed configuration settings : https://www.pomerium.com/docs/reference/


# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://sso.REDACTED

####################################################################################
# Certificate settings:  https://www.pomerium.com/docs/reference/certificates.html #
# The example below assumes a certificate and key file will be mounted to a volume #
# available to the  Docker image.                                                  #
####################################################################################
certificate_file: /ssl/sso.REDACTED.crt
certificate_key_file: /ssl/sso.REDACTED.key

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: "auth0"
idp_provider_url: "https://REDACTED.us.auth0.com"
idp_client_id: "REDACTED"
idp_client_secret: "REDACTED"
idp_service_acount: "REDACTED"

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: REDACTED
```

## What did you see in the logs?

```log
{"level":"info","service":"identity_manager","time":"2022-05-09T14:22:26Z","message":"refreshing directory users"}
{"level":"warn","service":"identity_manager","error":"auth0: could not list roles: request failed: Get \"https://REDACTED.us.auth0.com/api/v2/roles?include_totals=true&page=0&per_page=50\": oauth2: cannot fetch token: 403 Forbidden\nResponse: {\"error\":\"access_denied\",\"error_description\":\"Client is not authorized to access \\\"https://REDACTED.us.auth0.com/api/v2/\\\". You need to create a \\\"client-grant\\\" associated to this API. See: https://auth0.com/docs/api/v2#!/Client_Grants/post_client_grants\"}","time":"2022-05-09T14:22:27Z","message":"failed to refresh directory users and groups"}
{"level":"info","type":"type.googleapis.com/pomerium.events.LastError","id":"identity_manager_last_user_group_refresh_errors","time":"2022-05-09T14:22:27Z","message":"put"}
```

## Additional context

I am sure the `idp_client_id` and `idp_client_secret` are from the `Regular Web Application`

`idp_service_acount` is generated in cmd as the docs said, using the `machine-to-machine` application aksk

I can see from the Auth0 `Monitoring -> Logs`, pomerium is refreshing directory with the `Regular Web Application` AKSK.

After I grant `read:roles` and `read:role_members` to the `Regular Web Application` AKSK, the error gone.

So the `Service Account` and the `idp_service_acount` seem useless to me.

**Comment by calebdoxsey** [comment]
The error seems clear to me:

> oauth2: cannot fetch token: 403 Forbidden\nResponse: {\"error\":\"access_denied\",\"error_description\":\"Client is not authorized to access \\\"https://REDACTED.us.auth0.com/api/v2/\\\". You need to create a \\\"client-grant\\\" associated to this API. See: https://auth0.com/docs/api/v2#!/Client_Grants/post_client_grants\"}"

Did you try the steps outlined in the referenced page?
