### ISSUE TITLE
Stateful sessions towards backend

### ISSUE THREAD

**Issue by ventris** [pomerium/pomerium#3379]
**Is your feature request related to a problem? Please describe.**

If you load-balance requests towards an policy in Pomerium that goes towards two or more backends you will experience some issues if the services are not fully in sync.

This can be replicated by using multiple Alertmanagers behind a single policy in Pomerium.
Try adding a silence and you will more often than not get a 404 back when you create it. This is because after its created the service sends you to the newly created silence page but on another of the backend hosts. And because Alertmanager uses a gossip protocol it can take a second for the data to be shared with the other hosts resulting in the 404.

This is also extremely visible with web-socket connections as you will get the auth request towards one server and the actually WS connection towards another, resulting in a failed request because you have not sent the auth to that server.

**Describe the solution you'd like**

We need a way to sticky sessions towards one backend server depending on hash or source IP.
Preferably with a toggle in each policy so we can turn it on and off depending on if its needed or not.

**Additional context**

Stateful sessions has been implemented in envoy and documentation regarding it can be found here:
https://www.envoyproxy.io/docs/envoy/v1.22.0/configuration/http/http_filters/stateful_session_filter.html?highlight=session

**Comment by wasaga** [comment]
please see [`lb_policy`](https://docs.pomerium.io/reference/#load-balancing-policy) parameter. For session affinity to work, you need to use one of the hashing load balancers - either `MAGLEV` or `RING_HASH`.

**Comment by ventris** [comment]
Do you have any examples of a working configuration for this? 

I'm trying to find something in the envoy documentation regarding this but I can only find how it does the hashing for MAGLEV and/or RING_HASH. There is nothing about session stickyness from what I can find, but it can be that Im not reading the documentation correctly.

I have tried both MAGLEV and RING_HASH but in their default state they are not session sticky.

**Comment by calebdoxsey** [comment]
Both of these load balancing policies pick a backend server based on a hash of the session ID, so they are session sticky. We call this the routing key, and it is based on the session ID:

```go
		HashPolicy: []*envoy_config_route_v3.RouteAction_HashPolicy{
			// hash by the routing key, which is added by authorize.
			{
				PolicySpecifier: &envoy_config_route_v3.RouteAction_HashPolicy_Header_{
					Header: &envoy_config_route_v3.RouteAction_HashPolicy_Header{
						HeaderName: httputil.HeaderPomeriumRoutingKey,
					},
				},
				Terminal: true,
			},
			// if the routing key is missing, hash by the ip.
			{
				PolicySpecifier: &envoy_config_route_v3.RouteAction_HashPolicy_ConnectionProperties_{
					ConnectionProperties: &envoy_config_route_v3.RouteAction_HashPolicy_ConnectionProperties{
						SourceIp: true,
					},
				},
				Terminal: true,
			},
		},
```

As far as I know this functionality still works. We have an integration test configured here:

https://github.com/pomerium/pomerium/blob/0b0fba06b3374557ed7427d165190570ce4997f1/integration/tpl/backends/routes.libsonnet#L176

and tested here:

https://github.com/pomerium/pomerium/blob/820be99a2ffe79c0be4c51dd73988d363ab2633c/integration/policy_test.go#L354

**Comment by ventris** [comment]
Verified this on latest Pomerium and its working as intended with stickiness.

We were running an older version that did not behave in the same way and threw us to a different server each time.
