### ISSUE TITLE
set a header with a dynamic value

### ISSUE THREAD

**Issue by enenum** [pomerium/pomerium#3424]
**Is your feature request related to a problem? Please describe.**

Can Pomerium set a header with a dynamic value?
 

I would like to set a header value based on a token claim - e.g. group so that the application can apply rules based on the header value. I can use set_request_header but it only sets a static value, not something that might change based on token claim.

There are the regex_rewrite, etc that seem to be available for headers, but the match a value and replace, meaning the header needs to be there, and furthermore, the substation side also does not seem to be able to receive a dynamic value like the token claim.

**Describe the solution you'd like**

This can be very useful for a richer RBAC application where say we don't want just allow/deny, but allow and let the application decide what portion apply to what type of user based on the header value.
```
set_request_header:
  X-FOO: $group_claim # the group claim variable syntax can be anything that works for pomerium
```  
 
**Describe alternatives you've considered**
new entrants into the market like Ory oathkeeper offer an extensible capability to handle auth and extensions like ory's keto to support such features. But adoption of such new platform would also knock the trusted pomerium record and history off the stack.

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

Applications like splunk handle some level of RBAC in the server. Without this working the alternative is to integrate them directly to the identity provider - which works but is an addition path of flow that make the setup a little more complex and  weakens the case to the identity aware proxy.

**Comment by wasaga** [comment]
https://www.pomerium.com/docs/enterprise/reference/configure#jwt-claim-headers

**Comment by desimone** [comment]
Hey @enenum  --  let us know if that was what you are looking for, but we could certainly better document / crosslink how we talk about setting request headers to mention that we also support passing custom claims as well.

**Comment by alexfornuto** [comment]
@enenum I've updated the reference pages for `set_request_header` and `jwt_claim_headers` to crosslink to each other for dynamic/static header values, respectively. Feel free to let us know if need any additional help.
