### ISSUE TITLE
proxy: using kubernetes with TLS termination

### ISSUE THREAD

**Issue by matejkramny** [pomerium/pomerium#343]
We have an environment where cloudflare proxies all requests, sends them over https to the origin server and nginx dispatches the request based on the hostname.
SSL is terminated over at nginx.

It seems that pomerium **requires** the SSL to be terminated there, with no way to turn it off.

Is there any way around this?

We've tried deploying this using the wiki/docs, but it doesn't seem to work, giving us suspicious logs like:

```
5:48PM ERR http: TLS handshake error from 127.0.0.1:42010: remote error: tls: bad certificate addr=:443
5:48PM ERR http: TLS handshake error from 127.0.0.1:42016: remote error: tls: bad certificate addr=:443
```

Many thanks

**Comment by desimone** [comment]
Hi @matejkramny,

We added support for 3rd party TLS termination (#64) last night (#328 ) 😉 .  You can use it today using the `pomerium/pomerium:master` image or wait until the `0.4.0` release which should drop in the next few days. We haven't written up a guide for using TLS termination yet, but you'd just need to turn on `insecure_server` [mode](https://master.docs.pomerium.io/docs/reference/reference.html#insecure-server).

Let me know how it goes :)

**Comment by matejkramny** [comment]
Hey @desimone, thanks for this info!

I'll look into that option. Cheers
