### ISSUE TITLE
400 Bad Request: CSRF token invalid

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3465]
## What happened?

Users which had previously authenticated and accessed routes started receiving 400 Bad Requests

## What did you expect to happen?
Functional authorization

## How'd it happen?
1. Last week, users accessed routes as normal.
2. This week, they attempted to access the same routes but received the error message below.
![Screen Shot 2022-07-05 at 9 01 51 AM](https://user-images.githubusercontent.com/52292902/177346931-4314b53b-0915-46c3-a873-0f97adde97b1.png)
3.  Some combination of refreshing multiple pages/routes appears to fix the problem.

Note: Our WiFi RADIUS server was having problems, and we've switched some people over to a different WiFi network.  Perhaps sessions were started on one network, switched to another, and started having this issue?

## What's your environment like?

Pomerium version: `0.17.3-1651784655+f4bad550` (all-in-one)
Server Operating System/Architecture/Cloud: docker swarm.  Pomerium is behind nginx.

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://authenticate.<ourdomain>.com
# authorize service url will default to localhost in all-in-one mode, otherwise
# it should be set to a "behind-the-ingress" routable url
#authorize_service_url: https://pomerium-authorize-service.default.svc.cluster.local
#databroker_service_url: https://pomerium-databroker-service.default.svc.cluster.local

# Certificates can be loaded as files or base64 encoded bytes.
certificate_file: <cert>
certificate_key_file: <cert>
#certificate_authority_file: <cert>
autocert: true
# alternatively, insecure mode can be used if behind a TLS terminating ingress,
# or when using a sidecar proxy
#insecure_server: true

# base64 encoded cert, eg. `base64 -i cert.pem` / `base64 -i privkey.pem`
# certificate: |
#  "xxxxxx"
# certificate_key: |
#  "xxxx"

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
shared_secret: <secret>
cookie_secret: <secret>
# If set, a JWT based signature is appended to each request header `x-pomerium-jwt-assertion`
# signing_key: "Replace with base64'd private key from ./scripts/self-signed-sign-key.sh"
signing_key: <secret>

jwt_claims_headers:
- name
- email
- picture
- groups
- given_name
- family_name

# Use redis databroker backend
databroker_storage_type: redis
databroker_storage_connection_string: redis://base_pomerium-redis:6379

# Identity Provider Settings
## GOOGLE
idp_provider: "google"
idp_client_id: <secret>
idp_client_secret: <secret>

# IF GSUITE and you want to get user groups you will need to set a service account
# see identity provider docs for gooogle for more info :
idp_service_account: <secret>
# Proxied routes and per-route policies are defined in a routes block
routes:
<unchanged routes on ourdomain.com>
```

## What did you see in the logs?

I tried grepping for `400` or `CSRF` but found nothing.  Lots of normal logged events, and a few of the errors below.  (I can provide fuller logs if necessary)
```logs
2022-07-05 09:06:57 | {   "level": "error",   "service": "identity_manager",   "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",   "user_id": "115742284905408797056",   "session_id": "7c94c3bf-7dfd-4ace-928b-7719950537ba",   "time": "2022-07-05T09:06:57-05:00",   "message": "failed to update user info, deleting session" }
2022-07-05 09:06:57 | {   "level": "info",   "type": "type.googleapis.com/session.Session",   "id": "71f65243-a5bc-4869-9d76-1a340559f861",   "time": "2022-07-05T09:06:57-05:00",   "message": "put" }
2022-07-05 09:06:57 | {   "level": "info",   "type": "type.googleapis.com/pomerium.events.LastError",   "id": "identity_manager_last_user_refresh_errors",   "time": "2022-07-05T09:06:57-05:00",   "message": "put" }

```

## Additional context

See note about changing networks, although it could be a red herring.
No abnormal logs for the redis backend.

**Comment by desimone** [comment]
Thanks for the detailed issue @alexrudd2 

What was the user doing when they hit the CSRF error? Typically, we only check that value on protected pomerium endpoints. I've only seen the error when services had differing `shared_secret` /  `cookie_secret` values. Do all your services use the same values there? Were the rolled by any chance? 

```
2022-07-05 09:06:57 | {   "level": "error",   "service": "identity_manager",   "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",   "user_id": "115742284905408797056",   "session_id": "7c94c3bf-7dfd-4ace-928b-7719950537ba",   "time": "2022-07-05T09:06:57-05:00",   "message": "failed to update user info, deleting session" }
```

Suggests that `access_token` associated with that user was no longer valid, so possibly unrelated (it's expected that eventually a IdP will not allow us to use the` refresh_token` after some period of time (though I expect it to be fairly uncommon.

**Comment by alexrudd2** [comment]
> Thanks for the detailed issue @alexrudd2 
> 
> What was the user doing when they hit the CSRF error? Typically, we only check that value on protected pomerium endpoints. I've only seen the error when services had differing

This happened to both myself and at least two other users, both trying to access a "normal" route behind pomerium (i.e. not any pomerium administration).  Accessing `/.pomerium`  worked fine.  Users refreshing the page and/or working appeared to fix it with no other intervention.

>  `shared_secret` /  `cookie_secret` values. Do all your services use the same values there?

We only have a single all-in-one instance.

 > Were the rolled by any chance? 

No changes this week.  Last week I had restarted pomerium a few times trying to work on the Docker Swarm secrets, so it's possible that maybe e.g. a newline got added, but the main character string has remained the same.

> 
> ```
> 2022-07-05 09:06:57 | {   "level": "error",   "service": "identity_manager",   "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",   "user_id": "115742284905408797056",   "session_id": "7c94c3bf-7dfd-4ace-928b-7719950537ba",   "time": "2022-07-05T09:06:57-05:00",   "message": "failed to update user info, deleting session" }
> ```
> 
> Suggests that `access_token` associated with that user was no longer valid, so possibly unrelated (it's expected that eventually a IdP will not allow us to use the` refresh_token` after some period of time (though I expect it to be fairly uncommon. 
> 


I unfortunately didn't grab the user/session IDs from `.pomerium` so I'm not sure if this is even the same user(s).  However, the timeframe is correct and I haven't seen these before.

**Comment by alexrudd2** [comment]
> Thanks for the detailed issue @alexrudd2 
> 
> What was the user doing when they hit the CSRF error? Typically, we only check that value on protected pomerium endpoints. I've only seen the error when services had differing

This happened to both myself and at least two other users, both trying to access a "normal" route behind pomerium (i.e. not any pomerium administration).  Accessing `/.pomerium`  worked fine.  Users refreshing the page and/or working appeared to fix it with no other intervention.

>  `shared_secret` /  `cookie_secret` values. Do all your services use the same values there?

We only have a single all-in-one instance.

 > Were the rolled by any chance? 

No changes this week.  Last week I had restarted pomerium a few times trying to work on the Docker Swarm secrets, so it's possible that maybe e.g. a newline got added, but the main character string has remained the same.

> 
> ```
> 2022-07-05 09:06:57 | {   "level": "error",   "service": "identity_manager",   "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",   "user_id": "115742284905408797056",   "session_id": "7c94c3bf-7dfd-4ace-928b-7719950537ba",   "time": "2022-07-05T09:06:57-05:00",   "message": "failed to update user info, deleting session" }
> ```
> 
> Suggests that `access_token` associated with that user was no longer valid, so possibly unrelated (it's expected that eventually a IdP will not allow us to use the` refresh_token` after some period of time (though I expect it to be fairly uncommon. 
> 


I unfortunately didn't grab the user/session IDs from `.pomerium` so I'm not sure if this is even the same user(s).  However, the timeframe is correct and I haven't seen these before.

**Comment by alexrudd2** [comment]
![unnamed](https://user-images.githubusercontent.com/52292902/223542710-7bbc422b-1494-492b-bdb1-88eabdf17d83.jpg)


```
2023-03-07 13:47:18 | {   "level": "info",   "service": "envoy",   "upstream-cluster": "pomerium-control-plane-http",   "method": "GET",   "authority": "authenticate.domain.com",   "path": "/oauth2/callback",   "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/110.0.5481.114 Mobile/15E148 Safari/604.1",   "referer": "https://accounts.google.com/",   "forwarded-for": "10.0.0.2",   "request-id": "f26d58d4-e5f1-48e6-b278-70391d8118fa",   "duration": 1.740266,   "size": 569,   "response-code": 400,   "response-code-details": "via_upstream",   "time": "2023-03-07T13:47:18-06:00",   "message": "http-request" }
2023-03-07 13:47:19 | {   "level": "info",   "service": "envoy",   "upstream-cluster": "pomerium-control-plane-http",   "method": "GET",   "authority": "authenticate.domain.com",   "path": "/.pomerium/index.js",   "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/110.0.5481.114 Mobile/15E148 Safari/604.1",   "referer": "https://authenticate.numat.com/oauth2/callback",   "forwarded-for": "10.0.0.2",   "request-id": "11d6cbed-5d60-4856-a0da-e0d43e64d0da",   "duration": 0.859014,   "size": 0,   "response-code": 304,   "response-code-details": "via_upstream",   "time": "2023-03-07T13:47:19-06:00",   "message": "http-request" }





```

**Comment by alexrudd2** [comment]
> ```
> 2022-07-05 09:06:57 | {   "level": "error",   "service": "identity_manager",   "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",   "user_id": "115742284905408797056",   "session_id": "7c94c3bf-7dfd-4ace-928b-7719950537ba",   "time": "2022-07-05T09:06:57-05:00",   "message": "failed to update user info, deleting session" }
> ```
> 
> Suggests that `access_token` associated with that user was no longer valid, so possibly unrelated (it's expected that eventually a IdP will not allow us to use the` refresh_token` after some period of time (though I expect it to be fairly uncommon.

This time around I didn't see such an `identity_manager` error in the logs.  Bobby still has access to our raw logs if needed.

`pomerium/pomerium:git-3b2cc672` running all-in-one with PSQL datastore.  PSQL is replicated across 3 machines, and two of them saw heavy memory/disk pressure today but it doesn't look like any of the containers restarted.

**Comment by alexrudd2** [comment]
@patrickfuller is/was the affected user.  Apparently his laptop works fine but the phone does not.

The Enterprise Console has apparently fallen over since I installed it (getting a bad cert blocked by HSTS), so I can't use that to troubleshoot.  Instead I deleted both session entries corresponding to Pat from the datastore PSQL.  He told me this had no effect.
