### ISSUE TITLE
Add podAntiAffinity to each one of the deployments

### ISSUE THREAD

**Issue by TheMisterEletric** [pomerium/pomerium#3466]
Is not possible to make a true high availability with out the podAntiAffinity, currently the same pods(Ex proxy) may run on the same node.
If that node dies the service may be affected, if the pods are on the same node
**Describe the solution you'd like**
Add the possibility to do this automatically with an option(Ex HA with podAntiAffinity)
**Describe alternatives you've considered**
Add possibility to change the affinity of each deployment manual
Is currently possible to add the same affinity rules to all deployment, but that force to run only 1 pod on each node(not ideal)

**Comment by wasaga** [comment]
we are moving away from Helm based installation as it grew to have way too many options. 
we advise to use a manifest-based installation https://www.pomerium.com/docs/k8s/quickstart
which may be customized using `kubectl apply -k` - your use case would work just fine for that. 

you may wish to take a look at kustomize docs https://kustomize.io/ and see how the current deployment manifest is assembled - https://github.com/pomerium/ingress-controller/tree/main/config/default
