### ISSUE TITLE
Allow client TLS renegotiation

### ISSUE THREAD

**Issue by vsdesai** [pomerium/pomerium#3481]
**Is your feature request related to a problem? Please describe.**

Yes, we currently have several internal sites which are failing when trying to access them via pomerium. Pomerium is returning 503 with "upstream connect error or disconnect/reset before headers. reset reason: connection termination" to users

From pomerium logs:
 response-code-details: upstream_reset_before_response_started{connection_failure}
OPENSSL_internal:NO_RENEGOTIATION
OPENSSL_internal:PROTOCOL_IS_SHUTDOWN

My suspicion is that envoy is refusing TLS renegotiation and hanging up on connection. Packet capture suggests that pomerium is sending Encrypted Alert followed by FIN to the upstream application.  We don't exactly know what's causing this.

**Describe the solution you'd like**

envoy has "allow_renegotiation" option which can be useful in this context. Can pomerium expose this option either globally or per route?
Reference: 
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto
https://groups.google.com/g/envoy-users/c/kv9JFYboTSU

**Describe alternatives you've considered**
There is no other viable option that I can think of

**Explain any additional use-cases**

N/A

**Comment by desimone** [comment]
Hey @vsdesai -- this is difficult to test & validate on our side.

If you can test using a docker image, can you try pulling either the debug docker build off our "main" branch / or the specific git hash? 

- pomerium/pomerium:debug
- pomerium/pomerium:git-cef6b355

Thanks!

**Comment by desimone** [comment]
@vsdesai -- Did this do the trick?

**Comment by vsdesai** [comment]
Hi @desimone - we haven't had a chance to try it out yet. I'll give it a go early next week and report back. Thanks

**Comment by vsdesai** [comment]
Happy to confirm that this change resolves the issue. Thank you
