### ISSUE TITLE
Outlier detection and Health check aren't valid keys

### ISSUE THREAD

**Issue by ajcollett** [pomerium/pomerium#3506]
## What happened?
When using Outlier detection, and the health_checks (in any combo) they are not used, and I see:
```
{"level":"warn","config_file":"/etc/pomerium/config.yaml","keys":["routes[13].outlier_detection"],"time":"2022-07-28T12:21:21+02:00","message":"config contained unknown keys that were ignored"}
```

in the logs. 

This was on 0.17.03 and 0.18
## What did you expect to happen?

Outlier detection and healthchecks should work, and not be thrown out by config. 

## How'd it happen?
Added the settings to the config, and observed the above logs. 

Then restarted pomerium, and found the same. 

Finally, I upgraded to 18 and still had the same. 

All the while I have 7 hosts in the LoadBalancer, and with round robin I consistently get served connections to the hosts that should be ejected (they are down).

## What's your environment like?
Pomerium 18 on Ubuntu 18.04 VM, installed as binary

## What's your config.yaml?
```config.yaml
...
    - from: https://example
      prefix: /dev
      outlier_detection: {"consecutive_5xx": 3}
      health_checks:
      - timeout: 10s
        interval: 240s
        healthy_threshold: 1
        unhealthy_threshold: 2
        http_health_check:
          path: "/"
      to: 
      - http://host1/dev
      - http://host2/dev
      - ...
      tls_skip_verify: true
      allow_websockets: true
      policy:
        - allow:
            or:
              - email:
                  is: bla@bla.com
```

## What did you see in the logs?

```logs
Jul 28 12:19:44 host.com pomerium[31839]: {"level":"warn","config_file":"/etc/pomerium/config.yaml","keys":["routes[x].outlier_detection"],"time":"2022-07-28T12:19:44+02:00","message":"config contained unknown keys that were ignored"}
```

**Comment by wasaga** [comment]
The log message was not correct. `outlier_detection` is a correct key. 

The outlier detection and active health checks do work - i.e. see this config: 

Let's run httpbin locally, serving at port 8099:
```
docker run -p 8099:80 kennethreitz/httpbin
```

the other upstream at port `5555` is supposed to be non-functioning. 
```
  - from: https://httpbin-test.localhost.pomerium.io
    to:
      - http://localhost:8099/
      - http://localhost:5555/
    allow_public_unauthenticated_access: true
    outlier_detection: { "consecutive_5xx": 1 }
```

```
$ hey https://httpbin-test.localhost.pomerium.io

.. skipping for brevity ..

Status code distribution:
  [200]	199 responses
  [503]	1 responses
```

as expected, it would hit the non-working upstream server and it would be ejected from the pool - other requests would go to a healthy upstream. 

You may monitor the outlier detection ejections via [prometheus metrics](https://www.pomerium.com/docs/reference/metrics-address) (I removed labels)

```
$ curl --silent http://localhost:9091/metrics | grep outlier
envoy_cluster_outlier_detection_ejections_enforced_consecutive_5xx{} 1
envoy_cluster_outlier_detection_ejections_detected_consecutive_5xx{} 1
envoy_cluster_outlier_detection_ejections_total{} 1
```

Similarly with active health checks, they do work in this set up.
