### ISSUE TITLE
Autocert config option is overruled by wildcard certificate config option

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3543]
## What happened?

With autocert turned on AND a wildcard certificate (via [`CERTIFICATE_FILE`](https://github.com/pomerium/pomerium/issues/3441)), pomerium uses the wildcard exclusively.  This is true even if the wildcard is expired.

## What did you expect to happen?
Autocert to take precedence, perhaps falling back to the wildcard if autocert does not have a valid route certificate.

OR 

An error thrown from invalid config.

OR

[Documentation](https://www.pomerium.com/docs/topics/certificates#certificates) explains whether `autocert` or `certificate` takes precedence if both are configured.

## How'd it happen?

1. Enable both autocert and wildcard certificates.
2. Load a route
3. Observe pomerium serves the wildcard, even if a valid autocert cert is available.

## What's your environment like?

- Pomerium version: `v0.18`
- Server Operating System/Architecture/Cloud: Docker Swarm on Linux

## What's your config.yaml?

```config.yaml
certificate_file: "/run/secrets/<mydomain>.pem"
certificate_key_file: "/run/secrets/fullchain.pem"
#certificate_authority_file: "/pomerium/cert.pem"
autocert: true
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

## Additional context

Note sure if this happens with just `CERTIFICATE` instead of `CERTIFICATE_FILE`

**Comment by desimone** [comment]
I think this is expected behavior from autocert (which is to have manually specified certificates, when there is an overlapping SNI name take precedence). I think, to your point, we can point that out in the documentation.

**Comment by desimone** [comment]
We should also use this as an opportunity to document that autocert will attempt:

- HTTP01 
- TLS-ALPN-01 

And we do not support `DNS-01` challenges (and therefore, wildcard certificates).
