### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by chickahoona** [pomerium/pomerium#357]
Your docker documentation here https://www.pomerium.io/docs/quick-start/ says the private key needs to be mounted as /pomerium/**privkey**.pem

Yet here https://www.pomerium.io/docs/reference/examples.html#configurations you mention that the default is configured to be ./**certprivkey**.pem

**Comment by desimone** [comment]
Thanks for catching this inconsistency @chickahoona . Since `0.4.0` we've [removed the default cert location](https://docs.pomerium.io/docs/upgrading.html#since-0-3-0) so that should be updated in the examples as well.
