### ISSUE TITLE
controlplane: dropping event due to full channel: session invalidated

### ISSUE THREAD

**Issue by schmug** [pomerium/pomerium#3573]
## What happened?
Some user sessions are returning Error 500 for all routes, others are intermittent.

## What did you expect to happen?
Policy to proceed where allowed.

## How'd it happen?

1. Updated from Pomerium v15 > v18
2. In testing post upgrade, second pomerium node appeared not be handling authorization properly, so I stopped all services on the second node.
3. I am now running on a single node, node 1, and some users get error 500 for all routes.
4. I get intermittent error 500s, noticed more often with streaming requests. Static sites will work or fail, but when failing a refresh will allow it through.

## What's your environment like?

- pomerium: 0.18.0-1658889797+89a105c8
- envoy: 1.21.3+4861429dfffb599f28b9399c34ea2a2c268bfb6d10aca0a53bc9b67d847a4595
- Pomerium console version: 0.18.0-1658971952 + 7b8e18a8 + 2022-07-27T21:30:12-04:00
- Server Operating System/Architecture/Cloud: 2x CentOS Stream on premise virtual machines
Separate redis (did not see the redis deprecation) and postgres VMs

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://example.com

certificates:
  - cert: /path/to/cert.pem
    key: /path/to/key.pem

signing_key: SECRET
metrics_address: localhost:9999

http_redirect_addr: :80

idp_provider: google
idp_client_id: clientid
idp_client_secret: secret
idp_service_account: serviceaccount

idp_refresh_directory_timeout: 10m
idp_refresh_directory_internal: 20m

cookie_secret: cookiesecret

shared_secret: sharedsecret

databroker_storage_type: redis
databroker_storage_connection_string: redis://:@redis:6379

policy:
  - from: https://console.example.com
    to: https://127.0.0.1:8701
    pass_identity_headers: true
    allowed_groups:
      - group@example.com
    allowed_users:
      - example@example.com
```

## What did you see in the logs?

```logs
  {
    "level": "error",
    "config_file_source": "/etc/pomerium/config.yaml",
    "bootstrap": true,
    "service": "identity_manager",
    "error": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",
    "user_id": "xxx",
    "session_id": "xxx",
    "time": "2022-08-24T12:01:19-04:00",
    "message": "failed to update user info, deleting session"
  }

  {
    "level": "warn",
    "event": {
      "time": {
        "seconds": 1661363152,
        "nanos": 831339500
      },
      "message": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",
      "id": "identity_manager_last_user_refresh_errors"
    },
    "time": "2022-08-24T13:45:52-04:00",
    "message": "controlplane: dropping event due to full channel"
  }

  {
    "level": "info",
    "service": "envoy",
    "upstream-cluster": "",
    "method": "POST",
    "authority": "example.com",
    "path": "/path/to/page",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
    "referer": "example.com",
    "forwarded-for": "192.168.1.1",
    "request-id": "xxx",
    "duration": 9999.325248,
    "size": 0,
    "response-code": 500,
    "response-code-details": "ext_authz_error",
    "time": "2022-08-24T17:13:34-04:00",
    "message": "http-request"
  }
```

## Additional context

For my user account the problems are intermittment and I can get past them. 

For another user, if I impersonate them with the console I can replicate 100%.

**Comment by schmug** [comment]
I performed the redis flushall, waiting for a sync. getting a lot of 403 and 
  ```
  {
    "level": "warn",
    "error": "record not found",
    "time": "2022-08-24T19:48:59-04:00",
    "message": "clearing session due to missing session or service account"
  }
  ```

  during a large user/group sync, I believe this will appear:
  ```"allow-why-false":["groups-unauthorized","non-pomerium-route"]```

  in the past, the sync from Google takes a very long time before group policy works.

**Comment by schmug** [comment]
The flush does not seem to have changed anything.

**Comment by calebdoxsey** [comment]
I believe this error indicates the credentials are wrong:

```
identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}"
```

This error means that we are failing to store events in the databroker:

```
  {

    "level": "warn",

    "event": {

      "time": {

        "seconds": 1661363152,

        "nanos": 831339500

      },

      "message": "identity/oidc: user info endpoint: 401 Unauthorized: {\"error\":\"invalid_request\",\"error_description\":\"Invalid Credentials\"}",

      "id": "identity_manager_last_user_refresh_errors"

    },

    "time": "2022-08-24T13:45:52-04:00",

    "message": "controlplane: dropping event due to full channel"

  }
```

I don't know why that would fail but it should not effect policy evaluation.

This message:

```
  {

    "level": "info",

    "service": "envoy",

    "upstream-cluster": "",

    "method": "POST",

    "authority": "example.com",

    "path": "/path/to/page",

    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",

    "referer": "example.com",

    "forwarded-for": "192.168.1.1",

    "request-id": "xxx",

    "duration": 9999.325248,

    "size": 0,

    "response-code": 500,

    "response-code-details": "ext_authz_error",

    "time": "2022-08-24T17:13:34-04:00",

    "message": "http-request"

  }
```

Should have a corresponding log in the authorize service that indicates why policy evaluation is failing.

**Comment by calebdoxsey** [comment]
`ext_authz` 500 errors can also be indicative of network problems (if for example the proxy service is unable to communicate with the authorize service). This networking is handled by envoy. Further logs are available by setting the [`proxy_log_level`](https://www.pomerium.com/docs/reference/proxy-log-level), though those logs are verbose and may be hard to decipher.

**Comment by schmug** [comment]
> 
> This message:
> 
> ```
>   {
> 
>     "level": "info",
> 
>     "service": "envoy",
> 
>     "upstream-cluster": "",
> 
>     "method": "POST",
> 
>     "authority": "example.com",
> 
>     "path": "/path/to/page",
> 
>     "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36",
> 
>     "referer": "example.com",
> 
>     "forwarded-for": "192.168.1.1",
> 
>     "request-id": "xxx",
> 
>     "duration": 9999.325248,
> 
>     "size": 0,
> 
>     "response-code": 500,
> 
>     "response-code-details": "ext_authz_error",
> 
>     "time": "2022-08-24T17:13:34-04:00",
> 
>     "message": "http-request"
> 
>   }
> ```
> 
> Should have a corresponding log in the authorize service that indicates why policy evaluation is failing.

Would this be what we are looking for?
```
  {
    "level": "error",
    "error": "authorize: error evaluating policy.rego: eval_cancel_error: caller cancelled query execution",
    "time": "2022-08-25T11:37:43-04:00",
    "message": "error during OPA evaluation"
  }
```

**Comment by schmug** [comment]
> `ext_authz` 500 errors can also be indicative of network problems (if for example the proxy service is unable to communicate with the authorize service). This networking is handled by envoy. Further logs are available by setting the [`proxy_log_level`](https://www.pomerium.com/docs/reference/proxy-log-level), though those logs are verbose and may be hard to decipher.

proxy and authorize are on the same box right now, and the second pomerium node is off so I don't think this would be an issue

**Comment by schmug** [comment]
> 
> ```yaml
> grpc_client_timeout: "60s"
> ```

Would you expect any user disruption by adding this? Additionally, this should be set in open source config and nowhere in the Console right?

**Comment by calebdoxsey** [comment]
Also you mentioned the second pomerium node. Is it possible that node is still resolvable from DNS? e.g. `databroker.example.com` is pointing to both nodes, but only one of them is working? I'm not sure what the behavior would be if that were happening.

I would not expect user disruption from that setting. And yes it appears to only be available in the open source.

**Comment by schmug** [comment]
The initial run hit me with a request timeout, 408, after 30 seconds.

**Comment by calebdoxsey** [comment]
OK it sounds like it is timing out then. There's the timeout for browser -> proxy, and then proxy -> authorize, then authorize -> databroker. It's this last connection that's likely at fault. If it's due to a faulty databroker server in the DNS entry that might explain it (it would be attempting to access this server but wouldn't be able to connect to it).

**Comment by schmug** [comment]
> Also you mentioned the second pomerium node. Is it possible that node is still resolvable from DNS? e.g. `databroker.example.com` is pointing to both nodes, but only one of them is working? I'm not sure what the behavior would be if that were happening.

I am curious on the second node, but I have paused testing on it until I can resolve the 500s.

> 
> I would not expect user disruption from that setting. And yes it appears to only be available in the open source.

Also because of our environment (some duplicate froms, long story) wss connections are dropped when changing some things. It appears that `grpc_client_timeout` is one of those so my testing and reconfiguration may be limited during business hours.

**Comment by schmug** [comment]
I've moved both nodes to a postgres databroker and am monitoring now. I won't know until more users attempt routes.

**Comment by schmug** [comment]
If redis couldn't keep up then it adds up that postgres seems to be acting better.

Also, I noticed in my original config copy
> ```
idp_refresh_directory_internal: 20m
```
It should be interval and I missed that for who knows how long

**Comment by schmug** [comment]
After monitoring the changes, I'm not sure what was going on with redis but postgres is doing much better. Closing for now but I left the infrastructure there if I get bored after hours.
