### ISSUE TITLE
Self-signed certificate surfaced on unknown routes

### ISSUE THREAD

**Issue by schmug** [pomerium/pomerium#3577]
## What happened?
Non-routes are exposed using self-signed certificate

## What did you expect to happen?
404

## How'd it happen?

1. Wildcard DNS for domain
2. Browse to https://test3.example.com

## What's your environment like?

- pomerium: 0.18.0-1658889797+89a105c8
- envoy: 1.21.3+4861429dfffb599f28b9399c34ea2a2c268bfb6d10aca0a53bc9b67d847a4595
- Pomerium console version: 0.18.0-1658971952 + 7b8e18a8 + 2022-07-27T21:30:12-04:00
- Server Operating System/Architecture/Cloud: 2x CentOS Stream on premise virtual machines
- postgres VMs for console and databroker

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://example.com

certificates:
  - cert: /path/to/cert.pem
    key: /path/to/key.pem

signing_key: SECRET
metrics_address: localhost:9999

http_redirect_addr: :80

idp_provider: google
idp_client_id: clientid
idp_client_secret: secret
idp_service_account: serviceaccount

idp_refresh_directory_timeout: 10m
idp_refresh_directory_internal: 20m

cookie_secret: cookiesecret

shared_secret: sharedsecret

databroker_storage_type: postgres
databroker_storage_connection_string: postgres://:@postgres:5432

policy:
  - from: https://console.example.com
    to: https://127.0.0.1:8701
    pass_identity_headers: true
    allowed_groups:
      - group@example.com
    allowed_users:
      - example@example.com
```

## What did you see in the logs?

```logs
{
  "level": "info",
  "service": "envoy",
  "upstream-cluster": "",
  "method": "GET",
  "authority": "test3.example.com",
  "path": "/",
  "user-agent": "useragent",
  "referer": "",
  "forwarded-for": "x.x.x.x",
  "request-id": "xxx",
  "duration": 0.331926,
  "size": 0,
  "response-code": 404,
  "response-code-details": "route_not_found",
  "time": "2022-08-29T12:04:54-04:00",
  "message": "http-request"
}
```

## Additional context

Wildcard certificate is specified in config.yaml, seems related to this change:
https://docs.pomerium.com/docs/overview/upgrading#self-signed-fallback-certificates

User gets an invalid cert browser splash, if they proceed through they get the 404.

**Comment by desimone** [comment]
To add more context

1. There is a wildcard domain *.[int.foo.com](http://int.foo.com/)
2. There is a wildcard DNS entry to all of *.[int.foo.com](http://int.foo.com/) to pomerium
3. There is no route for [404.int.foo.com](http://404.int.foo.com/)
4. If a user goes to [404.int.foo.com](http://404.int.foo.com/) the user gets self signed not wildcard cert

Wildcard certificates are loaded by file, not console (though a enterprise user). 

```yaml
certificates:
  - cert: /path/to/cert.pem
    key: /path/to/key.pem
```

**Comment by desimone** [comment]
Expected behavior is that the user still get a `404` but the wildcard certificate should match before the self signed fallback.
