### ISSUE TITLE
Unable to use front channel signout on authenticate

### ISSUE THREAD

**Issue by robertmx** [pomerium/pomerium#3592]
## What happened?

When using a generic OIDC provider (Keycloak) with frontchannel logout, I am unable to logout using the endpoint on the authenticate service (https://authenticate/.pomerium/sign_out). I am logged out with the OP but my sessions with pomerium are still valid. I can still access the dashboard (https://authenticate/.pomerium) and my app at https://myapp/.

When using the frontchannel logout endpoint of the application at https://myapp/.pomerium/sign_out, the sessions are invalidated correctly.

Unfortunately the documentation is rather incomplete in that regard, which is a pity considering logout is one of the most important aspects of an access control system. I found some hints in various issues here, that it is necessary to logout on the proxy and not the authenticate service, but the docs at https://www.pomerium.com/docs/topics/single-sign-out do not say so. Furthermore it seems logical to ask the authenticate service to terminate all sessions for single sign out instead hitting a random app and ask for signout.

NOTE: The frontchannel logout endpoints are never accessed manually but through the OP (Keycloak) logout process using an iframe as per the OIDC front channel logout spec. 

## What did you expect to happen?

I would like to hit the frontchannel logout endpoint on the authentication service and have ALL sessions terminated.

## How'd it happen?

see above

## What's your environment like?

- Pomerium version 0.17.3 and 0.18.0 tested
- Server Operating System/Architecture/Cloud: Linux tested on Docker and bare metal deployment

## What's your config.yaml?

```config.yaml

# See detailed configuration settings : https://www.pomerium.com/docs/reference/

# this is the domain the identity provider will callback after a user authenticates
authenticate_service_url: https://{{ inventory_hostname }}

####################################################################################
# Certificate settings:  https://www.pomerium.com/docs/reference/certificates.html #
# The example below assumes a certificate and key file will be mounted to a volume #
# available to the  Docker image.                                                  #
####################################################################################
certificate_file: /etc/pomerium/cert.pem
certificate_key_file: /etc/pomerium/privkey.pem

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: oidc
idp_provider_url: https://{{ inventory_hostname }}:8443/realms/homelab
idp_client_id: pomerium
idp_client_secret: secret

# Generate 256 bit random keys  e.g. `head -c32 /dev/urandom | base64`
cookie_secret: secret

set_response_headers:
  Content-Security-Policy: frame-ancestors https://some-hosts 'self'

# https://pomerium.com/reference/#routes
routes:
  - from: https://myapp
    to: http://127.0.0.1:5005
    pass_identity_headers: true
    policy:
      - allow:
          and:
            - authenticated_user: True
            - claim/groups: /admin


```

## What did you see in the logs?

Nothing I could identify as important

**Comment by robertmx** [comment]
I poked around in the code for the generic oidc provider and tried to initiate a logout from /.pomerium/sign_out (RP initiated) instead of starting a frontchannel logout from the OP. That did not work as well (I was still logged into the OP). Some observations that seem related.

There is a line in the logs, indicating that revoke is not implemented. Tracing the code indicates, that the relevant endpoints are not detected (end_session_endpoint, revocation_endpoint). But then I would expect the error message from that code fragment to show up in the logs, which is not the case...

Log output:
```
Aug 30 18:06:55 XXXX [160425]: {"level":"warn","X-Forwarded-For":["192.168.1.40"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0","referer":"https://XXX/.pomerium/sign_out","request-id":"50e068c6-198d-47ad-a6b0-4a7f59f966b4","error":"identity/oidc: revoke not implemented","time":"2022-08-30T18:06:55Z","message":"authenticate: failed to revoke access token"}

```

```
	// add non-standard claims like end-session, revoke, and user info
	if err := pp.Claims(&p); err != nil {
		return nil, fmt.Errorf("identity/oidc: could not retrieve additional claims: %w", err)
	}
```

**Comment by JLyne** [comment]
After adding some logging, it would appear that `GetProvider` is never actually called while the user is logging out, so the claims never get populated and pomerium assumes the idp doesn't support revoking or logging out. A quick fix is adding `p.GetProvider()` to the top of `LogOut` and `Revoke` in identity/oidc/oidc.go.

**Comment by robertmx** [comment]
That is interesting, I assumed the provider struct gets populated only once at server startup.

**Comment by calebdoxsey** [comment]
I have never successfully run Keycloak with Pomerium so I can't confirm, but I'm guess it doesn't support logout, or our generic OIDC provider is not parsing the logout URL from it in whatever format it provides it.

The way the code is written, it will not delete the Pomerium session if this happens. I will update the code so that the deletion of the pomerium session happens regardless.

**Comment by JLyne** [comment]
> I have never successfully run Keycloak with Pomerium so I can't confirm, but I'm guessing it doesn't support logout, or our generic OIDC provider is not parsing the logout URL from it in whatever format it provides it.

It's the latter problem, keycloak provides an `end_session_endpoint` in its openid-configuration, which pomerium usually picks up correctly but doesn't on the sign_out route. This appears to have become a problem between 0.16.4 and 0.17.0 as far as I can tell.

**Comment by robertmx** [comment]
> I have never successfully run Keycloak with Pomerium so I can't confirm, but I'm guessing it doesn't support logout, or our generic OIDC provider is not parsing the logout URL from it in whatever format it provides it.
> 
> The way the code is written, it will not delete the Pomerium session if this happens. I will update the code so that the deletion of the pomerium session happens regardless.

I can confirm, that keycloak provides a standard-compliant `end_session_endpoint` and `revocation_endpoint`. I tested that setup with mod_auth_openidc, which detects the relevant settings from the keycloak `.well-known/...` discovery url. If it helps I might provide the json from the discovery endpoint.

Wouldn't it be a good idea to use the generic oidc provider as the basis for all the other providers and make that a first-class citizen? At the moment it seems like an afterthought, judging by it not being mentioned in the guides at all?

**Comment by robertmx** [comment]
> > I have never successfully run Keycloak with Pomerium so I can't confirm, but I'm guessing it doesn't support logout, or our generic OIDC provider is not parsing the logout URL from it in whatever format it provides it.
> 
> It's the latter problem, keycloak provides an `end_session_endpoint` in its openid-configuration, which pomerium usually picks up correctly but doesn't on the sign_out route. This appears to have become a problem between 0.16.4 and 0.17.0 as far as I can tell.

Wouldn't that qualify as a security related issue? The RP not terminating the session on the OP after the user thinks he is logged out might open that session to unauthorized parties.

**Comment by calebdoxsey** [comment]
There was a bug causing logout on the authenticate service to work differently from logout on the proxy service. (they were actually using different sessions) The above PR should fix that problem.

However using logout from authenticate is not ideal. It can't delete the cookie on the route itself, and we utilize a caching layer for session access, so it may take a few seconds for the user to appear logged out on the route. We should update the documentation to recommend using the route logout.

As for deleting the session in the IdP, we have code to do this, but it may not be working properly. OIDC is unfortunately not particularly consistent, so yes in an ideal world it would be sufficient, but in reality we have to account for the oddities of each provider. As an example, AWS Cognito returns the standard claim `email_verified` as a string instead of as a boolean. This violates the spec but we have to support it. And it seems like most users are using providers like Okta, Google, Azure, etc. (They also supply valuable directory information, like groups, which are important for policy decisions)

I think we're certainly open to having better documentation for how to work with Keycloak.

**Comment by desimone** [comment]
Closing this issue (fixed by https://github.com/pomerium/pomerium/pull/3597) with a follow up with docs changes and a request from the community to help better cover Keycloak.
