### ISSUE TITLE
v0.19.0 docker image does not work on ARM64 nodes

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#3598]
## What happened?

I'm running pomerium proxy on Graviton 2 nodes and while upgrading from v0.18.0 to v0.19.0 the proxy refused to start correctly:

```
{"level":"error","config_file_source":"/etc/pomerium/config.yaml","bootstrap":true,"error":"error starting envoy: fork/exec /tmp/pomerium-envoy1313994351/envoy: exec format error","service":"envoy","time":"2022-09-02T08:56:35Z","message":"envoy: failed to run envoy process"}
```

**Comment by desimone** [comment]
Slack context: 
- https://pomerium-io.slack.com/archives/CK92MUAES/p1662109098350819

**Comment by calebdoxsey** [comment]
I was able to reproduce this on an arm machine. I will investigate how it happened.

**Comment by calebdoxsey** [comment]
Our envoy-binaries repo has incorrect binaries for arm. Not sure how it happened but I will work on fixing it and also add tests to make sure the binaries work before publishing them.

**Comment by calebdoxsey** [comment]
Oh it's broken upstream: https://github.com/envoyproxy/envoy/issues/22261
