### ISSUE TITLE
Bug: AUTHENTICATE_SERVICE_URL should strip ending URL slash

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium#362]
## What happened?

Pomerium is not stripping ending URL slash from  `AUTHENTICATE_SERVICE_URL` value, this will results in fail state: `net/http: invalid Cookie.Domain "example.com/"; dropping domain attribute`

For example:
- `AUTHENTICATE_SERVICE_URL=https://auth.example.com/` -> KO
- `AUTHENTICATE_SERVICE_URL=https://auth.example.com` -> OK
## What did you expect to happen?

Cookie is propely set.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
pomerium/v0.4.0 (+github.com/pomerium/pomerium; 28eae36; go1.13.1)
- Server Operating System/Architecture/Cloud:
Ubuntu 19.04 / Docker CE 19.03.1
## What's your config.yaml?
```
SERVICES="all" 
AUTHENTICATE_SERVICE_URL=https://auth.example.com/ 
FORWARD_AUTH_URL=https://fwdauth.example.com/ 
INSECURE_SERVER=TRUE 
POMERIUM_DEBUG=true  
COOKIE_SECRET=xxx 
IDP_CLIENT_ID=xxxx 
IDP_CLIENT_SECRET=xxxx 
IDP_PROVIDER=oidc 
IDP_PROVIDER_URL=https://xxxx.eu.auth0.com/ 
```
```config.yaml
policy:
  - from: https://whoami.example.com
    to: https://whoami.example.com
    allowed_users:
      - foo@example.com
```

## What did you see in the logs?

```logs
8:26AM DBG http-request duration=0.181174 email= fwd_ip=["89.176.XX.XX"," 172.18.0.1"] group= host=fwdauth.example.com ip=172.18.0.27 method=GET path=/.pomerium/verify/whoami.example.com req_id=277e1cdc-255d-ac9d-b18d-0b22bca4b2a6 service=all size=233 status=302 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
2019/10/09 08:26:04 net/http: invalid Cookie.Domain "example.com/"; dropping domain attribute
8:26AM ERR authenticate: unexpected session state error="internal/sessions: session is not found" fwd_ip=["89.176.XX.XX"] ip=172.18.0.27 req_id=0d77786c-85e7-65ef-ced5-1f1939bdc247 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36"
2019/10/09 08:26:04 net/http: invalid Cookie.Domain "example.com/"; dropping domain attribute
```

**Comment by cuonglm** [comment]
This works fine in latest release, close now, feel free to re-open if you still face this issue.
