### ISSUE TITLE
v0.4.0: extra query parameters pomerium-auth-callback breaks protected apps

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#366]
## What happened?

With v0.4.0, just after authentication is triggered, pomerium adds a query parameter `?pomerium-auth-callback=true` to the url that is transmitted to the protected apps url: `https://my-app.corp.pomerium.io/?pomerium-auth-callback=true`.

The problem with that is twofold:
- the users are confused by the resulting url
- the application loose control of the location uri (in particular SPAs are used to be in full control of it), in my particular case, when the user reaches `/`, he is then redirected to a default page, but with the query parameter here, the SPA does not do the redirection.

## What did you expect to happen?

That once I am connected through pomerium, the url is exactly as typed originally by the user.

## How'd it happen?

1. Entered a protected app url in the browser
2. Got redirected to authenticate service then to google idp for auth
3. Got redirected to the original url + the extra query parameters

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): 0.4.0

**Comment by desimone** [comment]
Hi @victornoel -- Thanks as always for the bug report. I think I have a fix for this in #368 along with a test docker image if you don't mind giving it a try.

Thanks!

**Comment by victornoel** [comment]
@desimone I will try to do so in the next few days yes! Thx for the very quick feedback :)

**Comment by awkaplan** [comment]
This issue appears to still exist in 0.4.2.

**Comment by desimone** [comment]
@awkaplan Thanks for the heads up. This should be fixed as of #373
