### ISSUE TITLE
envoy config maybe wrong

### ISSUE THREAD

**Issue by RongerW** [pomerium/pomerium#3665]
in file https://github.com/pomerium/pomerium/blob/main/config/envoyconfig/clusters.go +78
`
	if len(databrokerURLs) > 1 {
		authorizeCluster.HealthChecks = grpcHealthChecks("pomerium-databroker")
		authorizeCluster.OutlierDetection = grpcAuthorizeOutlierDetection()
	}`

i think the databrokerCluster health checks config is wrong，the right maybe is 
`
	if len(databrokerURLs) > 1 {
		databrokerCluster.HealthChecks = grpcHealthChecks("pomerium-databroker")
		databrokerCluster.OutlierDetection = grpcAuthorizeOutlierDetection()
	}`

**Comment by desimone** [comment]
@RongerW  -- Could you elaborate? Is something not behaving as expected? The name looks mismatched, but curious if you are seeing any broken behavior.
