### ISSUE TITLE
Got stuck with csrf errors after pomerium restart and/or cookie secret change

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#367]
## What happened?

After I changed the cookie secret, one of my user started to get the error page with "csrf failure" message even after logout and re-login. Unfortunately we didn't keep the exact message.

Then after upgrading to v0.4.0 then reverting to v0.3.0 (because of #366), it happened again to me, with a slightly different error but also about csrf (the previous one didn't have the nil thing in it though):
![image](https://user-images.githubusercontent.com/160975/66717721-78fdd580-eddc-11e9-859f-5600c1f1be92.png)

In both case, the only way to fix this was to remove the cookie _pomerium_csrf by hand.

## What did you expect to happen?

No errors, pomerium should reset cookies in this kind of situation I think, so that users are not impacted by problems in the cookies?

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): 0.3.0 and 0.4.0
- Server Operating System/Architecture/Cloud: aks

## What's your config.yaml?

```config.yaml
policy: ....
cookie_domain: my-domain.com
```

The authenticate service is served on auth.aks.my-domain.com, i.e. not directly under the cookie-domain, maybe this is related?

## What did you see in the logs?

```logs
{"level":"error","fwd_ip":"10.242.1.250","ip":"10.242.1.255","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0","referer":"https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=xxxxxxxxxxx&as=xxxxxxxxx&destination=https%3A%2F%2Fauth.aks.my-domain.com&approval_state=xxxxxxxxxxx&oauthgdpr=1&xsrfsig=xxxxxxxxxxxx&flowName=GeneralOAuthFlow","req_id":"6dd05588-54f0-c5a6-9523-b64888615267","error":"oauth callback : csrf failure: %!w(<nil>)","http-message":"oauth callback : csrf failure: %!w(<nil>)","http-code":500,"time":"2019-10-13T15:01:12Z","message":"http-error"}
```

**Comment by desimone** [comment]
This one is tricky to diagnose. We improved csrf protection in `0.4.0`. My best guess is that there were two competing CSRF tokens being stored one at the domain level and one at the parent domain level. But I'm not sure.

I don't anticipate this issue going forward for future releases (unless we change csrf tokenization methods again, which I don't plan on). Unfortunately, this is annoying for end users who have an old CSRF token cached in their browser.

**Comment by victornoel** [comment]
@desimone yes, sorry for this, it's not clear what is the reason of this, and complex to reproduce.

I was wondering but I may be missing things: can't pomerium cleanup old csrf token when they are not at the expected level?

Also I was expecting that changing the cookie secret will force old cookies to be ignored/deleted so that my user get a clean slate :)

**Comment by victornoel** [comment]
@desimone still, there is something strange with the error shown in the screenshot above. One of my user got the error again even though pomerium was still on 0.3.0, the cookie secret didn't change from his previous accesses and his session were ok some time before.

What happens exactly is the following:
- he went to a protected app
- pomerium transferred him to the google idp auth page
- he clicked on his user account
- and then he got the error
  - we checked the cookies and on authenticate, there was only the `_pomerium` cookie, no csrf one.

The logs of authenticate (there was no error anywhere else !):
```
{"level":"error","fwd_ip":"10.242.5.10","ip":"10.242.1.255","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36","referer":"https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=xxxxxxxxxxx&as=xxxxxxxxxx&destination=https%3A%2F%2Fauth.sub.example.com&approval_state=xxxxxxxxxxx&oauthgdpr=1&xsrfsig=xxxxxxxxxx&flowName=GeneralOAuthFlow","req_id":"0ac52dc1-687b-e929-e0fa-593e78768702","error":"oauth callback : csrf failure: %!w(<nil>)","http-message":"oauth callback : csrf failure: %!w(<nil>)","http-code":500,"time":"2019-10-14T15:33:05Z","message":"http-error"}

{"level":"debug","fwd_ip":"10.242.5.10","ip":"10.242.1.255","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36","referer":"https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=xxxxxxxx&as=xxxxxxxxx&destination=https%3A%2F%2Fauth.sub.example.com&approval_state=xxxxxxxxxx&oauthgdpr=1&xsrfsig=xxxxxxx&flowName=GeneralOAuthFlow","req_id":"0ac52dc1-687b-e929-e0fa-593e78768702","duration":750.257369,"size":7929,"status":500,"email":"","group":"","method":"GET","service":"authenticate","url":"/oauth2/callback?state=xxxxxxxxxxxx&code=xxxxxxxxxxx&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&hd=example.com&session_state=d7f81c09abf4307b8da509245c80cc4a21c86ecd..5ba0&prompt=consent","time":"2019-10-14T15:33:05Z","message":"http-request"}
```

**Comment by victornoel** [comment]
@desimone I had an idea, those problems started "maybe" since we have 2 replicas for the proxy in front of pomerium, could there be a link? Maybe the auth flow starts with one proxy and continues with the other?

```
public ip <---> envoy 1 <---> pomerium (proxy, auth)
            \-> envoy 2 <-/ 
```

**Comment by desimone** [comment]
> I was wondering but I may be missing things: can't pomerium cleanup old csrf token when they are not at the expected level?

It depends on what cookie domain is set to. If they are identical between versions, I would have expected the CSRF token to be overwritten. 

> Also I was expecting that changing the cookie secret will force old cookies to be ignored/deleted so that my user get a clean slate :)

That would have been my expectation too. The only scenario I would imagine this not happening in is if the user visited a CSRF protected resource (`POST/PUT/DELETE`) before it had an opportunity to have the new csrf set (`GET/HEAD`). But the normal flow should by definition cause this reset.

**Comment by victornoel** [comment]
> It depends on what cookie domain is set to. If they are identical between versions, I would have expected the CSRF token to be overwritten.

It didn't change no

> The only scenario I would imagine this not happening in is if the user visited a CSRF protected resource (POST/PUT/DELETE) before it had an opportunity to have the new csrf set (GET/HEAD). But the normal flow should by definition cause this reset.

It is typical GET requests

> I don't have a ton of experience with envoy but are the equivalent of "sticky sessions" enabled?

I don't think it is no (I will investigate to see if it possible), but should that matter? Isn't the state in the browser (via cookies) only?

Last point: in https://github.com/pomerium/pomerium/issues/367#issuecomment-541756630, the problem happened once and then when the user tried to connect to the protected app, it worked again (contrarily with the two cases in the description of this issue where we got stuck).

**Comment by victornoel** [comment]
@desimone actually, I think the sticky session things does not apply since there is only one pomerium backend here.

**Comment by ValentinPortais** [comment]
I faced the same issue when upgrading from v0.4.0 to v0.5.2.

**Comment by desimone** [comment]
I believe this issue should now be resolved. Please reopen if that is not the case.

Thanks!
