### ISSUE TITLE
Timeout connecting to pihole in a different Docker container on the same docker network

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#372]
## What happened?
It looks like v0.4.0 has a regression that caused timeout connecting to a different docker container on the same docker network.

Error in the web UI:
```
INTERNAL SERVER ERROR
rpc error: code = DeadlineExceeded desc = latest connection error: connection closed
Request 57104aa0-656b-252c-c49c-a0c289351318
```

Error in the log:
```
11:11PM ERR http-error error="rpc error: code = DeadlineExceeded desc = latest connection error: connection closed" http-code=500 http-message="rpc error: code = DeadlineExceeded desc = latest connection error: connection closed" ip=104.132.11.82 req_id=57104aa0-656b-252c-c49c-a0c289351318 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
11:11PM DBG http-request duration=10156.830725 email=cnyegle@gmail.com group= host=pihole.your-dns.run ip=104.132.11.82 method=GET path=/admin/list.php?l=black req_id=57104aa0-656b-252c-c49c-a0c289351318 service=all size=7966 status=500 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
```

Downgrade to v0.3.1 fixed the issue for me.

## What did you expect to happen?
Request successfully handled.

## How'd it happen?

1. Upgrade from v0.3.1. to v0.4.0
2. The pihole web UI failed to open

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
pomerium/v0.4.0 (+github.com/pomerium/pomerium; 28eae36; go1.13.1)

- Server Operating System/Architecture/Cloud:
Debian Stable, Docker

## What's your config.yaml?

```config.yaml
services: all
pomerium_debug: true
http_redirect_addr: :80

policy:
  - from: https://pihole.your-dns.run
    to: http://pihole
    timeout: 10m
    allowed_users:
      - XXX@gmail.com
  - from: https://your-dns.run
    to: https://coredns
    allow_public_unauthenticated_access: true
    # TODO: change to tls_server_name once
    # https://github.com/pomerium/pomerium/pull/297 is merged.
    tls_skip_verify: true
```

## What did you see in the logs?

```logs
11:11PM ERR http-error error="rpc error: code = DeadlineExceeded desc = latest connection error: connection closed" http-code=500 http-message="rpc error: code = DeadlineExceeded desc = latest connection error: connection closed" ip=104.132.11.82 req_id=57104aa0-656b-252c-c49c-a0c289351318 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
11:11PM DBG http-request duration=10156.830725 email=XXX@gmail.com group= host=pihole.your-dns.run ip=104.132.11.82 method=GET path=/admin/list.php?l=black req_id=57104aa0-656b-252c-c49c-a0c289351318 service=all size=7966 status=500 user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36"
```

**Comment by desimone** [comment]
@yegle Hmm, this is a little confusing to me. You mention that this is a regression where pomerium is failing to connect to another service, but it looks like you are runnin in all in one mode. Is that right? 

1. Does this happen with other routes or just pihole? 
2. Oddly, this looks like the the authorize service is unable to connect to itself on GRPC over localhost. What do you see when you restart the service log wise?
3. Are there any additional configuration options being set (especially related to authorize service url?)

**Comment by yegle** [comment]
https://github.com/yegle/your-dns/blob/your-dns-run/pomerium/config.yaml is the actual config I'm using (along with other configs to run my setup).

**Comment by yegle** [comment]
Note this is still an issue to me. For some reason, I can only use v0.3.1, and any version higher than that would cause this connection closed error.

**Comment by desimone** [comment]
@yegle Thank you for the ping! Do you have a moment to jump into chat to debug this real time?

If not, I think I know what's going on. I didn't realize it until I looked at your [docker compose file](https://github.com/yegle/your-dns/blob/your-dns-run/docker-compose.yaml).  Does commenting out `AUTHORIZE_SERVICE_URL` solve the issue?

**Comment by yegle** [comment]
Oh wow, comment `AUTHORIZE_SERVICE_URL` out does fix the problem! I finally get to use the latest version after a long while...

**Comment by yegle** [comment]
Looks like https://github.com/pomerium/pomerium/issues/388 is related?

**Comment by desimone** [comment]
Great to hear. That's right, in `v0.4.0` we made some changes to the way we handle [gRPC/HTTPS in the all-in-one mode](https://www.pomerium.io/docs/FAQ.html#rpc-errors). Unfortunately, this broke your configuration and wasn't properly covered in the upgrade guide. I'll make a PR to fix that now.
