### ISSUE TITLE
Allow for empty config.yaml via flag or boolean

### ISSUE THREAD

**Issue by kking124** [pomerium/pomerium#3752]
**Is your feature request related to a problem? Please describe.**

When no `/pomerium/config.yaml` file is supplied, the proxy exits even if all required fields are supplied via environment variables.

**Describe the solution you'd like**

An optional environment variable to skip the check for the `/pomerium/config.yaml` file.

For example, add an environment variable named `IGNORE_MISSING_CONFIG_FILE` and have it's default be `false` or `0` with an option to set it to `true` or `1` to try and deploy from only environment variable values. 

**Describe alternatives you've considered**

create a derivative docker container that contains an empty `config.yaml` file to run the application

**Explain any additional use-cases**

Primarily, this is useful in containerized deployments where it is desirable to deploy source-defined containers as opposed to internally developed containers. 

**Additional context**

None.

**Comment by desimone** [comment]
I don't think `config.yaml` should be required; albeit we might be making some assumptions in our packaging that might make it effectively required.

ospkg/pomerium.service

```bash
5:ExecStart=/usr/sbin/pomerium -config /etc/pomerium/config.yaml
``

https://github.com/pomerium/pomerium/blob/6b5096b0fe89987cf0032c05db751d4ec10c19e4/Dockerfile#L29-L30

In docker, this create the file even if it's empty so I'm not sure why it would show as required. 

Needs investigation, and possibly a fix.

**Comment by calebdoxsey** [comment]
Confirmed. No config file is required. Pomerium starts without one.

**Comment by kking124** [comment]
When there is no config file, it tries to write one. It should not need write capability on a read-only config folder.

**Comment by calebdoxsey** [comment]
I don't see code to write a config file. I don't know why that would happen.

**Comment by calebdoxsey** [comment]
We do write temporary files for our envoy config. This includes the envoy bootstrap config and certificates.

**Comment by kking124** [comment]
Strange; when I readonly mount the `/pomerium` directory in the pomerium container using Fargate, the pomerium container crashes unless I `touch /pomerium/config.yaml` before the pomerium container launches.

**Comment by calebdoxsey** [comment]
ok I will re-open. The actual code doesn't have this issue but I guess something about Fargate doesn't interact well with how our code works.

**Comment by calebdoxsey** [comment]
(all we do is `ReadFile` the file if its specified. If you don't pass the config option it won't attempt to load it. If you do pass the config option it will try to read the file and error out if it can't load it. This is behaving as designed.)

**Comment by calebdoxsey** [comment]
It will only attempt to read `/pomerium/config.yaml` if Pomerium is passed the option on the command line. If the option is not passed it won't attempt to read the file. If it is and the file is not present it will fail.

**Comment by calebdoxsey** [comment]
I guess we could make a change to the code to silently ignore the missing file. I will add Needs Discussion and see if that's what the team wants to do.

**Comment by kking124** [comment]
What are the default command and entrypoint on the container? This might be as simple as overriding at runtime.

**Comment by kking124** [comment]
Should probably note this in the docs though
