### ISSUE TITLE
kubernetes integration test fails

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#3764]
## What happened?
The Kubernetes integration test always seems to fail now: https://github.com/pomerium/pomerium/actions/runs/3528649436/jobs/5927568091#step:8:24. It can't start k3s for some reason.

## What did you expect to happen?
The Kubernetes integration tests to succeed.

## How'd it happen?
Made a pull request.

## What's your environment like?
-  52c967b8a52ac55b9823368f5b111bb338d3e106

**Comment by calebdoxsey** [comment]
Not able to reproduce this locally. The images used in the docker file are pinned.

**Comment by calebdoxsey** [comment]
I don't know how to fix this. I guess the k3s docker image is no longer compatible with github actions. I guess we can use kind instead, though we used to use kind and stopped, but I don't remember why we switched.

**Comment by desimone** [comment]
Options I see:

1. Change how our integration tests are run
2. Change how our integration tests work

I'm strongly in favor of (1) especially given how "unknown" / little control we have over github actions environment. I think we should run our own self-hosted runners. This could also solve the Mac and prioritization issue (@wasaga ) we are seeing on the ingress controller. Plus it should just be faster.

It's just a lot of work.

**Comment by desimone** [comment]
https://pomerium-com.slack.com/archives/C012D1Q96TX/p1672349087314379
