### ISSUE TITLE
Unable to connect to local OIDC

### ISSUE THREAD

**Issue by shishkin** [pomerium/pomerium#3811]
## What happened?

I've installed Pomerium ingress controller and Dex IdP in a kubernetes cluster. Dex runs without TLS but is exposed via ingress as `https://dex.cluster.local` with TLS. I was unable to get Pomerium integrate with Dex in any way.

I could not configure IdP URL to Dex internal service as `http://dex.dex.svc.cluster.local` because CRD rejects non `^https://` URLs. I could not make Pomerium recognize that it should use ingress URL when connecting to Dex.

I even tried to add internal DNS record to point `dex.cluster.local` to `dex.dex.svc.cluster.local` but then got the issue that Dex is not serving TLS.

Is there a way to connect to internal IdP without IdP exposing TLS directly?

## What did you expect to happen?

Clear way to configure ingress controller and internal IdP on kubernetes.

## How'd it happen?

Errors I see are these:

```
{"level":"error","X-Forwarded-For":["10.42.0.0"],"X-Forwarded-Proto":["https"],"ip":"127.0.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","request-id":"498a0170-9d6e-4f03-b016-8743c63e94e1","error":"failed to get sign in url: identity/oidc: could not connect to oidc: Get \"https://dex.cluster.local/.well-known/openid-configuration\": dial tcp 10.43.195.81:443: connect: connection refused","status":500,"status-text":"Internal Server Error","request-id":"498a0170-9d6e-4f03-b016-8743c63e94e1","time":"2022-12-14T12:40:29Z","message":"httputil: error"}
```

That's because Dex is not serving TLS.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): v0.20.0 tag from ingress-controller repo
- Server Operating System/Architecture/Cloud: K3s on Docker via K3d.

**Comment by wasaga** [comment]
IdP URL must be HTTPS, as it carries an extremely sensitive information. 

you should be able to connect to your IdP via Ingress external IP address, unless there is some kind of issue that your host IP  address is not routable from inside the cluster, which is frequently the case for local kubernetes distributions. 

you may try to deploy i.e. a busybox container to your cluster and see if you can reach your IdP Ingress via https while inside the cluster. 

My suggestion would be to start with external hosted IdP provider such as Google or Cognito or Okta, before complicating your setup with setting up an internal IdP in parallel.

**Comment by shishkin** [comment]
Thanks. I think I'll try to get TLS on Dex working first. Involving an external service sounds more like a complication to me.

If Pomerium offers an ingress controller, I expect it to handle connection with its dependencies transparently. And it would be a killer feature for self-hosted quick starts to provide a simple embedded IdP out of the box.

**Comment by wasaga** [comment]
> a simple embedded IdP out of the box

Please sign up to https://www.pomerium.com/pomerium-zero/ and stay tuned ;-)

**Comment by shishkin** [comment]
> Please sign up to https://www.pomerium.com/pomerium-zero/ and stay tuned ;-)

Thanks for the link but I'm looking for a self-hosted solution.

**Comment by wasaga** [comment]
You should be able to do the following:

1. Create an Ingress resource, managed by Pomerium to expose your internal IdP publicly with TLS, using annotation public_unauthenticated_access
3. Put the HTTPS URL of this Ingress to Pomerium config CRD [authenticate](https://www.pomerium.com/docs/deploying/k8s/configure#authenticate-endpoint) 

Provided that you are able to communicate to the resulting host IP address.

**Comment by shishkin** [comment]
I couldn't get it to work with the suggested changes. Pomerium proxy logs show an error that it's not able to connect to the IdP host even after providing custom DNS entry inside the cluster.

**Comment by wasaga** [comment]
As Pomerium at some timepoint has to forward the user to the IdP authentication page, it must be behind a TLS.  

I think it's a fair requirement to be able to interoperate with an internal IdP; what was suggested above should work, but I do not have bandwidth to set up such environment to test or make a guide.
