### ISSUE TITLE
unknown ingress.pomerium.io/kubernetes_service_account_token

### ISSUE THREAD

**Issue by aldiserg** [pomerium/pomerium#3812]
## What happened?
unknown ingress.pomerium.io/kubernetes_service_account_token
## What did you expect to happen?
parse ingress
## How'd it happen?

1. created ingress for kubeapi
2. add to annotations 
```
ingress.pomerium.io/kubernetes_service_account_token: edsfgfsdg...
```
3. apply ingress
4. run kubectl describe pomerium
5. see the error
```
Warning  UpdateError  3s (x20 over 4h)     pomerium-ingress  default/kubeapi: parsing ingress: annotations: unknown ingress.pomerium.io/kubernetes_service_account_token
```

## What's your environment like?

- Pomerium version is 0.20.0
- Kubernetes

**Comment by wasaga** [comment]
there is an error in docs, you cannot supply a secret data directly via annotation, it must be a reference to Kubernetes secret, with a `token` key, containing an actual token. 

the correct annotation key is `ingress.pomerium.io/kubernetes_service_account_token_secret`.

**Comment by aldiserg** [comment]
yeap, it's work. Thank you
