### ISSUE TITLE
Improve user experience when authenticate callback session expires

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#383]
## What happened?

A thing I experienced, is that
- after trying to log into a protected app
- when I am redirected to the IdP (google in this case)
- if I wait a bit too long to click on the account in the IdP login page
- when the IdP redirects to the auth callback, I get a `session has expired` error page from pomerium.

## What did you expect to happen?

I would expect that waiting 30 or 60 seconds should not provoke this kind of error. Maybe either increasing the expiration time or instead of showing the error to the user, he could be redirected again to the IdP?

I'm pretty sure sometimes users tries to log in, then they can get interrupted in their work, and when come back to their browser after a few minutes, they should be able to log in.
Right now, after seeing the error, refreshing the page only shows more new errors while the situation is not so exceptional.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): `pomerium/pomerium:PR382` from #382.
- Server Operating System/Architecture/Cloud: AKS/Google Identity

## What did you see in the logs?

```logs
{"level":"error","fwd_ip":["a.b.c.d"],"ip":"10.242.1.28","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0","referer":"https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=xxxxxx&as=xxxxxx&destination=https%3A%2F%2Fauth.corp.example.com&approval_state=xxxxx&oauthgdpr=1&xsrfsig=xxxx&flowName=GeneralOAuthFlow","req_id":"5a0fc2bd-ef62-cd37-39ad-4a6df5f8b9d6","error":"oauth callback : 400 Bad Request: internal/cryptutil: timestamp expired: internal/cryptutil: timestamp expired","http-message":"internal/cryptutil: timestamp expired","http-code":400,"time":"2019-11-11T09:35:05Z","message":"http-error"}
```

**Comment by desimone** [comment]
> I would expect that waiting 30 or 60 seconds should not provoke this kind of error.

Timestamp leeway is currently a minute, though we had some earlier discussion on [setting five vs one minute](https://github.com/pomerium/pomerium/pull/373#discussion_r342370571 ). 


For some context, I think the timeout constraint should roughly be align with oauth2's authorization code. [rfc6749#section-4.1.2](https://tools.ietf.org/html/rfc6749#section-4.1.2)

>          REQUIRED.  The authorization code generated by the
>          authorization server.  The authorization code MUST expire
>          shortly after it is issued to mitigate the risk of leaks.  A
>          maximum authorization code lifetime of 10 minutes is
>          RECOMMENDED. 
> The OAuth 2.0 spec recommends a maximum lifetime of 10 minutes, but in practice, most services set the expiration much shorter, around 30-60 seconds.

https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/


Though technically, the expiration you are seeing is not on the authorization code (returned as part of oauth2 flow) but on the signed redirect uri pomerium uses to set it's internal state and access tokens, the signed redirect url effectively acts as an authorization code 

I had been thinking it made sense to use consistent values for token leeway (to account for time-shift), but I hadn't considered that this time constraint was also

**Comment by victornoel** [comment]
> I think increasing this to five minutes is reasonable, as previously recommended by @travisgroth.

Could be a good idea yes, the problem with parameters is that it always depend on the situation, so there will never be a good value, I better like changing the user behaviour instead as you propose:

> This might actually be a bit trickier to pull off, but I agree. I worry that anytime we redirect on error, we are masking the error cause from the user. Perhaps an alternative is to still show the user an error, but including a link to restart the process?

Yes I agree with you, I don't like to hide errors, it's best that they bubble up and stay well visible :)

Indeed a link saying something like:
> This failed, try logging in again later

**Comment by victornoel** [comment]
@desimone another example where this can be useful to have some button/link saying "try again" would be great:
![image](https://user-images.githubusercontent.com/160975/69705377-ba7ce280-10f5-11ea-9650-5eb99d6af43e.png)

**Comment by desimone** [comment]
Agree. Also, yuck, it looks like `v0.5.x` branch has broken styles.  #392 should fix that but isn't in mainline yet.
