### ISSUE TITLE
Client IP is not masked by the Proxy

### ISSUE THREAD

**Issue by mohsen0** [pomerium/pomerium#384]
## What happened?
So there is a scenario that there are some services in a remote data center and the proxy is deployed in another data center. Some HTTP endpoints are exposed and using IP whitelisting and basic auth authentication, I have exposed the upstream service for the proxy to handle the authentication and authorization. 
 
## What did you expect to happen?

Strangely, Based on the whitelisting rules the requests are dropped because of the client IP is not the IP of proxy, it is IP of the client of proxy.
I was expecting the Proxy mask the IP of the client or IP of the client will be only set in the HTTP `X-forwared` or `X-real-ip` rather than like this.

Do you have any suggestions about how things can be done differently?
or the reasons this was implemented like this?

## What's your environment like?

- Pomerium version 0.4.2
- Server Operating System/Architecture/Cloud: Kubernetes cluster

**Comment by desimone** [comment]
Hi @mohsen0 !

> dropped because of the client IP is not the IP of proxy, it is IP of the client of proxy

I would not expect that. Can you tell me a little bit more about that? How are you checking for the requests client ip? 

I'm not sure how the proxy would be presenting the client IP. Is there any chance `X-Forwarded-For` is being used? 


> I was expecting the Proxy mask the IP of the client or IP of the client will be only set in the HTTP X-forwared or X-real-ip rather than like this.

We currently only add `X-Forwarded-Host`, and `X-Forwarded-For` but probably should / can add additional proxy fields like `X-Real-IP`/ `X-Forwarded-Proto` or even the newer [forwarded](https://tools.ietf.org/html/rfc7239) header. 

https://github.com/pomerium/pomerium/blob/f3c62c10cc1d7ee70b34c416ea1e51dc3feb4202/internal/httputil/proxy.go#L12-L31

**Comment by mohsen0** [comment]
Might be related to that, I am investigating this further today 
https://github.com/grafana/grafana/issues/16633

**Comment by mohsen0** [comment]
This was an issue with upstream Nginx configuration.
https://stackoverflow.com/questions/36268272/nginx-allowing-origin-ip
Thanks
