### ISSUE TITLE
Audiences in /.pomerium endpoint are truncated

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#385]
## What happened?

I went to a service protected via pomerium (with image from #382) and in the `/.pomerium` page, there is a list of audiences.

There are two of them: one is the authenticate service, the other is the protected app.

The strange thing is that the name of the elements is truncated at 30 characters.

If my app is on `my-app.some.sub.very-long-domain-name-example.com` and my authentication service is on `auth.another.very-long-domain-name-example.com`, then the two elements in the list are:
- `my-app.some.sub.very-long-doma`
- `auth.another.very-long-domain-`

## What did you expect to happen?

That the audience would contain the full dns name of the services.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): v0.4.2-dirty+891828f (from #382)

**Comment by desimone** [comment]
Thanks @victornoel !

Let me know what you think of #386

**Comment by victornoel** [comment]
@desimone 

> Thanks @victornoel !
> 
> Let me know what you think of #386

Yep it seems good :) I didn't understand it was just a css thing, easy to solve ;)
