### ISSUE TITLE
Enterprise does not allow full postgres connection strings for database_url

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3884]
## What happened?
Enterprise console requires PSQL, but is unable to connect to "complex" postgres connection strings e.g. for high-availability.

## What did you expect to happen?
successful connection to HA postgres cluster (multiple hosts in connection string)

## How'd it happen?

1. Ran console
2. Observed crashloop

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): `0.20.0` on Docker Swarm on Ubuntu

## What's your console-config.yaml?

```console-config.yaml
audience: console.localhost.pomerium.io
administrators: <>
database_encryption_key: <key>
databroker_service_url: pomerium://pomerium_pomerium:5443
database_url: postgres://pomerium:pomerium@pomerium_pg-0,pomerium_pg-1,pomerium_pg-2/pomerium?sslmode=disable&target_session_attrs=read-write
shared_secret_file: "/run/secrets/POMERIUM_SHARED_SECRET"
license_key: <key>
signing_key_file: "/run/secrets/POMERIUM_SHARED_SECRET"
authenticate_service_url: http://authenticate.localhost.pomerium.io
```

## What did you see in the logs?

```
pomerium_console.1.v2nl2pq13ixx@water    | {"level":"info","version":"0.20.0-1668477346+e3316e4f+2022-11-14T21:25:32Z","envoy_version":"1.23.1+274b19f370e43bf1a9100139d294f526e3ddda8f055d10c87dab1fce95f1b4b3","time":"2023-01-12T20:40:53Z","message":"cmd/pomerium-console"}
pomerium_console.1.v2nl2pq13ixx@water    | {"level":"fatal","error":"dial tcp: lookup pomerium_pg-0,pomerium_pg-1,pomerium_pg-2: no such host","time":"2023-01-12T20:40:53Z","message":"failed to get database"}
```

## Additional context

Works "fine" with Pomerium Core databroker (after https://github.com/pomerium/pomerium/issues/3634 was fixed)
```config.yaml
# Use HA PSQL databroker backend
databroker_storage_type: postgres
databroker_storage_connection_string: postgres://pomerium:pomerium@pomerium_pg-0,pomerium_pg-1,pomerium_pg-2/pomerium?sslmode=disable&target_session_attrs=read-write
```

**Comment by alexrudd2** [comment]
There's no problem with PSQL here; the console connects fine to a single host.  In other words, this string is fine:
`database_url: postgres://pomerium:pomerium@pomerium_pg-0/pomerium?sslmode=disable`

**Comment by alexrudd2** [comment]
I have a suspicion it's ignoring the user/pass part of the connection string and using hardcoded postgres/postgres, also.

**Comment by wasaga** [comment]
Console uses `lib/pq` to connect to Postgres, that does not support multiple hosts in the connection string. 

https://github.com/lib/pq/issues/683

**Comment by calebdoxsey** [comment]
We should see if we can use the other `pgx` driver. It's a little tricky because we support sqlite too so we depend on a different interface, but it might not be too hard to get it working.
