### ISSUE TITLE
Enterprise: Cannot bootstrap multiple administrators

### ISSUE THREAD

**Issue by alexrudd2** [pomerium/pomerium#3891]
## What happened?
I attempted to configure Console with multiple administrators in the YAML.  It appears to only accept the first one in the list, and even then only sometimes.

![Screenshot 2023-01-13 at 4 14 28 PM](https://user-images.githubusercontent.com/52292902/212429077-747d31dc-40fa-40b9-bba3-0d3aabe934d7.png)

## How'd it happen?

1. Started console with no other config and a single admin using inline YAML
2. Succeeded in accessing console
3. Restarted console with multiple admins
4. (usually) failed in accessing console

## What's your environment like?

- Pomerium version: Core `v0.19.0-28-g3b2cc672 + 3b2cc672`
Enterprise `0.20.0-1668477346 + e3316e4f + 2022-11-14T21:25:32Z`
Docker Swarm on Ubuntu
PSQL via `bitnami/postgresql-repmgr:15` only for Console (not shared with Core)

## What's your console-config.yaml?

```
audience: pomerium.<domain>.com
administrators: [admin-fail@domain.com] # fail

administrators: 
 - admin-maybe@domain.com. # sometimes works?
 - admin-fail@domain.com # never works

administrators: admin-success@domain.com # works
```

## What did you see in the logs?

```logs
{"level":"warn","error":"rpc error: code = PermissionDenied desc = at least the viewer role is required for GetSettings","grpc.duration":11.006482,"grpc.service":"pomerium.dashboard.SettingsService","grpc.method":"GetSettings","grpc.code":"PermissionDenied","grpc.request":{},"grpc.response":{},"grpc.details":[],"time":"2023-01-13T22:16:09Z","message":"finished unary call"}
```

## Additional context
[The docs ](https://www.pomerium.com/docs/releases/enterprise/install/quickstart#administrators )claim that multiple admins can be bootstrapped, but offer no examples of doing so.

**Comment by wasaga** [comment]
1. it does accept comma separated string
2. once your console is up, the recommended course of action is to 
 - set up IdP connection in Settings, so that users and groups would get synced
 - add administrators to the Global namespace via the UI
 - remove `administrators` from the config file.

**Comment by alexrudd2** [comment]
> 1. it does accept comma separated string. You cannot currently define it via array in Yaml config.

Thanks this worked.  I suggested adding it to the docs [here](https://github.com/pomerium/documentation/pull/256/files#r1072500737).  You can close this issue.

> 2. once your console is up, the recommended course of action is to
> 
> * set up IdP connection in Settings, so that users and groups would get synced
> * add administrators to the Global namespace via the UI
> * remove `administrators` from the config file.

At this point I expect to keep `administrators` in the config file forever.  If I rely on the GUI, recovery gets harder.
