### ISSUE TITLE
Cross-platform devices authentication allowed for enclave_only policed routes

### ISSUE THREAD

**Issue by youdzinn** [pomerium/pomerium#3909]
## What happened?
Cross-platform devices authentication allowed for enclave_only policed routes

## What did you expect to happen?
authentication is not possible with cross-platform devices for routes with enclave_only device matcher

## How'd it happen?
1. Registered my android phone as a cross-platform authenticator on `Devices info`  tab
2. Went to enclave_only policed route, clicked `Authenticate existing device`, chose a phone registered at the previous step
3. Saw proxied web resource without any error

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
pomerium: 0.20.0-1668445494+9413123c
envoy: 1.23.2+1308d65bf4b74dc691645ccc972af243c812de1742f3e741918b4f613be80e5f

as I can see, v0.21.0-rc1 dos not contain any code to prevent this issue
- Server Operating System/Architecture/Cloud:
Almalinux 9.1, Rockylinux 9.1

## What's your config.yaml?

```config.yaml
routes:
  - from: https://app1.pomerium.example.tld
    to: https://app1.example.tld
    policy:
      - allow:
          and:
            - device:
                type: enclave_only
```

## What did you see in the logs?
no error, 
```logs
{"level":"info","service":"authorize","request-id":"800a8be7-3f63-4738-b802-e4da13d438b9","check-request-id":"800a8be7-3f63-4738-b802-e4da13d438b9","method":"GET","path":"/","host"
:"app1.pomerium.example.tld","query":"","ip":"10.0.0.7","session-id":"93c15034-6172-4c81-8bf5-8611facbb0fe","allow":true,"allow-why-true":["device-ok"],"deny":false,"deny-why-false":[
"valid-client-certificate-or-none-required"],"user":"3c0869fe-1bc2-4957-b06f-6ba0f2623dc8","email":"j.doe@example.tld","time":"2023-01-20T16:13:12Z","message":"authorize check
"}

```

## Additional context

One doesn't simply register non-platform device from Authenticate page rendered after accessing route, protected by platform authenticators. Modal window appears with the `Your identity couldn't be verified` message since I didn't configured TPM yet on my laptop.

# Fix suggestions
Filter known device credentials by enclave_only type when accessing routes with enclave_only device matcher.
Naive solution attached below.
[fix_platform_authn.patch.txt](https://github.com/pomerium/pomerium/files/10468114/fix_platform_authn.patch.txt)

**Comment by desimone** [comment]
It makes sense that we should try to filter this list.
