### ISSUE TITLE
Policy reload does not seem to work anymore

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#393]
## What happened?

In a kubernetes-based deployment of v0.5.0 (using the helm chart), when I update the `ConfigMap` containing the pomerium config file with the policy and then try to connect to the newly added route, pomerium shows me a 404 error telling me `route unknown`.

Note that:
- only the `ConfigMap` changes so the `Deployment`s are not updated and the `Pod`s are not restarted
- the logs of the pomerium services correctly detect the config file change with a `config: checksum change` message

## What did you expect to happen?

That the reload of the config would make pomerium serve it seamlessly.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): v0.5.0
- Server Operating System/Architecture/Cloud: AKS

**Comment by desimone** [comment]
\cc @travisgroth  I've noticed this too. Probably something I broke 😬

**Comment by travisgroth** [comment]
👀

**Comment by travisgroth** [comment]
Interesting.  Debug logs during a policy change:

```json
{"level":"info","file":".pomerium.yaml","time":"2019-11-21T08:42:40-05:00","message":"cmd/pomerium: config file changed"}
{"level":"debug","old-checksum":"dcfcc383aee5a2c2","new-checksum":"3c2c8df729027033","time":"2019-11-21T08:42:40-05:00","message":"config: checksum change"}
{"level":"info","time":"2019-11-21T08:42:40-05:00","message":"authorize: updating options"}
{"level":"debug","route":"grafana.lan.beyondcorp.org:8443","domain":"beyondcorp.org","time":"2019-11-21T08:42:40-05:00","message":"add domain"}
{"level":"debug","route":"grafana2.lan.beyondcorp.org:8443","domain":"beyondcorp.org","time":"2019-11-21T08:42:40-05:00","message":"add domain"}
{"level":"info","time":"2019-11-21T08:42:40-05:00","message":"proxy: updating options"}
```
