### ISSUE TITLE
Access is allowed to the routes without a policy

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#3951]
## What happened?
Access is allowed to the routes without a policy. 

## What did you expect to happen?
Access should be forbidden for routes without policy.

## How'd it happen?
**Console**:
1. Open Pomerium Console -> Routes -> Create a new route without applied policy
2. Follow this route
Access allowed.

The Routes work well on

Core 0.21.0-rc2-1674858337 + e8004bbb
Enterprise v0.21.0-rc2 + 83c3cce5 + 2023-01-31T14:04:39Z

## What's your environment like?

Core v0.20.0-154-gf2adeada + f2adeada
Enterprise v0.20.0 + f630e07c + 2023-01-10T00:59:28Z

**Comment by wasaga** [comment]
This was tested in console.master-pgsql which 

A) confusingly reports itself as v0.20.0+... while it's version from 'main'
B) has an enforced policy to allow pomerium.com domain users that takes effect when no policy is set on a route
