### ISSUE TITLE
v0.21.0 Release procedure sent notification with unfilled changelog

### ISSUE THREAD

**Issue by eriksw** [pomerium/pomerium#3955]
## What happened?

People watching releases of `pomerium/pomerium` received a notification with "preparing changelog..." as the only change details.

![Screenshot 2023-02-10 at 07 27 36](https://user-images.githubusercontent.com/24530198/218130690-94100376-5cd2-46da-91e4-dba8d78adc86.png)

## What did you expect to happen?

The release was kept in draft status and not published until the changelog was fully written.

## How'd it happen?

I don't know!

## What's your environment like?

Subscribed to releases of `pomerium/pomerium` via GitHub.

![Screenshot 2023-02-10 at 07 30 51](https://user-images.githubusercontent.com/24530198/218131095-7557fb67-1728-4f12-92c3-3b92772f26ac.png)

## What's your config.yaml?

N/A

## What did you see in the logs?

N/A

## Additional context

This isn't a real bug, but filing this seemed to be the best way of giving a heads-up about the problem, because I didn't notice mention of it elsewhere.

**Comment by desimone** [comment]
Thanks! Going to close this but official channels will be updated on:

- https://www.pomerium.com/docs/releases

> ## Stay updated
> 
> [Pomerium-announce](https://groups.google.com/forum/#!forum/pomerium-announce) is a low traffic mailing list for important releases and security announcements.
