### ISSUE TITLE
generated certificates get re-generated anytime config changes

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#3985]
## What happened?

Any time the config is updated new certificates get generated, resulting in the user having to click through the insecure screen again.

## What did you expect to happen?

It would be nice if we could generate the certificate in a way where its the same even if the config changes.

## How'd it happen?
1. Use pomerium with a config that doesn't have a certificate
2. Visit a route with the self-signed certificate
3. Click the allow anyway button
4. Change something in the config (like add a new route)
5. Refresh and have to click the allow button again

## What's your environment like?
- Pomerium version: b62efeb16ca87325cfa0f6dcc24cee844941201e

**Comment by desimone** [comment]
Let's create a stable certificate generated from `shared_secret` and as a follow up make sure this works with console.

**Comment by calebdoxsey** [comment]
Deterministically generating or re-using the certificates does not prevent being re-prompted. It appears to ask anytime a new connection is made. Therefore we would need to apply envoy changes without severing existing connections.

**Comment by calebdoxsey** [comment]
Actually it  might work. I am seeing certs change seemingly randomly. Something like 50% of the time I get one fingerprint and 50% of the time a different one. Maybe there's some element of the cert generation which is not deterministic.

**Comment by calebdoxsey** [comment]
Oh, it's not deterministic. 😢 https://cs.opensource.google/go/go/+/refs/tags/go1.20.1:src/crypto/ecdsa/ecdsa.go;l=249

**Comment by desimone** [comment]
https://www.rfc-editor.org/rfc/rfc6979

**Comment by desimone** [comment]
Sorry, I'm sniping from the side here but can we use `Ed25519` instead of `ECDSA` for signatures?  `Ed25519` is deterministic.
https://cryptobook.nakov.com/digital-signatures/eddsa-and-ed25519
