### ISSUE TITLE
Devices info in the User info page

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#4001]
## Question

Should  Device Credentials be displayed in User Info even if these enrollments were deleted from Console -> Devices?
## How'd it happen?

1. Open Console -> Devices
2. Delete all devices
![Screenshot from 2023-02-21 12-51-58.png](https://images.zenhubusercontent.com/63bc6de617e71f0442fdda1c/3550aa46-c71c-4372-b59e-1210f5933c23) 

3. Open the User info page https://verify.domain/.pomerium/  -> Devices Info
![Screenshot from 2023-02-21 12-53-05.png](https://images.zenhubusercontent.com/63bc6de617e71f0442fdda1c/d6b39ad3-aa55-42c3-9cd3-25ef3cf48b1b)

## What's your environment like?
Core
0.21.1-1676583956 + 26d76501
Enterprise
0.21.0-1676045406 + 53d6bf83 + 2023-02-09T22:09:46Z

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by desimone** [comment]
We should try to clean up the associated device records (even though they are disassociated and effectively tombstone'd).
