### ISSUE TITLE
Could add output logs to file?

### ISSUE THREAD

**Issue by SakaZhang** [pomerium/pomerium#4004]
**Is your feature request related to a problem? Please describe.**
Sometime we need to logrotate logfiles and collect it .If run pomerium with docker/podman this way, collect logs is difficult when we don't use loki/ELK...

**Describe the solution you'd like**
Maybe add configure like LOGFILE=/var/log/pomerium.log in config.yaml...
Actually, i'm doing this...
```
// DisableDebug tells the logger to use stdout and json output.
func DisableDebug() {
    logFile, err := os.OpenFile("/var/log/pomerium.log", os.O_APPEND|os.O_CREATE|os.O_RDWR, 0600)
    if err != nil {
        fmt.Println("Create logfile failed. err: ", err)
        os.Exit(8)
    }

    l := zerolog.New(logFile).With().Timestamp().Logger()
    SetLogger(&l)
    zapLevel.SetLevel(zapcore.InfoLevel)
    defer logFile.Close()
}

**Comment by desimone** [comment]
Hey @SakaZhang 

We'd prefer to keep this logic out of core since many other tools exist in the ecosystem and provide greater control over log output, storage, and rotation.  The particular tool depends on your environment.

**Comment by SakaZhang** [comment]
Thanks reply. Maybe i will rebuil it every time when pomerium release a new version.
