### ISSUE TITLE
databroker: pg URL scheme not supported for URLs

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#4050]
## What happened?
Connection strings like `pg://postgres` are not currently supported. Only `postgres` or `postgresql` are supported. Ideally we should support all of the following:

- `pg`
- `postgres`
- `postgresql`
- `px`
- `pgx`
- `pgsql`

## What did you expect to happen?

For a connection string like `pg://postgres` to work.

**Comment by wasaga** [comment]
they all are non-standard schemes, no?

> The URI scheme designator can be either postgresql:// or postgres://

https://www.postgresql.org/docs/current/libpq-connect.html#:~:text=The%20URI%20scheme%20designator%20can%20be%20either%20postgresql%3A//%20or%20postgres%3A//

**Comment by desimone** [comment]
I propose we:

1. Support all the connection strings (non-breaking change and probably the least user hostile)
2. Only support the official URI schema, and fail on any unrecognized scheme (explicit failure, possibly breaking)
