### ISSUE TITLE
Cookie session not invalidated when deauthenticated

### ISSUE THREAD

**Issue by xlejo** [pomerium/pomerium#4063]
## What happened?

When I logout from SSO, Pomerium let me access the service anyway.

## What did you expect to happen?

When I logout from SSO, Pomerium MUST invalidate the cookie session and prohibit the 
access. Then, if I login again, Pomerium must generate another cookie (or use the same cookie 
previously invalidated?).

## How'd it happen?

1. Install mkcert, docker and docker-compose.
2. Download [pomerium_cookie_issue.zip](https://github.com/pomerium/pomerium/files/10986557/pomerium_cookie_issue.zip), decompress and change directory to the root of the docker-compose.yml.
3. Ensure in your hosts file the next line:
    - `127.0.0.1 nginx.localhost.example.tld auth.localhost.example.tld keycloak.localhost.example.tld nextcloud.localhost.example.tld`
4. Run the followed commands:
    - `mkcert -install` (skip if was already initialized)
    - `mkdir certs && cd certs && mkcert "*.localhost.example.tld"` 
    - `cp "$(mkcert -CAROOT)/rootCA.pem" . && cd ..`
    - `docker-compose up -d`
5. Open a Private browsing and access to https://nextcloud.localhost.example.tld. Credentials of Keycloak and Nextcloud is admin and admin.
6. Open the Network Monitor (Ctrl+Shift+E on Firefox Linux).
7. From behind, open a tab and logout to SSO going to https://keycloak.localhost.example.tld/realms/master/account/.
8. Return to the Nextcloud tab and wait a few minutes you will see 401 responses.
9. Now, reload the page and you will navigate another minutes more (until the cookie expires).

## What's your environment like?

- Pomerium version v0.21.2
- Server Operating System/Architecture/Cloud: Fedora 37 (Docker 20.10.23)

## What did you see in the logs?

Attached in the zip (grep `/realms/pomerium/protocol/openid-connect/logout` for the moment of the logout).

## Additional context

- I put https://nextcloud.localhost.example.tld for test a fetch app (check that after a while, the connection is denied) and https://nginx.localhost.example.tld a simple static webserver. You will see the same behaviour on both services. 
- If you login again, the cookie session stay invalidated having to clear cookies.

## Attachment

[pomerium_cookie_issue.zip](https://github.com/pomerium/pomerium/files/10986557/pomerium_cookie_issue.zip) (updated with client configured with front-channel logout)

**Comment by xlejo** [comment]
Nice. The problem with that is that if I as the Administrator want to desactive a user, the user will still access to the service (until the cookies expires). Is the expected behaviour?

**Comment by calebdoxsey** [comment]
The authorize service maintains a local cache of sessions. The expected behavior is access for up to a few minutes before the session no longer works. But this requires deleting the session in Pomerium. If the remote session is deleted it would depend on the identity provider, but if refreshing the access token fails, the session will be deleted. But refreshing the access token is not done frequently.

**Comment by xlejo** [comment]
Yes, I noticed that Pomerium refreshes the access code from time to time.

```
# docker-compose logs pomerium | grep -i refresh
pomerium_1   | {"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","time":"2023-03-16T18:29:40Z","message":"refreshing user"}
pomerium_1   | {"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","time":"2023-03-16T18:39:40Z","message":"refreshing user"}
pomerium_1   | {"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"e545e7c5-9637-4ebc-8a86-3c8922014027","time":"2023-03-16T18:46:56Z","message":"refreshing session"}
pomerium_1   | {"level":"error","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","error":"identity/oidc: refresh failed: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"e545e7c5-9637-4ebc-8a86-3c8922014027","time":"2023-03-16T18:46:56Z","message":"failed to refresh oauth2 token, deleting session"}
pomerium_1   | {"level":"info","record-type":"type.googleapis.com/pomerium.events.LastError","record-id":"identity_manager_last_session_refresh_errors","time":"2023-03-16T18:46:56Z","message":"put"}
pomerium_1   | {"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"b3967c1c-341b-410b-8ca7-4e497b896af1","time":"2023-03-16T18:47:36Z","message":"refreshing session"}
pomerium_1   | {"level":"error","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","error":"identity/oidc: refresh failed: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"b3967c1c-341b-410b-8ca7-4e497b896af1","time":"2023-03-16T18:47:36Z","message":"failed to refresh oauth2 token, deleting session"}
pomerium_1   | {"level":"info","record-type":"type.googleapis.com/pomerium.events.LastError","record-id":"identity_manager_last_session_refresh_errors","time":"2023-03-16T18:47:36Z","message":"put"}
pomerium_1   | {"level":"info","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"0dee4558-4723-4a7a-a782-7143fc7b7821","time":"2023-03-16T18:48:36Z","message":"refreshing session"}
pomerium_1   | {"level":"error","config_file_source":"/pomerium/config.yaml","bootstrap":true,"service":"identity_manager","error":"identity/oidc: refresh failed: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Token is not active\"}","user_id":"b0738d60-ef2d-437f-9041-b506602012e3","session_id":"0dee4558-4723-4a7a-a782-7143fc7b7821","time":"2023-03-16T18:48:36Z","message":"failed to refresh oauth2 token, deleting session"}
pomerium_1   | {"level":"info","record-type":"type.googleapis.com/pomerium.events.LastError","record-id":"identity_manager_last_session_refresh_errors","time":"2023-03-16T18:48:36Z","message":"put"}
```

The problem is that it says it clears the session when in fact I can continue browsing if I reload the page :(

**Comment by wasaga** [comment]
please see https://www.pomerium.com/docs/releases/enterprise/about#session-management

**Comment by desimone** [comment]
Immediate session revocation is an enterprise feature. You can revoke the session on the identity provider side, but as @calebdoxsey mentioned the effect of that on Pomerium's side (and any OIDC based app really) will only be enforced on session refresh which is variable but usually around ~15-45 minutes for most identity providers. But is configurable on the identity provider sides.

 Feel free to re-open if you have any questions or issues.

**Comment by desimone** [comment]
Immediate session revocation is an enterprise feature. You can revoke the session on the identity provider side, but as @calebdoxsey mentioned the effect of that on Pomerium's side (and any OIDC based app really) will only be enforced on session refresh which is variable but usually around ~15-45 minutes for most identity providers. But is configurable on the identity provider sides.

 Feel free to re-open if you have any questions or issues.
