### ISSUE TITLE
`Access-Control-Allow-Origin` error on authenticate service

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#409]
## What happened?

I'm experimenting a strange and problematic situation, I suppose it is since v0.5.0 because I've never seen that before.

At first it seemed similar to #390 but this one is about the pomerium service not answering CORS correctly.

Basically what happens is something like this:
- An SPA is making XHR calls without problems (with the `X-Requested-With` header)
- at one point, one of the request is considered as needing reauth by the proxy
- so the proxy returns a redirect response toward the authenticate service
- the browser tries to validate this can be done with OPTIONS
- we get the following error in the browser:
```
Access to XMLHttpRequest at 'https://auth.example.com/.pomerium/sign_in?redirect_uri=https%3A%2F%2Fapp.example.com%2Fapi%stuff%2F10&sig=nSjPGT0tgnrsizrhZnWZZ0WvYSI_Zyy0UaMXkY-vdtg%3D&ts=1574843825' (redirected from 'https://app.example.com/api/stuff/10') from origin 'https://app.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

## What did you expect to happen?

It seems to me that it is authenticate that does not answer CORS requests while I think it should.

## Environment

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): v0.5.0
- Server Operating System/Architecture/Cloud: AKS

## What did you see in the logs?

The logs are not very clear about what happens

authenticate
```logs
{
    "level": "info",
    "fwd_ip": [
        "86.234.73.194"
    ],
    "ip": "10.242.1.28",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0",
    "referer": "https://app.example.com/optimize/stuff/10",
    "req_id": "08388fd6-6fcb-99e4-075a-12f4c86c4189",
    "error": "internal/sessions: session is not found",
    "time": "2019-11-27T08:32:05Z",
    "message": "authenticate: verify session"
}
{
    "level": "debug",
    "fwd_ip": [
        "86.234.73.194"
    ],
    "ip": "10.242.1.28",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:70.0) Gecko/20100101 Firefox/70.0",
    "referer": "https://app.example.com/optimize/stuff/10",
    "req_id": "08388fd6-6fcb-99e4-075a-12f4c86c4189",
    "duration": 0.227797,
    "size": 841,
    "status": 302,
    "email": "",
    "group": "",
    "method": "GET",
    "service": "authenticate",
    "host": "auth.example.com",
    "path": "/.pomerium/sign_in?redirect_uri=https%3A%2F%2Fapp.example.com%2Fapi%2Fstuffs%2F10&sig=oMLbIJX2xjMf2-YkzmZgCrdDYBJSSR5IDdxv7blDN_o%3D&ts=1574843525",
    "time": "2019-11-27T08: 32: 05Z",
    "message": "http-request"
}
{
    "level": "debug",
    "fwd_ip": [
        "109.220.184.108"
    ],
    "ip": "10.242.0.22",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
    "referer": "https://app.example.com/optimize/stuff/10",
    "req_id": "54dd9be1-43d9-65c4-16b6-f7ab64ba348e",
    "duration": 0.308897,
    "size": 0,
    "status": 200,
    "email": "",
    "group": "",
    "method": "OPTIONS",
    "service": "authenticate",
    "host": "auth.example.com",
    "path": "/.pomerium/sign_in?redirect_uri=https%3A%2F%2Fapp.example.com%2Fapi%2Fstuffs%2F10&sig=1bga3DYmFYiNUea7g_Fk4uTkeic7G34dOeWlt9eJWAM%3D&ts=1574843638",
    "time": "2019-11-27T08: 33: 58Z",
    "message": "http-request"
}
```

**Comment by desimone** [comment]
@victornoel Is `cors_allow_preflight: true` enabled for this particular route?

**Comment by victornoel** [comment]
> @victornoel Is `cors_allow_preflight: true` enabled for this particular route?
> 
> Perhaps related: #387

It's not, I can try, but I thought it was about letting CORS going through to the protected app, not so that the pomerium service answers OPTIONS…

**Comment by desimone** [comment]
Just curious. From your logs it looks like the authentication service is responding with a `200` to the `OPTIONS` request.  So I am a little confused why the browser is seeing no `Access-Control-Allow-Origin`. 

Would it be possible to generate a `HAR` file for this flow?

**Comment by victornoel** [comment]
> Just curious.

Yep, I'm trying to reproduce with it right now but of course with my sessions, there is no refresh happening :)

> From your logs it looks like the authentication service is responding with a `200` to the `OPTIONS` request. So I am a little confused why the browser is seeing no `Access-Control-Allow-Origin`.

Because it's not enough to answer 200, the response must contains some headers saying it accept any origin, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

> 
> Would it be possible to generate a `HAR` file for this flow so I can see what your browser is seeing?

If I can reproduce, yes no problem :)

**Comment by victornoel** [comment]
@desimone just sent you a HAR on slack :)

For the record `cors_allow_preflight: true` has no effect.

**Comment by victornoel** [comment]
@desimone any way to get this included in v0.6.0? This is quite worrying… :)

**Comment by desimone** [comment]
@victornoel I'm having trouble replicating the issue. 

When I try a cors request locally ( `/`) or directly to the authentication endpoint ( so long as the hmac is valid), the request flows as expected and the incoming request ACAO is as I would expect.

For some context, here's how we are currently handle CORS from authenticate point of view.

https://github.com/pomerium/pomerium/blob/74cd9eabbbe1e9094025d33a65b21b6e62461bc8/authenticate/handlers.go#L44-L50

So as long as the sign in request originates from pomerium's proxy, we trust it. 

Here's my HAR file. 
[cors.imac.bdd.io.har.zip](https://github.com/pomerium/pomerium/files/3913160/cors.imac.bdd.io.har.zip)

On of the challenges is testing. As far as I can tell there's not "httpbin" but for XHR/Single page Applications so I've been manually testing using https://github.com/monsur/test-cors.org.

**Comment by victornoel** [comment]
@desimone damned, I didn't think it would be this complex to reproduce :/

The one different thing I see is that in your case, the `Access-Control-Request-Method` is `OPTIONS` while in my case, it's the original `PATCH` method that is being tested via CORS.

**Comment by desimone** [comment]
Unfortunately, I think there is more going on here than I initially realized. I'm working hard to solve this entire class of issue (SPA problems  when trying to do a session refresh without breaking the app). 

Stay tuned. :)

**Comment by nitper** [comment]
I just wanted to chime in to say that I'm experiencing the same thing since upgrading from `0.4.2`->`0.5.2`

I have a page hosted at `site.corp.example.com` which makes an AJAX request to `a.corp.example.com`


when the AJAX call requests `a.corp.example.com`, pomerium redirects via 302 to `https://auth.corp.example.com/.pomerium/sign_in?pomerium_expiry=12345&pomerium_issued=12345&pomerium_redirect_uri=https%3A%2F%2Fa.corp.example.com&pomerium_signature=abcde`

The browser does not follow the 302 and instead errors with:
```
Access to XMLHttpRequest at 'https://a.corp.example.com/' from origin 'https://site.corp.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This was working smoothly for the most all the way through `0.4.2` execpt for a couple expiration quirks that I think #416 will solve.

**Comment by nitper** [comment]
Maybe my issue is actually #390 since I'm not seeing an OPTIONS request as mentioned by @victornoel

**Comment by desimone** [comment]
@nitper 

By any chance does the image `pomerium/pomerium:ISS409v1` fix the issues for you?

**Comment by desimone** [comment]
@nitper / @victornoel : this should fix `xhr` based refresh on master. `docker pull pomerium/pomerium:master` via #438 

🤞 let me know!

**Comment by victornoel** [comment]
@desimone thx, I will test it next week I think :)

**Comment by victornoel** [comment]
@desimone at least things seem to work normally with latest master, but I don't exactly know how to properly test this.

I guess that now there are no redirects anymore, I have to time my requests so that they happen after my session (with pomerium) has expired: do you have some idea of how long should I wait during my tests before two requests so that refresh is triggered?

**Comment by victornoel** [comment]
@desimone actually, there is at least a case where it doesn't work because of CORS.

This is what happens:
- a PATCH request is sent by the SPA
  - the cookie is included, I believe containing an expired session
  - there is NO header `X-Requested-With` (this is a bug in our app, but still, I don't think it should be a problem at that point IMHO)
- pomerium answers with a 302 to the authenticate service on `/sign_in`
- the browser sends an OPTIONS request
- pomerium answers as if it was a POST request instead of answering with the expected headers for CORS validation
- the browser refuses to continue

I think pomerium should answers correctly to OPTIONS whatever the situation.

I will continue to test to see how it behave with the `X-Requested-With` header being test and get back to you.

**Comment by victornoel** [comment]
@desimone I tried with the header, and it seemed to have worked as expected, but I'm not sure it was exactly the same situation of course.

Is there a different refresh behaviour if the header is present? I would have expected that with or without the header, the new flow depicted in #438 (i.e., no redirect at all from the client pov) would have been used, but as experimented in https://github.com/pomerium/pomerium/issues/409#issuecomment-571983030, there was a redirect to `/sign_in` without the header…

**Comment by desimone** [comment]
Thanks for testing @victornoel !

> at least things seem to work normally with latest master 

Great!

> there is NO header X-Requested-With (this is a bug in our app, but still, I don't think it should be a problem at that point IMHO

Agree. The backend refresh should just work now regardless of request type. 

> pomerium answers with a 302 to the authenticate service on /sign_in

Do you recall what the redirect location was? 




> but I don't exactly know how to properly test this.

> do you have some idea of how long should I wait during my tests before two requests so that refresh is triggered?

I've created a custom docker image that have session timeouts set at 30 or so seconds. Hopefully that helps speed up testing, and surface any problems! 

`pomerium/pomerium:PR446v2` 
`sha256:367335e7261a34c89027a11432a8b4ffeb6bcd8ef53734bf0870259cb8d94823`

> Is there a different refresh behaviour if the header is present?

There should not be. However, what I think may be going on is that #438 only fixed refresh for all-in-one and single instances of authenticate services. If you have multiple replicas of authenticate, you would need to use #446 which hopefully will be merged in soon. 

If you are using a multiple replicas of authenticate, you can use the above image and set `authenticate_internal_service_url` (... I know 😢 ) to whatever your internally routable DNS is for the authenticate service similar to authZ today.

**Comment by victornoel** [comment]
@desimone 
> Do you recall what the redirect location was?

It was on the authenticate public url with the path `/.pomerium/sign_in`.

> I've created a custom docker image that have session timeouts set at 30 or so seconds. Hopefully that helps speed up testing, and surface any problems!

For the record I'm using only one instance of each pomerium service.

Still, I tried this image with the shorter timeout: with and without the header present, the refresh behind the scene seems to happens as expected.

So all seems to be ok, and I don't know why I got a browser redirect last time I tried without a header… maybe the session couldn't be refreshed and I got redirected to `sign_in` instead of answering 401 because the header wasn't present?

I would thus conclude that:
- pomerium should answers correctly CORS OPTIONS requests on its own endpoints (even though in the SPA use case with the header there should be no such requests)
- pomerium behave as expected in the SPA use case as long as there is the header (and without the header, well, there is nothing that can be done)

**Comment by desimone** [comment]
> Still, I tried this image with the shorter timeout: with and without the header present, the refresh behind the scene seems to happens as expected.

Good!

> So all seems to be ok, and I don't know why I got a browser redirect last time I tried without a header… maybe the session couldn't be refreshed and I got redirected to sign_in instead of answering 401 because the header wasn't present?

Perhaps there was another error, unrelated to refresh. That could also result in a redirect. 

I'm going to close this for now then. If anything regresses, lmk.
