### ISSUE TITLE
Google as Identity Provider does not work (HTTP 502)

### ISSUE THREAD

**Issue by Gamewalker** [pomerium/pomerium#4097]
## What happened?
If I use Github as identity provider then everything works without any problems. As soon as I switch to Google and use them as below, I get an HTTP 502 error after selecting my account for login.

## What did you expect to happen?
I should be authenticated with my google account

## How'd it happen?

1. start pomerium
2. use google as provider
3. access any url
4. login with google
5. get redirected into 502

## What's your environment like?
Pomerium running on unraid behind a nginx proxy manager

## What's your config.yaml?

```config.yaml
# See detailed configuration settings: https://www.pomerium.com/docs/reference/

authenticate_service_url: https://xxx

cookie_secret: xxx
shared_secret: xxx

insecure_server: false
autocert: false

##################################################################################
# Identity provider settings : https://www.pomerium.com/docs/identity-providers/ #
# The keys required in this section vary depending on your IdP. See the          #
# appropriate docs for your IdP to configure Pomerium accordingly.               #
##################################################################################
idp_provider: "google"
idp_client_id: "xxx.apps.googleusercontent.com"
idp_client_secret: "xxx"

# Update the signing key: https://www.pomerium.com/docs/reference/signing-key
signing_key: xxx
```

## What did you see in the logs?

```logs
2023-04-03T23:28:01+02:00 INF http-request | service=envoy upstream-cluster=pomerium-control-plane-http method=GET authority=auth.home.xxx path=/.pomerium user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 referer=https://auth.home.xxx/oauth2/callback forwarded-for=84.175.173.103,10.0.0.102 request-id=fd8031e4-8130-43a8-9940-09c73b89893c duration=69.15819 size=413 response-code=302 response-code-details=via_upstream 
2023-04-03T23:28:03+02:00 ERR undefined 
2023-04-03T23:28:03+02:00 INF http-request | service=envoy upstream-cluster=pomerium-control-plane-http method=GET authority=auth.home.xxx path=/oauth2/callback user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 referer=https://accounts.google.com/ forwarded-for=84.175.173.103,10.0.0.102 request-id=6d132c9d-d413-42f1-b6b4-704405976850 duration=452.370298 size=58 response-code=302 response-code-details=via_upstream 
```

## Additional context

could be the same as this: https://github.com/pomerium/pomerium/issues/4076

**Comment by ssveta7ak** [comment]
Hi @Gamewalker, did you configure Google IdP as described in the documentation  https://www.pomerium.com/docs/identity-providers/google ? What Pomerium version do you use? It's strange because I run Pomerium with Google Idp and your config.yaml and everything works well.

```
authenticate_service_url: https://authenticate.localhost.pomerium.io

idp_provider: 'google'
idp_client_id: 'xxx'
idp_client_secret: 'xxx'

cookie_secret: xxx
shared_secret: xxx
signing_key:  xxx

insecure_server: false
autocert: false

routes:
  - from: https://test.localhost.pomerium.io
    to: https://httpbin.org
    allow_any_authenticated_user: true
    pass_identity_headers: true

```

**Comment by desimone** [comment]
@Gamewalker  -- What are your `nginx` header size defaults? My guess is that Pomerium's redirect urls might be exceeding the default which I believe is 4 or 8K from memory. 

Can you share your nginx manager config?

**Comment by Gamewalker** [comment]
@desimone you are the man.

added 
`    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;`

to the auth config and its working fine now

**Comment by timawesomeness** [comment]
If anyone experiences a similar issue using Apache, add a larger `responsefieldsize` to your ProxyPass line and increase the maximum URL length:

    ProxyPass / http://xxx responsefieldsize=32768
    LimitRequestLine 32768
