### ISSUE TITLE
authorize: only allow specific users to access routes

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium#41]
Is possible to implement 
`ALLOWED_USERS`
logic in disjuction to:
`ALLOWED_DOMAINS`
?
I would like to allow access only to specific users.

For example:
`ALLOWED_DOMAINS=foo.bar@example.com,liz.ard@domain.io`

It should be self-explanatory.

Thanks

**Comment by desimone** [comment]
Thanks for the feature request, @lukasmrtvy . Fine grained, per route, user authorization is absolutely something we have planned but I haven't had a chance to write up. I'll likely reference this issue in a follow up issue.

**Comment by desimone** [comment]
Added in #57
