### ISSUE TITLE
Unable to connect to websocket server

### ISSUE THREAD

**Issue by tommyskg** [pomerium/pomerium#412]
## What happened?

I am unable to connect using websockets on current master from a client using Gorilla websockets. The connection fails upon ``ws, err := upgrader.Upgrade(w, r, nil)`` . It looks quite similar to the issue encountered in #77.

## What did you expect to happen?

Websockets connects as expected. 

## How'd it happen?

1. Deployed Pomerium from master
2. Tried to connect to application trough browsing with Chrome and Safari, which work
3. Connect to server in background with javascript
4. Added a proxy from https://test.local to localhost:<port>
5. Demo fails to successfully establish connection with server backend
6. Direct connection to the server works

## What's your environment like?

* Pomerium version: v0.5.0-dirty+edba21e
* Server Operating System/Architecture/Cloud: macOS 10.15.1

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://localhost
pomerium_debug: true
service: all

idp_provider: google
idp_client_id: <redacted>
idp_client_secret: <redacted>
shared_secret: <redacted>
cookie_secret: <redacted>
signing_key: <redacted>

certificate_file: "/usr/local/etc/pomerium/server.crt"
certificate_key_file: "/usr/local/etc/pomerium/server.key"

insecure_server: false
allow_websockets: true

policy:
  - from: https://test.local
    to: http://localhost:3000
    allow_public_unauthenticated_access: false
    allowed_domains:
        - gmail.com
```

## What did you see in the logs?

```logs
ERR http: proxy error: can't switch protocols using non-Hijacker ResponseWriter type *http.timeoutWriter
```

**Comment by desimone** [comment]
Hi @tommyskg  -- thanks for the detailed issue.

I think I know what's going on. `allow_websockets` is a [route-based, not global](https://www.pomerium.io/configuration/#policy). So in your config... 

```diff
authenticate_service_url: https://localhost
pomerium_debug: true
service: all

idp_provider: google
idp_client_id: <redacted>
idp_client_secret: <redacted>
shared_secret: <redacted>
cookie_secret: <redacted>
signing_key: <redacted>

certificate_file: "/usr/local/etc/pomerium/server.crt"
certificate_key_file: "/usr/local/etc/pomerium/server.key"

insecure_server: false
-allow_websockets: true

policy:
  - from: https://test.local
    to: http://localhost:3000
    allow_public_unauthenticated_access: false
+    allow_websockets: true
    allowed_domains:
        - gmail.com
```

**Comment by tommyskg** [comment]
Hello @desimone - such a quick reply! 

That was a simple solution. It worked just as you said. Is there perhaps some way to clarify this in the debug message that is shown?

**Comment by desimone** [comment]
> That was a simple solution. It worked just as you said. Is there perhaps some way to clarify this in the debug message that is shown?

Unfortunately not at the moment.
