### ISSUE TITLE
Log isn't pure JSONL; includes some differently formatted "OCSP staple" lines

### ISSUE THREAD

**Issue by drewp** [pomerium/pomerium#4133]
## What happened?

I get occasional log lines like this:

`1.6824372849188025e+09	info	maintenance	advancing OCSP staple	{"identifiers": ["bigasterisk.com"], "from": 1682737198, "to": 1683039598}`

## What did you expect to happen?

It's nicer when all log lines are json documents. Then one can pipe to jq for pretty printing, etc.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):

Logs say this: `"pomerium_version": "v0.0.0 linux/amd64 "`

K8s deployment says my image is `pomerium/ingress-controller:sha-2c8038a`

- Server Operating System/Architecture/Cloud:

ubuntu/22.10 x86_64 selfhosted

## What's your config.yaml?

https://bigasterisk.com/code/pomerium/files/9bff6004bd605ee0d835e1b39b7ab00ff3ba6149/20-kube/10-pom-pom.yaml
https://bigasterisk.com/code/pomerium/files/9bff6004bd605ee0d835e1b39b7ab00ff3ba6149/20-kube/20-pom-deploy.yaml

**Comment by calebdoxsey** [comment]
I believe these log lines are coming from [certmagic](https://github.com/caddyserver/certmagic/blob/15a8b4f4c5a11fcf8a410b93d0bdb111b1096b48/maintain.go#L343). We should configure certmagic to use our logger.
