### ISSUE TITLE
How to deploy Pomerium behind existing proxy?

### ISSUE THREAD

**Issue by rajaseg** [pomerium/pomerium#4136]
**Is your feature request related to a problem? Please describe.**

I am trying to deploy Pomerium behind our existing Proxy server. I didn't find proper documentation to achieve this.

**Describe the solution you'd like**

As per the architecture, Pomerium is consists of 4 services. i.e., ```authenticate``` ```authorize``` ```databroker``` or ```proxy```
I want to deploy the ```authenticate``` ```authorize``` and ```databroker``` services using ```docker-compose``` behind existing proxy ```caddy```

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

I already running ```Caddy``` reverse proxy in our docker swarm environment and wanted to use Pomerium behind it.

**Comment by desimone** [comment]
Hey @rajaseg ,

Typically, we suggest folks put Pomerium at their edge of their deployments. Pomerium is backed by envoy, is at feature parity with products like Caddy (and probably faster). Alternatively, you could configure caddy / your load balancer to be a layer 4 pass through to send traffic directly to your Pomerium proxy. 

We used to support "forward-auth" style deployments for third party proxies like nginx / traefik, but the delta in functionality became too large to support all those deployments.

Hope that helps.
