### ISSUE TITLE
Pomerium v0.22.0 asking users for Certs 

### ISSUE THREAD

**Issue by jake-babcock** [pomerium/pomerium#4150]
## What happened?
When routing to anything specified in routes, it would prompt the user for a certificate before the webpage would load. Client_CA and associated parameters aren't set in `config.yaml`
## What did you expect to happen?
Pomerium not asking for certifications.
## How'd it happen?
Upgraded the docker image to v0.22.0

## What's your environment like?

- Pomerium v0.22.0
- Ubuntu 22.04LTS

## What did you see in the logs?

Nothing in the logs showed it prompting for a certificate prompt as it was happening before a user would hit the webpage. 

## Additional context

I know this has been a reocurring issue in some versions. Just wanted to report it again in case it has reoccured. I haven't been able to recreate the issue since rolling back the docker image version to v0.21

**Comment by calebdoxsey** [comment]
Do you have your route definitions?

**Comment by calebdoxsey** [comment]
Likely the same issue as https://github.com/pomerium/pomerium/issues/852 .

**Comment by desimone** [comment]
@jake-babcock  -- we just cut v0.22.1 to (hopefully) address this. Can you give it a try?

https://github.com/pomerium/pomerium/releases/tag/v0.22.1

**Comment by drewp** [comment]
Appears to be fixed in my case with the newest IC version.
