### ISSUE TITLE
Pomerium headers present in response

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#418]
## What happened?

The various `x-pomerium-authenticated-user-email` and other pomerium headers are present in the response when sending a request through pomerium.

## What did you expect to happen?

I didn't expect those to be present there, I thought they were only added in the request for the protected backend to access them.

I didn't think so much about it but isn't that a leak of potentially private information such as the groups or even the user id? Just asking, I'm not very clear about that, maybe it's totally fine :)

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): v0.5.0
- Server Operating System/Architecture/Cloud: AKS

**Comment by victornoel** [comment]
Some extra thoughts:
- they could have been added by our own backend, I'm not 100% clear on that…

**Comment by desimone** [comment]
Hi @victornoel We add [those headers](https://www.pomerium.io/docs/reference/getting-users-identity.html) to the response (mostly for forward-auth compatibility) and request headers. 

I don't think of them as being sensitive (the user can already see these fields in their cookie JWT). Did you have a specific concern I could be overlooking?

**Comment by victornoel** [comment]
@desimone ah, that's the doc I must have read and that made me think that maybe it was unwanted, the phrasing there is:
> By default, pomerium passes the following response headers to it's downstream applications to identify the requesting users.

So I focused on `downstream applications to identify the requesting users` and thought it wasn't wanted that the response sent to the user would contain those headers.

I don't see any problem with it, I just thought it wasn't maybe desired, so I preferred to ask :))

> I don't think of them as being sensitive (the user can already see these fields in their cookie JWT).
By the way, I don't see the `x-pomerium-iap-jwt-assertion` in the response, only the three other, is that desired?

**Comment by desimone** [comment]
@victornoel 

> I don't see any problem with it, I just thought it wasn't maybe desired, so I preferred to ask :))

No worries, always better to ask 👍 


> By the way, I don't see the x-pomerium-iap-jwt-assertion in the response, only the three other, is that desired?

If you have [signed headers enabled](https://www.pomerium.io/docs/reference/signed-headers.html) I would expect to see the assertion.

**Comment by victornoel** [comment]
@desimone ah ok, I suppose I needed `SIGNING_KEY` to be set for the jwt to be generated, which is not the case for my deployment.

Thanks, I'm closing this now :)
