### ISSUE TITLE
oidc: the LogOut URL is never invoked unless a pomerium_redirect_url parameter is set

### ISSUE THREAD

**Issue by wasaga** [pomerium/pomerium#4180]
## What happened?

Currently, 

https://github.com/pomerium/pomerium/blob/e245107d246d4447d8db7f763044506960995b41/authenticate/handlers.go#L260-L278

would only invoke the LogOut URL if

- [`signout_redirect_url`](https://www.pomerium.com/docs/reference/routes/signout-redirect-url) global parameter is set, or
- `pomerium_redirect_url` query parameter is added to `/.pomerium/sign_out` 

## What did you expect to happen?

The logout URL should be invoked if there is no redirect parameter provided. The parameter `post_logout_redirect_uri` is defined as **OPTIONAL** by the [front-line logout spec](https://openid.net/specs/openid-connect-rpinitiated-1_0.html). 

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`):
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by desimone** [comment]
Let's try to retain the current behavior but fix the issue of not hitting the IdP's signout url, by:

1. If `urlutil.QueryRedirectURI` and `options.GetSignOutRedirectURL` are unset, we default to setting `redirectString` to a simple go handler on the authenticate service that tells the user they have been logged out.
2. We always redirect to `authenticator.LogOut`
