### ISSUE TITLE
pass_identity_headers should default to true

### ISSUE THREAD

**Issue by calderonth** [pomerium/pomerium#4197]
**`pass_identity_headers` defaults to `false`**

Downstream services integrated with Pomerium are supposed to validate the JWT assertion to be really secure against unauthenticated/unauthorized access.
However, the current way to do this means setting the value of `pass_identity_headers` to `true` for every single route/policies.

This feels like a wrong decision that goes against secure by default principle and the behavior should be changed the other way around.

**Describe the solution you'd like**
`pass_identity_headers` default to `true`

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**
N/A

**Comment by calderonth** [comment]
Yes that would be great, would naming the variable `global_pass_identity_headers` be less confusing that re-using an existing variable name?

**Comment by desimone** [comment]
In retrospect, we probably should have named all global variables `global_*`, but to be consistent with how other global/route settings operate we use the same key name.

**Comment by calebdoxsey** [comment]
This option has been added and will be available in the next release.
