### ISSUE TITLE
Programmatic access allowlist feature not working as expected

### ISSUE THREAD

**Issue by calderonth** [pomerium/pomerium#4198]
## What happened?
The programmatic access redirect feature offers an allowlist behavior that doesn't seem accurate.
This is described in the documentation as:

```
Note: By default only localhost URLs are allowed as the pomerium_redirect_uri.
This can be customized with the programmatic_redirect_domain_whitelist option.
```

Instead of allowing a domain, the code actually perfoms a hostname check againt the entries in the list.

## What did you expect to happen?
If I set `programmatic_redirect_domain_whitelist` to a domain, say `example.com` then all valid hosts/subdomains should be accepted to work when passed as a `pomerium_redirect_uri`. For instance `devmachine.example.com` should be allowed.

## How'd it happen?

1. Set a `pomerium_redirect_uri` to a domain
2. Attempt the programmatic access
3. Saw error `400`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 0.22
- Server Operating System/Architecture/Cloud: Running in K8s

## What's your config.yaml?
N/A

## What did you see in the logs?
N/A

## Additional context
Code check performed here: https://github.com/pomerium/pomerium/blob/main/internal/urlutil/whitelist.go#L16-L18
Clearly doing a hostname comparions as opposed to attempting to do a math on the domain.

**Comment by desimone** [comment]
We should be more explicit in our docs to say we exact match on the hostname. 

I think we are matching on the correct level here for our security model; we aimed to model this after oauth2/oidc's redirect_url parameter.
