### ISSUE TITLE
help wanted: google group authorization not working

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium#421]
I have turned on POMERIUM_DEBUG. I have a Google service account set up per instructions. 

I see the group in the Pomerium configmap. 

I see the email group being added in the authorize log.

When I attempt to access a proxies service it works IF my email is on the authorized users list.  However, if my email is not (but is one of the emails in an authorized google group) it does not authorize.

I do not see authorization requests. 

Is there any way to get more insight into why my (Google) group authorization is not working?

**Comment by desimone** [comment]
Hi @derrickburns, 

My hunch is that there is a configuration issue (fetching google groups requires a fair deal more setup than the other providers, and requires an additional service account) and may be failing on startup. Do you see anything in the logs from the authenticate service on startup regarding groups?
 
If the service account is being registered properly, I'd expect to see user groups included on authentication for that user in the logs. And should be present session jwt. 

If you can provide (sanitized) logs that could help me better debug. 

Hope that helps.

**Comment by derrickburns** [comment]
Ah, I was looking in the `authorize` service.

I do see:
```
{"level":"warn","time":"2019-12-12T06:04:18Z","message":"identity/google: no service account, cannot retrieve groups"}
```
However, I do have the YAML describing a service account in the secret.  I will try to debug..

**Comment by derrickburns** [comment]
I didn' t set this helm chart value: 
```
authenticate.idp.serviceAccount: true
```
All working now.  Thx.

**Comment by desimone** [comment]
> All working now. Thx.

great!

**Comment by derrickburns** [comment]
The only thing confusing is that what i considered an `authorization` error was reported in the `authenticate` service logs.

**Comment by desimone** [comment]
Agree. In the near term i plan to move group membership to authz
