### ISSUE TITLE
autocert / OCSP stapling errors are shown when autocert is not enabled

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#4245]
## Got

OCSP stapling errors are shown even when autocert is not enabled.  My understanding is our autocert and ocsp code is deeply coupled. This often creates user confusion when our users aren't actually using autocert

## Want

Ideally, we should de-couple OCSP functionality from our autocert stack.

Less ideally, we should not present confusing error messages to our users. 

### Related

- https://github.com/pomerium/pomerium/issues/193
- https://github.com/pomerium/pomerium/issues/4133
- https://github.com/pomerium/pomerium/issues/1946
_Originally posted by @wasaga in https://github.com/pomerium/ingress-controller/issues/658#issuecomment-1585319120_

**Comment by calebdoxsey** [comment]
The linked issues have no apparent relationship to this issue.

We cannot de-couple OCSP functionality from autocert. It's a core piece of functionality in certmagic and AFAIK not a feature we want to remove.
