### ISSUE TITLE
config: CookieRefresh option is not used

### ISSUE THREAD

**Issue by danderson** [pomerium/pomerium#428]
## What happened?

While writing documentation on Pomerium's cookie settings, I found that CookieRefresh seems to be unused. It's declared and set to a default of `30m`, but the field is not referenced anywhere else in the Pomerium codebase.

**Comment by desimone** [comment]
@danderson Good catch. I think this can be simply removed.

**Comment by desimone** [comment]
Fixed by @u5surf in #436 . Thank you !
