### ISSUE TITLE
Websocket error with linkerd dashboard

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium#430]
## What happened?

I cannot get the linkerd dashboard live stream of calls to work. I get "websocket error: undefined`.

## What did you expect to happen?

I expect to see a stream of calls to my service.  I see the live stream if I port-forward. I do not see the live stream if I proxy with pomerium.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
v0.5.1
- Server Operating System/Architecture/Cloud:
 K8s Rev: v1.14.9-eks-ba3d77

## What's your config.yaml?

```config.yaml
apiVersion: v1
data:
  config.yaml: "policy: \n  - allow_websockets: true\n    allowed_groups:\n    - eng@tidepool.org\n
    \   allowed_users: []\n    from: https://glooe-monitoring.production.tidepool.org\n
    \   to: http://glooe-grafana.gloo-system.svc.cluster.local\n  - allow_websockets:
    true\n    allowed_groups:\n    - eng@tidepool.org\n    allowed_users: []\n    from:
    https://linkerd-dashboard.production.tidepool.org\n    to: http://linkerd-dashboard.linkerd.svc.cluster.local:8080\n"
kind: ConfigMap
metadata:
  annotations:
    flux.weave.works/antecedent: pomerium:helmrelease/pomerium
  creationTimestamp: "2019-12-12T18:50:52Z"
  labels:
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-4.1.2
  name: pomerium
  namespace: pomerium
  resourceVersion: "26735217"
  selfLink: /api/v1/namespaces/pomerium/configmaps/pomerium
  uid: 525ccabf-1d10-11ea-abeb-02c077500bb6
```

**Comment by desimone** [comment]
@derrickburns What do does your browser console logs look like? Do you mind posting a (sanitized) HAR file?

**Comment by derrickburns** [comment]
<img width="1572" alt="Screen Shot 2019-12-24 at 10 37 18 AM" src="https://user-images.githubusercontent.com/583930/71422775-6d7b2600-2639-11ea-9e0d-e47f5f27f8a5.png">

**Comment by derrickburns** [comment]
[redacted.txt](https://github.com/pomerium/pomerium/files/3998910/redacted.txt)

**Comment by derrickburns** [comment]
<img width="679" alt="Screen Shot 2019-12-24 at 10 55 27 AM" src="https://user-images.githubusercontent.com/583930/71423136-00b55b00-263c-11ea-8962-2d56b71685e8.png">

**Comment by desimone** [comment]
Copying [comment](https://github.com/pomerium/pomerium/pull/438#issuecomment-569750666) from #438 
![](https://user-images.githubusercontent.com/583930/71594181-c50f0b00-2aeb-11ea-80c5-4cee065e2365.png)

This does look like a different issue going on now. The google redirect from [the previous comment](https://github.com/pomerium/pomerium/issues/430#issuecomment-568791325) looks much more like #390 or #409 .  

I have a few websocket applications in my home lab and don't have this issue 🤔 ...

It's a little hard to tell from the har file what's actually going on with the sockets unfortunately. 
Does it happen immediately on first login (fails to connect at all?) or does it happen after a period of time?

**Comment by derrickburns** [comment]
The problem appears to occur immediately upon access to a link that uses web sockets.

**Comment by derrickburns** [comment]
@desimone
Can I sidestep these issues by using pomerium in a forward auth configuration with the Gloo API gateway?

**Comment by desimone** [comment]
@derrickburns  Sorry I haven't had a chance to try this out for myself. 

- Following initial pomerium login, are other server assets loading (e.g. robots.txt/favicon / other pages) and it's just the websocket connection that is failing?  From your har file, it looks like all non-`wss` requests are loading fine. I don't see the `wss` requests but that is probably just a limitation of `har` and websockets. 
- By any chance is the request going across domain boundaries?
- If the `403` is coming from pomerium, there will be an extra header value `x-pomerium-intercepted-response`, do you see that there? 
- The most recent screenshot shows a bunch of warnings related to the new changes related to the new [SameSite](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) enforcement rules coming in pomerium. I don't see any (nor should there be on master) anymore CORS related errors from pomerium and redirects to your IDP. 


> Can I sidestep these issues by using pomerium in a forward auth configuration with the Gloo API gateway?

It could, I haven't experimented with Gloo personally, so I couldn't really say.

**Comment by derrickburns** [comment]
The request is not going across domain boundaries.

Here is what I see for the request.  I do not see a response.

```

Provisional headers are shown
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Cookie: _ga=GA1.2.206260213.1573835266; _pomerium=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aGVudGljYXRlLnFhMS50aWRlcG9vbC5vcmciLCJsaW5rZXJkLWRhc2hib2FyZC5xYTEudGlkZXBvb2wub3JnIl0sImVtYWlsIjoiZGVycmlja0B0aWRlcG9vbC5vcmciLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNTc4NTk1ODU3LCJmYW1pbHlfbmFtZSI6IkJ1cm5zIiwiZ2l2ZW5fbmFtZSI6IkRlcnJpY2siLCJncm91cHMiOlsiYWRtaW4tdG9vbHNAdGlkZXBvb2wub3JnIiwiYWxlcnRzQHRpZGVwb29sLm9yZyIsImVtcGxveWVlc0B0aWRlcG9vbC5vcmciLCJlbmdAdGlkZXBvb2wub3JnIiwiZW5naW5lZXJpbmctYWRtaW4tdG9vbHNAdGlkZXBvb2wub3JnIl0sImlhdCI6MTU3ODU5MjI1OCwiaXNzIjoiYXV0aGVudGljYXRlLnFhMS50aWRlcG9vbC5vcmciLCJuYW1lIjoiRGVycmljayBCdXJucyIsIm5iZiI6MTU3ODU5MjI1OCwicGljdHVyZSI6Imh0dHBzOi8vbGg0Lmdvb2dsZXVzZXJjb250ZW50LmNvbS8tUnhKNUYwX3A4VmsvQUFBQUFBQUFBQUkvQUFBQUFBQUFBQUEvQUNIaTNyZWJ2N3ZOaGFELXpPSFVRX3hKUk8tN2RVUmV3QS9zOTYtYy9waG90by5qcGciLCJwcm9ncmFtYXRpYyI6ZmFsc2UsInN1YiI6IjEwMDA3NjQ5OTk4MTUzODEyODYyMCJ9.Z3cGb1uV-jcI3eRqLEJKzEQJzE8EPXTmXjv0jKBOIdE
Host: linkerd-dashboard.qa1.tidepool.org
Origin: https://linkerd-dashboard.qa1.tidepool.org
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: nr3kq0T0ompViviQ9aw3zw==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
```

**Comment by derrickburns** [comment]
I think this may be a configuration issue with my API gateway....

**Comment by desimone** [comment]
@derrickburns I was about to ask if you had any other infrastructure items between the user, pomerium, and the downstream application.

For example, I know that (pomerium aside) running websockets behind nginx requires some [extra markup](https://www.nginx.com/blog/websocket-nginx/).

PS. I removed the pomerium cookie you above response. Though there are no access tokens in there, I just wanted to be on the safe side.

**Comment by derrickburns** [comment]
@desimone FYI: https://docs.solo.io/gloo/latest/changelog/open_source/#v1-2-11

**Comment by desimone** [comment]
@derrickburns Did that fix it for you?

**Comment by derrickburns** [comment]
Unfortunately, no.

**Comment by derrickburns** [comment]
I presume that I only need websocket support in the connection that flows through the pomerium proxy.

**Comment by desimone** [comment]
@derrickburns 

 - Do you mind posting pomerium logs?
- if you expand that websocket connection error from your browser console, what does it show? 

Just thinking aloud here, that `403`  is very peculiar as there isn't a codepath in pomerium that returns a `403` directly. Based on the connection handshake error, I almost want to say this could be certificate related.

**Comment by derrickburns** [comment]
I think that linkerd is stopping the websocket request:

```
 time="2019-12-22T03:32:20Z" level=error msg="websocket: 'Origin' header value not allowed"
```


```
Origin Considerations
Web browsers allow Javascript applications to open a WebSocket connection to any host. It's up to the server to enforce an origin policy using the Origin request header sent by the browser.

The Upgrader calls the function specified in the CheckOrigin field to check the origin. If the CheckOrigin function returns false, then the Upgrade method fails the WebSocket handshake with HTTP status 403.

If the CheckOrigin field is nil, then the Upgrader uses a safe default: fail the handshake if the Origin request header is present and the Origin host is not equal to the Host request header.

The deprecated package-level Upgrade function does not perform origin checking. The application is responsible for checking the Origin header before calling the Upgrade function.
```

**Comment by desimone** [comment]
@derrickburns I got an email update, but don't see that post here. Is that a github-snafu or did you delete the post intentionally?

**Comment by derrickburns** [comment]
I deleted the post. Red herring.

**Comment by derrickburns** [comment]
<img width="973" alt="Screen Shot 2020-01-14 at 10 58 43 AM" src="https://user-images.githubusercontent.com/583930/72373304-db58c180-36bc-11ea-97c2-e49f0aad4afd.png">

Expanded view.

**Comment by derrickburns** [comment]
[pomerium-logs.txt](https://github.com/pomerium/pomerium/files/4060943/pomerium-logs.txt)

**Comment by derrickburns** [comment]
<img width="521" alt="Screen Shot 2020-01-14 at 11 29 26 AM" src="https://user-images.githubusercontent.com/583930/72375566-283e9700-36c1-11ea-9eb6-a24f8f0268f9.png">

Configuration.

**Comment by derrickburns** [comment]
Here is the log from the linkerd dashboard. I suspect this is the source of the 403.

```
time="2020-01-14T19:36:08Z" level=error msg="websocket: 'Origin' header value not allowed"                                                                                                               2020/01/14 19:36:08 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:59)
```

**Comment by derrickburns** [comment]
Problem SOLVED!

I had my gateway remove the `Origin` header BEFORE the request is passed to the Pomerium Proxy.

**Comment by desimone** [comment]
Good to hear! Sounds like there is nothing to follow up on the pomerium side?

**Comment by derrickburns** [comment]
I think we can close this.  Thx for you support!

**Comment by peter-hs** [comment]
> Problem SOLVED!
> 
> I had my gateway remove the `Origin` header BEFORE the request is passed to the Pomerium Proxy.

@derrickburns how did you do this? I'm encountering this same issue though I can't figure out how to get pomerium to strip the origin header.
