### ISSUE TITLE
Enable global `timeout_read` for Kubernetes

### ISSUE THREAD

**Issue by leonardochen** [pomerium/pomerium#4317]
**Is your feature request related to a problem? Please describe.**

Our application uses POST to upload files. Pomerium is timing out with 408 if the upload takes more than 30s.
I think we're hitting the `timeout_read` limit described in the [documentation](https://www.pomerium.com/docs/reference/global-timeouts)

Unfortunately Kubernetes deployments does not support changing these parameters.

**Describe the solution you'd like**

Allow modification of global timeouts for Kubernetes

**Describe alternatives you've considered**

We will need to modify client and server to upload file in parts. We can't control the bandwidth available for customers when they are uploading files. 

**Explain any additional use-cases**

Although 30s is a reasonable default, a user with upload speeds of 20Mbps (typical cable package in the US 😑) would be limited to uploading a 75MB file.

**Additional context**

**Comment by wasaga** [comment]
Please install from main:

kubectl apply -k github.com/pomerium/ingress-controller/config/default\?ref=main

In the CRD, please set timeouts:
 read: "30m"

**Comment by leonardochen** [comment]
I tried applying the following:
```
apiVersion: ingress.pomerium.io/v1
kind: Pomerium
spec:
  ... other values
  storage:
    postgres:
      secret: pomerium/postgresdb
  timeouts:
    read: 30m
```

And received an error
```
# pomerium.ingress.pomerium.io "global" was not valid:
 strict decoding error: unknown field "spec.timeouts"
```

I applied the `kubectl` command as suggested and I'm from main
```
~ » k get pod -o yaml | grep image
      image: pomerium/ingress-controller:main
      imagePullPolicy: Always
      image: docker.io/pomerium/ingress-controller:main
      imageID: docker.io/pomerium/ingress-controller@sha256:025570a41e4c67146f6801d99404edac8677434308b259406af49f16bd3e4e25
```

**Comment by leonardochen** [comment]
I just noticed that the CRD files do not have the timeouts. The only references for timeouts are for `refreshDirectory`
`customresourcedefinition.apiextensions.k8s.io/pomerium.ingress.pomerium.io`

**Comment by leonardochen** [comment]
I think I got it working by providing the 3 values to the pomerium CRD 🎉
```
  timeouts:
    idle: 5m
    read: 180s
    write: 300s
```

I was not able to set `write` to its default value of `write_timeout: 0`, but twice as read should be ok.

**Comment by calebdoxsey** [comment]
This was an ingress controller issue. It was fixed with https://github.com/pomerium/ingress-controller/pull/750.
