### ISSUE TITLE
logging: add ability to get the real client IP (`X-Real-Ip`, `Forwarded`, `X-Forwarded-For`

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#4377]
###  Is your feature request related to a problem? Please describe.**

Sometimes the upstream server or and auditor may need to know the original IP address of the connection, called the downstream remote address, for many reasons. Some examples include:

- the IP address being used to form part of an identity,
- the IP address being used to enforce network policy, or
- the IP address being included in an audit.

Currently we log:

https://github.com/pomerium/pomerium/blob/8e4f728c11473c70b20710390487b4c19a14cca1/internal/controlplane/grpc_accesslog.go#L42

###  **Describe the solution you'd like**

We should support a way get the _original_ and ideally _trusted_ source client IP of the connecting user (e.g. the originating downstream connection IP).  Typically this is done either with the : [x-forwaded-for](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for) header and/or the [X-Real-Ip](https://stackoverflow.com/questions/72557636/difference-between-x-forwarded-for-and-x-real-ip-headers) header. 

We should support passing the following as headers and logging the
-  `x-forwarded-for` (what everyone seems to use, includes all the hops, has security subtleties around trust)
- `x-real-ip` what most people are looking for with an edge proxy. Have to be careful in multi-hop situations. 
-  `forwarded` (the RFC one that no one seems to use)

### Considerations

> Since it is easy to forge an X-Forwarded-For field the given information should be used with care. The right-most IP address is always the IP address that connects to the last proxy, which means it is the most reliable source of information. X-Forwarded-For data can be used in a forward or reverse proxy scenario. If the server is behind a trusted [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy) and only allows connections from that proxy, the header value can usually be assumed to be trustworthy.

We will likely need to also configure the [number of trusted hops](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/http/original_ip_detection/xff/v3/xff.proto) to make sure this is implemented in a secure manner. 

We may also want or need to expose use_remote_address since most often Pomerium will be the edge proxy. 

### Related issues

- https://github.com/pomerium/pomerium/issues/3678

### Additional 

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-original-ip-detection-extensions
- https://en.wikipedia.org/wiki/X-Forwarded-For
- https://datatracker.ietf.org/doc/html/rfc7239
- https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
- http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by desimone** [comment]
Adding @kenjenkins comment since I couldn't convert the issue.

I think the Envoy equivalent of X-Real-Ip is the `DownstreamRemoteAddress`:[^1]

> 	// This field is the remote/origin address on which the request from the user was received.
>	// Note: This may not be the physical peer. E.g, if the remote address is inferred from for
>	// example the x-forwarder-for header, proxy protocol, etc.

(from https://github.com/envoyproxy/go-control-plane/blob/ffd91e13c8391024da6638719026cfb599ce15e5/envoy/data/accesslog/v3/accesslog.pb.go#L463-L466)

[^1]: This in contrast to the [`DownstreamDirectRemoteAddress`](https://github.com/envoyproxy/go-control-plane/blob/ffd91e13c8391024da6638719026cfb599ce15e5/envoy/data/accesslog/v3/accesslog.pb.go#L530-L533). I find Envoy's terminology very confusing here.

We could log this in addition to the current fields, somewhere in here: https://github.com/pomerium/pomerium/blob/26bbcdfe07a81204b4357b15998e2fe152f7669f/internal/controlplane/grpc_accesslog.go#L36-L43.

**Comment by calebdoxsey** [comment]
It's not clear to me what this issue is asking for. Logging headers was already implemented, so I am interpreting this issue to mean that we should add an access logging field `"ip"` that will log the `DownstreamRemoteAddress`.

**Comment by calebdoxsey** [comment]
I think my interpretation of this issue is likely incorrect. Unfortunately I don't know what the requirements are for this issue.

In particular Pomerium is intended to act as an edge proxy with untrusted downstream connections. This is incompatible with using Nginx in front of Pomerium and adding x-forwarded-for headers. The documentation is confusing, but we would need to disable `use_remote_address` in this case to trust those headers to derive the IP address. I can make this change if that's what's desired, but I think it's a security vulnerability and very likely incorrect.

If the ask is to expose this is as another configuration option than I guess we can do that instead.

I'm sorry I'm not an expert on nginx so referencing those options isn't helpful for me because I have never used them so I don't know what is the desired outcome of the feature.

**Comment by calebdoxsey** [comment]
Logging the ip was implemented in #4391.
