### ISSUE TITLE
logging: add option to log a request's query string to access log

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#4378]
### Problem

For some of our users, it is required to include a `uri`'s `query` and `fragment` in access logs.

```
         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
```

### Solution

We should provide a user configurable way to log query params and fragments. 

### Considerations

- Query params _can_ contain sensitive data. 
- This should be optional. see [REQ_WITHOUT_QUERY](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto)
- Ideally this would also be configurable on a route basis but I'm not sure that's possible. 
- Envoy's implementation is odd in that it's included in a request's path 

### Related issues

- https://github.com/pomerium/pomerium/pull/1894

### Prior art

- https://nginx.org/en/docs/http/ngx_http_log_module.html
- https://datatracker.ietf.org/doc/html/rfc3986#section-3
- https://projectcontour.io/docs/main/config/access-logging/
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto

**Comment by calebdoxsey** [comment]
FWIW, AFAIK the `fragment` is not sent to servers.

**Comment by calebdoxsey** [comment]
This has been implemented.
