### ISSUE TITLE
telemetry/trace: middleware spans should not wrap the entire request flow

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#440]
## What happened?

Middleware spans currently wrap the entire request body. While this makes sense from the point of view of how go middleware chains works, it makes it very difficult to deduce how long each middleware span is actually taking.

## What did you expect to happen?

Middleware spans should close prior to wrapping the next handler or middleware. 

For example. 

```diff
// SetHeaders sets a map of response headers.
func SetHeaders(headers map[string]string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx, span := trace.StartSpan(r.Context(), "middleware.SetHeaders")
-			defer span.End()
			for key, val := range headers {
				w.Header().Set(key, val)
			}
			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
```
```diff
// SetHeaders sets a map of response headers.
func SetHeaders(headers map[string]string) func(next http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ctx, span := trace.StartSpan(r.Context(), "middleware.SetHeaders")
			for key, val := range headers {
				w.Header().Set(key, val)
			}
+ 		      span.End()

			next.ServeHTTP(w, r.WithContext(ctx))
		})
	}
}
```
<img width="1376" alt="Screen Shot 2019-12-28 at 7 37 42 PM" src="https://user-images.githubusercontent.com/1544881/71552043-8c671880-29a9-11ea-9315-7551e2b6d24c.png">

**Comment by cuonglm** [comment]
@desimone is this issue still the case?

https://github.com/pomerium/pomerium/pull/444#issuecomment-634741772

**Comment by desimone** [comment]
I think we can close this.
