### ISSUE TITLE
Browser indicates connection as insecure for the routes with IdP per route.

### ISSUE THREAD

**Issue by ssveta7ak** [pomerium/pomerium#4483]
## What happened?
I tested IdP per route with Pomerium v0.23 (binaries). I used `mkcert` server certificates.
When I open `https://httpbin.localhost.pomerium.io` route - the browser indicates the connection as secure.
![Screenshot from 2023-08-23 10-59-39](https://github.com/pomerium/pomerium/assets/37595288/87b0e168-3f07-4b40-a223-651ed599a9bf)

When I open `https://httpbin.sveta.sandbox.pomerium.io` route - the browser indicates the connection as **insecure**

![Screenshot from 2023-08-23 11-02-20](https://github.com/pomerium/pomerium/assets/37595288/c99da059-da73-4d49-b8f2-059105b572d3)

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?
Core
v0.20.0-473-g3e330bb7 + 3e330bb7

Enterprise
v0.22.0 + 714e77f2 + 2023-08-04T23:47:44 + 01:00

## What's your config.yaml?

```config.yaml
authenticate_service_url: https://authenticate.localhost.pomerium.io
certificate_file: /home/sveta/certificates/_wildcard.localhost.pomerium.io.pem
certificate_key_file: /home/sveta/certificates/_wildcard.localhost.pomerium.io-key.pem
certificate_authority_file: /home/sveta/certificates/rootCA.pem

idp_provider: 'auth0'
idp_provider_url: 'https://dev-idkio16ws02jgfvl.us.auth0.com'
idp_client_id: 'VDSqEnPGFuHfPf5N58Nz85f2CANuGNF6'
idp_client_secret: 'STtVafavxysGBYxh3_PKGFDtzeqLJB-AHp0gV4tujjh_II_RFgACNC6dlB5IJ39Q'

cookie_secret: PpjkuZFgEjdNPMBMO7pdawir2hQ2vedbBKL2bjk1PEk=
shared_secret: +rbqgXoaMvU2EcMoUye12i3i12xsQcNrar6ZKr5C2yM=
metrics_address: 127.0.0.1:9091
signing_key:  <>

databroker_storage_type: postgres
databroker_storage_connection_string: postgresql://postgres:postgres@localhost:5432/database2?sslmode=require

routes:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin.org
    allow_any_authenticated_user: true
    pass_identity_headers: true
 
  - from: https://httpbin.sveta.sandbox.pomerium.io
    to: https://httpbin.org
    idp_client_id: 'eEPNrj8f7MgiD54wfI2bbXzkdZe0xj2z'
    idp_client_secret: '9MWMkKEr4WQ32Km4hnadT17iiI_wS9v72ytCGI45KS2ZSH939TFUXM-9aKWY5Zm4'
    allow_any_authenticated_user: true
    pass_identity_headers: true

```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by calebdoxsey** [comment]
Did you run mkcert with both names?

```bash
mkcert '*localhost.pomerium.io' '*.sveta.sandbox.pomerium.io'
```

**Comment by ssveta7ak** [comment]
@calebdoxsey  Thank you, you are right, with `*.sveta.sandbox.pomerium.io` certificate everything works well. 
I close this issue.
