### ISSUE TITLE
forward auth: extract host and path from headers

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium#451]
Your current design for forward auth requires that the client create a URL specialized for the authorization request that includes the host and path.  

Instead, why not simply grab those values from the HTTP headers `:authority` and `:path`? 

Then your solution would work with Envoy based proxies that simply forward auth requests to the auth service.

One backward compatible way to do this is to use the headers if there is no `uri` query parameter.

------

Separately, I am working on performing the URL rewrite with the Gloo API Gateway.  Gloo provides
a VirtualService abstraction that can route based on host and headers, among other things. It also provides a way to use the Envoy extauth feature.  

The model is simple.  One enables external authorization on a VirtualService. One identifies a Kubernetes service to send requests to.  Gloo forwards the original request to the named Kubernetes service.

With the current Pomerium implementation of forward auth, this does not quite work.  I need to rewrite the URL to add the host and path to the query.

With Gloo, one can rewrite a URL and append headers.  So, what I do is add a header to the authorization request.  I deploy a second Gloo virtual service for each service to be authenticated that matches requests with the additional header.  When the virtual service matches, it rewrites the URL as needed by Pomerium, i.e. it changes the DNS name to `externalauth.domain.example` and appends the proper query parameter `?uri=...`.

**Comment by msm595** [comment]
Likewise, for Traefik I believe you could use `X-Forwarded-Proto` and `X-Forwarded-Host`

**Comment by branchmispredictor** [comment]
Likewise, for Traefik I believe you could use `X-Forwarded-Proto` and `X-Forwarded-Host`

**Comment by branchmispredictor** [comment]
@derrickburns, as it stands my PR likely doesn't cover your usecase, but if you can provide an example of the headers and their values in your usecase, I can add them.
