### ISSUE TITLE
jwtClaimHeaders throws an exception for claim, contains list of uuids with size of 87 elements

### ISSUE THREAD

**Issue by paintkeeper** [pomerium/pomerium#4540]
## What happened?
2023-09-14T10:58:36.951621843Z {"level":"info","service":"envoy","upstream-cluster":"____-ingress-development-____-api-v1-85625da22e81139f","method":"GET","authority":"some.host","path":"/some/path","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15","referer":"","forwarded-for":"some.ip","request-id":"f8560550-789b-4c32-8d08-cf75b8f6ac9e","duration":9.965187,"size":0,"response-code":400,"response-code-details":"via_upstream","time":"2023-09-14T10:58:36Z","message":"http-request"}

## What did you expect to happen?
{"level":"info","service":"envoy","upstream-cluster":"_____-ingress-development-_____-api-v1-5b52a2979c07716d","method":"GET","authority":"some.host","path":"/some/path","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15","referer":"","forwarded-for":"some.ip","request-id":"bf9cb0bc-1ae0-474f-99e7-382346cd647c","duration":0,"size":12347,"response-code":101,"response-code-details":"upstream_reset_after_response_started{connection_termination}","time":"2023-09-13T18:07:55Z","message":"http-request"}

## How'd it happen?
I have a JWT with a claim, which contains list of uuids.
I'm using  jwtClaimHeaders: parameter to move this list into header
I have tested this on couple of tokens with different list size:
when list size was 52 elements, list was extracted and delivered inside header
with list size of 87 elements, pomerium just throws 400 http error
Connection to application did not happen

Have not checked exact claim size, when exception starting to appear

After removing jwtClaimHeaders, environment stabilized 

## What's your environment like?

- Pomerium 0.22.x, 0.23.0
- Kubernetes Ingress controller all-in-one
- Client connected to websocket

## What's your config.yaml?

jwtClaimHeaders  is an issue

**Comment by wasaga** [comment]
you're exceeding maximum request size that _your upstream application is willing to process__ . request headers become too large and its rejected by your upstream application, not by pomerium.

**Comment by paintkeeper** [comment]
thats, true, thanks for pointing
