### ISSUE TITLE
ingress controller on K3S don't turn ready due to invalid certificate

### ISSUE THREAD

**Issue by rgrente** [pomerium/pomerium#4586]
Hello,

## What happened?

Ingress controller pod on K3S can't turn ready.
It seems to have a problem with an expired certificate, but i can't found which one.
K3S and pomerium certs seems to be valid

## What did you expect to happen?

Ingress controller turn ready

## How'd it happen?

When my working K3S cluster start, all services run, but pomerium ingress controller don't turn ready.
Killing ingress controller pod don't fix the problem

## What's your environment like?

- K3S 1.24.3
- Pomerium 32.0.4

## What's your config.yaml?

```config.yaml
autocert: false
dns_lookup_family: V4_ONLY
address: :443
grpc_address: :443
certificate_authority_file: "/pomerium/ca/ca.crt"
certificates:
authenticate_service_url: https://authenticate.***
authorize_service_url: https://pomerium-authorize.pomerium.svc.cluster.local
databroker_service_url: https://pomerium-databroker.pomerium.svc.cluster.local
idp_provider: auth0
idp_scopes: 
idp_provider_url: https://***
idp_client_id: ***
idp_client_secret: ***
idp_service_account: ***
databroker_storage_tls_skip_verify: false    
routes:
```

## What did you see in the logs?

Ingress controller pod log this every 2 min:

```logs
{"level":"warn","error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = \"transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2023-09-21T18:41:40Z is after 2023-09-05T13:34:19Z\"","lease_name":"ingress-controller","time":"2023-09-21T18:42:17Z","message":"leaser: error acquiring lease"}
```

## Additional context

My cluster with pomerium worked fine until 2023-09-05 which is the date of certificate expiration display in logs. I can't find which certificate is expired, and i don't understand what pomerium ingress controller is trying to do at this step.

Sorry for my english
Regards

**Comment by wasaga** [comment]
Please switch to officially supported and recommended all-in-one installation method for Pomerium on Kubernetes: https://www.pomerium.com/docs/deploy/k8s/install

Helm chart installed pomerium in so called split-mode where each Pomerium service is running independently, and it also generated self-signed certificates for inter-service communication. 

The error you're observing is because pomerium ingress controller is unable to communicate to the databroker component, as it serves a cert that's no longer valid.

**Comment by rgrente** [comment]
its now ok with the all in one install.
thanks !
