### ISSUE TITLE
Google GSuite example

### ISSUE THREAD

**Issue by bweston92** [pomerium/pomerium#46]
Are we able to use Google's GSuite as an IDP?

**Comment by desimone** [comment]
I haven't tried it myself, but from my understanding of the [openid connect docs](https://developers.google.com/identity/protocols/OpenIDConnect), it should work using the google provider. 

We do not currently make use of the `hd` [param](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) which customizes the login aesthetic, however.

**Comment by victornoel** [comment]
Google GSuite use the normal google authentication, there should be nothing specific to it compared to other google identity provider such as gmail or google cloud identity.

**Comment by bweston92** [comment]
Google Cloud Identity provides me with a OAuth key/secret where would I get one for a GSuite? I cannot see anything in their docs other then SAML. I can see Google login but I want it restricted to my GSuite directory.

**Comment by victornoel** [comment]
@bweston92 when I did it I simply created a cloud project in my gsuite domain where I set up the credentials (restricted to the gsuite domain) and oauth applications in the same way I would do it for cloud identity. GSuite users ARE Cloud identity users actually (even if it's not explicit).

**Comment by bweston92** [comment]
Ok sweet, thanks for helping both of you! :)

**Comment by desimone** [comment]
FYI, #57 added group support specific to gsuite and #59 added group access controls.

**Comment by bweston92** [comment]
Sweet will take a look thanks!
