### ISSUE TITLE
proxy: allow original host headers

### ISSUE THREAD

**Issue by VTommyV** [pomerium/pomerium#461]
Some applications don't respect the X-Forwarded-* headers and require the public (from) host header to be sent rather than the private (to) host header. By Pomerium sending the private host header, the application redirects the user browser to the private address which is not routable. 

It is not currently possible to overwrite this header by using set_request_headers.  It would make sense to have this feature configurable as a policy setting, called preserve_host_header for example.

This feature would mirror the behaviour of other reverse proxies such as HAProxy and Nginx.

**Comment by desimone** [comment]
@VTommyV Added and merged as part of the new release.
