### ISSUE TITLE
Token expiry is too short when user must go through 2 factor auth

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#473]
**Is your feature request related to a problem? Please describe.**

Some of my users are reporting that they get the `internal/cryptutil: timestamp expired` message just after auth at the IdP level (google) because it takes them too much time to go through 2 factor authentication (receiving a code via SMS for example).

**Describe the solution you'd like**

I'm not sure if just increasing the expiry time is enough or if it should be configurable maybe?

**Describe alternatives you've considered**

None

Edit: this is with pomerium 0.5.2, so maybe the expiry time has already been increased since then?

**Comment by desimone** [comment]
@victornoel 
At the moment I believe the hmac leeway is five minutes which feels reasonable. 

https://github.com/pomerium/pomerium/blob/6a10112ebe943b47caaa26f2955eeb7d2875a671/internal/urlutil/signed.go#L35

We could make this configurable if it continues to be a rough edge. Thoughts?

**Comment by victornoel** [comment]
@desimone indeed 5 minutes should be enough. Can you confirm it wasn't the case with 0.5.2? I feel like it is the case but I'm not sure :)

**Comment by desimone** [comment]
@victornoel Sorry, I was looking at cross service hmac validity, not the oauth callback which has its own construction per the [oauth2 spec](https://tools.ietf.org/html/rfc6749#section-10.12). 

The validity period for authenticate is and was 1 minute. I think this should be standardized to five minutes.

https://github.com/pomerium/pomerium/blob/0413d4b1780e4499eafc97103a9faba7a675b8e8/internal/cryptutil/hmac.go#L12

https://github.com/pomerium/pomerium/blob/0413d4b1780e4499eafc97103a9faba7a675b8e8/authenticate/handlers.go#L296

**Comment by desimone** [comment]
Fixed in #476
