### ISSUE TITLE
add `X-Real-Ip` request header

### ISSUE THREAD

**Issue by pschiffe** [pomerium/pomerium#4846]
Some services rely more on a `X-Real-Ip` header than `X-Forwarded-For`, and sometimes it's not trivial to change/configure.
For example [traefik](https://github.com/traefik/traefik/blob/v2.10/pkg/middlewares/forwardedheaders/forwarded_header.go#L138): if it receives `X-Real-Ip` it will pass it unchanged, otherwise it sets it to the client IP, even if it's trusted proxy, etc..

Alternatively, allow setting custom headers with real client IP as a [dynamic value](https://www.pomerium.com/docs/reference/routes/headers#pass-dynamic-tokens-in-headers), I think that could work too.

**Comment by desimone** [comment]
Previously 
- https://github.com/pomerium/pomerium/issues/4377
