### ISSUE TITLE
Invalid audience claim when mixing forward auth mode with simple proxying

### ISSUE THREAD

**Issue by gkranis** [pomerium/pomerium#486]
## What happened?

I have two services
1. `http://service_secured_by_forward_auth`
This is behind an nginx with the http_auth_request_module pointed at the pomerium forward auth endpoint

2. `https://service_secured_by_pomerium`
This is behind a pomerium proxy component

## What did you expect to happen?

I should be able to visit `1` and `2` within the timespan of a session timeout without issues

## How'd it happen?

1. I go to `https://service_secured_by_forward_auth`, it redirects me to `login.microsoftonline.com` where I just pick my account and then I'm allowed access
2. I go to `https://service_secured_by_pomerium`,  it redirects me to `login.microsoftonline.com` where I just pick my account and then I'm allowed access
3. I go to `https://service_secured_by_forward_auth` and I get "Unauthorized: internal/sessions: validation failed, invalid audience claim (aud)"
![image](https://user-images.githubusercontent.com/4227126/73667187-92d56800-46ac-11ea-89c2-8a367edba5ed.png)
If i click on request details I get
```
Issuer pomerium.subdomain.ad1.company.com
Audience pomerium.subdomain.ad1.company.com
         pomeriumforwardauth.subdomain.ad1.company.com
```
## What's your environment like?

- pomerium/v0.6.0 (+github.com/pomerium/pomerium; dd54ce4; go1.13.6)
- official docker image
## What's your config.yaml?

```config.yaml
pomerium:
  cookie_domain: ad1.company.com
  auth_service_domain: pomerium.subdomain.ad1.company.com
  forward_auth_url: https://pomeriumforwardauth.subdomain.ad1.company.com
  shared_secret: <>
  cookie_secret: <>
  idp_client_id: <>
  idp_client_secret: <>
  idp_provider_url: https://login.microsoftonline.com/<>
  policy:
    - from: https://service_secured_by_pomerium.subdomain.ad1.company.com
      to: http://localhost:8080
      allowed_groups:
        - <snipped>
    - from: http://service_secured_by_forward_auth.ad1.company.com
      # 'to' field is dummy for forward auth'ed services
      to: http://localhost:8089
      allowed_groups:
        - <same as above>
```

## What did you see in the logs?

```logs
{"level":"info","ip":"172.21.70.160","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","req_id":"<snipA>","error":"Unauthorized: internal/sessions: validation failed, invalid audience claim (aud)","time":"2020-02-03T16:12:12Z","message":"httputil: ErrorResponse"}
{"level":"debug","ip":"172.21.70.160","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","req_id":"<snipA>","duration":0.547763,"size":1671,"status":401,"email":"","group":"","method":"GET","service":"all","host":"pomeriumforwardauth.subdomain.ad1.company.com","path":"/verify?uri=http://service_secured_by_forward_auth.ad1.company.com/","time":"2020-02-03T16:12:12Z","message":"http-request"}
{"level":"info","ip":"172.27.1.156","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","req_id":"<snipB>","error":"Unauthorized: internal/sessions: validation failed, invalid audience claim (aud)","time":"2020-02-03T16:12:12Z","message":"httputil: ErrorResponse"}
{"level":"debug","ip":"172.27.1.156","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","req_id":"<snipB>","duration":0.738483,"size":1671,"status":401,"email":"","group":"","method":"GET","service":"all","host":"pomeriumforwardauth.subdomain.ad1.company.com","path":"/?uri=http://service_secured_by_forward_auth.ad1.company.com/","time":"2020-02-03T16:12:12Z","message":"http-request"}
```

## Additional context
nginx config
```
server {
        listen 80;
        listen [::]:80;
        server_name service_secured_by_forward_auth.ad1.company.com;
        resolver <snipped>;

        auth_request /auth;
        auth_request_set $auth_cookie $upstream_http_set_cookie;

        location / {
                proxy_pass              http://kibana/;
                proxy_set_header        Host            $host;
                proxy_set_header        Referer         "";
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                error_page 401 = @error401;
        }

        location = /auth {
            internal;
            proxy_pass https://pomeriumforwardauth.subdomain.ad1.company.com/verify?uri=$scheme://$host$request_uri;
            proxy_pass_request_body off;
            proxy_set_header        Content-Length "";
        }

        location @error401 {
            add_header Set-Cookie $auth_cookie;
            return 302 https://pomeriumforwardauth.subdomain.ad1.company.com/?uri=$scheme://$host$request_uri;
        }
}

```

**Comment by desimone** [comment]
Thanks for the detailed bug report @gkranis . Does this _only_ occur when you navigate between the forwarded and proxied routes? Does this happen if you only authenticate with `http://service_secured_by_forward_auth.ad1.company.com` ?

**Comment by gkranis** [comment]
@desimone 
If I dont visit the proxied route, `http://service_secured_by_forward_auth.ad1.company.com` works fine indefinitely AFAIK.
So a better description would be that visiting the proxied route breaks the forwarded route.

**Comment by desimone** [comment]
Interesting. Can you give me an idea what's going on (what domain?) with the associated `_pomerium` cookies? From your config, it doesn't look like there are any special settings. Perhaps the proxy cookie is clobbering your fwd auth cookie?

**Comment by desimone** [comment]
If possible, could you create a `har` (redacting any secrets) of the flow that is causing you the issue?

**Comment by gkranis** [comment]
The only cookie domain relevant ENV vars in my configuration are
"COOKIE_DOMAIN=ad1.company.com"
"COOKIE_SECURE=false" (sorry that wasnt visible in the initial post, im using it for testing because I dont have a cert for the forwarded route)

The cookies I see in the proxied route, forwarded route, forward auth endpoint, auth endpoint are

1. `_pomerium` `ad1.company.com` `/` Logins to both proxied and forwarded route set this to the same domain if thats what you are asking). And after logging in to the proxied route the existing cookie is changed.
2. `_pomerium_crf` `pomeriumforwardauth.subdomain.ad1.company.com` `/.pomerium/`
3. `_pomerium_crf` `pomerium.subdomain.ad1.company.com` `/`

**Comment by desimone** [comment]
@gkranis If you remove the `COOKIE_DOMAIN` setting, does that solve the issue?

**Comment by desimone** [comment]
Does dropping `COOKIE_DOMAIN` from your config (or at least your proxy config) solve the issue.

Also, having cookies_SECURE=false might give you other issues depending on what version of chrome you are running https://blog.chromium.org/2019/10/developers-get-ready-for-new.html <https://blog.chromium.org/2019/10/developers-get-ready-for-new.html>

Are you seeing any output in your browser to that effect?

**Comment by gkranis** [comment]
@desimone wow thanks, yes removing `COOKIE_DOMAIN` solves the issue. Now each proxied service gets its own cookies. I thought the option would be needed so that the forwardauth endpoint would be able to share the 'token' with the forwarded service

Now I understand why the forwardauth endpoint returns `302` with the token in the url arguments. I guess the 'validate' nginx subquery consumes it and sends it back to the browser as a unique cookie for the forwarded service

**Comment by desimone** [comment]
@gkranis glad to hear this worked!
