### ISSUE TITLE
Adding X-Real-IP and X-Forwarded-For headers to pomerium proxy requests

### ISSUE THREAD

**Issue by samcgarry** [pomerium/pomerium#488]
I'm having a problem with Pomerium running in service mode (v0.5) where the IP address of the client is not being passed on from Pomerium. I saw a similar issue (#384) which described the opposite effect (the IP address of the client was being passed on and this was not desired in that particular case).

Context:
I'm running Pomerium in docker in service mode with each service running in a separate container. For authentication Pomerium forwards the request on to my authentication service which works fine, and then after authentication the request is passed onto a reverse proxy server (Nginx) which passes the requests onto the appropriate service based on the host name.

I have noticed that the IP addresses being logged in Nginx belong to the Pomerium server rather than the client IP address. The Nginx log also appears to log the X-Forwarded-For header which is added by Pomerium, but Pomerium sets the IP address for the header to 10.0.0.2 which is the private IP address of the docker container.

I would expect Pomerium to add the required headers (X-Real-IP and X-Forwarded-For) to the requests it forwards on to the upstream web services.

I have tried adding the IP addresses of the servers to the nginx configuration using:
set_real_ip_from <ip addresses>
real_ip_header X-Forwarded-For
real_ip_recursive on;

but I still encounter the same issue.

Any suggestions would be appreciated.

**Comment by desimone** [comment]
Thanks for the @samcgarry , I'm a little surprised because we should be adding the x-forwarded-for header to the downstream request as you would expect. 

https://github.com/pomerium/pomerium/blob/1901cb5ca0f61014e45f11a882a0dbe57a2bcb2d/proxy/proxy.go#L233

https://github.com/golang/go/blob/3089d189569ed272eaf2bc6c4330e848a46e9999/src/net/http/httputil/reverseproxy.go#L249-L257

See also:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
- https://github.com/golang/go/issues/30963

**Comment by samcgarry** [comment]
Thanks for the quick response.

It looks like the $remote_addr in nginx is being set to the IP of the pomerium server, and X-Forwarded-For is using the IP address of the docker container (10.0.0.2).

Is there any logging that would show the request headers coming into the pomerium server, or the IP address of the client request? I tried setting the log level to debug in each container but that doesn't seem to increase the output very much.

**Comment by desimone** [comment]
If you have debug enabled, you should actually see both headers of interest.  See:

https://github.com/pomerium/pomerium/blob/dccc7cd2ffe3fc6d3fb4a9864b33494955ba3ef6/cmd/pomerium/main.go#L195-L196

**Comment by samcgarry** [comment]
Hi @desimone,
Yeah they are coming through - it was showing 10.0.0.2 as the IP address but I think I've now figured out the issue. I actually had docker running in swarm mode, and there seems to be a known issue with getting the client IP from docker in swarm mode, it always comes through as the gateway IP address.

One way around this is to use the container and bind it to the host network as follows:
```
    ports:
      - mode: host
        protocol: tcp
        published: 443
        target: 443
```
With the issue then that you can't replicate nodes. For my purposes that's fine but at least that means it's not an pomerium issue. After adding this the client IP address comes through in the logs and is forwarded correctly.

Thanks for the help.
