### ISSUE TITLE
authenticate: make oauth callback address configurable

### ISSUE THREAD

**Issue by tl-adrian-bridgett** [pomerium/pomerium#489]
Investigating pomerium vs buzzfeed/sso and this is just causing a minor pain.

We'd like to re-use the client already setup in Google but the callback url there is /google/callback (it uses the provider "reference" IIRC).  And pomerium wants to use oath2/callback.  It would be nice if this was configurable for easing migrations.

**Comment by desimone** [comment]
@tl-adrian-bridgett This should be a pretty straightforward change. 👍
