### ISSUE TITLE
Programmatic access with Google service_account

### ISSUE THREAD

**Issue by freeyoung** [pomerium/pomerium#492]
**Is your feature request related to a problem? Please describe.**

We want to implement automated end-to-end tests for our pomerium-secured web applications, which involves a Google account. However, we do not really want to use an actual user account but rather a service account.

By following the instructions on [Programmatic access](https://www.pomerium.io/docs/reference/programmatic-access.html), I could not find it possible to use a service account to do so.

**Describe the solution you'd like**

Make it possible for service account to be authenticated via Pomerium without human intervention.

**Comment by desimone** [comment]
Hi @freeyoung ,

Would it be possible to use a [gsuite service account](https://support.google.com/gsuitemigrate/answer/9222993?hl=en) for your use case?  Ideally, I think we'd like to grab service accounts from the upstream identity provider and manage that access there.

If so, I can take a look at updating the instructions for using that.

**Comment by freeyoung** [comment]
> Would it be possible to use a [gsuite service account](https://support.google.com/gsuitemigrate/answer/9222993?hl=en) for your use case?

👍 That was exactly what we want.

> If so, I can take a look at updating the instructions for using that.

Thanks!

**Comment by desimone** [comment]
Sorry, I had forgotten how Google's service accounts work.

I could still be wrong but, but my understanding is that gcp/gsuite service accounts are assigned certain roles and scopes to perform actions on Google's APIs. And while that account could be used to [generate oidc tokens which pomerium could use directly with some work](https://cloud.google.com/iam/docs/understanding-service-accounts#generating_openid_connect_oidc_id_tokens) that seems like a rather large risk and google specific. 

An alternative approach to user-driven [three-legged oauth](https://www.google.com/support/enterprise/static/gapps/art/admin/en/cpanel/3-legged-oauth-diagram.png) flow could be to have Pomerium generate its own service accounts. That way you can generate custom sessions / scopes without needed an actual user.  

For example:

```
$ ./pomerium-cli sa --email sa-user@example.com --groups pomerium-sa --shared-secret hunter2
```

Which would [output a valid SA/jwt](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiaHR0cGJpbi5pbnQuZXhhbXBsZSJdLCJlbWFpbCI6InNhLXVzZXJAZXhhbXBsZS5jb20iLCJncm91cHMiOlsicG9tZXJpdW0tc2EiXSwiZXhwIjoxNTgxMzgwNzU3LCJpc3MiOiJhdXRoZW50aWNhdGUuaW50LmV4YW1wbGUuY29tIiwicHJvZ3JhbWF0aWMiOnRydWV9.xHW3f8teIcFTy-QQqlGvpzq0gjsF2zLSPUXkhz1kHlg)

```json
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiaHR0cGJpbi5pbnQuZXhhbXBsZSJdLCJlbWFpbCI6InNhLXVzZXJAZXhhbXBsZS5jb20iLCJncm91cHMiOlsicG9tZXJpdW0tc2EiXSwiZXhwIjoxNTgxMzgwNzU3LCJpc3MiOiJhdXRoZW50aWNhdGUuaW50LmV4YW1wbGUuY29tIiwicHJvZ3JhbWF0aWMiOnRydWV9.xHW3f8teIcFTy-QQqlGvpzq0gjsF2zLSPUXkhz1kHlg```

```

```json
{
  "aud": [
    "httpbin.int.example"
  ],
  "email": "sa-user@example.com",
  "groups": [
    "pomerium-sa"
  ],
  "exp": 1581380757,
  "iss": "authenticate.int.example.com",
  "programatic": true
}
```

The only tricky bit would be session renewal (if the `exp` is set) would not be possible because we couldn't renew this service account's session.

```json
// https://accounts.google.com/.well-known/openid-configuration
 token_endpoint": "https://oauth2.googleapis.com/token",
```

**Comment by freeyoung** [comment]
Sounds good. However, just want to make it clear, is what you said more like a proposal? I could not find anything documented about `pomerium-cli` for example.

I tried to dig into the existing docker images but could not find it either.

Also, how would `aud`, `exp`, etc. be set? The command line you provided only had `--email`, `--groups` and `--shared-secret` set. Maybe through one of the API endpoint of the `authenticate` service?

> The only tricky bit would be session renewal (if the exp is set) would not be possible because we couldn't renew this service account's session.

Then what if we want to revoke a session at the end of an end-to-end testing run?

**Comment by desimone** [comment]
@freeyoung Yes that's right it's more of a proposal for supporting pomerium based service account generation using a command line app. It doesn't exist yet. 

> Also, how would aud, exp, etc. be set? The command line you provided only had --email, --groups and --shared-secret set. 

For brevity, I just included just a few claims but standard oidc & pomerium claims would be configurable including exp/aud/etc. 

> Then what if we want to revoke a session at the end of an end-to-end testing run?

This is where things get tricky. You'd have to generate a SA that had a short enough expiration, or use a SA with a user account whose access you add / remove from the policy. 

Would either setting a short expiration / explicitly adding the SA user to the policy  work for your use case?

**Comment by freeyoung** [comment]
👍 Yes, and I personally prefer the latter.

**Comment by desimone** [comment]
@freeyoung great, on it.

**Comment by desimone** [comment]
Quick update... apologies for the dealy. I have  prototype for this and will come shortly after https://github.com/pomerium/pomerium/pull/514 .

**Comment by desimone** [comment]
Fixed in #552 , looking at bundling this in a docker image in `v0.7.0`

![carbon](https://user-images.githubusercontent.com/1544881/77498917-fe66c680-6e0d-11ea-9238-cbd3a4b265fb.png)

**Comment by desimone** [comment]
@freeyoung just a quick ping to let you know this is now in `v0.7.4` and docs are up [here](https://www.pomerium.io/docs/reference/impersonation.html#how)

**Comment by nareddyt** [comment]
Just to double check, is this feature removed in 0.13.x? I see user impersonation is removed.

**Comment by desimone** [comment]
Hey @nareddyt  -- yes, that's correct. We removed SA and user impersonation.
