### ISSUE TITLE
core/authorize: denied response is not an error page anymore

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#4951]
## What happened?
Using the `main` branch, the authorize service is no longer returning an error page in the browser for access denied. Instead there's a JSON object returned:

```json
{
  "error": "Forbidden",
  "request_id": "8736001c-c6db-4386-855c-441d2ae9b4b7"
}
```

## What did you expect to happen?
To see an HTML page.

## Additional context
This broke with #4904. The issue is that browsers send `*/*`. So `application/json` matches.

**Comment by ssveta7ak** [comment]
Fixed. Checked on 
Core v0.25.0-53-gd405a53b + d405a53b
Enterprise v0.25.0 + 13e803f7 + 2024-02-29T19:12:42Z
