### ISSUE TITLE
[Question] How to support API request to another domain in SPA?

### ISSUE THREAD

**Issue by psychomelet** [pomerium/pomerium#512]
I find a similar issue here -> https://github.com/pomerium/pomerium/issues/390#issuecomment-567614157

Our use case is we have a static website hosted at https://web.corp.com and API server hosted at https://api.corp.com

And I encounter this error

> Access to XMLHttpRequest at 'https://api.corp.com/api' from origin 'https://web.yogorobot.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Is it possible to protect the both domain under SSO and make the SPA application work?

**Comment by desimone** [comment]
Hi @psychomelet 

Due to browser cross site request credential security, it is _not_ recommended to do CORs (http://api.domain.com  & http://static.domain.com ) but instead it is suggested to have the api path live under a single domain. 

Currently, the best way to do this is by putting another reverse proxy (like nginx/traefik) and have that proxy essentially combine those two paths under a single `to` hostname (e.g. http://api.local and http://static.localhost would instead map to http://combinded and http://comibed/api respectively).

This will be natively supported in Pomerium started with #378 . 

hope that helps

**Comment by pflipp** [comment]
Isn't this a common and most suggested scenario?

The SPA starts the oauth flow and passes the returned auth code to the oauth proxy which then fetches the access/id_token and creates a session.
The oauth proxy then forwards the access token to the APIs which are then able to make standardized token introspection/verification. These APIs commonly are also used from third-party-apps/machines.

While pomerium handles the first part very well (while not equal) I don't know how i could just pass an `Authorization: Bearer {access-token}` header to the backend API.

Handling the pomerium assertion header only works with pomerium in front, to provide access to the API for other clients would then significantly increase the complexity of the API as it has to handle both.

**Comment by desimone** [comment]
> Isn't this a common and most suggested scenario?

Yes, this is a very common scenario. 

> The SPA starts the oauth flow and passes the returned auth code to the oauth proxy which then fetches the access/id_token and creates a session.

Correct. But a small wrinkle here. One of the advantages of Pomerium is that it can use a _single_ access/refresh token across `n` proxied routes. To make that possible, the authenticate service creates child, route-scoped JWT sessions (based off the original id_token).

>  ** The oauth proxy then forwards the access token ** to the APIs which are then able to make standardized token introspection/verification. These APIs commonly are also used from third-party-apps/machines.

The proxy component does not forward the parent (IdP returned) access token to the API. Nor does it forward child (route-scoped) session cookie to the downstream application.  The per-route session cookie acts as an access token. We intentionally strip that session cookie from the request to avoid that session being 1) leaked to the downstream application (which, it may accidentally log, etc) 2) keep the downstream application agnostic to the fact it is behind Pomerium. 

> .. which are then able to make standardized token introspection/verification. These APIs commonly are also used from third-party-apps/machines.

Can you tell me a little more about that, I don't follow.

> While pomerium handles the first part very well (while not equal)

What's not equal?

>  I don't know how i could just pass an Authorization: Bearer {access-token} header to the backend API.

This is tricky. Pomerium _does_ support passing the route-specific access token via an authorization bearer (the key is not bearer but Pomerium) token. The value will not be stripped (unlike the session token) which may be fine for your threat model and use case. 
https://www.pomerium.io/docs/reference/programmatic-access.html#example-code


> Handling the pomerium assertion header only works with pomerium in front, to provide access to the API for other clients would then significantly increase the complexity of the API as it has to handle both.

Can you explain more what you mean? What's your current situation? How do you imagine it working? I'm not quite tracking how you are trying to use Pomerium. Is the idea to allow access via both Pomerium, and directly?

**Comment by pflipp** [comment]
Thank you for your detailed answer @desimone.

Our use case is as follows:
We have our own Open Id Connect Provider and several APIs which are protected by this by evaluating the provided access token with OAuth 2.0 Token Introspection ( https://tools.ietf.org/html/rfc7662 ).

Now we have a web frontend which wants to talk to those APIs and for that I was evaluating Pomerium as an oauth proxy.

> Is the idea to allow access via both Pomerium, and directly?

So, yes

> What's not equal?

I don't think that we have to discuss this here as I'm totally fine with the Pomerium implementation. Just for clarification what I meant:
SPA directly redirects to idP
After login/access grand the idP redirects back to the SPA with the Authorization code
The SPA sends the Auth Code to a `login` route of the oauth proxy which fetches the Access and ID Token, stores them in a sessions and returns the session to the SPA

**Comment by jfcantu** [comment]
> A possible work around could be to issue a route-jwt with audiences for both api/static sites.

I can't speak intelligently to the design implications, but I'm having the exact same problem (JavaScript on `page.example.com` calling `api.example.com`) and being able to have multiple audiences per JWT would solve it for me.

**Comment by psychomelet** [comment]
Can we add a feature, for example `shared_session_key: abc` to share session under the same scope between multiple domains?

**Comment by desimone** [comment]
This should now (as of 0.8.0) be directly supported by using multiple policies for the same domains using different domain prefixes / regexes. 

e.g.
```yaml
policies:
  - from: http://from.example.com
    to: http://api
    prefix: /api
    allowed_groups: ["superuser"]
  - from: http://from.example.com
    to: http://static-site
    allow_public_unauthenticated_access: true
```

https://0-8-0.docs.pomerium.io/configuration/#policy

**Comment by namelivia** [comment]
I'm trying to solve this exact same problem (`spa.domain.com` doing AJAX requests to `api.domain.com`).
First my configuration was:
```
policy:
  - from: https://api.domain.com
    to: https://internal.api.domain.com
    allowed_users:
      - myuser@domain.com
```
And having this setup browsing `https://api.domain.com` would correctly redirect me to the identity provider login screen, but the AJAX requests made by the SPA application have the problems mentioned above.

Now after reading your last message this is my current configuration:
```
policy:
  - from: https://api.domain.com
    to: https://internal.api.domain.com
    prefix: /api
    allowed_users:
      - myuser@domain.com
  - from: http://api.domain.com
    to: https://spa.domain.com
    allow_public_unauthenticated_access: true
```
What is changed now is that if I browse `https://api.domain.com` now I get redirected to `https://spa.domain.com`. But I've updated the SPA application to make its requests to `https://api.domain.com/api` and I'm still getting 302 responses and CORS errors on the console.

I think I misunderstood something written here but I can't figure out what. Is this the appropriate config?
Thanks for your help!

**Comment by desimone** [comment]
@namelivia Do you mind creating a `har` file and sharing it here (make sure to redact any sensitive data)?

**Comment by namelivia** [comment]
Sure! Thanks for the fast answer.
This is the `har` file, I cleared most of the crap out of it, but there are still many requests that may be unnecessary, sorry if that's the case! Also I've randomized most of it, if there is some token or something there it actually doesn't matter since this is just a test environment.
[This is the har contents in pastebin](https://pastebin.com/Ja7v6kQF)
