### ISSUE TITLE
Is it possible to have an environment type variable substitution for the set_request_headers feature?

### ISSUE THREAD

**Issue by samcgarry** [pomerium/pomerium#515]
**Is your feature request related to a problem? Please describe.**

When a user has been identified using the identity provider, I was looking for a way to pass that user to a remote service using an HTTP header. The policy documents say there's an option for set_request_headers, where you can set a string map for HTTP headers. I was wondering if this could be extended to populate variables such as:

```
set_request_headers:
  "X-USER": "{{user_name}}"
```

where the variables correspond to values returned from the identity provider.
Currently as I understand it this can only be static values. Is there a security reason why this would be a bad idea?

**Comment by desimone** [comment]
This is possible today using the user / group / and attestation headers. The attestation header will contain (nearly) all the data you'd receive from your identity provider directly, but signed by Pomerium. It's highly recommended to use the signed JWT over `email`/`groups` headers directly. 

https://www.pomerium.io/docs/reference/signed-headers.html#verification
https://www.pomerium.io/docs/reference/getting-users-identity.html

Heads up! There's a slight typo in the JWT attestation header name and that will change in the upcoming version. 

https://github.com/pomerium/pomerium/blob/ca54c99a669879eb1798bd986cc5c73f04047a75/internal/httputil/headers.go#L10

**Comment by desimone** [comment]
@samcgarry did that answer your question? if not, please reopen 👍
