### ISSUE TITLE
Audience claims for forward auth not taken into account

### ISSUE THREAD

**Issue by nachtfisch** [pomerium/pomerium#516]
## What happened?

After sucessful login the audience claims are not populated properly with information from policy config.

## What did you expect to happen?

Audience claims being there.

## How'd it happen?

Forward auth trying to protect the dashboard. Accessing the dashboard page, logging in with Okta and then being redirected. Verify call from nginx ingress controller to proxy url will always return 401

## What's your environment like?

- Pomerium version 0.6
- Server Operating System/Architecture/Cloud: Kubernetes with nginx ingress controller

Installed through helm chart.

## What's your config.yaml?

```config.yaml
forward_auth_url: https://forwardauth.domain.com

pomerium_debug: true
policy:
  # this route is indirectly checked for access using forward-auth
  - from: https://dashboard.domain.com
    to: https://kubernetes-dashboard
    allowed_domains:
      - innoveo.com
```
```values.pom.yaml

config:
  rootDomain: domain.com
  existingConfig: config
authenticate:
  idp:
    provider: okta
    url: https://xxx.okta.com
    clientID: aaa
    clientSecret: xxx
    serviceAccount: xxx
  cacheServiceUrl: https://helm-pomerium-cache.default.svc.cluster.local
ingress:
  enabled: false
```

## What did you see in the logs?

No error message. Logs of authorization service don't show any activity from auth service.

## Additional context

Is there authorisatioon service supposed to be called and would it print something to the logs if so? It seems strange to me that my audiences are not populated and there is nothing in the logs.

**Comment by nachtfisch** [comment]
after going through the slack chat it might be that this is an nginx problem 

https://github.com/kubernetes/ingress-nginx/pull/5067

not retaining some header.

**Comment by travisgroth** [comment]
Hi @nachtfisch - yes there was a bug in nginx-ingress from 0.26.2 that broke the cookie set during auth flow.  0.29 contains the fix.  Let us know if you're on nginx-ingress <0.26.2 || >=0.29 and still having an issue.

**Comment by desimone** [comment]
@nachtfisch did the new version solve the issue for you? If not, please let re-open and let us know. Thanks!

**Comment by nachtfisch** [comment]
I didn't have the chance to try it out and went without forward auth. i would assume it's fixed in newer versions.
