### ISSUE TITLE
Multi domain support

### ISSUE THREAD

**Issue by mkohns** [pomerium/pomerium#523]
**This is a question, no bug or feature requests**

Use-Case: Having mulitple domains (i.e. domain1.com, domain2.org) handled by one server. 

With openresty + lua-resty-openidc I can configure the authentication service to listen on http/https and handle both domains. I can configure multiple sets of TLS Certificates (for each domain), multiple IDP Provider and multiple policies.

It seems as if this also could be done with "Service Mode" in pomerium.
Could you clarify?

**Comment by desimone** [comment]
> Having mulitple domains (i.e. domain1.com, domain2.org) handled by one server.

in general this is possible, as sessions are route-route (same-site domain) scoped.  

> I can configure multiple sets of TLS Certificates (for each domain), multiple IDP Provider and multiple policies. 

- ✅ TLS Certificates (for each domain)
- ✅ multiple policies 
- 🔜 multiple IDP Providers. support for this is possible, in beta, but not baked in yet. If you are using this at your company, let me know bdd@pomerium.io ; can you tell me a bit more about your usage scenario?

**Comment by mkohns** [comment]
@desimone 

That sounds really great! I just do not understand how to configure it. Most of the configuration parameters in https://www.pomerium.io/configuration/#authenticate-service seems to be singular.

Could you please give a rough example for this configuration I could complete myself?

Preconditions:
1) one pomerium server 
2) one DNS entry for example1.org pointing to pomerium server IP
3) one DNS entry for example2.org pointing to pomerium server IP
4) Two TLS certificates + keys  in /etc/ssl/example1.org and /etc/ssl/example2.org
5) Two authenticate_service_urls for example1.org and example2.org
6) SAME IDP (configured with both (5) redirect_urls)
7) one policy from httpbin.example1.org to http://httpbin1 (docker dns)
8) one policy from httpbin.example2.org to http://httpbin2 (docker dns)

**Comment by kernel-sanders** [comment]
I am also interested in this, specifically to serve `*.internal.example.com` and `*.example.com` from the same pomerium server. The certificate configurations are in shared settings and "these are configuration variables shared by all services, in all service modes." How can we use different certificates for different routes?

**Comment by followsound** [comment]
Would also like to use multiple IDP - is this available (even if in Beta)?

**Comment by desimone** [comment]
@kernel-sanders 

Sorry this issue seems to have gotten lost in mix a bit. The good news is that this should absolutely be possible. We now support loading an [arbitrary set of certificates](https://pomerium.com/reference/#certificates) that can be used for multiple domains, wild-card or not. 

@followsound Multiple IdP support is something we are looking at. Could you reach out directly bdd@pomerium.com?

Going to close as I believe multi-domain support is now complete in any configuration I can think of. If I'm wrong, feel free to reopen.

Thanks!
