### ISSUE TITLE
Direct Bearer Token Access

### ISSUE THREAD

**Issue by mkohns** [pomerium/pomerium#524]
**This is a question, no bug or feature requests**

Use-Case: REST API is behind pomerium, M2M clients directly use idp for token provisioning

With openresty + lua-resty-openidc I can configure the authentication service to 
a) if request does not include access_token and cookie -> redirect to IDP
b) if request does include valid cookie -> redirect to upstream
c) if request does include valid access_token (verfiy only) -> redirect to upstream

Is something like this possible with pomerium?

**Comment by palmalcheg** [comment]
Also curious about configuring "client credentials" (M2M) declarative configuration, if possible

**Comment by desimone** [comment]
> With openresty + lua-resty-openidc I can configure the authentication service to
> a) if request does not include access_token and cookie -> redirect to IDP
> b) if request does include valid cookie -> redirect to upstream
> c) if request does include valid access_token (verfiy only) -> redirect to upstream
> Is something like this possible with pomerium?

Yes, assuming I am understanding your use case correctly, machine to machine (/ programmatic access) is possible. 

https://www.pomerium.io/docs/reference/programmatic-access.html

@mkohns 

> M2M clients directly use idp for token provisioning

Do you mean that your clients have an access token that was already directly given to the client application, and you want to use that and exchange it for a pomerium token? Perhaps I am miss understanding. 

@palmalcheg 

> Also curious about "client credentials" (M2M) declarative configuration, if possible
Could you expound a bit on what you had in mind?

**Comment by mkohns** [comment]
@desimone 

Thanks for the quick answer: To clarify my use-case:

1) backend application (with no user interaction) can talk directly to IDP in order to get an access and refresh_token. Credentials for that are provided securely to the backend application by vaults/secret engines (i.e K8s)
2) backend application can call API behind openresty-luaopenidc with http header "Authorize: Bearer"  
3) openresty-luaopenidc identifies with given Bearer and not existing cookie that auth flow should not be handled by openresty.luaopenidc and only checks/verifies that bearer fits to the configure IDP. 

The usecase actually focues backends applications which are not able to have user interactions (fill in login-form of IDP). Credentials are provided to the backend application in some kind of vault and handled completely autonomous. The identity aware proxy is not in charge of managing access and refreshing - only bearer check/validation for proxy pass to upstream.

Does this make sense?

**Comment by palmalcheg** [comment]
@desimone 
I'm thinking about the case when there is service-to-service interaction with Bearer token managed by Pomerium 
1) service-A initiates call to service-B, call is proxied to Pomerium.
2) Pomerium keeps the most up-to-date token, refresh if needed
3) Pomerium injects Bearer as Authorization header
4) Redirect to service-B

**Comment by p53** [comment]
check features of https://github.com/louketo/louketo-proxy, this can nicely do m2m or user to API access by verifying token, which you can get from IDP (ways can be different) located in Authorization: Bearer $TOKEN header. It doesn't need cookies for retrieving session state...M2M can be achieved by configuring louketo-proxy as forward-signing on one side https://github.com/louketo/louketo-proxy/blob/master/docs/user-guide.md and configuring validating bearer token on other side

**Comment by RichiCoder1** [comment]
> Do you mean that your clients have an access token that was already directly given to the client application, and you want to use that and exchange it for a pomerium token? Perhaps I am miss understanding.

I want this, except I'd rather just bypass Pomerium if I've already got a token. EG: I want pomerium for interactive access, but I just want to bypass pomerium if I'm using the target application's native authentication.

**Comment by RichiCoder1** [comment]
There are DNS/LB based work arounds that I could do, but I'd rather all traffic go through a single endpoint.

**Comment by desimone** [comment]
Closing, as this is now available in pomerium enterprise. 

- https://docs.pomerium.com/docs/enterprise/reference/configure#service-accounts
