### ISSUE TITLE
Missing Pomerium claims from User Info Dashboard

### ISSUE THREAD

**Issue by goldie-bloomberg** [pomerium/pomerium#5246]
## What happened?

- We have a programmatic sanity check tool built using pomerium's authclient and certstore packages. The tool attempts retrieve a user's claims from the dashboard endpoint and cross check 403 response codes against the user's claims. 

- However the users claims (and other details) are only returned by web browser access. 
- Via programmatic access, all fields in POMERIUM_DATA's jwt, except for webAuthnUrl, are empty. 

## What did you expect to happen?
I expected all the fields POMERIUM_DATA's jwt to be identical whether accessed programmatically or via a browser. 

## How'd it happen?

1. Ran an internal tool programmatic_access.exe
2. It retrieved the pomerium_jwt
3. And then it set the Authorization header to the pomerium_jwt and accessed the dashboard url
4. the returned jwt did not have any claims set. 

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version`): 
  - Unfortunately we're missing the  pomerium version due to our messed up build that we will fix. 
  - The most recent commit that's pulled in is #e3e7de7
- Server Operating System/Architecture/Cloud: Server operating system : 
  - RHEL8

## What's your config.yaml?

Not particularly relevant

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?
```logs
 {
  "level": "info",
  "service": "envoy",
  "authority": "scrubbed",
  "path": "/.pomerium/",
  "query": "",
  "ip": "scrubbed",
  "forwarded-for": "scrubbed",
  "method": "GET",
  "duration": 21.085387,
  "referer": "",
  "request-id": "7dcf38d7-cc92-439f-91d3-de741c28b152",
  "response-code": 200,
  "response-code-details": "via_upstream",
  "size": 706,
  "upstream-cluster": "pomerium-control-plane-http",
  "user-agent": "Go-http-client/1.1",
  "client-certificate": {
    "issuer": "scrubbed",
    "subject": "scrubbed"
  },
  "time": "2024-08-27T14:22:26-04:00",
  "message": "http-request"
}
```

**Comment by calebdoxsey** [comment]
This should be fixed after https://github.com/pomerium/pomerium/commit/52d4899d4c883360815cf58abf4a74f56fcfac9f on main or in the next tagged release of 0.27.
