### ISSUE TITLE
POST body caching while token refresh

### ISSUE THREAD

**Issue by mkohns** [pomerium/pomerium#525]
**This is a question, no bug or feature requests**

Scenario: Web client is signed in with valid cookie. JS REST API calls do their jobs in the client. Lets assume they POST some data every 10 seconds to a REST endpoint. 

Question: If pomerium detects that token is expired, and initiating token refresh flow, how is the POST body data cached? If not, how is the client being informed that POST did not succeed (http response code?). Does the upstream backend api need special handling for this?

Same here: https://github.com/zmartzone/lua-resty-openidc/issues/236

**Comment by desimone** [comment]
@mkohns 

Great question.

> Question: If pomerium detects that token is expired, and initiating token refresh flow, how is the POST body data cached? 

The body data is not cached. The request will be slightly delayed by the refresh process that happens on the backend. We are looking at ways of refreshing this token in the background so it doesn't incur any additional latency. 

> If not, how is the client being informed that POST did not succeed (http response code?). Does the upstream backend api need special handling for this?

In most cases the session should be automatically refreshed (but, like I mentioned above with a bit of additional latency). In the case the token is not refreshed, the user will receive a 302 redirect to their IdP login page; if you have control over your backend API and want to specially handle this scenario a `x-pomerium-intercepted-response` header will be set.

**Comment by mkohns** [comment]
If I understand your answer right the following should be true. Please confirm:

0) Client login via pomerium authorization flow
1) Client calls pomerium secured API with valid token POSTing data (returning 201)
2) ...
3) Client calls pomerium secured API with expired token POSTing data 
   3.1) Pomerium refreshes token in background (?)
   3.2) posted data gets delivered to api and client gets 201 with short latency due to 3.1
