### ISSUE TITLE
set spec.externalTrafficPolicy: Local in kubernetes manifests

### ISSUE THREAD

**Issue by wasaga** [pomerium/pomerium#5265]
## What happened?

Pomerium runs Envoy in the edge server configuration, including setting `use_remote_address: true` in the HTTP connection manager, and supports `request.ip` in the external data sources [lookups](https://www.pomerium.com/docs/capabilities/integrations#foreign-key). https://github.com/pomerium/pomerium/blob/2b8411105883dea4895a26e7985b0d9361ac5df5/config/envoyconfig/listeners.go#L338-L340

When deployed to Kubernetes, we are currently not specifying the `spec.externalTrafficPolicy` that defaults to `Cluster`, that prevents Pomerium in [obtaining the client IP address](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip). 

## What did you expect to happen?

Set the default deployment for Pomerium Proxy service to be `spec.externalTrafficPolicy: Local`

**Comment by calebdoxsey** [comment]
This looks like its done.
