### ISSUE TITLE
Consider explicitly auto-mounting the Service Account Token in the deployment

### ISSUE THREAD

**Issue by gaurdro** [pomerium/pomerium#5279]
## What happened?

Upgraded a zero-connected instance to follow ref=main and pods in the deployment failed to start with 
> {"level":"fatal","error":"error creating bootstrap config writer: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory","time":"2024-09-11T17:57:44Z","message":"cmd/pomerium"}

## What did you expect to happen?

Upgrade happens without issue.

## How'd it happen?

update reference, have argo sync changes.

## What's your environment like?

GKE autopilot cluster
zero-connected pomerium instance 

## What did you see in the logs?

```logs
 {"level":"fatal","error":"error creating bootstrap config writer: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory","time":"2024-09-11T17:57:44Z","message":"cmd/pomerium"}
```

Adding `automountServiceAccountToken: true` to the pod template in the deployment should be sufficient to avoid this issue.

**Comment by kralicky** [comment]
`automountServiceAccountToken` is true by default if the pod does not specify, unless it is overridden by the service account. In your setup, does the pod's service account have it disabled?

**Comment by gaurdro** [comment]
I don't see it explicitly disabled, but this is on a 'vanilla' GKE autopilot cluster. Autopilot makes a lot of changes to defaults.  I don't see this particular setting called out but they do state this 

> Autopilot clusters enable and apply security best practices and settings by default, including many of the recommendations in the security overview and in [Harden your cluster security](https://cloud.google.com/kubernetes-engine/docs/how-to/hardening-your-cluster).

turning off automounting is called out in their [best-practices guide](https://cloud.google.com/kubernetes-engine/docs/best-practices/rbac#avoid-token-automount) 

I think if we're relying on a behavior to exist, and there's a setting that will ensure the behavior, we should consider using that setting.

**Comment by wasaga** [comment]
could it depend on some default GCP project settings maybe? I did not run into this issue with clusters in the sandbox 

I agree it may make sense to set this option explicitly.

**Comment by gaurdro** [comment]
I found where it's set to false.  The terraform module that was used to setup workload federation defaults to false for the service account.
