### ISSUE TITLE
k8s api access: support websocket upgrade

### ISSUE THREAD

**Issue by wasaga** [pomerium/pomerium#5293]
**Is your feature request related to a problem? Please describe.**

As of Kubernetes 1.31, WebSocket is a new streaming protocol that replaces SPDY.
https://kubernetes.io/blog/2024/08/20/websockets-transition/

**Describe the solution you'd like**

Support websocket upgrade request. 

**Describe alternatives you've considered**

**Explain any additional use-cases**

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by wasaga** [comment]
and probably automatically enable this upgrade if kubernetes service account token option is set

**Comment by wasaga** [comment]
1. need 1.31 cluster to test
2. we probably need support both SPDY and WebSocket upgrades as we're unaware which cluster version we're talking to

**Comment by kralicky** [comment]
This does seem to work fine as far as I can tell. Let me know if you want access to my 1.31 cluster to test.

**Comment by calebdoxsey** [comment]
It fails with:

```
RemoteCommand fallback: unable to upgrade streaming request: websocket: bad handshake (403 Forbidden)
```

Going to try just enabling websockets to see if that fixes it.

**Comment by calebdoxsey** [comment]
I tested this using `kind`.
