### ISSUE TITLE
authorize: access right per route

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#54]
**Is your feature request related to a problem? Please describe.**

In case different services have different access rights, it is needed to deploy pomerium multiple time (one instance per access right set), and this can become quite cumbersome when the number of services increase.

**Describe the solution you'd like**

It would interesting to be able to configure pomerium to have different access right depending on the routes. A bit like buzzfeed-sso does it for example (see https://github.com/buzzfeed/sso/blob/master/docs/sso_config.md).

Is this a planned feature?

**Comment by desimone** [comment]
Thank you for the request @victornoel

> become quite cumbersome when the number of services increase

I agree!

I think I understand what you have in mind, can you tell me a little more about what the ideal access solution would look like? Where you thinking along the lines of authorization based on group membership? 

- Bob from HR **should** be able to access payroll.corp.example.com but **not** github.corp.example.com 
- Alice from engineering **should** be able to access to github.corp.example.com but **not** payroll.corp.example.com? 


Or in terms different access rights within a route itself? e.g.

-  Alice from engineering **should** be able to access to github.corp.example.com/**alice**/repository and **not** github.corp.example.com/**bob**/repository 

Also, do you mind me asking which identity provider you are using? Unfortunately, one of the challenges of supporting multiple identity providers is that group membership is not standardized in the openid connect spec. 

 > Is this a planned feature?

Absolutely. I hope to tag and release v0.0.2 this week and have following release (v0.0.3) be centered around authorization.

**Comment by victornoel** [comment]
Glad to see this kind of requirements is on the roadmap :)

So, I think there are two different things to tackle here:
- authorization per route
- group-based authorization

Currently Pomerium seems to support defining domain-based authorization, user-based is on the road with #41 I suppose. Group-based seems a good next step I guess.

My request is mostly about applying authorization (whichever they are) per route.

I mostly approach the question at the level of kubernetes service. So I suppose it is closer to your first example, so we get, using a user-based authorization (even though this is not yet implemented):
- payroll.corp.example.com is authorized to bob@example.com 
- github.corp.example.com is authorized to alice@example.com

In my actual use case, I am using Google as an identity-provider, I have domain with gsuite/cloud identity and have different types of users: those of our organisation, say alice@example.com, bob@example.com then I have several sub-domains created specifically for our clients such as john@client1.example.com, sarah@client2.example.com.
I have services deployed for those different clients and thus want to say:
- app1.example.com is authorized to domains example.com as well as client2.example.com
- app2.example.com is authorized to client1.example.com
- app3.example.com is authorized to client1.example.com and client2.example.com
- app4.example.com is authorized to example.com only

And so on :)

Of course group-membership will most certainly be a need for many people I suppose.

**Comment by desimone** [comment]
Thank you @victornoel this very helpful as I am currently planning authorization. Just a few follow up questions, if you don't mind. 😄 

- Would you be using a single set of oauth2 credentials to manage all these users? 
- Are these users typically in groups as well? Would it be workable/preferable to apply a policy for at the group level instead of using the domain of a the user? 

Thanks!

**Comment by victornoel** [comment]
@desimone 
> Would you be using a single set of oauth2 credentials to manage all these users?

At first only one, but it would be clearly a need with time to be able to configure multiple IdP and use them in the various routes.
So for example we could have client1.example.com authorized to both users of examples.com and users of client1.com, where example.com is managed by GSuite and client1.com is say, an Azure AD

> Are these users typically in groups as well? Would it be workable/preferable to apply a policy for at the group level instead of using the domain of a the user?

I think that it will be a need to work at the group level instead of the domain or user level yes. I believe at first it sould be alright to work, say, at the user level, but for sure with time, access management will become much easier if it is done at the group level.

Glad to help with requirements :)

**Comment by desimone** [comment]
Added in #57

**Comment by victornoel** [comment]
@desimone excellent, I will test this very soon :)
