### ISSUE TITLE
direct http/https access by IP address

### ISSUE THREAD

**Issue by mkohns** [pomerium/pomerium#546]
**This is a question, no bug or feature requests**

In nginx configuration it is best practise to catch direct IP address access like https://w.x.y.z like [this](https://blog.knoldus.com/nginx-disable-direct-access-via-http-and-https-to-a-website-using-ip/).

How can I deal with direct http/https IP access in pomerium?

**Comment by desimone** [comment]
@mkohns I'm not sure I understand. What are you trying to do exactly?

**Comment by travisgroth** [comment]
Pomerium does not have any default backend, so accessing the proxy without a valid `Host` header will result in a 404 anyway.  If I understand what you're looking for, it is already the current behavior.
