### ISSUE TITLE
authorize: policy and authorization

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#56]
## Authorization modules
- **Device state** (vNext)
	- Persistent device identifier (X.509 certificates in TCB)
	- Encryption status, secure boot enabled, etc
	- Device inventory (OSQuery, others?)
	- Hardware enclaves and trusted attestation is absolutely critical. Devices cannot be trusted to report their own state. (intel sgx, Apple T2)
- **Identity state** (muddy mix of oidc / oauth2 / rest / saml for unified interface) 
	- v0.0.3
		- groups  #57 
	- vNext
		- multi-factor authentication used?
		- roles 
		- titles
		- status
- **Request state** (vNext)
	- IP
	- Geo
	- Date/time
	- Known tor exit, proxy, vpn
	- Browser version (though UA is spoof-able, better to get from device state)

## Policy Engine
- v0.0.3 #59 
	- Policy applied per route; Combine policy assignment with route map?
	- Yaml /Json based? ACL driven.
	- User should be shown a deny landing page explaining why they were denied (lack group membership etc). 
- vNext
	- dynamic “policy as code” w/ generic Language or DSL🤮 ( see sentinel, OPA) 
	- Compiled for speed
	- Centralized ? (support storage backends?😕)
	- Queryable by RPC (support storage backends?😕)
	- Managed by security team
	- Self service support

￼
￼See:
- #54 
- #41 

/cc @tboerger

**Comment by desimone** [comment]
#59  adds the near-term policy and authorization features. Future versions can reference this as needs evolve.

**Comment by pawneeranger** [comment]
I cannot find any references to the **device state** in the code nor the documentation, are those features still considered for further versions ? If yes, is there any way to contribute to their implementation ?
