### ISSUE TITLE
Create an `x` package

### ISSUE THREAD

**Issue by ilgooz** [pomerium/pomerium#564]
and move any utility pkg or generic packages under there.

This is a coding style proposal which helps creating a distinct between the actual business logic and helpers. 

I see some utility code such as [this](https://github.com/pomerium/pomerium/blob/9bee6bb/cmd/pomerium-cli/cli.go#L19-L33) one directly added to business code.

Instead of having that kind of there, moving them under `x` pkg with a proper pkg name would make re-usability and code readability easier.

Wrapping up,

Under `x` pkg,

* If the utility code looks like relevant to an already existent std or commonly used 3rd party package use the same pkg name but with an `x` prefix. For ex. `x` > `xstrings` to create a `xstrings.Slice()` helper.

* If the utility code can became to a regular, reusable, generic pkg then choose a standalone package name.

**Comment by desimone** [comment]
@ilgooz 

Thanks for making an issue.

> This is a coding style proposal which helps creating a distinct between the actual business logic and helpers.

I'm not a fan of `x`packages for a few reasons. To me,

- `x` style packages like  (things like `/x/crypto` come to mind) mostly signify that though the package is externalized, it does not fall under go's strict 1.0 backward compatibility policy.
- I prefer to use `/internal/` for all but the most essential external dependencies (like `config` used by operator) which will fall under semver and can be managed by gomod. 
- No other part of the code base uses `commaSlice`, so I think it makes sense to keep this package local and internal.  While reusability is absolutely a goal, I think a little copy and pasting (mentally, 3+ times) is better than an externalized dependency. 
- For util like packages I prefer to emulate the standard library ([ioutil](https://golang.org/pkg/io/ioutil/) , [httputil](https://golang.org/pkg/net/http/httputil/)) 


My feeling is that we should keep code local until it hurts. And only externalized (enforced by `/internal`) packages as necessary. 

See also

- https://go-proverbs.github.io/
- https://dave.cheney.net/practical-go/presentations/qcon-china.html#_avoid_package_names_like_base_common_or_util

**Comment by ilgooz** [comment]
Thanks for the big explanation! Ah, I haven't noticed what was kept inside the `internal` pkg.

Following thoughts:

**1-**
I agree your point on creating a package for every util-like func that may not be used multiple times might be too much, I think highly for maintenance reasons.

Tho, my main motivation is to make business logic more readable by eliminating the code that does related to do actual logic, like utilities. This way code gets shortened. Packages like `cli` are the ones that getting faced by everyday. I like the idea of shortening the code that heavily worked on by removing the unrelated code to directly see the business logic at the first look.

For the `xstrings.CommaSlice` example, maybe renaming it to `xflag.CommaSlice` makes more sense. x=extension, `flag` pkg lacks of supporting comma encoded slices and we extend its features by creating a `xflag` pkg.

**2-**
Yes, `x` name by itself can remind different patterns in Go. I don't mind renaming it with something else.

**3-**
I just checked the `internal` pkg and saw that it is used to keep both util packages and generic packages that similar to what I was mentioning in the first message. But unlike the idea behind of `x`, packages inside `internal` seems to be really internal since some of them specific to Pomerium, like [this](https://github.com/pomerium/pomerium/blob/master/internal/frontend/templates.go#L23) one.

What I would do is, make them not specific to Pomerium if possible and move under `x` and import them from `internal` and configure to make them specific to Pomerium by primitive func arguments or _XOption_(s) as needed.

**Comment by desimone** [comment]
I think you missed one of my main points. 

`commaSlice` is not being use _anywhere_ else right now. It doesn't make sense to abstract that utility struct into its own package until (at the very least) we need it elsewhere, the code becomes harder to reason about (where the code would now physically no longer right there). 

> I just checked the internal pkg and saw that it is used to keep both util packages and generic packages that similar to what I was mentioning in the first message. But unlike the idea behind of x, packages inside internal seems to be really internal since some of them specific to Pomerium, like this one.

Yes. That is what is intended by the internal package naming which is _enforced_ by the language itself. It's not a package naming convention.

> What I would do is, make them not specific to Pomerium if possible and move under x and import them from internal and configure to make them specific to Pomerium by primitive func arguments or XOption(s) as needed.

Since we aren't a library, I don't see externalizing and generalizing all pomerium code as strictly a good thing to do especially at the cost of (packaging) complexity.
