### ISSUE TITLE
G Suite Service Account Group Membership Validation Fails

### ISSUE THREAD

**Issue by shreyaskarnik** [pomerium/pomerium#567]
## What happened?
* Running on Kubernetes with the helm chart along with nginx ingress 
* We use G Suite Service account for group membership validation. 
* We have two users A and B
* user A is part of roughly 20 something groups
* user B is part of roughly 60 something groups (including owner of some groups)
## What did you expect to happen?
* Group membership works for user A and user A can access everything downstream fine
* For user B they get an error `ERR_CONNECTION_CLOSED` on Chrome and a blank page on Firefox
* When tried on Safari user got `kCFErrorDomainCFNetwork error 303`
* Also when user A who is an Pomerium admin tried to log in they got an 403 (creating separate issue for that)

## How'd it happen?

1. User B tried to log in

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
```bash
pomerium/v0.6.3 (+github.com/pomerium/pomerium; 1c7d30b; go1.14)
```
- Server Operating System/Architecture/Cloud:

## What's your config.yaml?

```config.yaml
- from: https://EXT
  to: http://INT
  allowed_groups:
    - admins@user.com
```

## What did you see in the logs?

```logs
[
    {
        "level": "debug",
        "X-Forwarded-For": [
            "XXXXX"
        ],
        "X-Forwarded-Host": [
            "INTERNAL"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "X-Real-Ip": [
            "XXXXX"
        ],
        "ip": "XXXXX",
        "user_agent": "REMOVED",
        "req_id": "f9ec84a4-14d9-ecc1-4632-aee4d192bd76",
        "error": "Forbidden: user@user.com is not authorized for INTERNAL",
        "time": "2020-03-26T19:18:33Z",
        "message": "proxy: AuthorizeSession"
    },
    {
        "level": "info",
        "X-Forwarded-For": [
            "INTERNAL"
        ],
        "X-Forwarded-Host": [
            "INTERNAL"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "X-Real-Ip": [
            "INTERNAL"
        ],
        "ip": "XXXXX",
        "user_agent": "REMOVED",
        "req_id": "f9ec84a4-14d9-ecc1-4632-aee4d192bd76",
        "error": "Forbidden: user@user.com is not authorized for INTERNAL",
        "time": "2020-03-26T19:18:33Z",
        "message": "httputil: ErrorResponse"
    }
]
```

**Comment by desimone** [comment]
@shreyu86 are either of the users also Pomerium (e.g. `administrators`) admins?

**Comment by camerondavison** [comment]
This exact same thing is happening to someone in my org. They have 100s of groups. They are able to authenticate but then when the redirect to httpbin.x.y.z it just errors out. Is there a work around for it? can I whitelist which groups are part of the jwt?

**Comment by camerondavison** [comment]
i am running `pomerium/0.9.2 (+https://wwww.pomerium.io; 3b74053; go1.14.4)`

**Comment by cuonglm** [comment]
> i am running `pomerium/0.9.2 (+https://wwww.pomerium.io; 3b74053; go1.14.4)`

Could you please try with current master branch?

There's change in v0.10.x that helping storing all groups information.

**Comment by camerondavison** [comment]
when i upgraded the code I am no longer seeing `X-Pomerium-Jwt-Assertion` in the headers

**Comment by camerondavison** [comment]
I tried to turn on `pass_identity_headers` and it just went into an infinite redirect loop

**Comment by cuonglm** [comment]
> I tried to turn on `pass_identity_headers` and it just went into an infinite redirect loop

Could you please provide some logs?

`pass_identity_headers` should not affect the routing.

**Comment by camerondavison** [comment]
I restarted everything and cleared all my cookies and the redirect loop seems to have gone away.

Running in k8s
```
pomerium-authenticate-5b7bd9cddf-kckwg 
pomerium-authorize-88554ccfc-8qdzt  
pomerium-cache-668676f8b-flhzv         
pomerium-proxy-7567d6869b-kkf99       
```

version
```
pomerium/v0.9.0 (+github.com/pomerium/pomerium; d40f294; go1.14.4)
```

with this config
```
address: ":443"
grpc_address: ":443"
certificate_file: "/pomerium/cert.pem"
certificate_key_file: "/pomerium/privkey.pem"
certificate_authority_file: "/pomerium/ca.pem"
authenticate_service_url: REDACT
authorize_service_url: https://pomerium-authorize.infrastructure.svc.cluster.local
cache_service_url: https://pomerium-cache.infrastructure.svc.cluster.local
idp_provider: google
idp_scopes:
idp_provider_url:

jwt_claims_headers: email
pass_identity_headers: true

cookie_secret: REDACT
shared_secret: REDACT
idp_client_id: REDACT
idp_client_secret: REDACT
policies: ...
```

looking at the headers that are sent to httpbin service shows no jwt assertion header. not sure what log you would like.

**Comment by camerondavison** [comment]
oh. woops. i figured it out. i had to move `pass_identity_headers` into the policy. not sure how i missed that in the documentation.

**Comment by cuonglm** [comment]
> oh. woops. i figured it out. i had to move `pass_identity_headers` into the policy. not sure how i missed that in the documentation.

So does it work now?

**Comment by camerondavison** [comment]
I had to change the `aud` that our app was verifying as well. So finally just got this deployed. But, then noticed that it broke all the routes using `allow_groups`. Is there a changelog that I should make another configuration change to get the `allow_groups` to work?

**Comment by cuonglm** [comment]
> I had to change the `aud` that our app was verifying as well. So finally just got this deployed. But, then noticed that it broke all the routes using `allow_groups`. Is there a changelog that I should make another configuration change to get the `allow_groups` to work?

I don't think there's any changes related to `allow_groups` format, I think you should just set the right form of group. Could you please post the rule related to `allow_groups`?

See [this](https://github.com/pomerium/pomerium/issues/573) for more general discussion.

**Comment by camerondavison** [comment]
this is my policy
```
    - from: https://dp-tools.secure.digitalpharmacist.com
      to: http://dp-tools-front-end.default.svc.cluster.local
      pass_identity_headers: true
      allowed_domains:
        - digitalpharmacist.com
```

**Comment by cuonglm** [comment]
> this is my policy
> 
> ```
>     - from: https://dp-tools.secure.digitalpharmacist.com
>       to: http://dp-tools-front-end.default.svc.cluster.local
>       pass_identity_headers: true
>       allowed_domains:
>         - digitalpharmacist.com
> ```
> 
> with the only difference from the config above being i have a service account
> 
> ```
> idp_service_account: REDACTED_SERVICE_KEY
> ```

Sorry, I mean the policy which contains `allowed_groups`.

**Comment by camerondavison** [comment]
oh my bad. I should have realized that
```
  - allowed_groups:
    - messages@digitalpharmacist.com
    from: https://message-search.secure.digitalpharmacist.com
    to: http://message-search.default.svc.cluster.local
```

**Comment by cuonglm** [comment]
@camerondavison cam

Could you please check that the group `messages@digitalpharmacist.com` appears in your dashboard page when you access `https://message-search.secure.digitalpharmacist.com/.pomerium`?

**Comment by camerondavison** [comment]
It is not showing up in there anymore. It used to with the old code. I'm wondering if there is some other configuration change that is needed. I am using the `idp_service_account` like I said above.

**Comment by cuonglm** [comment]
> It is not showing up in there anymore. It used to with the old code. I'm wondering if there is some other configuration change that is needed. I am using the `idp_service_account` like I said above.

Do you see any error in log indicate that syncing directory failed? I suspect that's the problem, because the new databroker can not retrieve your group information using `idp_service_account`, maybe it's something related to permission settings in Azure.

**Comment by camerondavison** [comment]
would it be worth chatting on a different medium? it works when i revert. so i am not what changed? what kind of log am I looking for. I turned on debug logging and I am running the k8s helm chart which run the authenticate,authorize,cache,proxy services. i changed everything to have the same `SIGNING_KEY` because it did not seem like it was coming from the correct service and I could not figure out which one I was suppose to use. 

I am on GCP by the way not Azure.

**Comment by camerondavison** [comment]
https://gist.github.com/camerondavison/236f95a76853c927fdb9484a8cbbbe3f
i dont see anything interesting in the authenticate logs.

**Comment by camerondavison** [comment]
```
{"level":"info","X-Forwarded-For":["70.114.218.62,10.120.8.4"],"X-Forwarded-Host":["authenticate.secure.dev.digitalpharmacist.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["70.114.218.62"],"ip":"127.0.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","request-id":"3dae90b3-7eac-40a8-b221-56169f6322fe","error":"Bad Request: internal/sessions: session is not found","time":"2020-07-14T01:23:57Z","message":"authenticate: session load error"}
```
somehow i got stuck in a redirect loop again. all i see is the above error message

**Comment by camerondavison** [comment]
I posted some authz logs. to the gist above

**Comment by camerondavison** [comment]
redirect loop went away when I moved off the 0.10.0-rc1 and to `pomerium/v0.9.0 (+github.com/pomerium/pomerium; 645f0a2; go1.14.4)` but still no groups are showing up and no logs that i can find

**Comment by cuonglm** [comment]
> I posted some authz logs. to the gist above

This one:

```
{"level":"warn","error":"rpc error: code = Unimplemented desc = unknown service databroker.DataBrokerService","time":"2020-07-14T01:49:34Z","message":"sync error"}
```

is strange, I guess that cause the error, because v0.10.x will use the databroker to store user directory information. Somehow the databroker server is not up.

**Comment by camerondavison** [comment]
i think that one went away when i upgraded to the latest version. i am seeing this
```
{"level":"warn","service":"identity_manager","error":"google: error getting group members: context deadline exceeded","time":"2020-07-14T02:25:33Z","message":"failed to refresh directory users and groups"}
```

**Comment by cuonglm** [comment]
> i think that one went away when i upgraded to the latest version. i am seeing this
> 
> ```
> {"level":"warn","service":"identity_manager","error":"google: error getting group members: context deadline exceeded","time":"2020-07-14T02:25:33Z","message":"failed to refresh directory users and groups"}
> ```

What do you mean `latest`? Is it `master`?

In any case, that error means there's problem when pomerium connect to Google APIs to retrieve your groups.

**Comment by desimone** [comment]
@cuonglm / @camerondavison maybe this would be good to pull into http://pomerium-io.slack.com/ ?

**Comment by cuonglm** [comment]
> @cuonglm / @camerondavison maybe this would be good to pull into http://pomerium-io.slack.com/ ?

Sure 👍

**Comment by camerondavison** [comment]
by latest i meant master yes. i am not sure that i have access to that slack?

**Comment by camerondavison** [comment]
maybe this is the problem? https://github.com/pomerium/pomerium/issues/1052

**Comment by cuonglm** [comment]
> by latest i meant master yes. i am not sure that i have access to that slack?

You can register [here](http://slack.pomerium.io/)

**Comment by camerondavison** [comment]
I think that I figured out at least the problem that I was running into with the new code. https://pomerium-io.slack.com/archives/CK92MUAES/p1594763955278400?thread_ts=1594737395.260800&cid=CK92MUAES

It looks like the timeout is 1 minute and that is not enough time to enumerate all the groups
```
{"level":"info","service":"identity_manager","time":"2020-07-14T21:47:03Z","message":"refreshing directory users"}
{"level":"warn","service":"identity_manager","error":"google: error getting group members: context deadline exceeded","time":"2020-07-14T21:48:03Z","message":"failed to refresh directory users and groups"}
```

Maybe we can up this timeout to 5 minutes? I am not sure what would make sense, or make it configurable?
https://github.com/pomerium/pomerium/blob/091b71f12e0c27ff72442b87733f90e3625b8fdb/internal/identity/manager/manager.go#L191-L194

This also makes sense to why I am seeing bunches of 200 requests to the google apis.
![image](https://user-images.githubusercontent.com/165381/87480975-097b7780-c5f4-11ea-9afb-45acb0a7335a.png)

**Comment by desimone** [comment]
@camerondavison that's really interesting. Could you give a ballpark figure of how many groups we are talking about?

**Comment by desimone** [comment]
@camerondavison I think you might be hitting the 1QPS usage limit.

https://github.com/pomerium/pomerium/issues/27#issuecomment-468565835

**Comment by camerondavison** [comment]
I'm new to the company but looking through the panel i got through 25 pages of 50 and it looks like we may have 1 group per customer. So maybe 5000 groups? Not every group has members. So maybe an optimization could be made around there?

**Comment by camerondavison** [comment]
@cuonglm helped me turn up the timeout to 9 minutes, and we still are unable to get the sync to work.
```
{"level":"info","service":"identity_manager","time":"2020-07-15T14:48:48Z","message":"syncing directory users"}
{"level":"warn","service":"identity_manager","error":"google: error getting group members: context deadline exceeded","time":"2020-07-15T14:57:48Z","message":"failed to refresh directory users and groups"}
{"level":"info","service":"identity_manager","time":"2020-07-15T14:58:48Z","message":"refreshing directory users"}
```
maybe one of the following would help?
1. make the refresh and timeout numbers configurable instead of every 10 minutes, and 1 minute for the timeout
1. whitelist of groups to sync
1. read the list of groups to lookup membership for from the policies (it would kind of be like specifying a whitelist of groups to sync)
