### ISSUE TITLE
Policy based access to routes in a webapp

### ISSUE THREAD

**Issue by shreyu86** [pomerium/pomerium#580]
**Is your feature request related to a problem? Please describe.**

Would like to see Pomerium being able to support being able to `skip auth` for certain routes in a webapp via the policy.

**Describe the solution you'd like**
For example
```yaml
skip_auth_regex:
- ^\/public\/$
```
**Describe alternatives you've considered**

**Explain any additional use-cases**
This is to support internal portals which have read only and read/write capabilities. 
Would love to see route based auth/access controls

If there are any use-cases that would help us understand the use/need/value please share them as they can help us decide on acceptance and prioritization.

**Additional context**

**Comment by desimone** [comment]
I think this approach could also help us address #548

**Comment by desimone** [comment]
Hey @shreyu86 ! This is now supported as part of v0.8.0!
https://0-8-0.docs.pomerium.io/configuration/#policy

#686

**Comment by shreyu86** [comment]
Excellent! 🙌 Thanks @desimone upgraded to 0.8.0 and will try new policy configuration
