### ISSUE TITLE
Group impersonation does not work

### ISSUE THREAD

**Issue by sylr** [pomerium/pomerium#581]
## What happened?

As admin I tried to impersonate someone with a specific group.

## What did you expect to happen?

`x-pomerium-authenticated-user-groups` has the group specified in the `Sign-in-as` `Group` field.

## How'd it happen?

Althought the user email impersonation does work correctly the HTTP header `x-pomerium-authenticated-user-groups` still contains my groups instead of the one specified in the `Sign-in-as` `Group` field.

I also checked the JWT token in `x-pomerium-iap-jwt-assertion`, my groups are still present.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): pomerium/v0.6.2 (+github.com/pomerium/pomerium; 5f67a70; go1.13.7)
- Server Operating System/Architecture/Cloud: Kubernetes pods

**Comment by desimone** [comment]
Thanks @sylr , this should be fixed in #569 and will be in the next release v0.7.0
