### ISSUE TITLE
deployment: add debug docker image

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#584]
**Is your feature request related to a problem? Please describe.**

We build our main images from a distroless base because:

> Restricting what's in your runtime container to precisely what's necessary for your app is a best practice employed by Google and other tech giants that have used containers in production for many years. It improves the signal to noise of scanners (e.g. CVE) and reduces the burden of establishing provenance to just what you need.

**Describe the solution you'd like**

Sometimes (especially related to DNS, or certificate issues) we _do_ want to be able to shell into a box and debug what's going on. In which case, I suggest we release a `-debug` container for each each major release, master, and latest. 

See: https://github.com/GoogleContainerTools/distroless#debug-images

**Describe alternatives you've considered**

Use busybox on the same pod. But that's not the same thing. 

**Explain any additional use-cases**

na

**Additional context**

na

\cc @travisgroth

**Comment by desimone** [comment]
@travisgroth  I believe this was completed in https://github.com/pomerium/pomerium/pull/1513 ?

https://hub.docker.com/layers/pomerium/pomerium/debug/images/sha256-040a8abff61d19226a7849baff3cfbb2ee151044bf8d4882dcfc89a4547b8d48?context=explore

**Comment by travisgroth** [comment]
As discussed we should add this for releases too before calling it closed.
