### ISSUE TITLE
v0.7.0 X-Pomerium-Authenitcated-* headers are missing

### ISSUE THREAD

**Issue by vic3lord** [pomerium/pomerium#585]
## What happened?

There are missing headers that are not going to upstream once authenticated

## What did you expect to happen?

`X-Pomerium-Authenticate-User-Email` to be available upstream

## How'd it happen?

1. Ran `upgraded to v0.7.0`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): pomerium/v0.7.0 (+github.com/pomerium/pomerium; d780281; go1.14.1)
- Server Operating System/Architecture/Cloud: GCP, CoS, GKE

## What's your config.yaml?

```config.yaml
LOG_LEVEL: info 
SERVICES: all
IDP_PROVIDER: google
ADMINISTRATORS: admin@example.com
CERTIFICATE_FILE: /var/run/secret/tls/tls.crt
CERTIFICATE_KEY_FILE: /var/run/secret/tls/tls.key
OVERRIDE_CERTIFICATE_NAME: '*.example.com'
AUTHENTICATE_SERVICE_URL: https://pomerium.example.com
```

## What did you see in the logs?

```logs
"error":"internal/sessions: session is not found"
```

## Additional context

"x-pomerium-jwt-assertion" header is full with all the relevant details including email

**Comment by desimone** [comment]
Hey @vic3lord this was an intentional breaking change see [upgrade guide](https://www.pomerium.io/docs/upgrading.html#breaking) 

Would it be possible to migrate your application to use the `x-pomerium-jwt-assertion`? Can you tell me a little more how you are using it?

Thanks!

**Comment by vic3lord** [comment]
Hey @desimone,

I'm using pomerium as my grafana (and other apps) zero-trust proxy, I cannot modify grafana to do this.

Currently Grafana is not supporting JWT assertion, there is a WIP PR https://github.com/grafana/grafana/pull/15187

In the meantime I rolled back to v0.6.3

**Comment by travisgroth** [comment]
Hi @vic3lord - based on user feedback, we're looking at re-adding these headers in a generic way.  See #596.  

If you have a way to test the PR for your use case, set `jwt_claims_headers: email` and update grafana to read header `x-pomerium-claim-email`.

**Comment by vic3lord** [comment]
That’s awesome, I’ll try it and report back

**Comment by travisgroth** [comment]
@vic3lord no -  we don't have PRs publish images currently.  I pushed one to `travisgroth/pomerium:pr-596` manually just now.

**Comment by vic3lord** [comment]
So @travisgroth, I've tested PR #596 and it's working great! 👏

**Comment by travisgroth** [comment]
Great.  Thanks @vic3lord.  We'll be looking to merge that in the next day or so.
