### ISSUE TITLE
authenticate: session load error

### ISSUE THREAD

**Issue by shreyu86** [pomerium/pomerium#590]
## What happened?

Getting 500 from an service behind Pomerium
![image](https://user-images.githubusercontent.com/311217/78587898-8d9eb180-77f2-11ea-9cc4-37b8972d22e8.png)

## What did you expect to happen?
Usual OAuth flow

## How'd it happen?

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
```
pomerium/v0.7.0 (+github.com/pomerium/pomerium; d780281; go1.14.1)
```
- Server Operating System/Architecture/Cloud:
Kubernetes deployment via. Helm 3 (pomerium-8.0.0 Helm chart)

## What's your config.yaml?

Using Google IDP

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```json
{
    "level": "info",
    "X-Forwarded-For": [
        "1.1.1.1"
    ],
    "X-Forwarded-Host": [
        "auth-domain"
    ],
    "X-Forwarded-Port": [
        "443"
    ],
    "X-Forwarded-Proto": [
        "https"
    ],
    "X-Real-Ip": [
        "1.1.1.1"
    ],
    "ip": "10.3.68.142",
    "user_agent": "Go-http-client/1.1",
    "referer": "https://domain/",
    "req_id": "caa5b7b2-a2fb-ea41-6110-0af3384a16ce",
    "error": "internal/sessions: session is not found",
    "time": "2020-04-06T16:50:36Z",
    "message": "authenticate: session load error"
}
```

**Comment by desimone** [comment]
Thanks @shreyu86 , will need to dig a bit deeper to see if this is helm chart related (no breaking changes jump to the top of my head) or kubernetes specific. 

In my limited testing on K8s and docker-composed based environments, I haven't hit  this though I haven't tried with the latest helm chart + updating the image. Though there's not much logging, it _looks_ this stems from some sort of connectivity issue when a gRPC client is timing out trying to contact another serivce.  

\cc @travisgroth 

Related
- #576

**Comment by desimone** [comment]
@shreyu86 I believe this was due to a regression in our pinned version of gRPC and should be fixed with #609 and be on latest. Would you be able to confirm?

Thanks!

**Comment by shreyu86** [comment]
@desimone thanks! I'll checkout this week.

**Comment by shreyu86** [comment]
@desimone confirmed this is working correctly. Currently on 
```
pomerium/0.7.5 (+https://wwww.pomerium.io; 3149e54; go1.14.2)
```
