### ISSUE TITLE
No /.pomerium path when using foward auth

### ISSUE THREAD

**Issue by msm595** [pomerium/pomerium#599]
## What happened?
There is no /.pomerium path when using forward auth. This means there is no way to sign out or check the current user for a service behind forward auth.

## What did you expect to happen?
Have /.pomerium populated or some other mechanism to view the user for a service behind foward auth.

## How'd it happen?
Visit https://httpbin.my.domain/.pomerium/ -> 404

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): pomerium/0.7.2 (+https://wwww.pomerium.io; 789068e; go1.14.2)
- Server Operating System/Architecture/Cloud: Docker + Traefik

## What's your config.yaml?

https://github.com/pomerium/examples/tree/master/traefik

## What did you see in the logs?
N/A

## Additional context

Also, based on my reading of the changelog, does the example config only need `x-pomerium-jwt-assertion` set for `authResponseHeaders` as the other headers have been deprecated?

**Comment by desimone** [comment]
Hi @msm595  -- Sorry for the slow response and thanks for the detailed issue report. Looking into this.


Related #548

**Comment by desimone** [comment]
This should be fixed in `v0.8.0`, could you confirm @msm595 and reopen if that's not the acse? Thanks!
