### ISSUE TITLE
Allow running authenticator and proxy separately as standalone processes

### ISSUE THREAD

**Issue by mbarrien** [pomerium/pomerium#6]
I found this while following the buzzfeed SSO. Looking at it, the code looks clean and seems to cleanup a lot of the configuration messiness from Buzzfeed and bit.ly's SSO. Most importantly for my organization, it adds Okta SSO support.

For my organization, the double OAuth flow is pretty important to prevent having to configure separate applications within Okta for every single internal app we create. The code seems architected for this, but it looks like you've hard coded in cmd/main.go that you instantiate both an Authenticator and Proxy object every time, and that all environment settings must be valid for both simultaneously. There doesn't seem to be some way using environment variables to disable one or the other.

pomerium needs to either split the command line into 2 apps (I know you are intentionally trying to merge them though), add flags/subcommands to only enable one, or provide environment variable settings/combinations to selectively disable one or the other.

**Comment by desimone** [comment]
Hi @mbarrien, thanks for checking out pomerium and creating this issue.

As you mentioned, I planned to keep pomerium a single binary but to add a `service_mode` flag. That flag would allow authentication, proxy and (soon!) authorization services to be run separately or together. Would that fit your needs?

**Comment by desimone** [comment]
Fixed by #12 . Thanks for the issue and suggested fix @mbarrien .
