### ISSUE TITLE
proposal: remove file support for certificates

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#60]
**Is your feature request related to a problem? Please describe.**

For a few settings, we allow the option to specify file paths to be used in addition to passing base64 encoded bytes. Those settings are:

- Certificate files
- Certificate private key files

The problem is basically we just have to maintain more code paths than I would like. As I started implementing policy and considering whether to support a file as well, I started to question the benefits of maintaining code paths for **both** file paths and file contents directly. 

**Describe the solution you'd like**

Remove support for files. Instead extend [envconfig](https://github.com/pomerium/envconfig) to support a base64 type and return bytes.  Or even optionally support compressed bytes if size becomes an issue. 

**Describe alternatives you've considered**

The one downside is that envars are typically limited to about 1MB in size. Which seems pretty massive for policy/text/certs/ but maybe I'm overlooking something.  Supporting both files and environmental variables for configurations that may be large (certificates, policy files, etc). 

**Additional context**

- https://kubernetes.io/docs/concepts/services-networking/ingress/#tls
- https://github.com/kubernetes/kubernetes/issues/23125

Any good reasons to keep support for file paths?

**Comment by mbarrien** [comment]
Having support for filenames is useful for cases where someone is setting up their own Kubernetes secrets that they mount into the container at their own specified path; to Pomerium that will just look like a file. Is that going to be removed in this proposal?

**Comment by desimone** [comment]
@mbarrien It's something I was considering but you are giving me exactly the type of feedback I was hoping for. It sounds like allowing certificates files *is* useful. I wasn't sure if it / how much it was being used relative to downside of having overlapping configuration options. 

I have a PR (#59) that will add an access policy file (probably YAML). Would it be similarly be useful to support both a file or base64 encoded bytes for something like that as well?

**Comment by desimone** [comment]
If it's useful, let's keep both for things that are not simple key value pairs. Closing.
