### ISSUE TITLE
Error 500 for self hosted gitlab. could not retrieve groups

### ISSUE THREAD

**Issue by ajcollett** [pomerium/pomerium#612]
## What happened?
After authentication, user is redirected to the page attached in the picture.

![Screenshot from 2020-04-15 09-29-49](https://user-images.githubusercontent.com/7753041/79310962-068dbf80-7efd-11ea-8ae5-65e939358e6c.png)

## What did you expect to happen?

Successful login and be able to view httpbin.

## How'd it happen?

1. Ran pomerium docker configuration.
2. I visited https://httpbin.localhost.pomerium.io, accepted my self signed cert
3. Was redirected to gitlab for auth. Successfully authenticated. 
4. Saw error 500: could not retrieve groups Unauthorized

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): 0.7
- Server Operating System/Architecture/Cloud: Docker on local machine

## What's your config.yaml?

**Pomerium config**
```config.yaml
pomerium_debug: true
authenticate_service_url: https://authenticate.localhost.pomerium.io

certificate_file: "./cert.pem"
certificate_key_file: "./privkey.pem"

idp_provider: gitlab
idp_provider_url: "https://<snip>"
idp_scopes: "openid,read_user,profile,email"
idp_client_id: <snip>
idp_client_secret: <snip>

policy:
  - from: https://httpbin.localhost.pomerium.io
    to: https://httpbin.org
```

**Docker compose**
```config.yaml
version: "3"
services:
  pomerium:
    image: pomerium/pomerium:v0.7.0
    environment:
      - COOKIE_SECRET=<snip>
    volumes:
      - ./authenticate.localhost.pomerium.io.crt:/pomerium/cert.pem:ro
      - ./authenticate.localhost.pomerium.io.key:/pomerium/privkey.pem:ro
      - ./config.yaml:/pomerium/config.yaml:ro
    ports:
      - 443:443
```

## What did you see in the logs?

```logs
httputil: ErrorResponse error="Internal Server Error: oauth callback : error redeeming authenticate code: internal/identity: could not retrieve groups Unauthorized" ip=172.17.0.1
```

## Additional context
I had to add the `idp_scopes`and restrict it to `openid,read_user,profile,email` since the default ones also included the `api` scope. Why should the app need that? I tried giving it that scope anyway, allowing it in gitlab, but that made no difference, I still had the same error.

**Comment by ajcollett** [comment]
I hadn't noticed the newer release 0.7.3, so I tried that too (with the above config) and it also didn't work.

**Comment by desimone** [comment]
@ajcollett if you comment out the custom scopes does it work?

I think you may be missing the api scope. 

```go
		p.Scopes = []string{oidc.ScopeOpenID, "api", "read_user", "profile", "email"}
```

**Comment by desimone** [comment]
Hi @ajcollett thanks for the detailed issue report.

I took a look, and it seems like the groups api url  is currently hardcoded to the hosted version.

https://github.com/pomerium/pomerium/blob/47f9765a47db73ec949ad423da1069a7e06c4650/internal/identity/gitlab.go#L22-L23

Should be a quick fix. 👍 

@Lumexralph thoughts on using the `api` scope being required here?

**Comment by Lumexralph** [comment]
Hi @ajcollett thanks for making the issue report and as @desimone said, we will work on a quick fix.

Regarding your thoughts on the `api` scope, we need it to be able to get information of the gitlab group(s) a user belongs to. https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#limiting-scopes-of-a-personal-access-token

On second thought, we would change the scope to `read_api`.

**Comment by ajcollett** [comment]
Hey @desimone, no worries! This software looks great and I would love to use it to secure some sites at the uni I admin things at. Specially now. VPN's aren't great when they drop thanks to flaky LTE connections!

Anyway, I did a little digging so we have all the right info. @Lumexralph I really hope the `api` scope can be avoided, since it grants wide access, especially with someone like me, the instance admin!

First off, I am not sure all the scopes in the personal access tokens are available in the applications settings, `read_api` seems to be absent. 
See the below screenshot from the application setup page:
![Screenshot from 2020-04-16 09-58-43](https://user-images.githubusercontent.com/7753041/79431105-42db2180-7fca-11ea-8c3b-eb3455e56868.png)

Secondly, GitLab seem to indicate that groups can be fetched from the OpenID endpoint:
https://docs.gitlab.com/ee/integration/openid_connect_provider.html

Thirdly, it seems this all needs updating in the docs too, as there is only instructs a user to select 2 scopes, and neither are `api`:-P

**Comment by Lumexralph** [comment]
@ajcollett Thank you, we are glad to hear this and really appreciate your suggestions.

Regarding the scope, we are also not comfortable with the permissions of the `api` scope and we are changing it to `read_api`.

Also, thank you for informing us about the information gotten from `/oauth/userinfo`, the earlier implementation didn't require an additional request for a user's group but there was a security issue about GitLab's group names not being unique and we decided to change it to `ID` according to this PR https://github.com/pomerium/pomerium/pull/571 and that warranted making another API call to get the group `IDs`,  since GitLab only returns an array of group names.

It is still a spot we have some thoughts about, we want group names for good user experience but it is mostly not unique and then we settle for IDs for now.

We'll update the docs to reflect the scopes `read_api` and any additional scope, thank you.
We would definitely love to have you test the fix when it is done. 😄

**Comment by ajcollett** [comment]
Hello @Lumexralph OKay great. 

FYI: It seems `read_api` is only just implemented. It will only be available in 12.10, and that's not released yet. Seems on the 22nd it will be released. So I couldn't see it because it's a pending feature. 

Since this is anyways broken, it shouldn't matter. But this would be a breaking change for anyone who is not on 12.10 or above. Maybe that can be in the docs too. 

I shall surely test it!

**Comment by Lumexralph** [comment]
@ajcollett Thank you!

**Comment by ajcollett** [comment]
@Lumexralph I see in the MR that the api scope was used, and not read_api. Any particular reason? Or is that for a future MR?

**Comment by Lumexralph** [comment]
Hi @ajcollett,  we changed the scope to `read_api` but got an error from GitLab saying it's an invalid scope. It will be in version 12.10 and I'm not sure it has been released yet, because the latest version I saw on their site is 12.9.

You might also like to pay attention to this conversation on GitLab
https://gitlab.com/gitlab-org/gitlab/-/merge_requests/28944

**Comment by ajcollett** [comment]
Ah okay. No worries!

**Comment by ajcollett** [comment]
Hello All, so I see gitlab release has happened (so you could now use read_api) and I also see this isn't in 0.7.5. Just wondering when it's planned to be released?

**Comment by Lumexralph** [comment]
@ajcollett Thanks for the reminder, we will work on it and see if the scope is also made available to their `openid`. If all goes well, we'll be glad to update the scope.

**Comment by Lumexralph** [comment]
Just tested added the new scope and it is all good. Thank you @ajcollett

**Comment by ajcollett** [comment]
Great! Thanks you for the prompt response.

Any idea on release date?

**Comment by desimone** [comment]
@ajcollett we are targeting v0.8.0 for the first of the month but you should be able to get all the latest changes on `:master` if are able to build from source or use a docker container.
