### ISSUE TITLE
Forward authentication does not account for policy routes with public access

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/pomerium#623]
## What happened?
If you set `allow_public_unauthenticated_access` on a policy route and use forward authentication with that route, the proxy will always return a `301`.

## What did you expect to happen?
For unauthenticated access the proxy should return a `200`.

## Code Details
To fix this issue we need to add additional code to this block in `forward_auth.go`:

```go
			if verifyOnly {
				return httputil.NewError(http.StatusUnauthorized, err)
			}
```

Before returning the `401` the code needs to check if the policy allows unauthenticated access.

With the way the code is currently structured we rely on the mux router to determine which policy route should be used for a URL. The mux router has a `Match` function which we can leverage. It fills a `RouteMatch` struct, which contains a `Handler` field. If we create our own `Handler` type we could add a field to the `Handler` to store the policy.

Currently we simply create a reverse proxy from the std httputil package. We can easily wrap this and put it in our own httputil package:

```go
type PolicyRouteHandler struct {
  *httputil.ReverseProxy
  Policy *config.Policy
}
```

and then we just use it like:

```go
if prh, ok := match.Handler.(*httputil.PolicyRouteHandler); ok && prh.Policy.AllowPublicUnauthenticatedAccess {
// return 200
}
```

**Comment by desimone** [comment]
> Currently we simply create a reverse proxy from the std httputil package. We can easily wrap this and put it in our own httputil package

+1 from me.
