### ISSUE TITLE
oidc provider docs and examples

### ISSUE THREAD

**Issue by pcrockett-pathway** [pomerium/pomerium#628]
After a good deal of failed searching and experimentation trying to get an unsupported provider to work with Pomerium, I learned from @desimone in the support channel on Slack that Pomerium supports a generic `oidc` provider. I would find it pretty handy to have some docs and / or examples for this along with the other providers.

**Comment by desimone** [comment]
Thanks for making the issue @pcrockett-pathway ; though I probably asked that you make an issue for this, I just remembered we've already got another issue tracking this.

\cc dupe of https://github.com/pomerium/pomerium/issues/307
