### ISSUE TITLE
Return JWT headers from forward auth requests

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#631]
**Is your feature request related to a problem? Please describe.**

In forward-auth configuration, pomerium is not in-path for application traffic and we lose the opportunity to pass the various JWT related headers.

**Describe the solution you'd like**

It appears that traefik and nginx, at least, support copying headers from the forward-auth response and sending them downstream with the proxied request traffic.  The pomerium forward-auth endpoint should return at least the identity related attestation headers.  

In a more general sense, it should probably return _all_ headers it would have otherwise provided to a normal proxied request.  This would give the forward-auth flow information parity with the proxy flow.

**Describe alternatives you've considered**

N/A

**Explain any additional use-cases**

This specifically came up while trying to use `x-pomerium-claim-*` to pass identity information to grafana in a forward-auth configuration.  

**Additional context**

N/A

**Comment by Vad1mo** [comment]
would https://www.pomerium.io/configuration/#jwt-claim-headers not work if forward auth mode?

**Comment by Vad1mo** [comment]
This issue is the same as #532

**Comment by travisgroth** [comment]
@Vad1mo Yes, this is related to that issue.  We've changed how we're doing claim specific headers, though.  So, we'll likely only be fixing this with jwt_claim_headers on the 0.7.x series and above.

Should have a fix soon.
