### ISSUE TITLE
GitLab Auth Provider Scope URL param should be scopes instead of scope

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium#635]
## What happened?

When using GitLab as the Auth Provider, the scopes request key in the URL should be `scopes` instead of `scope` 

Example: https://github.com/tootsuite/mastodon/issues/8210

Looking into the code it seems to be part of oauth2 // import "golang.org/x/oauth2". I am not golang savvy enough to be able to change that.

**Comment by desimone** [comment]
@Vad1mo thanks for making the issue. Could you tell me a little more about the error you are seeing? 

Per the Oauth2 and OpenID connect spec it looks like `scope` is correct (and is what is used to build the signin url elsewhere). 

https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

```
  HTTP/1.1 302 Found
  Location: https://server.example.com/authorize?
    response_type=code
    &scope=openid%20profile%20email
    &client_id=s6BhdRkqt3
    &state=af0ifjsldkj
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb

```

**Comment by Vad1mo** [comment]
I did a clean run this morning, new GitLab application and made sure I had all the needed scopes, I see it is working now as expected.
