### ISSUE TITLE
Does pomerium support mainframe security?. 

### ISSUE THREAD

**Issue by karthik137** [pomerium/pomerium#641]
Does beyond corp architecture support mainframe security?. If it supports then how?. Can we use pomerium to secure mainframe security?. How does pomerium secure mainframe systems?

**Comment by karthik137** [comment]
What is an end to end flow to authenticate a user of mainframe using beyondcorp?.

**Comment by desimone** [comment]
Hi @karthik137 -- can you explain a bit more by what you mean by "mainframe security" in this context? 

Generally speaking though, Pomerium is designed to support a broad range of deployment and security configurations. I'm obviously a bit biased in this regard, but I think implementing a tool such as Pomerium (and the principles behind zero trust and beyondcorp-style access) would help the vast majority of organization's security. 

I hope to get to #296 soon which will detail the threat model pomerium is designed for and hopefully help you with making the determination of if Pomerium is a good fit for your use.
