### ISSUE TITLE
Issue with sso

### ISSUE THREAD

**Issue by HaroldBernard** [pomerium/pomerium#660]
## What happened?
Getting blank screen when trying to go to a pomerium protected website after being logged in for 24hrs in the same browser. I have to delete my cookies for it to go away.

## What did you expect to happen?
need to re-log in via sso

## How'd it happen?
see what happened

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

## What's your environment like?
- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
v0.6.2
- Server Operating System/Architecture/Cloud:
Amazon eks
## What's your config.yaml?

```config.yaml
# Paste your configs here
# Be sure to scrub any sensitive values
```

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by HaroldBernard** [comment]
<img width="244" alt="Screen Shot 2020-05-06 at 12 37 32 PM" src="https://user-images.githubusercontent.com/46585964/81206260-d8e6e400-8f99-11ea-8bc7-56863552d3db.png">

**Comment by HaroldBernard** [comment]
just finding #80 will see if this solves my issue.

**Comment by desimone** [comment]
@HaroldBernard Did that solve your issue?
