### ISSUE TITLE
Bad Request: internal/urlutil: hmac failed

### ISSUE THREAD

**Issue by rinshadka** [pomerium/pomerium#667]
Getting 404 status with following while redirecting to pomerium. Running pomerium as forward auth behind traefik.

Bad Request: internal/urlutil: hmac failed

**Comment by desimone** [comment]
Hi @rinshadka thanks for trying pomerium.

Please follow the bug template and provide enough context such that we can help diagnose what may be going on.

https://github.com/pomerium/pomerium/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by rinshadka** [comment]
Hi, Thank for sharing this template, I will surely follow this in future. For me this error gone while I used https endpoints for all services, I am now using pomerium:master with selfhosted gitlab 12.10 version and is working fine.

I am running under traefik, can I deploy pomerium in another server and use my container's traefik label to call to pomerium public url through forward auth.address. 
Working if running in same server and if I call like:- ...forwardauth.address: "http://pomerium:443/?uri=https....
But not working if I replace "http://pomerium:443" this with public url eg:- "https://auth.example.com"

Thanks

**Comment by KGuillemot** [comment]
Hi,
I'm having the same problem while trying to configure pomerium.
I'm using the release 0.7.6 binary from github linux-amd64 on Debian 9.
Here is my configuration file : 
address: ":4443"
pomerium_debug: true
authenticate_service_url: http://auth.testing.tr:4443/
insecure_server: true
idp_provider: "google"
idp_provider_url: "https://accounts.google.com"
idp_client_id: "xxx.apps.googleusercontent.com"
idp_client_secret: "aKQxxx"
idp_service_account="zzzz" # output of `cat service-account-key.json | base64`
cookie_secret: rt3kUv1r4HjQEjV9sdUh+hgImBm3AFX8dAl21Ptesew=
policy:
  - from: http://test.testing.tr:4443
    to: http://127.0.0.1

I have pomerium listening on port 4443 and in my /etc/hosts file I have : 
127.0.0.1 auth.testing.tr
127.0.0.1 test.testing.tr

And on 127.0.0.1 port 80 I have an Apache listening.

I'm discovering the product so maybe am I doing something wrong ?

Thank you by advance for your help.

**Comment by kumarjp** [comment]
Like rinshadka suggested, Use HTTPS for all end-points.. from, to, and authenticate-service-url.  It worked for me.

**Comment by followsound** [comment]
Sorry to re-open this but the Kubernetes example uses http internally and seems to cause this issue

**Comment by followsound** [comment]
Also just found out this is not an issue in v0.9.2 docker image, but is in v0.10.0-rc1

**Comment by desimone** [comment]
@followsound Thanks for bringing this up. This should now be fixed on master -- could you check?

https://github.com/pomerium/pomerium/pull/1075

**Comment by followsound** [comment]
> @followsound Thanks for bringing this up. This should now be fixed on master -- could you check?
> 
> #1075

Yep looks like this is fixed on master :)

**Comment by fightforlife** [comment]
Is this already integrated in v0.9.6? I am experiencing this issue with v0.9.6 as a reverse proxy for portainer.

**Comment by kumarjp** [comment]
Try setting a fixed "shared_secret", Seems it was happening post pomerium restart or reload.

**Comment by fightforlife** [comment]
@kumarjp Thanks, this seems to be working now!

**Comment by desimone** [comment]
Thanks @kumarjp / @fightforlife 

Going to close this now. Feel free to reopen if anything pops back up.

**Comment by vanhtuan0409** [comment]
Hi, I experienced this again with the latest v0.16.2 version. Running with the following config
```
insecure_server: true
grpc_insecure: true
services: all
```
