### ISSUE TITLE
Groups of Google IdP seems to be referenced by name instead of email

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#67]
**Describe the bug**

Looking at the logs of the authorize service, it seems that pomerium retrieves the name of the groups and not the unique id in the form of an email address.

This means I can't use a stable identifier to authorize users by group.

**To Reproduce** Steps to reproduce the behavior:

1. Login on a group protected service
2. Check logs

:30PM DBG authorize/grpc Valid?=true email=user@xxx.com groups=["Infra","Demo Ops","Demo Test Group for SSO","Support","Tech"] route=www.xxx.com

**Expected behavior**

Pomerium should use the email as a way to identify a group in the policy file.

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.2+45e6a8d

**Comment by desimone** [comment]
Thanks for the bug report @victornoel . I've gone back and forth about this one. I'm not sure but I remember seeing that groups was mutable. Email is a very g-suite thing, and I was hoping to standardize on either group name (user beware?) or GUID which is universally supported, but often difficult to use and retrieve with other providers (azure ad jumps out at me). 

Would the option to use guid suffice? Or maybe to retrieve guid AND group?

**Comment by victornoel** [comment]
@desimone I'm not sure why we would want to standardize group names.

First, groups are a security things, so a group "admin" defined in gsuite is not the same thing as a group "admin" defined in azure: that's why they should be based on a stable identifier that uniquely identify a group. I don't think anybody is expecting both those "admin" groups to be conflated as one.

Then, I personally think it is easier as an admin to use the same vocabulary as in the IdP: if gsuite uses email to represent groups, it is easier for me to see emails in the security proxy. If Okta uses alphanumerical identifier, then let's use alphanumerical identifiers. If Azure uses guid, then let's use guid.

On thing that is 100% sure: using the descriptive group name is a security nightmare, I'm never 100% a group with the same descriptive name is not going to be created by someone else in my organization!

The only thing that could justify not using the identifier provided by the IdP is if Pomerium supports multiple IdP per pomerium instance (which would be very neat I believe). In that case, it may become necessary to add some extra information to identify the IdP on top of the group used. But it's not currently the case so I wouldn't bother with that now :)

**Comment by desimone** [comment]
> I'm not sure why we would want to standardize group names.

At the time, [my thinking was consistency](https://github.com/pomerium/pomerium/pull/57#issuecomment-466732535) with other providers. I'm open to changing that though.

> they should be based on a stable identifier that uniquely identify a group 

Agreed. But the gsuite case is a good example. Is a group email a [stable identifier](https://developers.google.com/admin-sdk/directory/v1/reference/groups)? It seems mutable. In any case, either way, it sounds like for gsuite email is at least a better (unique, if mutable) identifier than group name. 


> I personally think it is easier as an admin to use the same vocabulary as in the IdP 

Ideally, I agree. However, this creates a bit of a management issues because most IdP use a non-stable identifier to be user friendly in the user interface but using a unique ID under the hood. 

> if gsuite uses email to represent groups, it is easier for me to see emails in the security proxy. If Okta uses alphanumerical identifier, then let's use alphanumerical identifiers. If Azure uses guid, then let's use guid.

My hunch is that each identity provider externally shows one thing (email, name, guid) but all basically use unique ID on the backend for all the security reasons you've rightly brought up. 

Ideally, I'd like to offer the same user experience as the provider's themselves but right now we just have policy files, and no GUI . Most of the identity providers hide group unique id behind an API call and could make writing policy a pretty ugly task. 

> The only thing that could justify not using the identifier provided by the IdP is if Pomerium supports multiple IdP per pomerium instance (which would be very neat I believe). In that case, it may become necessary to add some extra information to identify the IdP on top of the group used. But it's not currently the case so I wouldn't bother with that now :)

Soon 😄 

In any case, I'm in favor of changing group name to group email for gsuite. But should we really be using immutable unique ids?

**Comment by victornoel** [comment]
> Agreed. But the gsuite case is a good example. Is a group email a stable identifier? It seems mutable. In any case, either way, it sounds like for gsuite email is at least a better (unique, if mutable) identifier than group name.

I think it is "as stable" as a username can be (so as stable a what we can put in pomerium `allowed_users`). So I guess it's not as stable as guid but from the administration console of gsuite, I don't even know how to find the guid of a group (and tried to look for it). If you change the email of a group, for me, it is almost the same as changing the identity of the group, so I wouldn't be bothered by that situation. Changing the name is the same as changing the description of the group.

I don't know if it considered immutable enough, but at least it is user-friendly and stable enough for me. But as always, I'm not a security expert at all and may be missing something there, so take my advocating with a grain of salt :)

**Comment by desimone** [comment]
It's very helpful feedback. 

I think this comes back to my other idea of returning BOTH user friendly group name (or group email) and GUIDs. If the administrator wants to set policy using the safer guid, she is free to do so and administrators who prefer easier administration with the potential security downsides can do that too.

I guess the only concern would be that a GUID would overlap with a group name, but that seems extremely unlikely given how group guids are generated....

**Comment by victornoel** [comment]
@desimone except if a malicious user creates a group with another group's GUID as a name… !

**Comment by desimone** [comment]
I ... erm... should have had my morning coffee first  😱 

We could extend policy to support  `allowed_group_id` and `allowed_user_id` and make the check explicitly.

**Comment by victornoel** [comment]
@desimone it works as expected now, thanks :)
