### ISSUE TITLE
After sign out, user is redirected to previous url and is signed on automatically again (Google IdP)

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium#68]
**Describe the bug**

After signing out, user is signed on automatically again without choice using the same Google user as before.

**To Reproduce** Steps to reproduce the behavior:

1. Sign out of a give route via https://xxx.com/.pomerium/sign_out
2. Click on sign out in the pomerium sign out page
3. User is redirected to https://xxx.com/ and signed in without any question

**Expected behavior**

User should be presented with the normal Google IdP user choice, so that:
- he can choose not to sign in again
- he can choose another identity in the IdP

**Environment:**

- Pomerium version (retrieve with `pomerium --version`): v0.0.2+45e6a8d
- Server Operating System/Architecture/Cloud: GKE/Google Oauth2

**Comment by desimone** [comment]
I've reproduced. Looking into a fix.

**Comment by desimone** [comment]
update: I believe this has to do with the mechanics of google's revoke endpoint.
Video of the bug. 
https://gfycat.com/frigidtanfinnishspitz

**Comment by victornoel** [comment]
@desimone yep it's strange, because I connected to a pomerium-protected service today, it has been some time I hadn't connected to it or any of the other pomerium-protected service there. When I logged out of it, google did redirect me to the identity chooser. Then I signed in, and signed out again, and this time it didn't!

**Comment by desimone** [comment]
This is going to sound crazy but I believe (#82) fixed this. @victornoel curious if you are seeing this fixed too.

**Comment by victornoel** [comment]
@desimone yes it does indeed! It may have been #81 also?

**Comment by victornoel** [comment]
@desimone I'm closing this then :)

**Comment by desimone** [comment]
Yes 81 was the fix; 82 fixed the fix :)
