### ISSUE TITLE
Disable user identity headers

### ISSUE THREAD

**Issue by satwell** [pomerium/pomerium#702]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to disable the `X-Pomerium-Jwt-Assertion` and `X-Pomerium-Claim-*` headers on a per-policy basis.  I have some policies that forward requests to services that I don't control, and these services don't consume the per-user identity information that Pomerium provides in these headers.  For privacy reasons I'd like to avoid sending PII like name and email address to these services unnecessarily.

**Describe the solution you'd like**

A per-policy configuration (maybe something like `pass_user_identity`) that defaults to true but can be set to false to prevent Pomerium from adding user identity headers.  Alternately, allow `set_request_headers` to override `X-Pomerium-Jwt-Assertion` and `X-Pomerium-Claim-*`, but that seems a little hacky.

**Describe alternatives you've considered**

None, there doesn't seem to be any way to configure Pomerium to avoid adding `X-Pomerium-Jwt-Assertion`.

**Comment by desimone** [comment]
@satwell I think that makes sense. We'll add a flag to disable identifying headers on a per-policy basis.

**Comment by cuonglm** [comment]
Since when we already have `set_request_headers` which reflect envoy [route.Route.RequestHeadersToAdd](https://pkg.go.dev/github.com/envoyproxy/go-control-plane/envoy/config/route/v3?tab=doc#Route), maybe we can add something like `remove_request_headers`, which will reflect `RequestHeadersToRemove`.

The `pass_user_identity` option will add the `X-Pomerium-Jwt-Assertion` and `X-Pomerium-Claim-*` to `RequestHeadersToRemove`

**Comment by desimone** [comment]
I think that makes sense, @cuonglm . 

1. If no `set_request_headers` is set, default to users/email/groups + jwt-assertion as. occurs today. 
2. If `set_request_headers` is set, only apply those headers added per the policy (so, if the user wants `user/group/groups`, they'll have to manually specify _all_ the headers they want, and we make no assumptions.
3. If `remove_request_headers` ... removes whatever headers they want by header name.

What do you think? 
\cc @calebdoxsey @travisgroth

**Comment by cuonglm** [comment]
@desimone I think we can keep the current behavior, and only introduce `remove_request_headers`. My proposal means:

 - Add `remove_request_headers` to remove headers that user wants.
 - Add `pass_user_identity`, which is default to `false`, so we won't add `X-Pomerium-Jwt-Assertion` and `X-Pomerium-Claim-*` headers to the request (This is backward incompatible, as it will break old version which relies on those headers). If `true`, behaves like current behavior.

> If set_request_headers is set, only apply those headers added per the policy (so, if the user wants user/group/groups, they'll have to manually specify all the headers they want, and we make no assumptions.

We can't do this, because `set_request_headers` requires explicit key-value pair to set header value, like `x-foo: bar`. While the `X-Pomerium-*` headers are only known at runtime, so user can't specify it in config.

**Comment by BenoitKnecht** [comment]
>> If set_request_headers is set, only apply those headers added per the policy (so, if the user wants user/group/groups, they'll have to manually specify all the headers they want, and we make no assumptions.
>
> We can't do this, because set_request_headers requires explicit key-value pair to set header value, like x-foo: bar. While the X-Pomerium-* headers are only known at runtime, so user can't specify it in config.

I always thought this was a pity, because it leads to completely different configuration options to set static or dynamic headers.

Would it be possible to allow for template values in the `set_request_headers` option? Something like

```yaml
set_request_headers:
  X-Pomerium-Claim-User: "{{ .JWT.User }}"
```

**Comment by cuonglm** [comment]
> > > If set_request_headers is set, only apply those headers added per the policy (so, if the user wants user/group/groups, they'll have to manually specify all the headers they want, and we make no assumptions.
> > 
> > 
> > We can't do this, because set_request_headers requires explicit key-value pair to set header value, like x-foo: bar. While the X-Pomerium-* headers are only known at runtime, so user can't specify it in config.
> 
> I always thought this was a pity, because it leads to completely different configuration options to set static or dynamic headers.
> 
> Would it be possible to allow for template values in the `set_request_headers` option? Something like
> 
> ```yaml
> set_request_headers:
>   X-Pomerium-Claim-User: "{{ .JWT.User }}"
> ```

It's doable, but I'm afraid it's not good UX. The user must know both Go and the internal structure of pomerium to specify the value.

**Comment by travisgroth** [comment]
@desimone I think that makes sense.  

While we're making these changes, I think we should have an option to explicitly turn the attestation header (`X-Pomerium-Jwt-Assertion`) on at the global level, and have it disabled by default.  It's rather large and should be opt-in.

**Comment by BenoitKnecht** [comment]
> > Would it be possible to allow for template values in the `set_request_headers` option? Something like
> > ```yaml
> > set_request_headers:
> >   X-Pomerium-Claim-User: "{{ .JWT.User }}"
> > ```
> 
> It's doable, but I'm afraid it's not good UX. The user must know both Go and the internal structure of pomerium to specify the value.

Fair enough. But I'm not saying that it should be this exact syntax, my point was that if you have an option to set static headers (`set_request_headers`), it's a bit surprising to have to use a completely different option to set dynamic ones (`jwt_claims_headers`). If you make it

```yaml
set_request_headers:
  X-My-Custom-Header: "$user"
```

or something, then you don't have to know Go templates or internal Pomerium data structures; you just need to know the name of the claim you want to use.

**Comment by cuonglm** [comment]
> > > Would it be possible to allow for template values in the `set_request_headers` option? Something like
> > > ```yaml
> > > set_request_headers:
> > >   X-Pomerium-Claim-User: "{{ .JWT.User }}"
> > > ```
> > 
> > 
> > It's doable, but I'm afraid it's not good UX. The user must know both Go and the internal structure of pomerium to specify the value.
> 
> Fair enough. But I'm not saying that it should be this exact syntax, my point was that if you have an option to set static headers (`set_request_headers`), it's a bit surprising to have to use a completely different option to set dynamic ones (`jwt_claims_headers`). If you make it
> 
> ```yaml
> set_request_headers:
>   X-My-Custom-Header: "$user"
> ```
> 
> or something, then you don't have to know Go templates or internal Pomerium data structures; you just need to know the name of the claim you want to use.

Fair point, SGTM :+1:

**Comment by cuonglm** [comment]
> > > Would it be possible to allow for template values in the `set_request_headers` option? Something like
> > > ```yaml
> > > set_request_headers:
> > >   X-Pomerium-Claim-User: "{{ .JWT.User }}"
> > > ```
> > 
> > 
> > It's doable, but I'm afraid it's not good UX. The user must know both Go and the internal structure of pomerium to specify the value.
> 
> Fair enough. But I'm not saying that it should be this exact syntax, my point was that if you have an option to set static headers (`set_request_headers`), it's a bit surprising to have to use a completely different option to set dynamic ones (`jwt_claims_headers`). If you make it
> 
> ```yaml
> set_request_headers:
>   X-My-Custom-Header: "$user"
> ```
> 
> or something, then you don't have to know Go templates or internal Pomerium data structures; you just need to know the name of the claim you want to use.

One down side of this, user can't specify the header with exact value like `$user`.
