### ISSUE TITLE
docs: clarify PROXY_ROOT_DOMAIN option

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#71]
**Describe the bug**

There is an inconsistency here because rootDomain is singular while the description is plural.

Also when using the PROXY_ROOT_DOMAIN envvar (which is singular), I thought it was actually meant to be able to parse multiple domains. But since rootDomain is also used for the ingress, if someone uses multiple domains, the ingress is going to be broken.

**Additional context**
 - https://github.com/helm/charts/commit/2084a17f57fd2ef34308084df5484d72cd9fe532#commitcomment-32894738 

Thank you @victornoel for reporting this.

**Comment by victornoel** [comment]
@desimone :+1: 

What is not clear to me is what is `PROXY_ROOT_DOMAIN` for in practice?
- If I want to restrict access, I can use `allowed_domains`
- if I want to proxy some domains, I can define routes (via the policy file).

**Comment by desimone** [comment]
@victornoel this should be addressed in #83 . Since we can infer these setting from `AUTHENTICATE_SERVICE_URL`, we should.  Thanks again for raising the issue.

**Comment by victornoel** [comment]
@desimone great, thanks, I will play with it soon to confirm it works as expected :)
