### ISSUE TITLE
403 - forbidden after editing config.yaml

### ISSUE THREAD

**Issue by fightforlife** [pomerium/pomerium#711]
## What happened?

After changing the config.yaml, the configuration gets reloaded correctly.
After that I get a 403 on all routes.
Solved by restarting the Pomerium Docker container.

Maybe important: 
all configuration is done using environment variables, only policies are described in config.yaml.

## What did you expect to happen?

Session should still be valid after changing a policy and reloading.

## How'd it happen?

1. changed a policy in the config.yaml
2. saved
3. config.yaml is successfully reloaded, new policy is active
4. opening any route shows 403 - forbidden

## What's your environment like?

- Pomerium 0.8.0-1589338260+80166bc
- Docker in Ubuntu 19.10

## What's your config.yaml?

```
config.yaml
policy:
# Portainer
  - from: https://some.domain.com
    to: http://192.168.178.2:9000
    allowed_users:
      - some.mail@gmail.com 
```

## What's your docker compose file?

```
docker compose
version: "2"
services:
  pomerium:
    container_name: pomerium
    image: pomerium/pomerium:latest
    environment:
      - AUTHENTICATE_SERVICE_URL=https://authenticate.domain.com
      - AUTOCERT=true
      - AUTOCERT_USE_STAGING=false
      - AUTOCERT_DIR=/pomerium/certs/
      - IDP_PROVIDER=google
      - IDP_CLIENT_ID=XXX.apps.googleusercontent.com
      - IDP_CLIENT_SECRET=XXX
      - COOKIE_SECRET=XXX
      - ADMINISTRATORS="some.mail@gmail.com"
      - HTTP_REDIRECT_ADDR=:80
    volumes:
      - pomerium_config:/pomerium/
    ports:
      - 80:80
      - 443:443
    restart: always
```

## What did you see in the logs?

```logs
2020-05-17T11:53:50.497696647Z {"level":"warn","ip":"XXX","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.56 Safari/537.36","req_id":"ad382873-4f49-dcce-0ef3-e972cb7223c1","reason":[],"allow":false,"expired":false,"time":"2020-05-17T11:53:50Z","message":"proxy/authorize: deny"}
2020-05-17T11:53:50.497752476Z {"level":"info","ip":"XXX","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.56 Safari/537.36","req_id":"ad382873-4f49-dcce-0ef3-e972cb7223c1","error":"Forbidden: request denied","time":"2020-05-17T11:53:50Z","message":"httputil: ErrorResponse"}
2020-05-17T11:53:50.497796496Z {"level":"debug","ip":"XXX","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.56 Safari/537.36","req_id":"ad382873-4f49-dcce-0ef3-e972cb7223c1","duration":31.549891,"size":1620,"status":403,"method":"GET","service":"all","host":"some.domain.com","path":"/","time":"2020-05-17T11:53:50Z","message":"http-request"}


```

**Comment by desimone** [comment]
@fightforlife Could you post what `_pomerium` cookie JWT looks like for the user that is getting denied (and redact any sensitive fields). And just to be sure, are there any capitalization or punctuation differences in the policy's username vs what is being returned by the identity provider?

**Comment by fightforlife** [comment]
Hi @desimone, below is the cookie content.
The content stays exactly the same after changing the config.yaml.

I had pomerium running in a docker container, that gets updated every night. This behaviour started with some of the 0.7.X version numbers. I hoped, that maybe it would fix itself :)
But it could also be a configuration problem on my site, since no other user complained till now?

The username (some.mail@gmail.com)  is written exactly the same in
- the policy declaration
- the _pomerium cookie
- on /.pomerium/
- ADMINISTRATORS="some.mail@gmail.com"


### _pomerium

Header
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```


Payload

```
{
  "ati": "c1f4713373e9bbe9",
  "aud": [
    "authenticate.domain.com",
    "some.domain.com"
  ],
  "email": "some.mail@gmail.com",
  "email_verified": true,
  "exp": 1589740534,
  "family_name": "Lastname",
  "given_name": "Firstname",
  "iat": 1589736934,
  "iss": "authenticate.domain.com",
  "name": "Firstname Lastname",
  "nbf": 1589736934,
  "picture": "https://lh4.googleusercontent.com/-6oaEsXGmSpw/AAAAAAAAAAI/AAAAAAAAAkg/AMZvucmted2h6gyn5NEhFSO9yLnFKmP0PQ/photo.jpg",
  "programatic": false,
  "sub": "102637594211933652749"
}
```

**Comment by ajcollett** [comment]
I have the opposite problem. I just deploy 0.8.0 and config does not get reloaded when the file changes. 

I have a similar setup. docker, most things in the env except the policy in the config.yaml file.

**Comment by Labbs** [comment]
Hello, I have the same issue. After update the configuration and start new containers with the configuration, 403 error. I need remove cookies for reconnect to the application.

**Comment by ChipWolf** [comment]
I'm seeing the same 403s.
Checking the JWT, only the first endpoint you hit is stored in the cookie, even with cookie_domain scoped correctly.

Here are the relevant keys from a JWT token from the cookie included the request for `bar.corp.example.org` immediately after hitting `foo.corp.example.com` (notice the duplicated domain):

```json
{
  "aud": [
    "authenticate.corp.example.org",
    "foo.corp.example.org",
    "foo.corp.example.org",
    "forwardauth.corp.example.org"
  ],
  "email": "chip.wolf@example.org",
  "email_verified": true,
  "family_name": "Wolf",
  "given_name": "Chip",
  "groups": [
    "admin@example.org"
  ],
  "iat": 1590258549,
  "iss": "authenticate.corp.example.org",
  "name": "Chip Wolf"
  "programatic": false
}
```

**Comment by cuonglm** [comment]
I think this is fixed with current [master](https://github.com/pomerium/pomerium/commit/dbd7f55b20fbacd4b13b023644bc9be4b2b2d290)

**Comment by desimone** [comment]
Closing. @Labbs / @fightforlife please reopen if this is not the case on master.
