### ISSUE TITLE
GitLab group memberships, only lists 20. 

### ISSUE THREAD

**Issue by ajcollett** [pomerium/pomerium#728]
## What happened?
(gitlab used as Oauth endpoint)
Should have been able to auth with a specific group in gitlab that I am a part of, after configuring pomerium to allow that group. 

## What did you expect to happen?
Authentication to succeed since I am in the group. 

## How'd it happen?
I added to the config the group ID that should be allowed. 
I then tried to auth, it said access denied. 

After looking at the debug output, I saw that only 20 groups were listed, which also happens to be the default API limit on returned items. 

## What's your environment like?
- Pomerium version 0.8
- Server Operating System/Architecture/Cloud: Gitlab Oauth, docker container. 

## What's your config.yaml?

```config.yaml
# Not full configs:
  - from: https://some_place
    to: https://some_other_place/
    preserve_host_header: true
    allowed_groups:
      - 360
```

## What did you see in the logs?
I was not authorised, and it seems the API call to gitlab does not fetch all groups. 
Logs shows only 20 groups, but I am in many more. 

## Additional context
GitLab has a default return limit of 20 items. I suspect the endpoint is being called once, and not paged through. 

In the API, you can either specify all=true, to get all items, or maybe specify a search filter? I am not sure which way you call the membership/user API endpoint.

**Comment by desimone** [comment]
>  I suspect the endpoint is being called once, and not paged through.

I think that is the case here as well. Unfortunately, having that many groups in your identity token is likely going to break the browser's session store (limited to 4096 bytes). We are working on a way to solve this by storing all associated data in cache, unfortunately it's not an easy fix.

**Comment by cuonglm** [comment]
This seems to be fixed in current [master](https://github.com/pomerium/pomerium/commit/dbd7f55b20fbacd4b13b023644bc9be4b2b2d290)

**Comment by desimone** [comment]
@ajcollett please reopen if you still have an issue.
