### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rinshadka** [pomerium/pomerium#729]
Hi, I am using self hosted gitlab as idp provider and using self signed certificate as I am testing locally. But getting connection issue from pomerium to gitlab . Attaching the logs below..

---
{"level":"info","time":"2020-05-19T17:50:09Z","message":"using /etc/ssl/certs/ca-certificates.crt as the system root certificate authority bundle"}
5:50PM INF cmd/pomerium version=v0.8.0+0ca5230
5:50PM INF internal/grpc: grpc with insecure addr=localhost:5443
5:50PM FTL cmd/pomerium error="error creating authenticate service: gitlab: failed creating oidc provider: identity/oidc: could not connect to gitlab: Get \"https://gitlab.test.local/.well-known/openid-configuration\": x509: certificate signed by unknown authority"

i have tried replacing "/etc/ssl/certs/ca-certificates.crt" this file with a custom CA file used for creating the self signed certs using this link - https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309
Thanks.

**Comment by desimone** [comment]
It looks like that custom CA is still not part of your trusted certificate store.

Again, please use the bug template.
