### ISSUE TITLE
Cors issue when enabling  pomerium auth on traefik label

### ISSUE THREAD

**Issue by asharabu** [pomerium/pomerium#753]
Hi,

I am facing the cors issue when accessing  domain2.com from domain1.com when enabling pomerium auth on traefik label.  I have given the below labels on traefik, 

---------------
    labels:
            traefik.http.routers.graph-https-redirect.entrypoints: "http"
            traefik.http.routers.graph-https-redirect.rule: "HostRegexp(`{any:.*}`)"
            traefik.http.routers.graph-https-redirect.middlewares: "graph-https-redirect"
            traefik.http.middlewares.graph-https-redirect.redirectscheme.scheme: "https"
            #traefik.http.services.graph-https-redirect.loadbalancer.server.port: "5015"
            traefik.http.routers.graph.entrypoints: "https"
            traefik.http.routers.graph.rule: "Host(`domain2.com`)"
            traefik.http.routers.graph.middlewares: "graph-allow"
            traefik.http.middlewares.graph-allow.headers.accesscontrolallowmethods: "GET,OPTIONS,PUT"
            traefik.http.middlewares.graph-allow.headers.accesscontrolalloworigin: "*"
            traefik.http.middlewares.graph-allow.headers.accesscontrolallowheaders: "*,X_AUTHENTICATION,X_CSRF_TOKEN"
            traefik.http.middlewares.graph-allow.headers.accesscontrolmaxage: "100"
            traefik.http.middlewares.graph-allow.headers.addvaryheader: "true"
            traefik.http.routers.graph.middlewares: "graph-auth"
            traefik.http.middlewares.graph-auth.forwardauth.trustForwardHeader: 'true'
            traefik.http.middlewares.graph-auth.forwardauth.authResponseHeaders: "Content-Type,Access-Control-Allow-Headers,X-Pomerium-Authenticated-User-Email,x-pomerium-authenticated-user-id,x-pomerium-authenticated-user-groups,x-pomerium-jwt-assertion"
            traefik.http.middlewares.graph-auth.forwardauth.address: "http://pomerium:443/?uri=https://domain2.com"
--------------------

Please note that pomerium and other to domains are in docker containers. The authentication is working but showing cores issue on domain1.com. When disabling the auth there is no cores issue on domain1.com.

Please see the police we used on pomerium configuration.

-------------------

   policy:
       - from: https://domain2.com
        to: https://domain1.com
        allowed_domains:
         - domain1.com
        cors_allow_preflight: true
         allowed_users:
         - user1@test.com
         - test.user@test.com

-------------

Can anyone please help me to solve this issue?

**Comment by desimone** [comment]
Please reopen following the issue guide! Thank you!
