### ISSUE TITLE
error redeeming authenticate code when using aws cognito

### ISSUE THREAD

**Issue by kernel164** [pomerium/pomerium#775]
## What happened?

Followed the instructions as per this link => https://www.pomerium.io/docs/identity-providers/cognito.html

I get the following error on https://authenticate.xxxxx.com/oauth2/callback

**Internal Server Error: oauth callback : error redeeming authenticate code: identity/oidc: could not retrieve user info oidc: failed to decode userinfo: json: cannot unmarshal string into Go struct field UserInfo.email_verified of type bool**

## What's your environment like?

- Pomerium version
{"level":"info","version":"0.8.0-1589338260+80166bc","time":"2020-05-26T09:17:20Z","message":"cmd/pomerium"}

- Server Operating System/Architecture/Cloud:
AWS EKS 1.16

## What did you see in the logs?

```logs
{"level":"info","X-Forwarded-For":["xx"],"X-Forwarded-Host":["authenticate.fleet.stg.telematicsct.com"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xx"],"ip":"xx","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36","req_id":"cc8f3f3d-3fda-1af0-799d-6177ba2c4705","error":"Internal Server Error: oauth callback : error redeeming authenticate code: identity/oidc: could not retrieve user info oidc: failed to decode userinfo: json: cannot unmarshal string into Go struct field UserInfo.email_verified of type bool","time":"2020-05-26T11:29:19Z","message":"httputil: ErrorResponse"}
```

**Comment by calebdoxsey** [comment]
This is an issue in an upstream library we use (go-oidc). I've submitted a fix there: https://github.com/coreos/go-oidc/pull/249.
