### ISSUE TITLE
Google: Missing refresh token during re-authorization after clearing cookies

### ISSUE THREAD

**Issue by chemhack** [pomerium/pomerium#80]
In an edge case, session state can end up without a refresh token, which causing 500 in pomerium proxy due to unable to fresh oauth token.

1. Login to a pomerium proxied app with Google account.
2. Clear all pomermium cookies
3. Login with Google again. If you check session state at this point, refresh_token is already empy.
4. Wait a few hours until oauth token expire
5. Go to pomerium proxied app.
6. 500 Error

**Expected behavior**

Pomerium should always be able to get a fresh token, since it's "persisted" in cookies, and the chance of losing it is very high.

**Environment:**

- Pomerium version: 0.0.3
- Server Operating System/Architecture/Cloud: kubernetes 1.12

Logs(s):

```proxy: refresh failed [31merror=[0m[31m"missing refresh token"...```

**Additional context**

PR to fix will follow.

**Comment by desimone** [comment]
Closed by #81
