### ISSUE TITLE
telemetry: requestID tripper should work with HTTPStatsRoundTripper

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium#808]
**Is your feature request related to a problem? Please describe.**

Our IdP HTTP client does not use the standard HTTPStatsRoundTripper and uses a requestID tripper instead.  

**Describe the solution you'd like**

These should be consolidated into a single tripper that injects requestID data along with other telemetry data.

**Comment by cuonglm** [comment]
What should we put int `destination` parameter of `metrics.HTTPMetricsRoundTripper` then?

```
// DefaultClient avoids leaks by setting an upper limit for timeouts.
var DefaultClient = &http.Client{
	Timeout: 1 * time.Minute,
	//todo(bdd): incorporate metrics.HTTPMetricsRoundTripper
	Transport: tripper.NewChain(metrics.HTTPMetricsRoundTripper("idp_http_client", "")).Then(requestid.NewRoundTripper(&ochttp.Transport{})),
}
```
