### ISSUE TITLE
Ability to rename headers

### ISSUE THREAD

**Issue by camerondavison** [pomerium/pomerium#826]
Post https://github.com/pomerium/pomerium/pull/596 I can enable the jwt auth claim email in the headers and I can see it show up as
```
X-Pomerium-Claim-Email
```

I am trying to run the elk stack behind pomerium, and would like to use the jwt claim as the authorization claim for users.

ELK requires that I set `es-security-runas-user` as the header and there is not a way to change it AFAIK. It would be nice to just have some setting to rename any headers, such as `X-Pomerium-Claim-Email` to `es-security-runas-user`

**Comment by cuonglm** [comment]
Related https://github.com/envoyproxy/envoy/issues/8947

**Comment by travisgroth** [comment]
Closed by https://github.com/pomerium/pomerium/pull/1906
