### ISSUE TITLE
OIDC Provider Claim Passing

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#834]
**Is your feature request related to a problem? Please describe.**

Many providers have additional claims that don't fit into the Pomerium JWT standard claims.   It would be nice to be able to bring those in so that they can be used by downstream applications.

**Describe the solution you'd like**

Have some way of bringing in additional OIDC claims from the provider.  Perhaps a dictionary object on the Pomerium JWT and some config options that let you specify the claims to include in the dictionary?

**Comment by sly-net** [comment]
Hello,
I have this need too.
My OpenID provider is [Dex](https://github.com/dexidp/dex), which is configured to get identities from an OpenLDAP server.
Dex can pass LDAP user identifiers to clients via a custom claim. Here's the doc: https://github.com/dexidp/dex/blob/master/Documentation/custom-scopes-claims-clients.md
As you can read, the claim looks like this:
```
"federated_claims": {
  "connector_id": "ldap",
  "user_id": "john"
}
```

My use case is the following: I'd like to put a [Netbox](https://github.com/netbox-community/netbox) instance behind Pomerium. Netbox supports external authentication and expects the authentication proxy to set a HTTP header corresponding to the name of the user (which has the role of user identifier). So I'd like to use the LDAP user identifier as username here. And in Netbox, we just have to specify the name of that header carrying the username via the _REMOTE_AUTH_HEADER_ variable. 
Documentation is available here: https://github.com/netbox-community/netbox/blob/develop/docs/release-notes/version-2.8.md#remote-authentication-support-2328

**Comment by desimone** [comment]
@sly-net 

Would it be workable to pull this data out of the JWT or does it need to be a header? 


See #1375

**Comment by sly-net** [comment]
@desimone Well, in short, sometimes it may work, sometimes not. For Netbox it will likely work.

The concept of having a backend application retrieving user identity (like username) via an environment variable, and more precisely via a HTTP header, is used by many applications. Sometimes those applications are developed using a well known framework, like Django — this is the case for Netbox. Then, authentication logic is implemented by the framework usually.

Django for example, provides modules for authentication against [LDAP](https://django-auth-ldap.readthedocs.io/en/latest/) or [remote user](https://docs.djangoproject.com/en/3.1/howto/auth-remote-user/). Remote user is typically getting user identity via HTTP header.

In the Django implementation of that HTTP header authentication concept, that header can be "cleaned" by overriding [clean_username](https://github.com/django/django/blob/53c0d16ac1d45ddc973fdffb6a6ee95c55a6fb3d/django/contrib/auth/backends.py#L213). So yes, we could here parse the JWT It should work. But again, the goal of this header is to clean an **username**. For example, clean _DOMAIN\John_ to _John_. Similarly to Django, there are other apps/frameworks that expect for an username only. And I guess it's not always possible to "clean" it. Worse: Django allows to "clean" it but when you just want to deploy Netbox or other Django app, it's not enough to simply configure the app. You have to modify a Python file to implement your _clean_username_ logic.

I have no idea how common are applications that are JWT-aware. But one thing seems clear: JWT is quite recent, while passing username by HTTP header is nothing new, and probably more common as of now.

**Comment by FireDrunk** [comment]
I would like to 'upvote' this feature. I'm using Keycloak which is linked to Google as an Identity Provider (I know pomerium can do this, but i have my reasons :-) ).

Keycloak passes the firstname and lastname (or given name) to Pomerium, because I can see it in the /.pomerium/ session details. This means that Pomerium reads the claims from the Keycloak identity.

Problem is, they don't exist in the JWT generated by Pomerium, and as such (I think) are not passed as HTTP Headers.

My use-case is Grafana, which supports auto-generating users from a given HTTP Headers, so using the users proper first and last name, will make Grafana autogenerate users based on the authentication information passed on by Pomerium.

My current configuration:

```
  - from: https://<external-url>
    to: http://<internal-service>
    pass_identity_headers: true
    jwt_claims_headers: name,email
    allowed_users:
      - <email address>
```

**Comment by desimone** [comment]
This should now be supported by https://github.com/pomerium/pomerium/pull/2102

Related:
- https://github.com/pomerium/pomerium/issues/1588
- https://github.com/pomerium/pomerium/issues/1855
