### ISSUE TITLE
Allow to toggle robots.txt in policy

### ISSUE THREAD

**Issue by fightforlife** [pomerium/pomerium#837]
**Is your feature request related to a problem? Please describe.**

I am using pomerium for internal and public websites, which I selfhost. (not alot of traffic) 
Currently pomerium overwrites the robots.txt file on any policy, even with `unauthenticated_public_acces=true`. 

**Describe the solution you'd like**

I think this is a correct security measure, but it would be nice if this was toggleable per policy. Something like `allow_robots=true`. This way we dont need to setup an extra reverse proxy like nginx for small personal blog. 

**Describe alternatives you've considered**

One could use an additional webserver like caddy or nginx to use as a reverse proxy alongside pomerium. But it would be much easier for low traffic sites to just be able to active the robots.txt file.

**Additional context**

Current robots.txt response:
`User-agent: *
Disallow: /`

Thanks in advance!

**Comment by fightforlife** [comment]
So https://github.com/pomerium/pomerium/pull/966 is only bringing back the old behaviour of always serving the same robots.txt file on all routes, right?

`User-agent: * Disallow: /`

**Comment by desimone** [comment]
> So #966 is only bringing back the old behaviour of always serving the same robots.txt file on all routes, right?
 
That's right.

**Comment by desimone** [comment]
@fightforlife Short of making a toggle-able configuration setting, would it solve your use case to have robots.txt not be overwritten if `unauthenticated_public_acces` = true?

**Comment by fightforlife** [comment]
@desimone 
I think this would be a viable solution, since this is the way `unauthenticated_public_acces = true` should be interpreted

**Comment by fightforlife** [comment]
Any plans when  #1361 will be included in the release?
