### ISSUE TITLE
Programmatic access to resources behind proxy

### ISSUE THREAD

**Issue by Nyoroon** [pomerium/pomerium#85]
I'd like to have programmatic access for resources behind proxy for "dumb" software like grafana or prometheus (like connect prometheus behind pomerium proxy).

Solution can be something like API tokens via basic auth or some http header.

For example, with nginx + auth_request + oauth2_proxy you can allow by IP.

**Comment by desimone** [comment]
@Nyoroon Thank you for the creating this issue. In short, yes I agree. I have a draft proposal I've been working on that I'll ping you on when it's read -- hopefully early next week.

**Comment by Nyoroon** [comment]
I don't think #177 completely solves it because not all existing apps can handle OIDC (like grafana -> prometheus in case when grafana is behind pomerium too or doesn't use oauth. or prometheus -> alertmanager).

**Comment by desimone** [comment]
@Nyoroon Are you primarily interested in service-to-service communication?

**Comment by desimone** [comment]
@Nyoroon ping :)

**Comment by Nyoroon** [comment]
@desimone oh, sorry, forgot to answer 😅 
Initially I was planning to use pomerium to grant access to local services which doesn't require authentication (mostly read-only access) and often used programmatically with other scripts or services.

**Comment by desimone** [comment]
Hi @Nyoroon  --- I'm going to close this because broadly speaking programmatic support is now in the release. I'm still a little unclear of your specific use case but would it be alright if we addressed that in a follow up issue?
