### ISSUE TITLE
Pomerium now ask to select client TLS certificate

### ISSUE THREAD

**Issue by yegle** [pomerium/pomerium#852]
## What happened?

![ink](https://user-images.githubusercontent.com/146133/84087175-715bf400-a99e-11ea-8c00-11a47aab15e7.png)

Looks like due to the use of Envoy, especially on browsers with client certificate installed, Pomerium start asking to select a client certificate.

## What did you expect to happen?

Unless I explicitly ask for client certificate authentication (mTLS), Pomerium should not ask for that.

## How'd it happen?

1. Update to the latest Pomerium
2. Use a browser with client certificate installed to access Pomerium.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint):
pomerium/0.9.0 (+https://wwww.pomerium.io; 914b952; go1.14.3)
- Server Operating System/Architecture/Cloud:
Docker

## What's your config.yaml?

Not applicable

## What did you see in the logs?

```logs
# Paste your logs here.
# Be sure to scrub any sensitive values
```

**Comment by desimone** [comment]
\cc @calebdoxsey

**Comment by calebdoxsey** [comment]
@yegle I have not seen this behavior. What browser are you using?

**Comment by yegle** [comment]
This is a Chrome browser with two client TLS certs installed.

**Comment by yegle** [comment]
I tried the docker image with master label and the issue is now fixed.
