### ISSUE TITLE
Signout Redirect Url Param Name

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#856]
**Is your feature request related to a problem? Please describe.**

I'm going to preface with this is my first time writing in Go, so I didn't want to submit pull requests that are probably not great.  You can take a look at my fork if you want to investigate how I've resolved this issue/feature.  My environment is Pomerium/Traefik (forward auth)/Keycloak.

Some OIDC providers (in my case, keycloak), require a different sign out redirect parameter name (in this case redirect_uri).  The hard coded name should probably be replaced by a configurable value (perhaps called idp_end_session_redirect_param).

**Describe the solution you'd like**

See above, new config option.

**Comment by desimone** [comment]
It's not totally clear what the move forward on this issue would be. We now have [single sign out](https://www.pomerium.com/docs/topics/single-sign-out) which may accomplish the desired effect.
