### ISSUE TITLE
Auth Url - Change path prefix

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#857]
**Is your feature request related to a problem? Please describe.**

I'm going to preface with this is my first time writing in Go, so I didn't want to submit pull requests that are probably not great.  You can take a look at my fork if you want to investigate how I've resolved this issue/feature.  My environment is Pomerium/Traefik (forward auth)/Keycloak.

In forward auth mode with Traefik, I've got the external authenticate url setup to be sso.example.com.  When you go to sso.example.com/.pomerium/, you see the dashboard, as expected.  However, when you hit the Sign Out button, it tries to execute the authentication signout instead of the proxy signout since there are two routes for the same path.

No idea if I'm doing this right, but figured there shouldn't be multiple routers for the same path no matter how it's all hosted.

**Describe the solution you'd like**

In my fork I've moved the auth router pah prefix to "./pomerium/auth" to resolve the conflicts and allow the dashboard to function correctly from the externally accessible authenticate domain.

**Describe alternatives you've considered**

Perhaps I need to create another externally accessible dns host instead of using the authenticate host directly?  Seems a waste to use two names for the same service though.

**Comment by cuonglm** [comment]
Close now after #926
