### ISSUE TITLE
Forward Auth - Invalid Session Issue

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#858]
## What happened?

I'm going to preface with this is my first time writing in Go, so I didn't want to submit pull requests that are probably not great.  You can take a look at my fork if you want to investigate how I've resolved this issue/feature.  My environment is Pomerium/Traefik (forward auth)/Keycloak.

In the forward auth functionality in the proxy, the IsAuthorized check is a boolean value.  However, the actual check in envoy also considers session issues (expired, not yet valid, etc).  If the session drops (i.e. the user manually logs out of the identity provider and so the session can't be refreshed), the forward auth still gives you a 403 error instead of a 401 error.

## What did you expect to happen?

I expected the forward auth to request re-authentication if there is a session issue.  Instead it just denies access.  In my fork I added a new bool return value that indicates whether authentication is needed, which clears the session and starts the auth process.

## What's your environment like?

- Pomerium 0.9.0 (forked now)
- Traefik (forward auth)
- Keycloak IDP

## What's your config.yaml?

Not Applicable

## What did you see in the logs?

Not Applicable

**Comment by cuonglm** [comment]
I think @calebdoxsey's PR #904 will fix this issue.

**Comment by simbaja** [comment]
> I think @calebdoxsey's PR #904 will fix this issue.

Sorry, work stuff came up and haven't had a chance to implement your suggested change on the pull request.  I'm not sure that #904 will resolve - I didn't see updates to the proxy in the changed file list.  But, I'm not yet fully versed with all the layers of this, so it could be something I just didn't notice.

**Comment by cuonglm** [comment]
@simbaja would you mind re-checking if this is fixed on master branch?

**Comment by simbaja** [comment]
I had a few moments and confirmed that it still shows a 403 instead of 401 under the scenario described.  I will go ahead and continue with the pull request adjustments to resolve.

**Comment by cuonglm** [comment]
@simbaja I can confirm this problem still occurs with latest commit 9821476086c60193748b42511a4cb7c1c1706ad1
