### ISSUE TITLE
Policy should check user, not just email

### ISSUE THREAD

**Issue by simbaja** [pomerium/pomerium#875]
**Is your feature request related to a problem? Please describe.**

Accounts may not always have an email associated with them.  In the policy, it should be possible to check the "allowed_user" against the signed-in user, not just the signed-in user's email.

**Describe the solution you'd like**

See above.  Can provide a pull request if needed.

**Describe alternatives you've considered**

Consider breaking out the allowed_user and allowed_email into two policy configurations.  Then you can check either and it's more clear what is being checked.  This would break existing policies though, whereas just checking allowed_user for both usernames and emails doesn't.

**Comment by cuonglm** [comment]
See https://github.com/pomerium/pomerium/issues/573 for more general discussion.

**Comment by simbaja** [comment]
Didn't notice that discussion, default filters hid it... I'll make sure to look at more issues next time :).  Thanks for pointing me at it!

**Comment by desimone** [comment]
In the near future we should support checking generic claims as well. Closing in favor of #573 discussion.
