### ISSUE TITLE
Hide impersonation options in /.pomerium path from non-admins

### ISSUE THREAD

**Issue by cjwalton** [pomerium/pomerium#881]
Currently, all users will see the impersonation form in the /.pomerium URL. This is not only confusing, but may be a source of security concerns (real or perceived). 

Since a non-admin cannot use this feature, it should not be present for non-admin users. 

Additionally, it may be desirable to optionally disable this path completely for non-admin users.

**Comment by xeor** [comment]
I tried logging in as a user that didnt have access. The user got denied, but I was still able to impersonate another user which had access, and then I could access the resource.. Can anyone else try and check?

**Comment by cuonglm** [comment]
@xeor which version you used? Could you please try with latest master branch. Thanks

**Comment by xeor** [comment]
I'm trying with `0.9.2`.. This is a little strange, because the impersonate option visible and can be used by everyone, no question asked.. I guess the master-branch will at least remove it from the ui. But it feels flaky if it still doesnt check if you are an admin before impersonating.

I guess it will be protected by a csrf token if it is hidden. But that shoulnt be the correct way.

I will try with master

**Comment by cuonglm** [comment]
@xeor 

> But it feels flaky if it still doesnt check if you are an admin before impersonating.

it does. You can't access `/admin/*` if you're not an admin.

**Comment by xeor** [comment]
On my test using an unauthorized user, I was able to impersonate the admin user. Thinking about it, it might have been another bug since the admininistrators config was defined as a list (using helm).
It ended up being "[admin@domain.com]". Maybe the brackets made everyone an admin...?

**Comment by cuonglm** [comment]
> On my test using an unauthorized user, I was able to impersonate the admin user. Thinking about it, it might have been another bug since the admininistrators config was defined as a list (using helm).
> It ended up being "[[admin@domain.com](mailto:admin@domain.com)]". Maybe the brackets made everyone an admin...?

It's serious if it's like that, please fire another bug, thanks.
