### ISSUE TITLE
Gitlab default scopes changed

### ISSUE THREAD

**Issue by cuonglm** [pomerium/pomerium#938]
After 666fd6aa358ac1cfef1fb96490a3c609cce4e8e3, gitlab default scopes are now: `oidc, api, profile, email` https://github.com/pomerium/pomerium/blob/c29807c3915b2e61d1a53dd007a8871b6494c3c6/internal/identity/oidc/gitlab/gitlab.go#L19

So following instruction at https://github.com/pomerium/pomerium/blob/c29807c3915b2e61d1a53dd007a8871b6494c3c6/docs/docs/identity-providers/gitlab.md won't work anymore.

We should re-thinking of default scopes changes are necessary, and why? If yes, the documentation need to be updated to reflect new default scopes.

cc @desimone @calebdoxsey

**Comment by calebdoxsey** [comment]
The default scopes were not changed as part of the data broker refactor.

**Comment by cuonglm** [comment]
> The default scopes were not changed as part of the data broker refactor.

Ah right, I mis-read the git diff. The actual commit is 666fd6aa358ac1cfef1fb96490a3c609cce4e8e3

**Comment by desimone** [comment]
I believe I changed this because I found that (at least at the time) read_user and read_api were not available to those using the hosted SaaS project.
