### ISSUE TITLE
internal/directory/google: user groups list failed

### ISSUE THREAD

**Issue by cuonglm** [pomerium/pomerium#942]
## What happened?

Google directory provider does not work.

```
{"level":"warn","service":"identity_manager","error":"google: error getting groups: googleapi: Error 404: Domain not found., notFound","time":"2020-06-21T23:57:32+07:00","message":"failed to refresh directory users and groups"}
```

## What did you expect to happen?

User groups are synced.

## How'd it happen?

Run pomerium in local, with google as IDP provider.

## What's your environment like?

- Pomerium version (retrieve with `pomerium --version` or `/ping` endpoint): master
- Server Operating System/Architecture/Cloud: Mac OSX

**Comment by calebdoxsey** [comment]
@cuonglm the google directory provider uses the Google Service Account JSON credentials in the `idp_service_account` field. Do you have that set? Do you also have an `impersonate_user` field inside of it?

**Comment by cuonglm** [comment]
> the google directory provider uses the Google Service Account JSON credentials in the idp_service_account field. Do you have that set

Yes

> Do you also have an impersonate_user field inside of it?

Ah no, adding it then it's working.
