### ISSUE TITLE
deployment: docker image does not contain nsswitch.conf

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium#97]
**Describe the bug** 
Pomerium's base image inherits from alpine linux which does not currently have `nsswitch.conf`. This is problematic because Go uses nsswitch.conf by default.  

As a result, Pomerium will not resolve hosts via /etc/hosts but instead always uses DNS. 

**Expected behavior**

To be completely frank, I'm not sure if this is our problem to fix, Go's or Alpine's. 

**Potential fix?**

Could we simply add a minimal `nsswitch.conf` to our `Dockerfile`?

```yml
RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
```

**Additional context**

> As @tianon mentions and as commented here: docker-library/docker#82 (comment) it is Go that is hardcoded to behave as glibc (dns first and then use hosts if it fails) if there is no /etc/nsswitch.conf. musl libc does not use this file at all since it does not implement NSS. I'd say that this is a bug in Go which assumes that linux always is glibc.
- https://github.com/gliderlabs/docker-alpine/issues/367#issuecomment-354316460

See also: 

- Pomerium #88
- Alpine https://github.com/gliderlabs/docker-alpine/issues/367
- Go golang/go#22846
- Kubernetes https://github.com/kubernetes/kubernetes/issues/71082

/cc @yegle

**Comment by eriksw** [comment]
Drive-by suggestion: Your current Dockerfile results in the final image being based on `FROM scratch`, with a manual step to copy in ca certs. (I'm not sure how Alpine has anything to do with this.)

Something I've done for private personal projects that works _great_ is to use [`gcr.io/distroless/static`](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md) as the image that the `CGO_ENABLED=0`-built binary is copied into by the second stage of the docker build. (Note: It's not mentioned in the readme, but the `static` image [does include nsswitch.conf](https://github.com/GoogleContainerTools/distroless/blob/master/base/BUILD#L114).)

**Comment by desimone** [comment]
Great suggestion @eriksw. I was looking at this project earlier, and it seems like a win/win.

The only other thing I would (ideally) like to have is the ability for users to be able to bootstrap an additional certificate authority to the trust store so can more easily manage mTLS between source apps and pomerium. I checked the docs but came up without much... Do you know if distroless can do something like that?

**Comment by eriksw** [comment]
`FROM pomerium/pomerium:latest` `ENV CERTIFICATE_AUTHORITY_FILE=/etc/myca.pem` `COPY myca.pem /etc/` seems about as simple as it could be if the goal is to actually make a custom image with the internal CA baked in.

**Comment by desimone** [comment]
Thanks @eriksw !
As weird as this sounds, I'm actually looking to add certificates to the system store ([here?](https://github.com/GoogleContainerTools/distroless/blob/master/cacerts/extract.sh)) at runtime. Confusingly, the `CERTIFICATE_AUTHORITY_FILE` covers adding a trusted CA for intra-pomerium service communication but not for say connecting to a backend service. What I want to do is to be able to add a custom CA at runtime to that store so it's trusted for all [communication](https://golang.org/src/crypto/x509/root_linux.go) including reverse proxying. Seems like a common use case but I can't find much about it.

**Comment by eriksw** [comment]
I don't think there's a good way to _append_ to the bundle file as part of an image build.

It should be pretty straightforward to use [SystemCertPool()](https://golang.org/pkg/crypto/x509/#SystemCertPool) to load the baseline truststore (what's baked into distroless) and then programatically add to it. You can then clobber `http.DefaultClient` with a new client that includes the extended cert pool in the client's `Transport.TLSClientConfig`.

**Comment by eriksw** [comment]
(I suspect there's a way to customize the http client's transport without breaking automatic http2 support, but I don't know what that is.)
