### ISSUE TITLE
Phoenix

### ISSUE THREAD

**Issue by Fabiophoenix1978** [pomerium/pomerium#98]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Ran `x`
2. Clicked `y`
3. Saw error `z`

**Expected behavior**

**Environment:**

- Pomerium version (retrieve with `pomerium --version`):
- Server Operating System/Architecture/Cloud:

Configuration file(s):

```text
# Paste your confis here.
# Be sure to scrub any sensitive values
```

Logs(s):

```text
# Paste your confis here.
# Be sure to scrub any sensitive values
```

**Additional context**

**Comment by desimone** [comment]
@Fabiophoenix1978 Was this bug report made in mistake?
