### ISSUE TITLE
Documentation does not specify newly required dependencies, and it is not handled by the Makefile

### ISSUE THREAD

**Issue by ekovac** [pomerium/pomerium#996]
After the pivot to envoy, the process for building pomerium from source has changed.

# Steps to reproduce

1. Start on a clean environment with Golang set up, but without OPA or Envoy installed.
2. Follow the instructions on https://www.pomerium.io/docs/quick-start/from-source.html
3. Run `make build` and `make test`

# Actual Behavior

3. Run into dependency errors, first for envoy, then for OPA.

# Expected Behavior

3. either:
   a. Document that installation of these packages is necessary.
   b. Modify the Makefile to fetch and use a local copy of OPA+Envoy

# Errors

Error for `make build` without envoy:

```
./scripts/embed-envoy.bash /home/philipkovac/pomerium/bin/pomerium./scripts/embed-envoy.bash: line 25: getenvoy: command not found
make: *** [Makefile:73: build] Error 127
```

Error for `make test` without opa:
```
make: opa: Command not found
make: *** [Makefile:84: test] Error 127
```

**Comment by desimone** [comment]
@ekovac Thanks for making the issue! By any chance does `make build-deps` / `make` work? (I took a glance at the makefile when I got back to my computer and noticed we should indeed be boot strapping both of those dependencies) .

**Comment by ekovac** [comment]
Took another look and you're right, it installs these as go packages in the go workspace, my go workspace just *still* wasn't set up correctly. Fixed my PATH and now everything's good. Thanks for the help, sorry for the trouble.
